import Link from 'next/link';
import type {ReactNode} from 'react';
import {Icon} from '@/components/icons';
import {Glyph,type GlyphName} from './layout';
import {AccountLink} from './actions';

export function DesignHeading({eyebrow,title,children,id}:{eyebrow:string;title:string;children?:ReactNode;id?:string}){return <div className="d-heading" id={id}><p className="d-eyebrow">{eyebrow}</p><h2>{title}</h2>{children&&<p>{children}</p>}</div>;}
export function TrustItems(){return <div className="d-trust">{[['shield','확인 가능한 원문'],['clock','중요한 변화부터'],['star','내 종목 중심 탐색']].map(([icon,text])=><span key={text}><i><Glyph name={icon as GlyphName} size={21}/></i>{text}</span>)}</div>;}
export function DesignHero({eyebrow,title,children,art,secondary={href:'#demo',label:'데모 화면 보기'},trust=true}:{eyebrow:string;title:ReactNode;children:ReactNode;art:ReactNode;secondary?:{href:string;label:string};trust?:boolean}){return <section className="d-hero"><div className="public-info-container public-info-hero-grid"><div className="public-info-hero-copy"><p className="d-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="d-lead">{children}</p><div className="public-info-actions"><AccountLink className="public-info-button primary">무료로 시작하기 <Icon name="arrow" size={18}/></AccountLink><Link className="public-info-button secondary" href={secondary.href}>{secondary.label}</Link></div>{trust&&<TrustItems/>}</div><div className="public-info-hero-art">{art}</div></div></section>;}
export function DesignCard({icon,title,children,href,protectedPage=false,label='자세히 보기',tone='blue'}:{icon:GlyphName;title:string;children:ReactNode;href?:string;protectedPage?:boolean;label?:string;tone?:string}){return <article className="d-card public-info-card"><div className="d-card-head"><span className={'d-icon tone-'+tone}><Glyph name={icon}/></span><h3>{title}</h3></div><p className="d-card-copy">{children}</p>{href&&(protectedPage?<AccountLink href="/login" destination={href} ariaLabel={title+' '+label} className="d-card-link">{label}<Icon name="arrow" size={16}/></AccountLink>:<Link href={href} className="d-card-link">{label}<Icon name="arrow" size={16}/></Link>)}</article>;}
export function DesignFaq({items,title='자주 묻는 질문',id='faq'}:{items:readonly {question:string;answer:ReactNode}[];title?:string;id?:string}){return <section className="d-faq" id={id}><DesignHeading eyebrow="FREQUENTLY ASKED QUESTIONS" title={title}/><div className="d-faq-grid">{items.map(item=><details key={item.question}><summary>{item.question}<Icon name="plus" size={18}/></summary><div>{item.answer}</div></details>)}</div></section>;}
export function DesignSteps({source=false}:{source?:boolean}){const steps=source?[['database','자료 수집','공식 원문과 게시 정보를 확인합니다.'],['settings','정리·검증','출처, 수치와 인용의 일치를 검토합니다.'],['spark','변화 분석','이전과 현재 자료의 차이를 연결합니다.'],['file','근거 제공','요약과 해석을 원문과 함께 표시합니다.']]:[['plus','내 종목 등록','관심종목과 보유종목을 정리합니다.'],['search','변화 확인','새 공시의 중요한 내용을 살펴봅니다.'],['spark','맥락 읽기','사실과 이전 대비 변화를 구분합니다.'],['file','원문 검토','연결된 출처에서 직접 확인합니다.']];return <ol className="d-steps">{steps.map(([icon,title,copy],i)=><li key={title}><span className="d-step-icon"><b>{i+1}</b><Glyph name={icon as GlyphName} size={25}/></span><h3>{title}</h3><p>{copy}</p></li>)}</ol>;}
const providers=[{name:'SEC EDGAR',icon:'shield',copy:'미국 기업 공식 공시',status:'현재 수집 범위',href:'https://www.sec.gov/edgar/search/'},{name:'OpenDART',icon:'globe',copy:'한국 기업 공시',status:'연결 보류',href:'https://opendart.fss.or.kr/'},{name:'시장 데이터',icon:'bars',copy:'공급자별 시세·이력',status:'연결 범위 확인',href:'/status'},{name:'기업 원문',icon:'file',copy:'연결·검토된 공식 자료',status:'원문 링크 제공',href:'https://www.sec.gov/edgar/search/'},{name:'실적 발표 자료',icon:'book',copy:'확인된 기업 발표 자료',status:'자료별 확인',href:'/sources#scope'},{name:'뉴스·리서치',icon:'search',copy:'외부 기사와 분석 자료',status:'연결 범위 확인',href:'/status'}] as const;
export function SourceCards({compact=false}:{compact?:boolean}){return <div className={'d-source-grid'+(compact?' compact':'')}>{providers.map(provider=><article className="d-source-card public-info-card" key={provider.name}><span className="d-icon tone-blue"><Glyph name={provider.icon}/></span><h3>{provider.name}</h3><p>{provider.copy}</p>{!compact&&<p className="d-source-description">{provider.name==='SEC EDGAR'?'10-K, 10-Q, 8-K 등 공시의 게시 정보와 공식 원문을 연결합니다.':'제공자 사용 조건과 실제 수집·검토 상태가 확인된 범위에서 이용합니다.'}</p>}{provider.href.startsWith('https:')?<a className="d-source-status" href={provider.href} target="_blank" rel="noopener noreferrer" aria-label={provider.name==='SEC EDGAR'?'SEC 공식 공시 SEC 자료 예시 보기':provider.name+' 공식 사이트 보기'}>{provider.status}<Icon name="arrow" size={13}/></a>:<Link className="d-source-status" href={provider.href}>{provider.status}<Icon name="arrow" size={13}/></Link>}</article>)}</div>;}
export function EvidenceArt(){return <div className="d-evidence-art" aria-label="원문과 인용의 연결 예시"><article className="d-evidence-summary"><span className="d-source-status"><Icon name="spark" size={16}/>근거와 함께 읽는 요약</span><h2>새 공시에서 무엇이 달라졌는지 확인하세요.</h2><p>확인한 사실과 이전 자료의 차이를 구분하고, 연결된 원문에서 맥락을 읽습니다.</p><span className="d-sample-note">화면 예시 · 실제 기업·시세 데이터가 아닙니다</span><div className="d-citation-tags"><a href="https://www.sec.gov/edgar/search/" target="_blank" rel="noopener noreferrer">1 SEC 원문</a><Link href="/sources#scope">2 자료 범위</Link><Link href="/privacy#scope">3 서비스 안내</Link></div></article><div className="d-evidence-documents">{[['shield','공식 공시','SEC EDGAR'],['book','기업 원문','검토한 자료'],['file','출처·인용','직접 확인']].map(([icon,title,label])=><a key={title} href="https://www.sec.gov/edgar/search/" target="_blank" rel="noopener noreferrer"><span className="d-icon tone-blue"><Glyph name={icon as GlyphName}/></span><div><strong>{title}</strong><small>{label}</small><i/><i/></div><Icon name="arrow" size={14}/></a>)}</div></div>;}
export function SecurityArt(){return <div className="d-security-art" aria-hidden="true"><div className="d-security-window"><div className="demo-logo"><span className="public-info-mark"/>SignalBrief</div><div className="d-security-bars"><i/><i/><i/><i/></div></div><span className="d-security-shield"><Glyph name="shield" size={100}/><Glyph name="lock" size={35}/></span></div>;}
