'use client';
import {useId,useRef,useState} from 'react';
import Link from 'next/link';
import {Icon} from '@/components/icons';
import {AccountLink} from './actions';

export function FeatureSample({kind}:{kind:'today'|'portfolio'|'summary'|'sources'|'timeline'|'questions'}){
 const [selected,setSelected]=useState(0),[question,setQuestion]=useState(''),[answer,setAnswer]=useState('');
 const id=useId();
 if(kind==='portfolio')return <div className="d-feature-sample"><div className="d-mini-tabs" aria-label="종목 목록 예시">{['포트폴리오','관심종목'].map((label,i)=><button type="button" aria-pressed={selected===i} key={label} onClick={()=>setSelected(i)}>{label}</button>)}<AccountLink href="/login" destination={selected?'/watchlist':'/portfolio'}>+ 등록</AccountLink></div><table><caption className="d-visually-hidden">합성 종목 목록 예시</caption><thead><tr><th>기업</th><th>자료</th><th>상태</th></tr></thead><tbody>{['A','B','C'].map((name,i)=><tr key={name}><td><span className="d-company-token">{name}</span>예시 기업 {name}</td><td>{selected?'관심종목':'보유종목'}</td><td>예시 {i+1}</td></tr>)}</tbody></table></div>;
 if(kind==='summary')return <div className="d-feature-sample"><strong><Icon name="spark" size={16}/> AI 브리핑</strong><div className="d-mini-tabs">{['확인한 사실','왜 중요한가'].map((label,i)=><button type="button" aria-pressed={selected===i} key={label} onClick={()=>setSelected(i)}>{label}</button>)}</div><p>{selected?'이전 자료와 현재 자료의 차이를 확인하고, 연결된 원문에서 추가 맥락을 읽습니다.':'새로운 자료에서 확인된 사실을 정리합니다. 해석과 확인 가능한 사실은 구분해 표시합니다.'}</p><div className="d-mini-note"><Icon name="shield" size={16}/>판단의 출발점은 확인 가능한 근거입니다.</div></div>;
 if(kind==='questions')return <div className="d-feature-sample"><strong><Icon name="spark" size={16}/>근거에 질문하기</strong>{['이전 자료와 무엇이 달라졌나요?','이 내용의 원문을 볼 수 있나요?'].map(text=><button className="d-question-chip" type="button" onClick={()=>setQuestion(text)} key={text}>{text}</button>)}<form onSubmit={event=>{event.preventDefault();setAnswer('화면 예시입니다. 실제 근거 질문은 로그인 후 공시를 선택해 이용할 수 있습니다.');}}><label className="d-visually-hidden" htmlFor={id}>예시 질문</label><input id={id} value={question} onChange={event=>setQuestion(event.target.value)} placeholder="질문을 입력하세요" maxLength={300} required/><button type="submit" aria-label="예시 질문 확인"><Icon name="arrow" size={17}/></button></form>{answer&&<p role="status">{answer} <AccountLink href="/login" destination="/questions">근거 질문 열기</AccountLink></p>}</div>;
 if(kind==='sources')return <div className="d-feature-sample"><strong>확인 가능한 출처</strong>{['SEC 공식 공시','자료 수집 범위','서비스의 제공 범위'].map((label,i)=>i===0?<a className="d-mini-source" href="https://www.sec.gov/edgar/search/" target="_blank" rel="noopener noreferrer" key={label}><span className="d-mini-tag">공시</span>{label}<Icon name="arrow" size={14}/></a>:<Link className="d-mini-source" href={i===1?'/sources#scope':'/privacy#scope'} key={label}><span className="d-mini-tag">안내</span>{label}<Icon name="arrow" size={14}/></Link>)}</div>;
 if(kind==='timeline')return <div className="d-feature-sample"><strong>예시 기업의 타임라인</strong><ol className="d-mini-timeline">{[['새 공시','변화와 인용 근거 확인'],['이전 공시','비교할 이전 자료 확인'],['기업 원문','공개한 자료의 맥락 확인']].map(([title,description])=><li key={title}><span>{title}</span><p>{description}</p></li>)}</ol></div>;
 return <div className="d-feature-sample"><strong>오늘 확인할 변화</strong>{['새 공시 확인','이전 자료와 비교','연결된 원문 읽기'].map((title,i)=><AccountLink href="/login" destination="/today" className="d-mini-event" key={title}><span className="d-company-token">{['A','B','C'][i]}</span><div><strong>예시 기업 {['A','B','C'][i]}</strong><p>{title}</p></div><Icon name="arrow" size={14}/></AccountLink>)}</div>;
}
const available=['관심종목·보유종목 관리','오늘의 변화와 브리핑','출처·인용 근거 확인','타임라인·근거 질문'];
export function PricingPlans({compact=false}:{compact?:boolean}){
 const [period,setPeriod]=useState<'monthly'|'annual'>('monthly');
 const id=useId();
 return <div className={'d-plans'+(compact?' is-compact':'')}>
  <div className="d-billing-control" role="group" aria-label="요금 표시 기간"><button type="button" aria-pressed={period==='monthly'} onClick={()=>setPeriod('monthly')}>월간</button><button type="button" aria-pressed={period==='annual'} onClick={()=>setPeriod('annual')}>연간</button><span>공개 베타 무료</span></div>
  <p className="d-billing-notice" role="status">{period==='monthly'?'월 단위':'연 단위'} 안내 · 현재 청구되는 요금은 0원입니다. 유료 요금은 미확정입니다.</p>
  <div className="d-plan-grid">{['Free','Pro','Pro+'].map((name,i)=><article className={'d-plan public-info-card'+(i===1?' featured':'')} key={name}><div className="d-plan-top"><span className="d-icon tone-blue"><Icon name={i===0?'pie':i===1?'spark':'star'} size={26}/></span><span className="d-plan-badge">{i===0?'공개 베타':'준비 중'}</span></div><h3>{name}</h3><p>{i===0?'현재 제공되는 기능을 무료로.':'가격과 제공 기능 확정 후 안내합니다.'}</p><div className="d-plan-price"><strong>{i===0?'₩0':'미정'}</strong><span> / {period==='monthly'?'월':'년'}</span></div><ul>{(i===0?available:['유료 결제 미연결','요금과 제공 범위 미정','출시 시점 미정','별도 신청 전 자동 결제 없음']).map(text=><li key={text}><Icon name={i===0?'check':'clock'} size={16}/>{text}</li>)}</ul>{i===0?<AccountLink className="public-info-button primary">{compact?'무료로 시작하기':'지금 바로 시작하기'}<Icon name="arrow" size={16}/></AccountLink>:<a href={'#'+id+'-availability'} className="public-info-button secondary">준비 상태 확인<Icon name="arrow" size={16}/></a>}</article>)}</div>
  <div className="d-plan-availability" id={id+'-availability'}><Icon name="shield" size={17}/><p>현재는 무료 공개 베타입니다. 유료 요금과 제공 범위는 확정 후 안내합니다. 결제나 자동 갱신이 이루어지지 않습니다.</p></div>
 </div>;
}
export function WalkthroughButton(){const dialog=useRef<HTMLDialogElement>(null);return <><button type="button" className="public-info-button secondary" onClick={()=>dialog.current?.showModal()}><Icon name="spark" size={17}/>사용 흐름 보기</button><dialog ref={dialog} className="d-walkthrough" aria-labelledby="walkthrough-title"><div><h2 id="walkthrough-title">근거로 읽는 네 단계</h2><button type="button" aria-label="사용 흐름 닫기" onClick={()=>dialog.current?.close()}><Icon name="close"/></button></div><ol>{['관심종목이나 보유종목을 등록합니다.','관련 공시와 새 이벤트를 확인합니다.','이전과 현재의 차이를 브리핑에서 읽습니다.','출처 링크를 열어 원문에서 확인합니다.'].map(text=><li key={text}>{text}</li>)}</ol><AccountLink className="public-info-button primary">무료로 시작하기<Icon name="arrow" size={16}/></AccountLink></dialog></>;}
