import Link from 'next/link';
import type {ReactNode} from 'react';
import {Icon,type IconName} from '@/components/icons';
import {marketingNav,type MarketingRoute} from '@/lib/marketing';
import {AccountLink,DashboardPreview} from './actions';
import MarketingHeader from './header';
import './marketing.css';
import './refinement.css';
import './responsive-design.css';
import './reference.css';

export type GlyphName=IconName|'bars'|'user'|'target'|'database'|'cookie'|'mail'|'globe'|'grid'|'book'|'credit-off'|'infinity'|'megaphone'|'warning'|'lock';
const glyphs:Partial<Record<GlyphName,string>>={bars:'M4 14h3v7H4ZM10 8h3v13h-3ZM16 3h3v18h-3Z',user:'M12 3a4 4 0 1 1 0 8 4 4 0 0 1 0-8M4 21v-3c0-6 16-6 16 0v3Z',target:'M19 10a8 8 0 1 1-5-6M16 3v5h5M12 12l9-9M15 11a3 3 0 1 1-3-2',database:'M3 6c0-5 18-5 18 0s-18 5-18 0ZM3 6v12c0 5 18 5 18 0V6M3 12c0 5 18 5 18 0',cookie:'M21 12a9 9 0 1 1-9-9c0 5 4 9 9 9ZM8 8h.1M7 14h.1M12 17h.1M14 11h.1',mail:'M3 5h18v14H3ZM3 5l9 7 9-7',globe:'M12 3a9 9 0 1 1 0 18 9 9 0 0 1 0-18M3 12h18M12 3c-5 5-5 13 0 18 5-5 5-13 0-18',grid:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',book:'M12 6v15M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2Z','credit-off':'M3 3l18 18M3 9h18M4 5h16v14h-2M14 19H4V5',infinity:'M12 12c-8-13-14 8-6 6 4-1 8-13 12-12 8 2 2 19-6 6',megaphone:'M3 9h5l12-5v16L8 15H3ZM8 15l2 6H6l-2-6',warning:'M12 3 2 21h20ZM12 9v5M12 17h.1',lock:'M5 10h14v11H5ZM8 10V7a4 4 0 1 1 8 0v3M12 14v3'};
export function Glyph({name,size=24}:{name:GlyphName;size?:number}){const path=glyphs[name];return path?<svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={path}/></svg>:<Icon name={name as IconName} size={size}/>;}
export function Brand(){return <Link href="/" className="public-info-brand" aria-label="SignalBrief 홈"><span className="public-info-mark"/>SignalBrief</Link>;}
export default function MarketingLayout({current,children}:{current:MarketingRoute;children:ReactNode}){return <div className="public-info-page"><a href="#public-info-main" className="public-info-skip">본문으로 건너뛰기</a><MarketingHeader current={current}/><main id="public-info-main">{children}</main><footer className="public-info-footer"><div className="public-info-container"><div className="public-info-footer-top"><div><Brand/><p>내 종목의 변화, 확인 가능한 근거와 함께.</p></div><nav aria-label="하단 서비스 안내">{marketingNav.map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}</nav><div className="public-info-legal-links"><Link href="/terms">서비스 이용 안내</Link><Link href="/privacy#scope">서비스 범위</Link><Link href="/privacy">개인정보처리방침</Link><Link href="/disclaimer">투자 유의사항</Link><Link href="/status">서비스 상태</Link></div></div><div className="public-info-footer-bottom"><span>© 2026 SignalBrief. All rights reserved.</span><span>더 나은 정보가, 더 나은 내일을 만듭니다.</span></div></div></footer></div>;}
export function Hero({eyebrow,title,description,art='dashboard',secondary={href:'/about#story',label:'서비스 소개 보기'},stats,hideActions=false}:{eyebrow:string;title:ReactNode;description:ReactNode;art?:'dashboard'|'sources'|'customers'|'privacy';secondary?:{href:string;label:string};stats?:readonly {value:string;label:string}[];hideActions?:boolean}){return <section className={'public-info-hero hero-'+art}><div className="public-info-container public-info-hero-grid"><div className="public-info-hero-copy"><p className="public-info-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="public-info-lead">{description}</p>{!hideActions&&<div className="public-info-actions"><AccountLink className="public-info-button primary">무료로 시작하기 <Icon name="arrow" size={16}/></AccountLink><Link className="public-info-button secondary" href={secondary.href}>{secondary.label}</Link></div>}{stats&&<div className="public-info-stats">{stats.map(stat=><div key={stat.value}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</div>}</div><div className="public-info-hero-art"><p className="public-info-art-label"><span/> FACT · CHANGE · EVIDENCE</p>{art==='dashboard'?<DashboardPreview/>:art==='privacy'?<PrivacyArt/>:art==='sources'?<SourcesArt/>:<CustomerArt/>}</div></div></section>;}
function PrivacyArt(){return <div className="public-info-privacy-art"><span className="privacy-shield d-vector-shield"><Glyph name="shield" size={150}/></span><span className="privacy-art-badge badge-storage"><Glyph name="shield"/>안전한 보관</span><span className="privacy-art-badge badge-purpose"><Glyph name="file"/>투명한 운영</span><span className="privacy-art-badge badge-rights"><Glyph name="user"/>사용자 권리 존중</span><span className="privacy-art-badge badge-lock"><Glyph name="lock"/>계정별 접근 보호</span></div>;}
function SourcesArt(){return <div className="public-info-sources-art"><div className="source-art-providers">{['SEC','Nasdaq','NYSE','Business Wire','PR Newswire'].map((name,i)=><a href={['https://www.sec.gov/edgar/search/','https://www.nasdaq.com/','https://www.nyse.com/','https://www.businesswire.com/','https://www.prnewswire.com/'][i]} key={name} target="_blank" rel="noopener noreferrer"><span className={'provider-mark provider-'+i}>{['SEC','N','▥','bw','PR'][i]}</span><strong>{name}</strong></a>)}</div><div className="source-art-result"><div className="demo-logo"><span className="public-info-mark"/>SignalBrief</div><h2>공식 출처 기반의<br/>신뢰할 수 있는 투자 정보</h2><div className="source-art-lines"><i/><i/><i/></div>{['원문 출처 확인','근거 링크 제공','변화와 맥락 연결','수집·검토 상태 표시'].map(t=><p key={t}><Icon name="check" size={15}/>{t}</p>)}<span className="source-art-note">출처 구조 예시 · 실제 제공 범위는 아래에서 확인</span></div></div>;}
function CustomerArt(){return <div className="public-info-customer-art" aria-label="서비스 활용 예시, 실제 고객 후기가 아닙니다">{['더 나은 투자 결정을 위한 근거를 확인해 보세요.','복잡한 정보를 정리하고 내 종목의 변화에 집중하세요.','시장과 기업의 흐름을 원문과 함께 읽어보세요.'].map(t=><div className="customer-quote" key={t}><span aria-hidden="true">“</span><div><p>{t}</p><small><Glyph name="user" size={14}/>서비스 활용 예시 · 고객 사례 준비 중</small></div></div>)}</div>;}
export function SectionTitle({eyebrow,title,children,id}:{eyebrow:string;title:string;children:ReactNode;id?:string}){return <div className="public-info-section-title" id={id}><p className="public-info-eyebrow">{eyebrow}</p><h2>{title}</h2><p>{children}</p></div>;}
export function Card({icon,title,children,href,label='자세히 보기',protectedPage=false,tone='blue',external=false}:{icon:GlyphName;title:string;children:ReactNode;href?:string;label?:string;protectedPage?:boolean;tone?:'blue'|'purple'|'green';external?:boolean}){return <article className="public-info-card"><span className={'public-info-icon tone-'+tone}><Glyph name={icon}/></span><h3>{title}</h3><div className="public-info-card-copy">{children}</div>{href&&(protectedPage?<AccountLink href="/login" destination={href} ariaLabel={title+' '+label} className="public-info-card-link">{label} <Icon name="arrow" size={16}/></AccountLink>:external?<a href={href} target="_blank" rel="noopener noreferrer" className="public-info-card-link" aria-label={title+' '+label}>{label} <Icon name="arrow" size={16}/></a>:<Link href={href} className="public-info-card-link">{label} <Icon name="arrow" size={16}/></Link>)}</article>;}
export function ClosingBanner({title,children,secondary={href:'/pricing',label:'요금제 바로가기'},eyebrow='A BRIGHTER TOMORROW'}:{title:string;children:ReactNode;secondary?:{href:string;label:string};eyebrow?:string}){return <section className="public-info-closing"><div className="public-info-mountain d-mountains" aria-hidden="true"><i/><i/><i/></div><div className="public-info-closing-copy"><p className="public-info-eyebrow">{eyebrow}</p><h2>{title}</h2><p>{children}</p><div className="public-info-actions"><AccountLink className="public-info-button primary">무료로 시작하기 <Icon name="arrow" size={16}/></AccountLink><Link href={secondary.href} className="public-info-button secondary">{secondary.label}</Link></div></div></section>;}
