import Link from 'next/link';
import MarketingLayout,{type GlyphName} from './layout';
import {LegalToc} from './legal';
import {VisualIcon,SecurityPicture} from './screenshot-preview';
import {Handnote} from './reference-pages';
import {AccountLink} from './actions';
import './screenshot-design.css';

const terms=[
 {id:'acceptance',title:'서비스 이용 목적',text:'SignalBrief는 투자 정보 탐색과 원문 근거 확인을 돕는 공개 베타입니다. 매수·매도 추천, 목표주가 또는 수익 보장을 제공하지 않습니다. 이 페이지는 현재 이용 범위에 관한 안내이며 정식 이용약관은 준비 중입니다.',aliases:['scope']},
 {id:'accounts',title:'회원가입 및 계정 관리',text:'이메일 또는 Google 계정과 Supabase 인증으로 계정을 관리합니다. 이메일 가입은 인증 메일의 안내에 따라 완료하며 비밀번호 찾기에서 복구 메일을 요청할 수 있습니다. 로그인 정보는 안전하게 관리하고, 공용 기기에서는 이용 후 로그아웃하세요.',aliases:[]},
 {id:'data',title:'서비스 제공 및 변경',text:'수집과 검토가 완료된 자료를 기준으로 제공합니다. 현재 미국 기업 공시를 우선 연결하며 국내 DART·KRX는 준비 중입니다. 기능과 출처 연결 범위는 개선될 수 있으며 변경 사항은 해당 화면과 서비스 상태에서 안내합니다.',aliases:['changes']},
 {id:'security',title:'이용자의 계정 관리',text:'계정별 접근 권한을 적용합니다. 다른 사람의 계정이나 자료에 접근하거나 인증·접근 제한을 우회하지 마세요. 자신의 관심종목, 보유종목, 일정과 동의 설정은 로그인 후 각 관리 화면에서 확인할 수 있습니다.',aliases:[]},
 {id:'sources',title:'출처 및 자료 이용',text:'공식 원문의 링크와 인용 근거를 제공합니다. 자료의 권리와 이용 조건은 각 출처의 정책을 확인하세요. 출처를 표시하는 것이 해당 기관과의 제휴나 원문 권리의 이전을 의미하지 않습니다.',aliases:[]},
 {id:'billing',title:'서비스 요금 및 이용 안내',text:'현재 공개 베타는 무료이며 결제와 자동 갱신은 연결되어 있지 않습니다. 유료 요금제의 실제 가격, 제공 범위와 시작 시점은 미확정입니다. 향후 변경 시에는 가격과 조건을 먼저 안내하고 별도 신청 절차를 제공합니다.',aliases:[]},
 {id:'limitations',title:'서비스 이용 시 유의사항',text:'AI 해석에는 오류와 누락이 있을 수 있습니다. 자료 수집과 외부 제공자 연결이 지연될 수 있으며 근거가 부족하거나 충돌하는 자료는 검토 대상으로 취급합니다. 중요한 내용은 원문에서 재확인하세요. 화면의 가상 예시는 실제 자료나 성과가 아닙니다.',aliases:[]},
 {id:'privacy',title:'개인정보 및 문의 안내',text:'개인정보 처리 항목, 목적, 외부 제공자와 이용자 권리는 개인정보 처리 안내에서 확인할 수 있습니다. 선택적 이용 통계 동의는 설정에서 변경할 수 있습니다. 계정 삭제 등 운영 접수 채널과 공식 연락처는 준비 중이며 확정 후 안내합니다.',aliases:['contact']},
];
const privacy=[
 {id:'scope',title:'개인정보처리방침 개요',text:'SignalBrief는 계정, 관심종목, 보유종목과 설정을 처리하는 공개 베타 서비스입니다. 이 안내는 현재 확인된 처리 범위와 사용자 설정을 설명합니다. 구체적 보유기간, 처리위탁·국외 이전 조건 및 운영 연락처는 확정 후 안내합니다.'},
 {id:'collection',title:'수집하는 개인정보 항목',text:'인증 제공자는 이메일과 로그인 정보를 처리합니다. 앱은 사용자 ID와 표시 이름, 관심종목, 보유 수량·평균 취득가, 질문, 일정·알림 및 이용 설정을 처리합니다. 앱 데이터베이스에는 이메일을 별도로 저장하지 않습니다.'},
 {id:'account',title:'계정 인증 및 수집 방법',text:'이메일 또는 Google 로그인은 Supabase 인증을 이용합니다. 회원이 입력한 계정 정보와 서비스 이용을 위해 등록한 종목·설정 등을 처리합니다. 이메일 복구 안내는 계정 존재 여부를 노출하지 않도록 표시합니다.'},
 {id:'purpose',title:'이용 목적',text:'계정 인증과 관리, 관심종목 및 보유종목의 관련 이벤트 연결, 근거 질문 처리, 알림과 일정 관리에 사용합니다. 선택적 이용 통계는 명시적으로 동의한 경우에만 수집합니다.'},
 {id:'retention',title:'보유 및 이용 기간',text:'구체적 보유기간과 삭제·계정 탈퇴의 운영 접수 방법은 준비 중입니다. 확정된 조건은 이 안내에 반영합니다.'},
 {id:'sharing',title:'외부 제공자 및 처리',text:'Google·Supabase 인증을 이용합니다. AI에는 질문과 공개 공시의 인용 후보를 보낼 수 있으나 보유 수량·취득가는 보내지 않습니다. AI 요청의 저장 제한과 제공자의 보안 로그 보관은 별개입니다.'},
 {id:'rights',title:'이용자 권리',text:'열람·정정·삭제 요청의 운영 접수 채널은 준비 중입니다. 선택적 이용 통계 동의는 설정에서 철회할 수 있으며 이후 이벤트에 적용됩니다.'},
 {id:'cookies',title:'쿠키 및 로그 데이터',text:'로그인 세션은 브라우저 저장소에 유지되며 로그아웃으로 지울 수 있습니다. 서비스에 필요한 로그를 사용하며 선택적 이용 통계는 명시적 동의 후에만 수집합니다.'},
 {id:'analytics',title:'선택적 이용 통계',text:'동의는 계정 설정에서 관리하며 철회는 이후 이벤트에 적용됩니다. 개인 보유 수량과 질문 내용은 이용 통계로 전송하지 않습니다.'},
 {id:'changes',title:'보호 조치 및 변경 안내',text:'계정별 접근 권한으로 사용자 정보를 보호합니다. 보유기간, 처리위탁·국외 이전과 운영 연락처는 확정 시 갱신합니다.'},
 {id:'contact',title:'문의처',text:'개인정보 및 서비스 문의 접수 채널을 준비 중입니다. 공식 연락처와 응대 시간은 확정 후 안내합니다.'},
];
function HelpStrip({small=false}:{small?:boolean}){return <section className={'v-help-strip '+(small?'v-help-small':'')}><div><p className="v-eyebrow">언제든지 확인해주세요</p><h2>{small?'약관 관련 문의':'도움이 필요하신가요?'}</h2><p>현재 확정된 서비스 범위와 문의 채널의 준비 상태를 안내합니다.</p></div><div className="v-help-item"><VisualIcon name="spark"/><div><h3>고객센터</h3><p>서비스 이용 관련 문의</p><Link href="/privacy#contact" className="public-info-button secondary">문의 안내 →</Link></div></div>{!small&&<><div className="v-help-item"><VisualIcon name="mail"/><div><h3>문의 채널</h3><p>공식 접수 채널 준비 중</p><Link href="/privacy#contact" className="v-link">운영 안내 확인</Link></div></div><div className="v-help-item"><VisualIcon name="file"/><div><h3>자주 묻는 질문</h3><p>궁금한 내용을 빠르게 확인하세요</p><Link href="/pricing#faq" className="public-info-button secondary">FAQ 보기 →</Link></div></div></>}</section>;}
function Terms(){return <><section className="v-container v-legal-hero v-terms-hero"><div className="v-background-bars" aria-hidden="true"/><div><p className="v-breadcrumb">홈 › 이용약관</p><h1>이용약관</h1><p className="v-lead">SignalBrief는 신뢰와 투명성을 바탕으로, 모두가 안심하고 이용할 수 있는<br/>서비스 환경을 만들어갑니다.</p></div><Handnote>더 나은 투자 판단을 위한<br/>신뢰할 수 있는 정보 파트너,<br/>SignalBrief</Handnote><div className="v-legal-dates"><VisualIcon name="calendar"/><span>서비스 상태<b>무료 공개 베타</b></span><VisualIcon name="clock"/><span>안내 갱신<b>2026년 10월 5일</b></span></div></section><div className="v-container v-legal-grid v-terms-grid"><LegalToc items={terms}/><div><p className="v-legal-beta">정식 이용약관은 준비 중입니다. 아래는 현재 공개 베타의 서비스 이용 안내이며 확정된 법적 조건이 아닙니다.</p><div className="v-terms-rows">{terms.map((t,i)=><article id={t.id} className="v-terms-row" key={t.id}>{t.aliases.map(alias=><span className="v-anchor-alias" id={alias} key={alias}/>)}<h2><span>{String(i+1).padStart(2,'0')}</span>{t.title}</h2><p>{t.text}</p></article>)}</div><HelpStrip small/></div></div></>;}
function PolicySection({index}:{index:number}){const p=privacy[index];return <section className="v-policy-section" id={p.id}><h3><span>{index+1}</span>{p.title}</h3><p>{p.text}</p>{index===1&&<div className="v-policy-table"><table><thead><tr><th>구분</th><th>처리 항목</th></tr></thead><tbody><tr><th>계정 정보</th><td>사용자 ID, 표시 이름, 인증 정보</td></tr><tr><th>서비스 정보</th><td>관심종목, 보유 수량·취득가, 질문, 알림·일정</td></tr><tr><th>선택적 정보</th><td>이용 통계 동의 및 사용자 설정</td></tr></tbody></table></div>}{index===4&&<div className="v-policy-table"><table><thead><tr><th>구분</th><th>현재 안내 상태</th></tr></thead><tbody><tr><th>계정 정보</th><td>구체적 보유기간 확정 후 안내</td></tr><tr><th>이용 기록</th><td>보유·파기 조건 준비 중</td></tr><tr><th>동의 설정</th><td>로그인 후 설정에서 변경 가능</td></tr></tbody></table></div>}{[3,6,8].includes(index)&&<AccountLink href="/login" destination="/settings" className="v-link">동의 설정 관리 →</AccountLink>}{index===10&&<div className="v-contact-notice"><VisualIcon name="mail"/><p>공식 문의 채널 준비 중<br/><span>연락처와 응대 시간은 확정 후 안내합니다.</span></p></div>}</section>;}
function Privacy(){return <><section className="v-container v-legal-hero v-privacy-hero"><div className="v-background-bars" aria-hidden="true"/><div><h1>개인정보처리방침</h1><p className="v-lead">SignalBrief는 이용자의 개인정보 처리 범위와<br/>계정 설정, 사용자 권리를 투명하게 안내합니다.</p></div><SecurityPicture/><Handnote>신뢰할 수 있는 데이터,<br/>더 나은 투자의 시작</Handnote></section><div className="v-container v-legal-grid v-privacy-grid"><LegalToc items={privacy}/><article className="v-policy-card"><div className="v-policy-head"><div><p className="v-eyebrow">개인정보 처리 안내</p><h2>개인정보처리방침</h2></div><small>공개 베타 안내 · 갱신 2026년 10월 5일</small></div><div className="v-policy-banner"><VisualIcon name="shield"/><p>현재 확인된 개인정보 처리 범위를 안내합니다. 구체적 보유기간, 처리위탁·국외 이전 조건 및 운영 연락처는 준비 중이며, 확정 후 이 페이지에 안내합니다.</p></div><div className="v-policy-columns"><div>{[0,1,2,3,4].map(i=><PolicySection index={i} key={i}/>)}</div><div>{[5,6,7,8,9,10].map(i=><PolicySection index={i} key={i}/>)}</div></div></article></div></>;}
const notices:readonly [GlyphName,string,string][]=[['file','정보 제공의 성격','SignalBrief는 공개된 시장 데이터와 기업 자료를 바탕으로 정보를 정리합니다. 제공되는 콘텐츠는 투자 판단을 돕는 참고 자료이며 매수·매도 추천이나 목표주가를 제공하지 않습니다.'],['user','투자 판단의 책임','원문 근거와 정보의 시점을 확인하고 자신의 판단으로 투자 결정을 내리세요. 중요한 투자 판단에 앞서 근거의 충분성과 불확실성을 함께 검토하시기 바랍니다.'],['bars','수익률 및 손실 가능성','과거의 성과는 미래의 수익을 보장하지 않습니다. 모든 투자에는 원금 손실의 가능성이 있으며, 시장 상황에 따라 예상과 다른 결과가 발생할 수 있습니다.'],['spark','데이터 및 AI 분석의 한계','AI 해석에는 오류와 누락이 있을 수 있으며 모든 변수를 고려하지 못할 수 있습니다. 중요한 주장과 수치, 이전 대비 변화는 공식 원문에서 재확인하세요.'],['clock','지연 및 오류 가능성','수집 지연, 외부 서비스 장애, 불완전한 근거가 발생할 수 있습니다. 정보의 발표 시점과 검토 상태를 확인하고 중요한 판단 시 최신 정보를 재확인하세요.'],['upload','외부 자료 및 링크','외부 출처 자료에는 해당 제공자의 이용 조건이 적용됩니다. 출처 표시는 제휴나 정보의 완전성을 보장하지 않으며 원문의 맥락과 이용 조건을 함께 확인해야 합니다.']];
function Disclaimer(){return <><section className="v-container v-legal-hero v-disclaimer-hero"><div className="v-background-bars" aria-hidden="true"/><div><p className="v-eyebrow">투자를 더 현명하게, 더 안전하게</p><h1>투자 유의사항</h1><p className="v-lead">SignalBrief는 투자에 필요한 정보와 근거를 제공하는 서비스입니다.<br/>모든 콘텐츠는 투자 권유가 아니며, 투자 수익을 보장하지 않습니다.</p></div><SecurityPicture warning/><Handnote>더 나은 투자 판단을 위한<br/>신뢰할 수 있는 정보 파트너,<br/>SignalBrief</Handnote></section><div className="v-container v-disclaimer-content"><section className="v-caution-banner"><VisualIcon name="warning"/><div><h2>투자에 따른 판단과 책임은 이용자 본인에게 있습니다.</h2><p>중요한 주장과 수치를 원문에서 확인하고, 불확실성을 함께 검토하세요. 화면의 가상 예시는 실제 기업 자료나 투자 성과가 아닙니다.</p></div></section><section className="v-disclaimer-grid"><div><h2>주요 유의사항</h2><p>더 안전하고 현명한 투자를 위해<br/>다음 사항을 반드시 확인해주세요.</p></div><div className="v-grid v-grid-3">{notices.map(([icon,title,copy])=><article className="v-notice-card" key={title}><VisualIcon name={icon} tone={icon==='bars'?'teal':'blue'}/><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section><section className="v-service-caution"><VisualIcon name="shield" tone="teal"/><h2>서비스 이용 시 유의점</h2><ul className="v-check-list">{['제공되는 정보는 개인의 투자 목적, 재무 상황과 위험 선호를 고려하지 않은 일반적인 정보입니다.','특정 종목, 산업, 금융 상품에 대한 매수·매도 타이밍을 제시하지 않습니다.','세금, 수수료 및 기타 비용을 모두 반영하지 않을 수 있습니다.','정보의 발표 시점, 수집 상태와 원문 근거를 함께 확인하세요.'].map(t=><li key={t}><span>✓</span>{t}</li>)}</ul></section></div><div className="v-support-band"><div className="v-container"><HelpStrip/></div></div></>;}
export function LegalReferencePage({kind}:{kind:'terms'|'privacy'|'disclaimer'}){return <MarketingLayout current={kind==='disclaimer'?'/':`/${kind}`}><div className={'v-page v-legal-page v-legal-'+kind} data-design="prelogin-20261005">{kind==='terms'?<Terms/>:kind==='privacy'?<Privacy/>:<Disclaimer/>}</div></MarketingLayout>;}
