'use client';

import {useId,useState} from 'react';
import {Glyph,type GlyphName} from './layout';
import {AccountLink} from './actions';

export type SampleKind='portfolio'|'watchlist'|'today'|'event'|'evidence'|'timeline'|'questions'|'calendar';
export function SampleChart(){const id=useId().replace(/:/g,'');return <svg className="v-chart" viewBox="0 0 220 80" aria-label="가상 예시 추이"><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop stopColor="#02c68c" stopOpacity=".20"/><stop offset="1" stopColor="#02c68c" stopOpacity="0"/></linearGradient></defs><path d="M2 75 18 61 30 54 42 60 54 53 66 58 80 46 92 35 104 38 116 29 129 33 140 22 152 25 164 17 176 20 188 9 201 14 216 5V80H2Z" fill={`url(#${id})`}/><path d="M2 75 18 61 30 54 42 60 54 53 66 58 80 46 92 35 104 38 116 29 129 33 140 22 152 25 164 17 176 20 188 9 201 14 216 5" stroke="#00be88" strokeWidth="1.7" fill="none"/></svg>;}
export function VisualIcon({name,tone='blue'}:{name:GlyphName;tone?:'blue'|'teal'|'purple'|'amber'}){return <span className={'v-icon v-'+tone}><Glyph name={name} size={27}/></span>;}
export function SecurityPicture({mail=false,warning=false}:{mail?:boolean;warning?:boolean}){return <span className={'v-security-picture'+(mail?' v-envelope':'')} aria-hidden="true"><span className="v-security-halo"/>{mail?<svg viewBox="0 0 180 130"><rect x="45" y="37" width="91" height="69" rx="15" fill="#dbeaff"/><path d="m48 45 42 28 43-28" fill="#8abcff" stroke="white" strokeWidth="4"/><circle cx="139" cy="98" r="26" fill="#009df6" stroke="white" strokeWidth="3"/><path d="m127 98 24-11-8 23-5-10Z" fill="white"/></svg>:<svg viewBox="0 0 180 150"><path d="M90 12c-20 12-40 16-57 20v43c0 35 33 55 57 65 24-10 57-30 57-65V32c-17-4-37-8-57-20Z" fill="#006eff" stroke="#b7e1ff" strokeWidth="5"/><path d="M90 18c-15 9-32 15-50 19v33c0 31 24 52 50 64" fill="#178dff"/><path d={warning?'M88 47h5v39h-5ZM88 103h5':'M78 70V59a12 12 0 0 1 24 0v11M72 71h36v33H72Z'} stroke="white" strokeWidth="6" fill={warning?'none':'#fff'} strokeLinejoin="round"/><path d={warning?'M90 101v1':'M90 83v10'} stroke={warning?'white':'#076cff'} strokeWidth="5" strokeLinecap="round"/></svg>}</span>;}
const stocks=[['A전자','70,500원','+3.2%'],['B하이닉스','180,200원','+1.8%'],['N플랫폼','207,000원','−0.6%']];
const issues=[['A전자','1분기 실적 컨센서스 상회','실적'],['B모빌리티','미국 관세 정책 관련 대응 발표','정책'],['C플랫폼','신규 AI 서비스 출시 계획 공개','신규']];
const evidence=['A전자 1분기 실적 발표 자료','주요 언론사 뉴스','증권사 리포트','관련 산업 리서치'];
function More({to='/today',text='전체 보기'}:{to?:string;text?:string}){return <AccountLink href="/login" destination={to} className="v-more">{text} ›</AccountLink>;}
export function SampleWidget({kind,compact=false}:{kind:SampleKind;compact?:boolean}){
 const [filter,setFilter]=useState('전체');const [calendarOffset,setCalendarOffset]=useState(0);
 const [question,setQuestion]=useState('');const [questionNotice,setQuestionNotice]=useState(false);
 const date=new Date(2025,3+calendarOffset,1);const month=date.toLocaleDateString('ko-KR',{year:'numeric',month:'long'});
 return <div className={'v-widget v-widget-'+kind+(compact?' v-widget-compact':'')}>
 {kind==='portfolio'?<><div className="v-widget-heading"><b>포트폴리오</b><More to="/portfolio"/></div><div className="v-portfolio-total"><div><strong>52,230,000원</strong><span className="v-positive">+2,316 (+2.8%)</span></div><SampleChart/></div>{stocks.map(([name,price,change],i)=><div className="v-stock-row" key={name}><span className={'v-stock-mark v-stock-'+i}>{['A','B','N'][i]}</span><span>{name}</span><span>{price}</span><em className={i===2?'v-negative':'v-positive'}>{change}</em></div>)}</>:
 kind==='watchlist'?<><div className="v-widget-heading"><b>관심종목</b><More to="/watchlist"/></div>{[['T모터스','TSLA','248.50달러','−1.2%'],['N반도체','NVDA','903.20달러','+2.3%'],['A전자','005930','70,500원','+3.2%'],['C플랫폼','035720','48,200원','−0.8%']].map(([name,code,price,change],i)=><div className="v-watch-row" key={name}><span className={'v-stock-mark v-stock-'+i}>{['T','N','A','C'][i]}</span><span>{name}<small>{code}</small></span><span>{price}</span><em className={change.startsWith('+')?'v-positive':'v-negative'}>{change}</em></div>)}</>:
 kind==='today'?<><div className="v-widget-heading"><b>오늘의 변화</b><small>2025년 4월 24일 (목)</small></div><div className="v-filters" aria-label="예시 이슈 필터">{['전체','주요 상승','주요 하락','신규 이슈'].map((f,i)=><button key={f} onClick={()=>setFilter(f)} aria-pressed={filter===f}>{f} <span>{[12,2,1,4][i]}</span></button>)}</div>{issues.filter((_,i)=>filter==='전체'||i===['주요 상승','주요 하락','신규 이슈'].indexOf(filter)).map(([name,text,tag],i)=><div className="v-issue-row" key={name}><span className={'v-stock-mark v-stock-'+i}>{name.slice(0,1)}</span><span><b>{name}</b><small>{text}</small></span><span><small>{(i+1)*2}시간 전</small><em className="v-tag">{tag}</em></span></div>)}<More text="전체 변화 보기"/></>:
 kind==='event'?<><div className="v-widget-heading"><span className="v-tag">실적</span><small>2시간 전</small></div><h4>A전자 1분기 실적 컨센서스 상회</h4><div className="v-event-intro"><p>시장 예상을 상회하는 1분기 실적을 발표하며, 메모리 반도체 수요 회복세가 확인되었습니다.</p><div className="v-building" aria-hidden="true"><span>A ELECTRONICS</span></div></div>{['매출 71.9조원 (예상치 +4.2%)','영업이익 6.6조원 (예상치 +12.1%)','AI 반도체 수요 확대 지속 전망'].map(t=><p className="v-checkline" key={t}><span>✓</span>{t}</p>)}<More to="/today" text="관련 이벤트 더 보기"/></>:
 kind==='evidence'?<><div className="v-widget-heading"><b>관련 근거 자료</b><span className="v-tag">12</span></div>{evidence.map((t,i)=><div className="v-evidence-row" key={t}><VisualIcon name="file"/><span>{t}<small>{['기업 발표','환경경제','리서치센터','산업연구원'][i]} · 2025.04.24</small></span><span className="v-tag">{['공식자료','뉴스','리포트','리서치'][i]}</span></div>)}</>:
 kind==='timeline'?<><div className="v-widget-heading"><b>A전자 주요 타임라인</b><More to="/watchlist"/></div><ol className="v-timeline">{['1분기 실적 컨센서스 상회','미국 반도체 관세 관련 입장 발표','신규 AI 반도체 제품 공개','주주환원 정책 강화 발표','4분기 실적 발표'].map((t,i)=><li key={t}><time>2025.{['04.24','04.15','03.28','02.10','01.31'][i]}</time><span>{t}</span><em className="v-tag">{['실적','정책','제품','공시','실적'][i]}</em></li>)}</ol></>:
 kind==='questions'?<><div className="v-widget-heading"><b>AI에게 더 물어보세요</b><span className="v-tag">Beta</span></div><p className="v-chat-user">이번 실적이 주가에 어떤 영향을 줄까요?</p><div className="v-chat-answer"><VisualIcon name="spark"/><p>이번 분기 실적은 시장 예상치를 상회한 예시입니다. 기업의 발표와 이전 자료를 비교해 변화를 확인하세요. 주가 방향은 단정할 수 없습니다.</p></div><form className="v-chat-input" onSubmit={e=>{e.preventDefault();setQuestionNotice(true);}}><input aria-label="예시 후속 질문" placeholder="추가로 궁금한 점을 질문해보세요." value={question} onChange={e=>setQuestion(e.target.value)}/><button aria-label="질문 기능 안내" type="submit">↗</button></form>{questionNotice&&<p className="v-sample-notice" role="status">미리보기입니다. <AccountLink href="/login" destination="/today">로그인 후 실제 근거에 질문하세요.</AccountLink></p>}</>:
 <><div className="v-calendar-tabs"><b>주요 일정</b><More to="/calendar" text="알림 설정"/></div><div className="v-widget-heading v-month"><button aria-label="이전 예시 달" onClick={()=>setCalendarOffset(i=>i-1)}>‹</button><b>{month}</b><button aria-label="다음 예시 달" onClick={()=>setCalendarOffset(i=>i+1)}>›</button><More to="/calendar"/></div>{calendarOffset===0?[['24일 (목)','A전자 1분기 실적 발표','실적'],['25일 (금)','미국 PCE 물가 지표 발표','경제지표'],['28일 (월)','B모빌리티 실적 발표','실적'],['30일 (수)','FOMC 금리 결정','경제지표']].map(([day,t,tag])=><div className="v-calendar-row" key={day}><time>4월 {day}</time><span>{t}</span><em className="v-tag">{tag}</em></div>):<p className="v-calendar-empty">이 달에는 등록된 예시 일정이 없습니다.</p>}</>}
 </div>;
}
export function ScreenshotPreview({kind='home'}:{kind?:'home'|'about'|'sources'|'customers'|'signup'|'login'}){
 const [tab,setTab]=useState<SampleKind|null>(null);
 return <div className={'v-browser v-browser-'+kind} aria-label="서비스 화면 미리보기 · 가상 데이터"><div className="v-browser-top"><i/><i/><i/><span>화면 예시 · 실제 시세·고객 데이터가 아닙니다</span></div><div className="v-browser-layout"><aside className="v-demo-sidebar"><b className="v-demo-brand"><span className="public-info-mark"/>SignalBrief</b><nav aria-label="미리보기 화면 선택">{([['home','대시보드',null],['pie','포트폴리오','portfolio'],['star','관심종목','watchlist'],['spark','AI 분석','questions'],['bell','알림','calendar'],['settings','설정','evidence']] as const).map(([icon,label,id])=><button key={label} aria-pressed={tab===id} onClick={()=>setTab(id)}><Glyph name={icon} size={13}/>{label}</button>)}</nav></aside><div className="v-demo-main"><div className="v-demo-toolbar"><AccountLink href="/login" destination="/watchlist"><Glyph name="search" size={13}/>종목명 또는 키워드를 검색해보세요.</AccountLink><Glyph name="bell" size={15}/><span className="v-demo-user"><Glyph name="user" size={16}/></span><span>김투자님⌄</span></div><div className="v-demo-content">{tab?<SampleWidget kind={tab}/>:
 kind==='about'?<><div className="v-about-stock"><div><h3>A전자 <small>005930</small></h3><strong>52,300원</strong><b className="v-positive">+1,800원 (+3.56%)</b></div><SampleChart/><div className="v-mini-summary"><b>✦ AI 한줄 요약</b><p>1분기 실적 컨센서스를 상회하는 실적을 발표하며 반도체 부문 개선세가 확인되었습니다.</p><More text="더 자세히 보기"/></div></div><div className="v-about-bottom"><div className="v-widget"><div className="v-widget-heading"><b>주요 최근 변화</b><More/></div>{issues.map(([,t,tag],i)=><div className="v-company-event" key={tag}><em className="v-tag">{tag}</em><span><b>{t}</b><small>{['매출과 영업이익 변화를 원문에서 확인','주요 고객사 관련 새로운 소식','이전 자료와 비교하여 맥락을 확인'][i]}</small></span><small>{i+2}시간 전</small></div>)}</div><div className="v-widget v-metrics"><b>관련 지표</b>{['시가총액','52주 최고','52주 최저','PER','PBR'].map((t,i)=><p key={t}>{t}<strong>{['311조원','88,800원','52,700원','17.3배','1.4배'][i]}</strong></p>)}</div></div></>:
 kind==='sources'?<><h3>A전자 <small>(005930)</small></h3><div className="v-stock-price">72,400원 <span>+1,200원 (+1.69%)</span></div><div className="v-source-tabs"><span>종합</span><span>AI 요약</span><b>최근 이슈</b><span>실적</span><span>기업 정보</span><span>관련 뉴스</span></div><div className="v-widget"><div className="v-widget-heading"><b>최근 주요 이슈</b><More/></div><div className="v-source-story"><div><div className="v-source-story-title"><span className="v-building"/><span><b>2분기 실적, 시장 예상치 상회</b><small>2025년 4월 24일 | 기업 실적자료</small></span></div><p>영업이익이 시장 컨센서스를 상회했습니다. 원문에 연결된 근거를 확인하고 이전 발표와 비교하세요.</p></div><aside><b>이 정보의 출처</b>{['기업 실적자료','공시자료','뉴스'].map(t=><p key={t}><Glyph name="file" size={12}/>{t}<small>2025.04.24 ↗</small></p>)}</aside></div></div></>:
 kind==='customers'?<div className="v-customer-dashboard"><div className="v-widget"><div className="v-widget-heading"><b>오늘의 투자 인사이트</b><More/></div>{['AI 반도체 산업, 중장기 성장 지속 전망','친환경 에너지 섹터, 정책 모멘텀 강화','미국 기술주, 실적 개선세 지속'].map((t,i)=><div className="v-insight-row" key={t}><VisualIcon name={(['file','target','globe'] as const)[i]} tone={i===1?'teal':'blue'}/><span><b>{t}</b><small>원문과 함께 확인하는 주요 산업의 변화</small></span><small>{i*2+2}시간 전</small></div>)}</div><aside className="v-widget v-customer-stats"><p>더 나은 투자 습관을<br/>SignalBrief와 함께하세요.</p>{[['user','개인화','관심종목 중심'],['bars','근거 확인','출처 기반 요약'],['star','함께 읽기','다양한 활용 방법']].map(([icon,n,t])=><div key={n}><VisualIcon name={icon as GlyphName}/><span><b>{n}</b><small>{t}</small></span></div>)}</aside></div>:
 <><div className="v-widget-heading"><h3>오늘의 변화</h3><small>2025년 4월 24일 (목)</small></div><div className="v-today-summary"><VisualIcon name="file"/><div><b>전체 요약</b><p>보유 3개 종목에서 주요 이슈가 확인되었습니다.<br/>새로운 공시와 산업 관련 소식이 주목됩니다.</p></div>{[['주요 상승','2','↑'],['주요 하락','1','↓'],['신규 이슈','4','▤']].map(([t,n,arrow],i)=><div className={'v-count v-count-'+i} key={t}><small>{t}</small><b>{n} <em>{arrow}</em></b></div>)}</div><div className="v-home-panels"><SampleWidget kind="portfolio" compact/><SampleWidget kind="watchlist" compact/><div><SampleWidget kind="evidence" compact/><div className="v-widget v-home-questions"><b>▣ AI 후속 질문</b><AccountLink href="/login" destination="/today">“이번 실적이 중요한 이유는?”</AccountLink><AccountLink href="/login" destination="/today">“확인할 위험 요인은 무엇인가요?”</AccountLink></div></div></div></>}
 </div></div></div></div>;
}
export function PasswordEye({visible}:{visible:boolean}){return <svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/>{!visible&&<path d="m3 3 18 18"/>}</svg>;}
