"""Network-free browser integration checks of the actual ten presentation controllers.
Run build_harness.mjs first. Uses isolated synthetic fixtures, never production accounts.
"""
import base64
import json
import os
import re
from pathlib import Path

from playwright.sync_api import expect, sync_playwright

ROOT = Path(__file__).resolve().parents[2]
ASSET = ROOT / '.reference-test'
OUT = Path(os.environ.get('REFERENCE_RESULTS', str(ROOT / 'reference-results')))
OUT.mkdir(exist_ok=True)
script = (ASSET / 'controller.js').read_text().replace('export ', '') + '\n' + (ASSET / 'templates.js').read_text().replace('export ', '') + '\n' + re.sub('^import .*$', '', (ASSET / 'fixture.js').read_text(), flags=re.M)
image = 'data:image/webp;base64,' + base64.b64encode((ASSET / 'reference-assets/onboarding-guide.webp').read_bytes()).decode()
script = script.replace('/reference-assets/onboarding-guide.webp', image)
css = '\n'.join(((ROOT / f'apps/web/src/{name}').read_text() for name in ['app/globals.css', 'app/release-layout.css', 'reference/reference.css', 'reference/overrides.css']))
HTML = '<html lang="ko"><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0}' + css + '</style></head><body><div id="root"></div><script>' + script + '</script></body></html>'
results = []

def record(mode, name):
    results.append({'viewport': mode, 'check': name, 'status': 'passed'})
with sync_playwright() as pw:
    browser = pw.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH', '/usr/bin/chromium'), headless=True, args=['--no-sandbox'])
    for mode, width, height in [('desktop', 1534, 960), ('mobile', 412, 915)]:
        context = browser.new_context(viewport={'width': width, 'height': height}, is_mobile=mode == 'mobile', has_touch=mode == 'mobile')

        def screen(name):
            page = context.new_page()
            page.set_default_timeout(7000)
            errors = []
            page.on('pageerror', lambda e: errors.append(str(e)))
            page.set_content(HTML)
            page.evaluate('(s)=>window.renderScreen(s)', name)
            page.wait_for_timeout(160)
            assert not errors, errors
            assert not page.locator('.referenceError').count(), page.locator('.referenceError').all_text_contents()
            assert not page.evaluate('document.documentElement.scrollWidth>innerWidth+2'), name + ' overflows'
            page.screenshot(path=str(OUT / f'{mode}-{name}.png'), full_page=True)
            record(mode, name + '_renders_without_js_errors_or_horizontal_overflow')
            return page
        page = screen('landing')
        page.locator('#email').fill('test@example.invalid')
        page.locator('#password').fill('TestPasswordNotUsed123')
        page.locator('#emailLogin').click()
        page.wait_for_function("fixture.calls.some(c=>c.path==='login'&&c.method==='AUTH')")
        record(mode, 'email_login_control_uses_auth_adapter')
        page.locator('#googleLogin').click()
        page.wait_for_function("fixture.calls.some(c=>c.path==='google')")
        record(mode, 'google_login_control_uses_auth_adapter')
        page.close()
        page = screen('onboarding')
        page.locator('[data-choice="experience"][data-value="professional"]').click()
        page.locator('[data-choice="markets"][data-value="US"]').click()
        page.locator('[data-choice="has_holdings"][data-value="yes"]').click()
        page.locator('#nextStep').click()
        page.wait_for_function("lastNavigation==='/watchlist?onboarding=1'")
        assert page.evaluate('fixture.prefs.experience') == 'professional'
        assert 'US' in page.evaluate('fixture.prefs.markets')
        record(mode, 'onboarding_selections_persist_and_navigate')
        page.close()
        page = screen('setup')
        page.locator('#searchResults [data-add-watch]').nth(1).click()
        expect(page.locator('#selected')).to_contain_text('Example Cloud')
        record(mode, 'watchlist_add_updates_count_and_chips')
        page.locator('#addHolding').click()
        expect(page.get_by_role('dialog')).to_be_visible()
        page.locator('[data-select-position]').first.click()
        page.locator('[data-position="0"][data-field="quantity"]').fill('10.25')
        page.locator('[data-position="0"][data-field="average_cost"]').fill('100.50')
        page.locator('#saveAll').click()
        page.wait_for_function('fixture.positions.length===1')
        assert page.evaluate('fixture.positions[0].quantity') == '10.25'
        record(mode, 'holding_modal_inputs_and_save_hit_target_work')
        page.locator('[data-position="0"][data-field="quantity"]').fill('NaN')
        calls = page.evaluate("fixture.calls.filter(c=>c.path==='sb_reference_setup').length")
        page.locator('#saveAll').click()
        page.wait_for_timeout(100)
        assert page.evaluate("fixture.calls.filter(c=>c.path==='sb_reference_setup').length") == calls
        record(mode, 'invalid_holding_is_rejected_before_write')
        page.locator('[data-position="0"][data-field="quantity"]').fill('10.25')
        page.locator('#csv').set_input_files({'name': 'holdings.csv', 'mimeType': 'text/csv', 'buffer': b'ticker,quantity,average_cost,currency\nTEST2,2.5,11.50,USD\n'})
        page.wait_for_function("document.querySelector('#holdings').textContent.includes('Example Cloud')")
        page.locator('#saveAll').click()
        page.wait_for_function("fixture.positions.some(p=>p.company.ticker==='TEST2')")
        record(mode, 'csv_resolves_company_and_preserves_decimal_strings')
        page.locator('[data-remove-position="0"]').click()
        page.locator('#saveAll').click()
        page.wait_for_function('fixture.positions.length===1')
        record(mode, 'holding_delete_is_scoped_to_saved_draft')
        page.close()
        page = screen('today')
        expect(page.locator('.todayItem')).to_have_count(3)
        assert page.locator('.todayItem a[href^="/events/"]').count() > 0
        record(mode, 'today_cards_link_to_actual_event_ids')
        page.close()
        page = screen('detail')
        expect(page.locator('#analysisGrid .analysisBox')).to_have_count(6)
        page.locator('#evidenceTabs [data-source="news"]').click()
        expect(page.locator('#evidenceList')).to_contain_text('근거가 없습니다')
        page.locator('#evidenceTabs [data-source="filing"]').click()
        expect(page.locator('#evidenceList .evi')).to_have_count(1)
        record(mode, 'six_analysis_panels_and_evidence_filters')
        page.locator('[data-toggle-evidence]').click()
        expect(page.locator('.evidencePane')).to_be_hidden()
        page.locator('[data-toggle-evidence]').click()
        expect(page.locator('.evidencePane')).to_be_visible()
        record(mode, 'evidence_panel_can_close_and_reopen')
        page.close()
        page = screen('timeline')
        page.locator('[data-type="guidance"]').click()
        expect(page.locator('#tlCount')).to_have_text('0')
        page.locator('[data-type="all"]').click()
        expect(page.locator('#tlCount')).to_have_text('1')
        page.locator('[data-period="1y"]').click()
        page.wait_for_function("fixture.calls.some(c=>c.path.includes('days=365'))")
        record(mode, 'timeline_type_and_period_controls_query_correct_data')
        page.close()
        page = screen('chat')
        page.locator('#question').fill('이전과 무엇이 바뀌었나요?')
        page.locator('#askForm button').click()
        expect(page.locator('.msg.ai')).to_have_count(1)
        expect(page.locator('.msg.ai')).to_contain_text('원문 근거')
        assert page.evaluate('fixture.history.length') == 1
        record(mode, 'question_send_renders_returned_answer_and_citation')
        page.locator('[data-chat-history]').click()
        expect(page.get_by_role('dialog')).to_contain_text('이전과 무엇이')
        record(mode, 'question_history_is_interactive')
        page.close()
        page = screen('calendar')
        old = page.locator('#monthLabel').inner_text()
        page.locator('#next').click()
        assert page.locator('#monthLabel').inner_text() != old
        page.locator('#todayBtn').click()
        assert page.locator('#monthLabel').inner_text() == old
        record(mode, 'calendar_month_navigation_and_today')
        page.locator('[data-new-calendar]').click()
        page.locator('#newCalendarTitle').fill('New personal test')
        page.locator('#newCalendarDate').fill('2030-01-15')
        page.locator('#calendarAdd button[type="submit"]').click()
        page.wait_for_function("fixture.calendar.some(e=>e.title==='New personal test')")
        record(mode, 'personal_calendar_form_saves')
        page.locator('#todayBtn').click()
        page.locator('[data-reminder]').first.click()
        page.wait_for_function('fixture.reminders.length===1')
        record(mode, 'calendar_interest_switch_persists')
        page.close()
        page = screen('alerts')
        page.locator('#markRead').click()
        page.wait_for_function('fixture.notifications.every(n=>n.read_at)')
        expect(page.locator('#unreadN')).to_have_text('(0)')
        record(mode, 'mark_all_read_refreshes_unread_count')
        page.locator('[data-manage-rules]').click()
        page.locator('[data-new-rule]').click()
        page.locator('#ruleName').fill('New test rule')
        page.locator('#ruleForm button[type="submit"]').click()
        expect(page.locator('#alertList')).to_contain_text('New test rule')
        record(mode, 'alert_rule_create_roundtrip')
        page.locator('[data-threshold="0.7"]').click()
        page.wait_for_function('fixture.prefs.notify_min_score===.7')
        record(mode, 'alert_threshold_persisted')
        page.close()
        page = screen('ops')
        expect(page.locator('#opsKpis .kpi')).to_have_count(10)
        page.locator('[data-range="7d"]').click()
        page.wait_for_function("fixture.calls.some(c=>c.path==='sb_reference_ops'&&c.payload.p.range==='7d')")
        record(mode, 'ops_range_controls_query_admin_metrics')
        page.locator('[data-filter-table="reviewTable"]').fill('not-present')
        expect(page.locator('#reviewTable tbody tr[data-search-text]')).to_be_hidden()
        record(mode, 'ops_table_filters_apply')
        page.close()
        context.close()
    browser.close()
(OUT / 'checks.json').write_text(json.dumps(results, ensure_ascii=False, indent=2))
print(json.dumps({'passed': len(results), 'results': results}, ensure_ascii=False, indent=2))
