'use client';
import Link from 'next/link';
import {useEffect,useState,type FormEvent} from 'react';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {useResource} from '@/components/ui';
import {body,emptySchema,errorMessage,request} from '@/lib/api';
import {alertsSchema,alertSchema,notificationsSchema,portfolioSchema} from '@/lib/contracts';
import {typeLabels} from '@/lib/format';
import {usePrefs} from '@/workspace/preferences';
import {useMutation} from '@/workspace/ui';
import {ActionNotice,CompanyLogo,Dialog,EmptyState,LoadState,MIcon,eventLabel,relativeTime} from '@/mobile/ui';
import {useMobileAlertBadge} from './shell';
import './calendar-alerts.css';
type AlertRule=z.infer<typeof alertSchema>;
export function notificationDateGroup(iso:string,now:number,timeZone:string):'today'|'yesterday'|'week'|'older'{
 const day=(time:number)=>new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(time),today=day(now),created=day(Date.parse(iso)),date=Date.parse(`${today}T00:00:00Z`),yesterday=new Date(date-86400000).toISOString().slice(0,10),weekday=(new Date(date).getUTCDay()+6)%7,weekStart=new Date(date-weekday*86400000).toISOString().slice(0,10);
 return created===today?'today':created===yesterday?'yesterday':created>=weekStart&&created<=today?'week':'older';
}
export default function MobileAlerts(){
 const {token}=useAuth(),{text:t,value}=usePrefs(),action=useMutation(),notices=useResource('/v1/notifications?limit=100',notificationsSchema),rules=useResource('/v1/alerts',alertsSchema),portfolio=useResource('/v1/portfolio',portfolioSchema),setBadge=useMobileAlertBadge();
 const [tab,setTab]=useState('all'),[company,setCompany]=useState(''),[type,setType]=useState(''),[period,setPeriod]=useState('all'),[showRules,setShowRules]=useState(false),[editor,setEditor]=useState<AlertRule|'new'|null>(null),[name,setName]=useState(''),[threshold,setThreshold]=useState(.4),[types,setTypes]=useState<string[]>([]),[enabled,setEnabled]=useState(true),[now,setNow]=useState(Date.now);
 const reload=notices.reload;useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible'){setNow(Date.now());reload();}},60000);return()=>clearInterval(timer);},[reload]);
 useEffect(()=>{if(notices.data)setBadge(notices.data.filter(item=>!item.read_at).length);},[notices.data,setBadge]);
 const unread=notices.data?.filter(item=>!item.read_at)??[],held=new Set(portfolio.data?.positions.map(p=>p.company.id)),heldNotices=notices.data?.filter(item=>held.has(item.event.company.id))??[];
 const companies=[...new Map((notices.data??[]).map(item=>[item.event.company.id,item.event.company])).values()].sort((a,b)=>a.name.localeCompare(b.name,value.locale)),eventTypes=[...new Set(notices.data?.map(item=>item.event.event_type)??[])];
 const shown=(notices.data??[]).filter(item=>(tab!=='unread'||!item.read_at)&&(tab!=='portfolio'||held.has(item.event.company.id))&&(!company||item.event.company.id===company)&&(!type||item.event.event_type===type)&&(period==='all'||period==='today'&&notificationDateGroup(item.created_at,now,value.timezone)==='today'||period==='7'&&Date.parse(item.created_at)>=now-7*86400000||period==='30'&&Date.parse(item.created_at)>=now-30*86400000)).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const groups=[['today',t('오늘','Today')],['yesterday',t('어제','Yesterday')],['week',t('이번 주','This week')],['older',t('이전 알림','Earlier')]];
 async function markRead(id:string){await request(`/v1/notifications/${encodeURIComponent(id)}/read`,token,emptySchema,body('PUT')).catch(e=>{throw new Error(errorMessage(e));});notices.reload();}
 function edit(rule?:AlertRule){setEditor(rule??'new');setName(rule?.name??'');setThreshold(rule?.min_score??.4);setTypes(rule?.event_types??[]);setEnabled(rule?.enabled??true);}
 function submit(event:FormEvent){event.preventDefault();void action.run(async()=>{if(!name.trim())throw new Error(t('규칙 이름을 입력해 주세요.','Enter a rule name.'));if(!editor)throw new Error(t('수정할 규칙을 선택해 주세요.','Select a rule to edit.'));await request(editor==='new'?'/v1/alerts':`/v1/alerts/${encodeURIComponent(editor.id)}`,token,alertSchema,body(editor==='new'?'POST':'PUT',{name:name.trim(),min_score:threshold,event_types:types,enabled})).catch(e=>{throw new Error(errorMessage(e));});setEditor(null);rules.reload();setShowRules(true);},t('알림 규칙을 저장했습니다.','Alert rule saved.'));}
 function openEvent(id:string,readAt:string|null){if(!readAt)void action.run(()=>markRead(id));}
 return <div className="m-alert-page"><header className="ma-heading"><h1>{t('알림 센터','Notification center')}</h1><p>{t('중요한 투자 소식을 놓치지 않도록 알려드려요.','Keep up with important investment updates.')}</p></header><ActionNotice action={action}/>
 <nav className="ma-tabs" aria-label={t('알림 보기','Notification views')}>{[['all',t('전체','All'),notices.data?.length],['unread',t('읽지 않음','Unread'),notices.data?unread.length:undefined],['company',t('기업','Companies'),notices.data?.length],['portfolio',t('포트폴리오','Portfolio'),portfolio.data&&notices.data?heldNotices.length:undefined]].map(([key,label,count])=><button type="button" key={key} aria-pressed={tab===key&&!showRules} className={tab===key&&!showRules?'active':''} onClick={()=>{setTab(String(key));setShowRules(false);}}>{label} ({count??'—'})</button>)}</nav>
 {!showRules?<><div className="ma-filters"><label><MIcon name="filter" size={18}/><select aria-label={t('알림 유형 필터','Notification type filter')} value={type} onChange={e=>setType(e.target.value)}><option value="">{t('알림 유형','Alert type')}</option>{eventTypes.map(key=><option key={key} value={key}>{eventLabel(key,value.locale)}</option>)}</select></label><label><MIcon name="bank" size={18}/><select aria-label={t('알림 기업 필터','Notification company filter')} value={company} onChange={e=>setCompany(e.target.value)}><option value="">{t('기업','Company')}</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><MIcon name="calendar" size={18}/><span><small>{t('기간','Period')}</small><select aria-label={t('알림 기간 필터','Notification period filter')} value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">{t('전체 기간','All time')}</option><option value="today">{t('오늘','Today')}</option><option value="7">{t('최근 7일','Last 7 days')}</option><option value="30">{t('최근 30일','Last 30 days')}</option></select></span></label></div>
 <LoadState loading={notices.loading} error={notices.error} retry={notices.reload}/>{tab==='portfolio'&&<><LoadState loading={portfolio.loading} error={portfolio.error} retry={portfolio.reload}/><p className="ma-scope-note">{t('현재 보유기업에 연결된 이벤트 알림입니다. 포트폴리오 수익률 알림은 제공하지 않습니다.','Event alerts for your current holdings. Portfolio return alerts are not available.')}</p></>}
 <div className="ma-groups">{!notices.loading&&groups.map(([key,label])=>{const items=shown.filter(item=>notificationDateGroup(item.created_at,now,value.timezone)===key);return items.length>0&&<section key={key}><h2>{label}</h2><div className="ma-list">{items.map(item=><article className={`m-alert-card ma-card ${item.read_at?'':'unread'}`} key={item.id}>{!item.read_at&&<span className="ma-unread-dot" aria-label={t('읽지 않음','Unread')}/>}<Link className="ma-logo" href={`/companies/${item.event.company.id}`} aria-label={item.event.company.name}><CompanyLogo ticker={item.event.company.ticker} size={38}/></Link><div className="ma-content"><header><Link className="m-alert-title ma-title" href={`/events/${item.event.id}`} onClick={()=>openEvent(item.id,item.read_at)}>{item.event.headline}</Link><time dateTime={item.created_at}>{relativeTime(item.created_at,value.locale)}</time></header><p>{item.event.fact_summary||item.event.what_happened}</p><footer><div className="ma-tags"><span className={`ma-event-tag ma-type-${item.event.event_type}`}>{eventLabel(item.event.event_type,value.locale)}</span><Link className="ma-ticker" href={`/companies/${item.event.company.id}`}>{item.event.company.ticker}</Link></div><div className="ma-actions"><Link className="ma-view" href={`/events/${item.event.id}`} onClick={()=>openEvent(item.id,item.read_at)}><svg width="10" height="12" viewBox="0 0 10 12" fill="currentColor" aria-hidden="true"><path d="M1 1v10l8-5Z"/></svg>{t('바로 보기','View')}</Link><button type="button" disabled={action.busy||!!item.read_at} onClick={()=>void action.run(()=>markRead(item.id),t('읽음으로 표시했습니다.','Marked read.'))} aria-label={`${item.event.headline} ${item.read_at?t('읽음','read'):t('읽음으로 표시','mark read')}`}><MIcon name="check" size={13}/>{item.read_at?t('읽음','Read'):t('읽음 처리','Mark read')}</button></div></footer></div></article>)}</div></section>;})}</div>
 {!notices.loading&&notices.data&&!shown.length&&<EmptyState title={tab==='unread'?t('읽지 않은 알림이 없습니다.','You are all caught up.'):t('표시할 알림이 없습니다.','No notifications available.')} description={t('설정한 규칙에 맞는 새로운 이벤트가 게시되면 여기에 표시됩니다.','Newly published events matching your rules appear here.')} href="/settings/notifications" label={t('알림 설정','Notification settings')}/>}
 {notices.data?.length===100&&<p className="ma-scope-note">{t('최근 알림 최대 100개를 표시합니다.','Showing up to 100 recent notifications.')}</p>}
 <section className="ma-summary"><span className="ma-summary-icon"><MIcon name="bell" size={24}/></span><div><strong>{notices.data?(unread.length?t(`읽지 않은 알림 ${unread.length}개가 기다리고 있어요.`,`${unread.length} unread alerts are waiting.`):t('모든 알림을 확인했어요.','You are all caught up.')):t('알림을 확인하고 있어요.','Loading your alerts.')}</strong><p>{t('새 소식의 근거를 확인해 보세요.','Review the evidence behind new updates.')}</p></div><button type="button" disabled={action.busy||!unread.length} onClick={()=>void action.run(()=>markRead('all'),t('모두 읽음으로 표시했습니다.','All notifications marked read.'))}>{t('모두 확인하기','Mark all read')}<MIcon name="chevron" size={14}/></button></section>
 </>:<><div className="ma-rule-heading"><h2>{t('알림 규칙','Alert rules')}</h2><button className="m-button m-button-secondary" disabled={!!rules.data&&rules.data.length>=20} onClick={()=>edit()}><MIcon name="plus" size={15}/>{t('규칙 추가','Add rule')}</button></div><LoadState loading={rules.loading} error={rules.error} retry={rules.reload}/><div className="ma-rules">{!rules.loading&&rules.data?.map(rule=><article className="m-alert-rule ma-rule" key={rule.id}><div><button className="ma-rule-name" onClick={()=>edit(rule)}>{rule.name}<MIcon name="chevron" size={14}/></button><p>{t('중요도','Importance')} {Math.round(rule.min_score*100)} / 100 · {rule.event_types.length?rule.event_types.map(key=>eventLabel(key,value.locale)).join(', '):t('전체 유형','All types')}</p></div><button className={`m-alert-switch ma-rule-switch ${rule.enabled?'on':''}`} role="switch" aria-label={`${rule.name} ${t('사용','enabled')}`} aria-checked={rule.enabled} disabled={action.busy} onClick={()=>void action.run(async()=>{await request(`/v1/alerts/${encodeURIComponent(rule.id)}`,token,alertSchema,body('PUT',{name:rule.name,event_types:rule.event_types,min_score:rule.min_score,enabled:!rule.enabled})).catch(e=>{throw new Error(errorMessage(e));});rules.reload();},t('알림 규칙을 변경했습니다.','Alert rule updated.'))}><span/></button><button className="m-icon-button" aria-label={`${rule.name} ${t('삭제','delete')}`} disabled={action.busy} onClick={()=>void action.run(async()=>{await request(`/v1/alerts/${encodeURIComponent(rule.id)}`,token,emptySchema,body('DELETE')).catch(e=>{throw new Error(errorMessage(e));});rules.reload();},t('규칙을 삭제했습니다.','Rule deleted.'))}><MIcon name="trash" size={17}/></button></article>)}</div>{!rules.loading&&rules.data&&!rules.data.length&&<EmptyState title={t('알림 규칙을 추가해 보세요.','Add your first alert rule.')} description={t('이벤트 유형과 중요도 기준을 선택해 알림을 관리하세요.','Choose event types and an importance threshold.')}/>}<p className="ma-scope-note">{t('최대 20개 규칙을 저장할 수 있어요. 중요도는 수익 가능성이나 수익률이 아닙니다.','You can save up to 20 rules. Importance is not an expected investment return.')}</p></>}
 <div className="ma-tools"><button type="button" onClick={()=>setShowRules(current=>!current)}><MIcon name={showRules?'bell':'filter'} size={14}/>{showRules?t('알림 목록','Notification list'):t('알림 규칙 관리','Manage alert rules')}</button><Link href="/settings/notifications"><MIcon name="settings" size={14}/>{t('알림 설정','Notification settings')}</Link><button type="button" onClick={notices.reload} disabled={notices.loading}><MIcon name="refresh" size={14}/>{t('새로고침','Refresh')}</button></div>
 {editor&&<Dialog title={editor==='new'?t('알림 규칙 만들기','Create alert rule'):t('알림 규칙 수정','Edit alert rule')} onClose={()=>setEditor(null)}><ActionNotice action={action}/><form onSubmit={submit}><label className="m-field"><span>{t('규칙 이름','Rule name')}</span><input autoFocus required value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></label><label className="m-field"><span>{t('중요도 기준','Importance threshold')}: {Math.round(threshold*100)} / 100</span><input type="range" min="0" max="1" step="0.05" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><fieldset className="ma-type-fields"><legend>{t('이벤트 유형','Event types')}</legend>{Object.entries(typeLabels).map(([key,label])=><label key={key}><input type="checkbox" checked={types.includes(key)} onChange={e=>setTypes(current=>e.target.checked?[...current,key]:current.filter(item=>item!==key))}/><span>{value.locale==='ko'?label:key}</span></label>)}</fieldset><p className="m-muted">{t('유형을 선택하지 않으면 전체 유형에 적용합니다.','Selecting no type includes all event types.')}</p><label className="ma-enable"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span>{t('이 규칙 사용','Enable this rule')}</span></label><button className="m-button" disabled={action.busy}>{action.busy?t('저장 중…','Saving…'):t('규칙 저장','Save rule')}</button></form></Dialog>}
 </div>;
}
