'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {usePrefs} from '@/workspace/preferences';
import {catalogSchema} from '@/workspace/contracts';
import {useData,useMutation} from '@/workspace/ui';
import {useQuotes} from '@/workspace/market';
import {ActionNotice,CompanyLogo,LoadState,MIcon,SmallChart,formatMoney} from './ui';
import './appearance.css';

function AppearanceRow({icon,color='',title,description,children,wide=false}:{icon:string;color?:string;title:string;description:string;children:ReactNode;wide?:boolean}){return <section className={`m-card m-appearance-row ${wide?'m-appearance-wide':''}`}><span className={`m-setting-icon ${color}`}><MIcon name={icon} size={25}/></span><div className="m-appearance-copy"><h2>{title}</h2><p>{description}</p></div><div className="m-appearance-control">{children}</div></section>;}

export default function MobileAppearance(){
 const prefs=usePrefs(),{value,text:t}=prefs,action=useMutation(),[font,setFont]=useState(value.font_scale);
 const catalog=useData({action:'catalog',p:{kind:'company',limit:2}},catalogSchema),companies=catalog.data?.items??[];
 const prices=useQuotes(companies.map(x=>x.ticker),'1m');
 useEffect(()=>setFont(value.font_scale),[value.font_scale]);
 const busy=!prefs.loaded||prefs.busy||action.busy;
 const save=(patch:Parameters<typeof prefs.save>[0])=>action.run(()=>prefs.save(patch),t('표시 설정을 저장했습니다.','Display settings saved.'));
 async function commitFont(next:number){if(next===value.font_scale)return;const ok=await save({font_scale:next});if(!ok)setFont(value.font_scale);}

 return <div className="m-appearance-page"><h1 className="m-visually-hidden">{t('화면 및 언어 설정','Appearance & language')}</h1><p className="m-detail-intro">{t('나만의 보기 환경을 설정하여','Choose your display preferences for')}<br/>{t('더 편안한 투자 경험을 만들어보세요.','a more comfortable research experience.')}</p>
 <LoadState loading={!prefs.loaded&&!prefs.error} error={prefs.error} retry={prefs.reload}/><ActionNotice action={action}/>
 <section className="m-appearance-preview" aria-label={t('화면 미리보기','Display preview')}><div><h2>{t('미리보기','Preview')}</h2><p>{t('선택한 설정이 적용된 화면을','See your selected settings')}<br/>{t('미리 확인할 수 있습니다.','in this live preview.')}</p></div><div className="m-preview-phone"><div className="m-preview-brand"><strong>Signal<span>Brief</span></strong><MIcon name="search" size={15}/><span className="m-avatar"><MIcon name="person" size={16}/></span></div><small>{t('세상의 신호를, 더 나은 투자로','A clearer view. A better decision.')}</small><h3>{t('관심종목','Watchlist')}</h3><LoadState loading={catalog.loading} error={catalog.error} retry={catalog.reload}/>{companies.map(company=>{const quote=prices.quotes.find(x=>x.symbol===company.ticker);return <div className={`m-preview-company ${quote?.change_pct==null?'':quote.change_pct<0?'m-preview-fall':'m-preview-rise'}`} key={company.id}><CompanyLogo ticker={company.ticker} size={34}/><div><b>{company.company_name||company.title}</b><small>{company.ticker}</small><strong>{formatMoney(quote?.price,quote?.currency,value.locale==='ko'?'ko-KR':'en-US')}</strong><span className={quote?.change_pct!=null&&quote.change_pct<0?'m-down':'m-up'}>{quote?.change_pct==null?t('시세 확인 전','Quote unavailable'):`${quote.change_pct>0?'+':''}${quote.change_pct.toFixed(2)}%`}</span></div><SmallChart values={quote?.history.map(x=>x.close)??[]}/></div>;})}{catalog.data&&!companies.length&&<p className="m-preview-empty">{t('지원 기업을 불러오면 표시됩니다.','Supported companies appear when available.')}</p>}</div></section>
 <div className="m-appearance-rows">
 <AppearanceRow icon="sun" title={t('테마 모드','Theme mode')} description={t('앱 전체의 색상 테마를 설정합니다.','Choose the app’s color theme.')}><div className="m-segments" role="radiogroup" aria-label={t('테마 모드','Theme mode')}>{[['light','라이트','Light'],['dark','다크','Dark'],['system','시스템','System']].map(([key,ko,en])=><button type="button" key={key} role="radio" aria-checked={value.theme===key} disabled={busy} onClick={()=>void save({theme:key as typeof value.theme})}>{t(ko,en)}</button>)}</div></AppearanceRow>
 <AppearanceRow icon="file" color="purple" title={t('화면 밀도','Layout density')} description={t('카드와 항목 사이 간격을 조절합니다.','Adjust spacing between cards and items.')}><div className="m-segments" role="radiogroup" aria-label={t('화면 밀도','Layout density')}>{[['compact','컴팩트','Compact'],['comfortable','편안함','Comfortable']].map(([key,ko,en])=><button type="button" key={key} role="radio" aria-checked={value.ui_density===key} disabled={busy} onClick={()=>void save({ui_density:key as typeof value.ui_density})}>{t(ko,en)}</button>)}</div></AppearanceRow>
 <AppearanceRow icon="font" color="green" title={t('글자 크기','Text size')} description={t('앱에서 표시되는 글자의 크기를 조절합니다.','Adjust text size throughout the app.')} wide><input type="range" min="0" max="3" step="1" value={font} aria-label={t('글자 크기','Text size')} aria-valuetext={[t('작게','Small'),t('보통','Default'),t('크게','Large'),t('아주 크게','Largest')][font]} disabled={busy} onChange={e=>setFont(Number(e.target.value))} onPointerUp={e=>void commitFont(Number(e.currentTarget.value))} onKeyUp={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))void commitFont(Number(e.currentTarget.value));}} onBlur={e=>void commitFont(Number(e.currentTarget.value))}/><div className="m-appearance-range-labels">{[t('작게','Small'),t('보통','Default'),t('크게','Large'),t('아주 크게','Largest')].map((label,index)=><span key={index} className={font===index?'active':''}>{label}</span>)}</div></AppearanceRow>
 <AppearanceRow icon="bars" color="purple" title={t('차트 애니메이션','Chart animation')} description={t('차트의 움직임과 전환 효과를 표시합니다.','Show motion and transitions in charts.')}><button type="button" role="switch" className="m-switch" aria-label={t('차트 애니메이션','Chart animation')} aria-checked={value.chart_animation&&!value.reduced_motion} disabled={busy||value.reduced_motion} onClick={()=>void save({chart_animation:!value.chart_animation})}><span/></button></AppearanceRow>
 <AppearanceRow icon="motion" color="teal" title={t('움직임 최소화','Reduce motion')} description={t('화면 전환과 애니메이션 효과를 최소화합니다.','Reduce transitions and animation effects.')}><button type="button" role="switch" className="m-switch" aria-label={t('움직임 최소화','Reduce motion')} aria-checked={value.reduced_motion} disabled={busy} onClick={()=>void save({reduced_motion:!value.reduced_motion})}><span/></button></AppearanceRow>
 <AppearanceRow icon="globe" title={t('앱 언어','App language')} description={t('앱에 표시되는 언어를 선택합니다.','Choose the language used in the app.')}><div className="m-segments" role="radiogroup" aria-label={t('앱 언어','App language')}>{[['ko','한국어','Korean'],['en','영어','English']].map(([key,ko,en])=><button type="button" key={key} role="radio" aria-checked={value.locale===key} disabled={busy} onClick={()=>void save({locale:key as 'ko'|'en'})}>{t(ko,en)}</button>)}</div></AppearanceRow>
 </div><aside className="m-appearance-note"><span className="m-setting-icon"><MIcon name="info" size={24}/></span><div><strong>{t('설정이 저장 후 즉시 적용됩니다.','Settings apply as soon as they are saved.')}</strong><p>{t('같은 계정으로 다시 접속해도 유지됩니다.','Your settings are kept when you return to this account.')}</p></div></aside></div>;
}
