'use client';
import Link from 'next/link';
import {useState,type FormEvent} from 'react';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {useResource} from '@/components/ui';
import {API_URL,body,emptySchema,errorMessage,request} from '@/lib/api';
import {calendarSchema,companiesSchema,portfolioSchema,watchlistSchema} from '@/lib/contracts';
import {downloadText,monthDays} from '@/lib/product';
import {usePrefs} from '@/workspace/preferences';
import {safeSource} from '@/workspace/contracts';
import {useMutation} from '@/workspace/ui';
import {MIcon,SectionTitle,EmptyState,LoadState,ActionNotice,Dialog} from '@/mobile/ui';
import './collections.css';

type CalendarItem=z.infer<typeof calendarSchema>[number];
const dateKey=(time:number,timeZone:string)=>new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(time));
export default function MobileCalendar(){
 const {token}=useAuth(),{text:t,value,date:displayDate}=usePrefs(),action=useMutation(),[today]=useState(()=>dateKey(Date.now(),value.timezone)),[month,setMonth]=useState(()=>({year:Number(today.slice(0,4)),month:Number(today.slice(5,7))-1})),[selected,setSelected]=useState(''),[scope,setScope]=useState('all'),[add,setAdd]=useState(false),[detail,setDetail]=useState<CalendarItem|null>(null),[title,setTitle]=useState(''),[date,setDate]=useState(today),[company,setCompany]=useState('');
 const days=monthDays(month.year,month.month),first=days[0].date,last=days.at(-1)!.date,result=useResource(`/v1/calendar?from_date=${first}&until_date=${last}`,calendarSchema),watch=useResource('/v1/watchlist',watchlistSchema),portfolio=useResource('/v1/portfolio',portfolioSchema),catalog=useResource(add?'/v1/companies?limit=50':null,companiesSchema);
 const watched=new Set(watch.data?.items.map(c=>c.id)),held=new Set(portfolio.data?.positions.map(p=>p.company.id));
 const items=(result.data??[]).filter(item=>scope==='all'||scope==='watchlist'&&!!item.company_id&&watched.has(item.company_id)||scope==='portfolio'&&!!item.company_id&&held.has(item.company_id)||scope==='user'&&item.origin==='user'||scope==='official'&&item.origin==='official');
 const currentPrefix=`${month.year}-${String(month.month+1).padStart(2,'0')}`,shown=items.filter(item=>selected?item.occurs_on===selected:item.occurs_on.startsWith(currentPrefix)).sort((a,b)=>a.occurs_on.localeCompare(b.occurs_on)||a.title.localeCompare(b.title,value.locale));
 const monthName=new Intl.DateTimeFormat(value.locale==='ko'?'ko-KR':'en-US',{timeZone:'UTC',year:'numeric',month:'long'}).format(new Date(Date.UTC(month.year,month.month,1)));
 function move(delta:number){const next=new Date(Date.UTC(month.year,month.month+delta,1));setMonth({year:next.getUTCFullYear(),month:next.getUTCMonth()});setSelected('');}
 function choose(day:string){setSelected(day);setDate(day);}
 async function remove(item:CalendarItem){await request(`/v1/calendar/${encodeURIComponent(item.id)}`,token,emptySchema,body('DELETE')).catch(e=>{throw new Error(errorMessage(e));});setDetail(null);result.reload();}
 function submit(event:FormEvent){event.preventDefault();void action.run(async()=>{if(!title.trim())throw new Error(t('제목을 입력해 주세요.','Enter a title.'));await request('/v1/calendar',token,calendarSchema.element,body('POST',{title:title.trim(),occurs_on:date,company_id:company||null})).catch(e=>{throw new Error(errorMessage(e));});setMonth({year:Number(date.slice(0,4)),month:Number(date.slice(5,7))-1});setSelected(date);setTitle('');setAdd(false);result.reload();},t('내 일정을 저장했습니다.','Your schedule was saved.'));}
 async function exportCalendar(){await action.run(async()=>{if(!token)throw new Error(t('로그인이 필요합니다.','Sign in first.'));const response=await fetch(`${API_URL}/v1/calendar/export`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store',signal:AbortSignal.timeout(25000)});if(!response.ok)throw new Error(t('일정을 내보내지 못했습니다.','Calendar export failed.'));downloadText(await response.text(),'signalbrief-calendar.ics','text/calendar;charset=utf-8');},t('캘린더 파일을 만들었습니다.','Calendar file downloaded.'));}
 return <div className="m-calendar-page"><header className="m-calendar-heading"><div><h1>{t('캘린더','Calendar')}</h1><p>{t('중요한 기업 일정과 나의 확인 일정을 모아보세요.','Company dates and your own research reminders.')}</p></div><button className="m-button m-button-secondary" onClick={()=>{setDate(selected||today);setAdd(true);}}><MIcon name="plus" size={17}/>{t('일정 추가','Add date')}</button></header><ActionNotice action={action}/>
 <nav className="m-calendar-scopes" aria-label={t('일정 범위','Calendar scope')}>{[['all',t('전체','All')],['portfolio',t('보유종목','Holdings')],['watchlist',t('관심종목','Watchlist')],['official',t('공식 일정','Official')],['user',t('내 일정','My dates')]].map(([key,label])=><button key={key} aria-pressed={scope===key} className={scope===key?'active':''} onClick={()=>setScope(key)}>{label}</button>)}</nav>
 <section className="m-card m-calendar-month"><header><button className="m-icon-button" onClick={()=>move(-1)} aria-label={t('이전 달','Previous month')}><MIcon name="back" size={20}/></button><h2>{monthName}</h2><button className="m-icon-button" onClick={()=>move(1)} aria-label={t('다음 달','Next month')}><MIcon name="chevron" size={20}/></button><button className="m-calendar-today" onClick={()=>{setMonth({year:Number(today.slice(0,4)),month:Number(today.slice(5,7))-1});choose(today);}}>{t('오늘','Today')}</button></header><div className="m-calendar-weekdays">{(value.locale==='ko'?['일','월','화','수','목','금','토']:['Sun','Mon','Tue','Wed','Thu','Fri','Sat']).map(label=><span key={label}>{label}</span>)}</div><div className="m-calendar-grid">{days.map(day=>{const dates=items.filter(item=>item.occurs_on===day.date);return <button key={day.date} className={`${day.current?'':'other'} ${day.date===today?'today':''} ${selected===day.date?'selected':''}`} aria-label={`${day.date} · ${dates.length}${t('개 일정',' scheduled items')}`} aria-pressed={selected===day.date} onClick={()=>choose(day.date)}><strong>{day.day}</strong><span>{dates.slice(0,3).map(item=><i key={item.id} className={item.origin==='user'?'personal':''}/>)}{dates.length>3&&<small>+{dates.length-3}</small>}</span></button>;})}</div><footer><span><i/>{t('공식 일정','Official')}</span><span><i className="personal"/>{t('내 일정','My dates')}</span><button disabled={action.busy} onClick={()=>void exportCalendar()}><MIcon name="download" size={14}/>{t('내보내기','Export')}</button></footer></section>
 <LoadState loading={result.loading} error={result.error??undefined} retry={result.reload}/>{scope==='portfolio'&&<LoadState loading={portfolio.loading} error={portfolio.error??undefined} retry={portfolio.reload}/>} {scope==='watchlist'&&<LoadState loading={watch.loading} error={watch.error??undefined} retry={watch.reload}/>}
 <SectionTitle title={selected?displayDate(selected,'date'):t('이번 달 일정','This month')} action={selected?<button className="m-calendar-text" onClick={()=>setSelected('')}>{t('월 전체 보기','All dates this month')}</button>:undefined}/><div className="m-calendar-events">{!result.loading&&shown.map(item=>{const source=safeSource(item.source_url),href=item.event_id?`/events/${item.event_id}`:null;return <article className="m-card m-calendar-item" key={item.id}><div className="m-calendar-date"><strong>{Number(item.occurs_on.slice(8,10))}</strong><span>{item.occurs_on.slice(0,7)}</span></div><div><div className="m-calendar-item-meta"><span className={`m-pill ${item.origin==='user'?'personal':''}`}>{item.origin==='user'?t('내 일정','My date'):t('공식 일정','Official')}</span><small>{t('종일','All day')}</small></div>{href?<Link href={href} className="m-calendar-item-title">{item.title}<MIcon name="chevron" size={16}/></Link>:<button className="m-calendar-item-title" onClick={()=>setDetail(item)}>{item.title}<MIcon name="chevron" size={16}/></button>}{item.quote&&<p>{item.quote}</p>}<div className="m-calendar-item-links">{item.company_id&&<Link href={`/companies/${item.company_id}`}>{t('기업 개요','Company overview')}</Link>}{source&&<a href={source} target="_blank" rel="noopener noreferrer">{t('근거 / 출처','Source')}<MIcon name="external" size={12}/></a>}</div></div>{item.origin==='user'&&<button className="m-icon-button" disabled={action.busy} aria-label={`${item.title} ${t('삭제','delete')}`} onClick={()=>void action.run(()=>remove(item),t('일정을 삭제했습니다.','Schedule removed.'))}><MIcon name="trash" size={17}/></button>}</article>;})}</div>{!result.loading&&result.data&&!shown.length&&<EmptyState title={t('등록된 일정이 없습니다.','No dates scheduled.')} description={t('공식 자료에서 확인된 일정이나 직접 등록한 날짜가 여기에 표시됩니다.','Dates confirmed in official sources and your personal dates appear here.')}/>}
 <p className="m-calendar-note">{t('공시에서 확인된 날짜를 그대로 표시합니다. 확인되지 않은 실적 발표일을 예상해서 채우지 않습니다.','Dates follow their source. Unconfirmed earnings dates are not guessed.')}{result.data?.length===500&&t(' 현재 불러온 최대 500개 일정을 표시합니다.',' Showing up to 500 loaded dates.')}</p>
 {add&&<Dialog title={t('내 확인 일정 추가','Add a research date')} onClose={()=>setAdd(false)}><ActionNotice action={action}/><form onSubmit={submit}><label className="m-field"><span>{t('제목','Title')}</span><input autoFocus required value={title} maxLength={200} onChange={e=>setTitle(e.target.value)} placeholder={t('확인할 내용을 입력하세요','What would you like to review?')}/></label><label className="m-field"><span>{t('날짜','Date')}</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="m-field"><span>{t('관련 기업 · 선택','Company · optional')}</span><select value={company} onChange={e=>setCompany(e.target.value)}><option value="">{t('선택하지 않음','None')}</option>{catalog.data?.map(c=><option key={c.id} value={c.id}>{c.name} · {c.ticker}</option>)}</select></label><LoadState loading={catalog.loading} error={catalog.error??undefined} retry={catalog.reload}/><button className="m-button" disabled={action.busy}>{action.busy?t('저장 중…','Saving…'):t('일정 저장','Save date')}</button></form></Dialog>}
 {detail&&<Dialog title={t('일정 상세','Schedule details')} onClose={()=>setDetail(null)}><div className="m-calendar-details"><strong>{detail.title}</strong><p>{displayDate(detail.occurs_on,'date')} · {t('종일','All day')}</p>{detail.quote&&<blockquote>{detail.quote}</blockquote>}{detail.company_id&&<Link className="m-button m-button-secondary" href={`/companies/${detail.company_id}`}>{t('기업 개요','Company overview')}<MIcon name="chevron" size={15}/></Link>}{safeSource(detail.source_url)&&<a className="m-button m-button-secondary" href={safeSource(detail.source_url)} target="_blank" rel="noopener noreferrer">{t('근거 / 출처','Source')}<MIcon name="external" size={15}/></a>}{detail.origin==='user'&&<button className="m-button m-portfolio-delete" disabled={action.busy} onClick={()=>void action.run(()=>remove(detail),t('일정을 삭제했습니다.','Schedule removed.'))}>{t('일정 삭제','Delete date')}</button>}<ActionNotice action={action}/></div></Dialog>}
 </div>;
}
