'use client';

import Link from 'next/link';
import {useEffect,useState,type FormEvent} from 'react';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {useResource} from '@/components/ui';
import {API_URL,body,emptySchema,errorMessage,request} from '@/lib/api';
import {calendarSchema,companiesSchema,feedSchema,portfolioSchema,watchlistSchema} from '@/lib/contracts';
import {downloadText,monthDays} from '@/lib/product';
import {initializeSupabase} from '@/lib/supabase';
import {safeSource} from '@/workspace/contracts';
import {usePrefs} from '@/workspace/preferences';
import {useMutation} from '@/workspace/ui';
import {ActionNotice,CompanyLogo,Dialog,EmptyState,LoadState,MIcon,eventLabel} from '@/mobile/ui';
import './calendar-alerts.css';

type CalendarItem=z.infer<typeof calendarSchema>[number];
const remindersSchema=z.array(z.object({calendar_id:z.string()})),reminderSavedSchema=z.object({saved:z.literal(true),delivery:z.literal('saved_interest_only')});
export const calendarDateKey=(time:number,timeZone:string)=>new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(time));
const shiftDate=(date:string,days:number)=>new Date(Date.parse(`${date}T00:00:00Z`)+days*86400000).toISOString().slice(0,10);
export default function MobileCalendar(){
 const {token}=useAuth(),{text:t,value,date:displayDate}=usePrefs(),action=useMutation(),[now]=useState(Date.now),today=calendarDateKey(now,value.timezone);
 const [monthOverride,setMonth]=useState<{year:number;month:number}|null>(null),month=monthOverride??{year:Number(today.slice(0,4)),month:Number(today.slice(5,7))-1};
 const [selected,setSelected]=useState(''),[tab,setTab]=useState('calendar'),[scope,setScope]=useState('all'),[category,setCategory]=useState('all'),[sort,setSort]=useState('asc'),[weekly,setWeekly]=useState(false),[add,setAdd]=useState(false),[detail,setDetail]=useState<CalendarItem|null>(null),[title,setTitle]=useState(''),[date,setDate]=useState(''),[company,setCompany]=useState('');
 const [reminders,setReminders]=useState<Set<string>>(new Set()),[reminderLoading,setReminderLoading]=useState(true),[reminderError,setReminderError]=useState(''),[revision,setRevision]=useState(0);
 const days=monthDays(month.year,month.month),first=days[0].date,last=days.at(-1)!.date,weekEnd=shiftDate(today,6);
 const gridDays=days[35].current?days:days.slice(0,35);
 const result=useResource(`/v1/calendar?from_date=${first}&until_date=${last}`,calendarSchema),watch=useResource('/v1/watchlist',watchlistSchema),portfolio=useResource('/v1/portfolio',portfolioSchema),feed=useResource('/v1/feed?days=180&limit=100',feedSchema),catalog=useResource(add?'/v1/companies?limit=50':null,companiesSchema),weekDates=useResource(`/v1/calendar?from_date=${today}&until_date=${weekEnd}`,calendarSchema);
 useEffect(()=>{let alive=true;const ctrl=new AbortController();setReminders(new Set());setReminderLoading(true);setReminderError('');if(!token){setReminderLoading(false);return;}void (async()=>{try{const db=await initializeSupabase();const response=await db.rpc('sb_reference_reminders',{p:{action:'list'}}).abortSignal(AbortSignal.any([ctrl.signal,AbortSignal.timeout(20000)]));if(response.error)throw new Error(t('관심 일정을 불러오지 못했습니다. 다시 시도해 주세요.','Saved dates could not be loaded. Please retry.'));const items=remindersSchema.parse(response.data);if(alive)setReminders(new Set(items.map(item=>item.calendar_id)));}catch(e){if(alive)setReminderError(errorMessage(e));}finally{if(alive)setReminderLoading(false);}})();return()=>{alive=false;ctrl.abort();};},[token,revision,t]);
 const watched=new Set(watch.data?.items.map(c=>c.id)),held=new Set(portfolio.data?.positions.map(p=>p.company.id)),events=new Map(feed.data?.items.map(item=>[item.id,item]));
 const companies=new Map([...watch.data?.items??[],...portfolio.data?.positions.map(p=>p.company)??[],...feed.data?.items.map(item=>item.company)??[]].map(c=>[c.id,c]));
 const itemCategory=(item:CalendarItem)=>item.origin==='user'?'personal':events.get(item.event_id??'')?.event_type??'official';
 const items=(weekly?weekDates.data??[]:result.data??[]).filter(item=>(tab!=='mine'||item.origin==='user')&&(tab!=='theme'||!!item.company_id)&&(scope==='all'||scope==='watchlist'&&!!item.company_id&&watched.has(item.company_id)||scope==='portfolio'&&!!item.company_id&&held.has(item.company_id)||scope==='user'&&item.origin==='user'||scope==='official'&&item.origin==='official'));
 const currentPrefix=`${month.year}-${String(month.month+1).padStart(2,'0')}`;
 const dated=items.filter(item=>weekly?item.occurs_on>=today&&item.occurs_on<=weekEnd:selected?item.occurs_on===selected:item.occurs_on.startsWith(currentPrefix)&&(tab!=='upcoming'||item.occurs_on>=today));
 const categories=['all',...new Set(dated.map(itemCategory))],categoryLabel=(key:string)=>key==='all'?t('전체','All'):key==='personal'?t('내 일정','My dates'):key==='official'?t('공식 일정','Official dates'):key==='earnings'?t('실적발표','Earnings'):eventLabel(key,value.locale);
 const shown=dated.filter(item=>category==='all'||itemCategory(item)===category).sort((a,b)=>(sort==='asc'?1:-1)*(a.occurs_on.localeCompare(b.occurs_on)||a.title.localeCompare(b.title,value.locale)));
 const weekCount=weekDates.data?.filter(item=>item.occurs_on>=today&&item.occurs_on<=weekEnd).length,monthName=new Intl.DateTimeFormat(value.locale==='ko'?'ko-KR':'en-US',{timeZone:'UTC',year:'numeric',month:'long'}).format(new Date(Date.UTC(month.year,month.month,1)));
 function move(delta:number){const next=new Date(Date.UTC(month.year,month.month+delta,1));setMonth({year:next.getUTCFullYear(),month:next.getUTCMonth()});setSelected('');setWeekly(false);setCategory('all');}
 function choose(day:string){setSelected(current=>current===day?'':day);setDate(day);setWeekly(false);setCategory('all');}
 async function reminder(item:CalendarItem){const enabled=!reminders.has(item.id),db=await initializeSupabase();const response=await db.rpc('sb_reference_reminders',{p:{action:'set',calendar_id:item.id,enabled}}).abortSignal(AbortSignal.timeout(20000));if(response.error)throw new Error(t('관심 일정을 저장하지 못했습니다. 다시 시도해 주세요.','Saved date could not be updated. Please retry.'));reminderSavedSchema.parse(response.data);setReminders(current=>{const next=new Set(current);if(enabled)next.add(item.id);else next.delete(item.id);return next;});}
 async function remove(item:CalendarItem){await request(`/v1/calendar/${encodeURIComponent(item.id)}`,token,emptySchema,body('DELETE')).catch(e=>{throw new Error(errorMessage(e));});setDetail(null);result.reload();weekDates.reload();setRevision(x=>x+1);}
 function submit(event:FormEvent){event.preventDefault();void action.run(async()=>{if(!title.trim())throw new Error(t('제목을 입력해 주세요.','Enter a title.'));await request('/v1/calendar',token,calendarSchema.element,body('POST',{title:title.trim(),occurs_on:date,company_id:company||null})).catch(e=>{throw new Error(errorMessage(e));});setMonth({year:Number(date.slice(0,4)),month:Number(date.slice(5,7))-1});setSelected(date);setWeekly(false);setCategory('all');setTitle('');setAdd(false);result.reload();weekDates.reload();},t('내 일정을 저장했습니다.','Your schedule was saved.'));}
 async function exportCalendar(){await action.run(async()=>{if(!token)throw new Error(t('로그인이 필요합니다.','Sign in first.'));const response=await fetch(`${API_URL}/v1/calendar/export`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store',signal:AbortSignal.timeout(25000)});if(!response.ok)throw new Error(t('일정을 내보내지 못했습니다.','Calendar export failed.'));downloadText(await response.text(),'signalbrief-calendar.ics','text/calendar;charset=utf-8');},t('캘린더 파일을 만들었습니다.','Calendar file downloaded.'));}
 return <div className="m-calendar-page"><header className="mc-heading"><h1>{t('캘린더','Calendar')}</h1><p>{t('다가오는 중요한 투자 일정을 한눈에 확인하세요.','See upcoming dates that matter to your investments.')}</p></header><ActionNotice action={action}/>
  <nav className="mc-tabs" aria-label={t('캘린더 보기','Calendar views')}>{[['calendar',t('캘린더','Calendar')],['upcoming',t('주요 일정','Upcoming')],['theme',t('테마 일정','By event type')],['mine',t('내 일정','My dates')]].map(([key,label])=><button type="button" key={key} aria-pressed={tab===key} className={tab===key?'active':''} onClick={()=>{setTab(key);setSelected('');setWeekly(false);setCategory('all');setScope('all');}}>{label}</button>)}</nav>
  <section className="mc-month"><header><div className="mc-month-nav"><button className="m-icon-button" onClick={()=>move(-1)} aria-label={t('이전 달','Previous month')}><MIcon name="back" size={17}/></button><h2>{monthName}</h2><button className="m-icon-button" onClick={()=>move(1)} aria-label={t('다음 달','Next month')}><MIcon name="chevron" size={17}/></button></div><button className="mc-today" onClick={()=>{setMonth(null);setSelected(today);setWeekly(false);setCategory('all');}}>{t('오늘','Today')}</button></header><div className="mc-weekdays">{(value.locale==='ko'?['일','월','화','수','목','금','토']:['Sun','Mon','Tue','Wed','Thu','Fri','Sat']).map(label=><span key={label}>{label}</span>)}</div><div className="m-calendar-grid mc-grid">{gridDays.map(day=>{const dates=items.filter(item=>item.occurs_on===day.date);return <button type="button" key={day.date} className={`${day.current?'':'other'} ${day.date===today?'today':''} ${selected===day.date?'selected':''}`} aria-label={`${day.date} · ${dates.length}${t('개 일정',' scheduled items')}`} aria-pressed={selected===day.date} onClick={()=>choose(day.date)}><strong>{day.day}</strong><span>{dates.length>0&&<i/>}</span></button>;})}</div></section>
  {tab==='theme'&&<label className="mc-scope"><span>{t('종목 범위','Company scope')}</span><select value={scope} onChange={e=>{setScope(e.target.value);setCategory('all');}}><option value="all">{t('전체 기업','All companies')}</option><option value="watchlist">{t('관심종목','Watchlist')}</option><option value="portfolio">{t('보유종목','Holdings')}</option><option value="official">{t('공식 일정','Official dates')}</option></select></label>}
  <div className="mc-categories" aria-label={t('일정 유형 필터','Schedule type filter')}>{categories.map(key=><button type="button" key={key} className={category===key?'active':''} aria-pressed={category===key} onClick={()=>setCategory(key)}>{categoryLabel(key)} ({key==='all'?dated.length:dated.filter(item=>itemCategory(item)===key).length})</button>)}</div>
  <LoadState loading={weekly?weekDates.loading:result.loading} error={weekly?weekDates.error:result.error} retry={weekly?weekDates.reload:result.reload}/><LoadState loading={false} error={reminderError} retry={()=>setRevision(x=>x+1)}/>{scope==='portfolio'&&<LoadState loading={portfolio.loading} error={portfolio.error} retry={portfolio.reload}/>} {scope==='watchlist'&&<LoadState loading={watch.loading} error={watch.error} retry={watch.reload}/>} {tab==='theme'&&<LoadState loading={feed.loading} error={feed.error} retry={feed.reload}/>}
  <div className="mc-list-heading"><h2>{selected?displayDate(selected,'date'):weekly?t('이번 주 일정','This week'):tab==='mine'?t('내 일정','My dates'):t('예정된 주요 일정','Scheduled dates')} <span>{shown.length}{t('개','')}</span></h2><select aria-label={t('일정 정렬','Schedule sort')} value={sort} onChange={e=>setSort(e.target.value)}><option value="asc">{t('날짜 빠른 순','Earliest first')}</option><option value="desc">{t('날짜 늦은 순','Latest first')}</option></select></div>
  {(selected||weekly)&&<button className="mc-text-link" onClick={()=>{setSelected('');setWeekly(false);setCategory('all');}}>{t('월 전체 보기','All dates this month')}</button>}
  <div className="mc-events">{!result.loading&&shown.map(item=>{const c=companies.get(item.company_id??''),href=item.event_id?`/events/${item.event_id}`:null,weekday=new Intl.DateTimeFormat(value.locale==='ko'?'ko-KR':'en-US',{weekday:'short',timeZone:'UTC'}).format(new Date(`${item.occurs_on}T00:00:00Z`));return <article className="m-calendar-item mc-event" key={item.id}><button type="button" className="mc-date" onClick={()=>choose(item.occurs_on)} aria-label={`${item.occurs_on} ${t('일정 보기','view dates')}`}><strong>{value.locale==='ko'?`${Number(item.occurs_on.slice(5,7))}월 ${Number(item.occurs_on.slice(8))}일`:item.occurs_on.slice(5)}</strong><span>({weekday})</span><span>{t('종일','All day')}</span></button>{c?<CompanyLogo ticker={c.ticker} size={39}/>:<span className="mc-event-icon"><MIcon name={item.origin==='user'?'calendar':'file'} size={25}/></span>}<div className="mc-event-copy">{href?<Link href={href} className="m-calendar-item-title mc-event-title">{item.title}</Link>:<button type="button" className="m-calendar-item-title mc-event-title" onClick={()=>setDetail(item)}>{item.title}</button>}<p>{item.quote||c?.name||t('직접 등록한 확인 일정','Your research date')}</p><button type="button" className={`mc-category mc-${itemCategory(item)}`} onClick={()=>setDetail(item)}>{categoryLabel(itemCategory(item))}<span className="mc-hidden"> · {t('일정 상세','Schedule details')}</span></button></div><div className="mc-reminder"><button type="button" role="switch" aria-checked={reminders.has(item.id)} aria-label={`${item.title} ${t('관심 일정','saved date')}`} className={`mc-reminder-button ${reminders.has(item.id)?'on':''}`} disabled={action.busy||reminderLoading||!!reminderError||!token} onClick={()=>void action.run(()=>reminder(item),reminders.has(item.id)?t('관심 일정 저장을 해제했습니다.','Saved date removed.'):t('관심 일정에 저장했습니다.','Date saved.'))}>{reminders.has(item.id)?<span/>:<MIcon name="bell" size={19}/>}</button><small>{reminders.has(item.id)?t('관심 일정 저장됨','Saved'):t('관심 일정 저장','Save date')}</small></div></article>;})}</div>
  {!result.loading&&result.data&&!shown.length&&<EmptyState title={t('등록된 일정이 없습니다.','No dates scheduled.')} description={t('공식 자료에서 확인된 일정이나 직접 등록한 날짜가 여기에 표시됩니다.','Dates confirmed in official sources and your own dates appear here.')}/>}
  <section className="mc-week-banner"><span className="mc-week-icon"><MIcon name="calendar" size={23}/></span><div><strong>{t('이번 주 중요한 일정','Dates this week')} {weekCount??'—'}{t('개','')}</strong><p>{today.slice(5)} – {weekEnd.slice(5)} · {t('공식·개인 일정','Official and personal dates')}</p></div><button type="button" onClick={()=>{setMonth(null);setTab('calendar');setScope('all');setWeekly(true);setSelected('');setCategory('all');}}>{t('주간 일정 보기','View week')}<MIcon name="chevron" size={13}/></button></section>
  <LoadState loading={false} error={weekDates.error} retry={weekDates.reload}/><div className="mc-tools"><button className="mc-text-link" onClick={()=>{setDate(selected||today);setAdd(true);}}><MIcon name="plus" size={14}/>{t('일정 추가','Add date')}</button><button className="mc-text-link" disabled={action.busy} onClick={()=>void exportCalendar()}><MIcon name="download" size={14}/>{t('캘린더 내보내기','Export calendar')}</button></div><p className="mc-note">{t('관심 일정은 계정에 저장되며 예약 알림·외부 푸시를 발송하지 않습니다. 원문에 날짜만 있는 일정은 종일로 표시합니다. 유형을 확인하지 못한 일정은 공식 일정으로 표시합니다.','Saved dates persist to your account without scheduled alerts or external pushes. Date-only sources are shown as all-day. Unclassified dates are labeled official dates.')}{result.data?.length===500&&t(' 현재 최대 500개 일정을 표시합니다.',' Showing up to 500 dates.')}</p>
  {add&&<Dialog title={t('내 확인 일정 추가','Add a research date')} onClose={()=>setAdd(false)}><ActionNotice action={action}/><form onSubmit={submit}><label className="m-field"><span>{t('제목','Title')}</span><input autoFocus required value={title} maxLength={200} onChange={e=>setTitle(e.target.value)} placeholder={t('확인할 내용을 입력하세요','What would you like to review?')}/></label><label className="m-field"><span>{t('날짜','Date')}</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="m-field"><span>{t('관련 기업 · 선택','Company · optional')}</span><select value={company} onChange={e=>setCompany(e.target.value)}><option value="">{t('선택하지 않음','None')}</option>{catalog.data?.map(c=><option key={c.id} value={c.id}>{c.name} · {c.ticker}</option>)}</select></label><LoadState loading={catalog.loading} error={catalog.error} retry={catalog.reload}/><button className="m-button" disabled={action.busy}>{action.busy?t('저장 중…','Saving…'):t('일정 저장','Save date')}</button></form></Dialog>}
  {detail&&<Dialog title={t('일정 상세','Schedule details')} onClose={()=>setDetail(null)}><div className="mc-details"><strong>{detail.title}</strong><p>{displayDate(detail.occurs_on,'date')} · {t('종일','All day')}</p>{detail.quote&&<blockquote>{detail.quote}</blockquote>}{detail.event_id&&<Link className="m-button" href={`/events/${detail.event_id}`}>{t('이벤트 상세','Event details')}<MIcon name="chevron" size={15}/></Link>}{detail.company_id&&<Link className="m-button m-button-secondary" href={`/companies/${detail.company_id}`}>{t('기업 개요','Company overview')}<MIcon name="chevron" size={15}/></Link>}{safeSource(detail.source_url)&&<a className="m-button m-button-secondary" href={safeSource(detail.source_url)} target="_blank" rel="noopener noreferrer">{t('근거 / 출처','Source')}<MIcon name="external" size={15}/></a>}{detail.origin==='user'&&<button className="m-button m-button-secondary" disabled={action.busy} onClick={()=>void action.run(()=>remove(detail),t('일정을 삭제했습니다.','Schedule removed.'))}>{t('일정 삭제','Delete date')}</button>}<ActionNotice action={action}/></div></Dialog>}
 </div>;
}
