'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {decimalInput} from '@/lib/decimal-input';
import {workspace} from '@/workspace/client';
import {documentDetailSchema,resourceHref,safeSource} from '@/workspace/contracts';
import {usePrefs} from '@/workspace/preferences';
import {useData,useMutation} from '@/workspace/ui';
import {ActionNotice,Dialog,EmptyState,LoadState,MIcon,SectionTitle} from './ui';
import './research.css';

type DocumentDetail=z.infer<typeof documentDetailSchema>;
type DocumentSection=DocumentDetail['sections'][number];
type DocumentFact=DocumentDetail['facts'][number];
const labels:Record<string,[string,string]>={revenue:['매출','Revenue'],sales:['매출','Sales'],eps:['주당순이익 (EPS)','Earnings per share'],net_income:['순이익','Net income'],operating_income:['영업이익','Operating income'],operating_profit:['영업이익','Operating profit'],capex:['자본 지출','Capital expenditure'],dividend:['배당','Dividend']};
function exactValue(value:string|null){if(value===null)return '—';const expanded=decimalInput(value);if(!/^[+-]?\d+(\.\d+)?$/.test(expanded))return value;const [integer,fraction]=expanded.split('.');return integer.replace(/\B(?=(\d{3})+(?!\d))/g,',')+(fraction===undefined?'':`.${fraction}`);}
function fileSize(bytes:number,locale:string){if(bytes<1024)return `${bytes} B`;const unit=bytes<1024**2?'KB':'MB',amount=bytes/(unit==='KB'?1024:1024**2);return `${new Intl.NumberFormat(locale,{maximumFractionDigits:1}).format(amount)} ${unit}`;}
export default function MobileDocument({id,kind='document'}:{id:string;kind?:'document'|'filing'}){
 return <DocumentContent key={`${kind}:${id}`} id={id} kind={kind}/>;
}
function DocumentContent({id,kind}:{id:string;kind:'document'|'filing'}){
 const {token}=useAuth(),{text:t,date,value}=usePrefs(),result=useData({action:'document_detail',p:{id,kind}},documentDetailSchema),action=useMutation();
 const [saved,setSaved]=useState<boolean|null>(null),[section,setSection]=useState<DocumentSection|null>(null),[fact,setFact]=useState<DocumentFact|null>(null),[moreSections,setMoreSections]=useState<DocumentSection[]>([]),[nextOffset,setNextOffset]=useState<number|null|undefined>(undefined),[showAllFacts,setShowAllFacts]=useState(false),[chooseEvent,setChooseEvent]=useState(false);
 const data=result.data,item=data?.document,isSaved=saved??item?.is_saved??false,source=safeSource(item?.source_url??null);
 useEffect(()=>{if(item&&value.history_enabled)void workspace(token,{action:'visit',p:{kind:item.kind,id:item.id}},z.unknown()).catch(()=>{});},[item,token,value.history_enabled]);
 const sections=[...(data?.sections??[]),...moreSections],next=nextOffset===undefined?data?.next_section_offset:nextOffset;
 const metrics=data?.facts.filter(entry=>entry.value_raw!==null)??[];
 function save(){if(!item)return;void action.run(async()=>{const response=await workspace(token,{action:'save',p:{kind,id,saved:!isSaved}},z.object({saved:z.boolean()}));setSaved(response.saved);});}
 function loadSections(){if(next==null)return;void action.run(async()=>{const response=await workspace(token,{action:'document_detail',p:{id,kind,section_offset:next}},documentDetailSchema);setMoreSections(previous=>{const known=new Set([...(data?.sections??[]),...previous].map(entry=>entry.id));return [...previous,...response.sections.filter(entry=>!known.has(entry.id))];});setNextOffset(response.next_section_offset);});}
 return <div className="m-document"><h1 className="m-research-sr">{t('문서 상세','Document details')}</h1><LoadState {...result} retry={result.reload}/><ActionNotice action={action}/>{data&&item&&<>
  <section className="m-card m-document-hero"><div className="m-document-heading"><span className={`m-document-file ${data.metadata.mime_type==='application/pdf'?'is-pdf':''}`} aria-hidden="true"><MIcon name="file" size={32}/>{data.metadata.mime_type==='application/pdf'&&<b>PDF</b>}</span><div><Link className="m-document-company" href={`/companies/${encodeURIComponent(item.company_id)}`}><strong>{item.company_name}</strong><span>{item.ticker}</span></Link><h2>{item.title}</h2><div className="m-document-meta"><time dateTime={item.published_at??undefined}>{date(item.published_at,item.publication_precision)}</time>{data.metadata.size_bytes!==null&&<span>{fileSize(data.metadata.size_bytes,value.locale)}</span>}{data.metadata.page_count!==null&&<span>{data.metadata.page_count}{t('페이지',' pages')}</span>}</div></div></div><div className="m-document-actions">{source?<a className="m-button m-button-secondary" href={source} target="_blank" rel="noopener noreferrer"><MIcon name="external" size={17}/>{t('원문 열기','Open source')}</a>:<span className="m-document-source-missing">{t('원문 링크 확인 필요','Source link unavailable')}</span>}<button className="m-button m-button-secondary" type="button" disabled={action.busy} aria-pressed={isSaved} aria-label={isSaved?t('문서 저장 취소','Unsave document'):t('문서 저장','Save document')} onClick={save}><MIcon name="bookmark" size={19}/>{isSaved?t('저장됨','Saved'):t('저장','Save')}</button></div></section>
  <section className="m-document-summary"><SectionTitle title={t('핵심 요약','Key takeaways')} action={<span>{t('게시된 분석과 원문 근거','Published analysis and source evidence')}</span>}/>{data.summaries.length?<div className="m-document-summary-list">{data.summaries.map((summary,index)=><Link href={`/events/${encodeURIComponent(summary.event_id)}`} className="m-card m-document-summary-card" key={`${summary.event_id}-${index}`}><span className={`m-research-number m-document-tone-${index%4}`} aria-hidden="true">{index+1}</span><div><h3>{summary.title}</h3><p>{summary.text}</p></div></Link>)}</div>:<EmptyState title={t('게시된 요약이 없습니다','No published summary')} description={t('연결된 공식 원문에서 내용을 확인할 수 있습니다.','Read the document using the official source link.')}/>} {data.counts.summaries>data.summaries.length&&<p className="m-note">{t(`게시된 요약 ${data.counts.summaries}개 중 ${data.summaries.length}개를 표시합니다.`,`Showing ${data.summaries.length} of ${data.counts.summaries} published summaries.`)}</p>}</section>
  {metrics.length>0&&<><div className="m-document-metrics" aria-label={t('원문에서 확인한 지표','Sourced metrics')}>{(showAllFacts?metrics:metrics.slice(0,3)).map((entry,index)=><button className={`m-card m-document-metric m-document-tone-${index%3}`} type="button" key={entry.id} onClick={()=>setFact(entry)}><span className="m-document-metric-icon"><MIcon name={index%3===0?'trend':index%3===1?'chip':'file'} size={22}/></span><span className="m-document-metric-label">{labels[entry.field]?.[value.locale==='ko'?0:1]??entry.field}</span><strong>{exactValue(entry.value_raw)}</strong>{entry.unit&&<span className="m-document-metric-unit">{entry.unit}</span>}<small>{[entry.period,entry.basis].filter(Boolean).join(' · ')}</small></button>)}</div>{metrics.length>3&&<button className="m-document-more" type="button" aria-expanded={showAllFacts} onClick={()=>setShowAllFacts(previous=>!previous)}>{showAllFacts?t('지표 접기','Show fewer metrics'):t(`지표 ${metrics.length}개 전체 보기`,`View all ${metrics.length} metrics`)}<MIcon name="chevron" size={13}/></button>}</>}
  {data.counts.facts>data.facts.length&&<p className="m-note">{t(`공개된 원문 사실 ${data.counts.facts}개 중 ${data.facts.length}개를 표시합니다. 전체 내용은 공식 원문에서 확인하세요.`,`Showing ${data.facts.length} of ${data.counts.facts} public facts. Open the official source for the full document.`)}</p>}
  <section className="m-document-contents"><SectionTitle title={t('목차','Contents')} action={<span>{t(`총 ${data.sections_total}개 근거 구간`,`${data.sections_total} evidence sections`)}</span>}/>{sections.length?<div className="m-card m-document-toc">{sections.map((entry,index)=><button type="button" key={entry.id} onClick={()=>setSection(entry)} aria-label={`${index+1}. ${entry.title||entry.location} ${t('내용 열기','Open section')}`}><span className="m-research-number" aria-hidden="true">{index+1}</span><strong>{entry.title||entry.location}</strong><span>{entry.page_start!==null?`${entry.page_start}${entry.page_end!==null&&entry.page_end!==entry.page_start?` - ${entry.page_end}`:''} ${t('페이지','pages')}`:entry.location}</span><MIcon name="chevron" size={16}/></button>)}</div>:<EmptyState title={t('공개된 근거 구간이 없습니다','No public evidence sections')} description={t('이 문서의 원문 링크는 위에서 열 수 있습니다. 페이지 번호와 목차를 임의로 만들지 않습니다.','Open the original document above. Page numbers and document sections are not inferred.')}/>} {next!=null&&<button className="m-document-more" type="button" disabled={action.busy} onClick={loadSections}>{t('근거 구간 더 보기','Load more evidence sections')}<MIcon name="chevron" size={14}/></button>}{sections.length>0&&<p className="m-document-contents-note">{t('검토된 사실에 연결된 원문 구간입니다. 전체 문서는 원문에서 확인하세요.','These source sections support reviewed facts. Open the source for the complete document.')}</p>}</section>
  <section className="m-document-related"><SectionTitle title={t('관련 문서','Related documents')} href={`/search?q=${encodeURIComponent(item.ticker)}&kind=document`}/>{data.related.length?<div className="m-document-related-grid">{data.related.slice(0,3).map(related=><Link className="m-card m-document-related-card" key={`${related.kind}:${related.id}`} href={resourceHref(related)}><span className="m-document-related-icon"><MIcon name="file" size={20}/></span><div><h3>{related.title}</h3><time dateTime={related.published_at??undefined}>{date(related.published_at,related.publication_precision)}</time><span>{related.category}</span></div></Link>)}</div>:<p className="m-note">{t('연결된 관련 문서가 없습니다.','No related documents are available.')}</p>}</section>
  {data.events.length===1?<Link className="m-button m-document-ask" href={`/questions?event=${encodeURIComponent(data.events[0].id)}`}><MIcon name="spark" size={21}/>{t('이 문서로 AI에게 질문하기','Ask AI about this document')}<MIcon name="chevron" size={18}/></Link>:data.events.length>1?<button className="m-button m-document-ask" type="button" onClick={()=>setChooseEvent(true)}><MIcon name="spark" size={21}/>{t('이 문서로 AI에게 질문하기','Ask AI about this document')}<MIcon name="chevron" size={18}/></button>:<p className="m-notice">{t('질문할 수 있는 게시된 이벤트가 아직 없습니다. 공식 원문을 확인해 주세요.','No published event is available for evidence questions yet. Read the official source above.')}</p>}
  <details className="m-document-provenance"><summary>{t('문서 출처 및 수집 정보','Document provenance')}</summary><dl><div><dt>{t('제공자','Provider')}</dt><dd>{data.metadata.provider}</dd></div><div><dt>{t('발행 시간대','Publication timezone')}</dt><dd>{data.metadata.publication_timezone??t('제공되지 않음','Unavailable')}</dd></div><div><dt>{t('수집 시각','Ingested at')}</dt><dd>{data.metadata.ingested_at?date(data.metadata.ingested_at):t('제공되지 않음','Unavailable')}</dd></div><div><dt>{t('파일 크기 / 페이지 수','File size / page count')}</dt><dd>{data.metadata.size_bytes!==null?fileSize(data.metadata.size_bytes,value.locale):t('크기 미제공','Size unavailable')} · {data.metadata.page_count!==null?`${data.metadata.page_count}${t('페이지',' pages')}`:t('페이지 수 미제공','Page count unavailable')}</dd></div>{data.metadata.raw_sha256&&<div><dt>{item.kind==='filing'?t('SEC 제출 목록 SHA-256','SEC submissions SHA-256'):t('원문 SHA-256','Document SHA-256')}</dt><dd>{data.metadata.raw_sha256}</dd></div>}</dl>{source&&<a href={source} target="_blank" rel="noopener noreferrer">{source}</a>}</details>
 </>}
 {!result.loading&&!result.error&&!item&&<EmptyState title={t('자료를 확인할 수 없습니다','Document not available')} description={t('자료가 비공개되었거나 수집 범위 밖입니다. 검색에서 다시 확인하세요.','The source may be withdrawn or outside current coverage. Try searching again.')} href="/search" label={t('검색으로 이동','Open search')}/>}
 {section&&<Dialog title={section.title||section.location} onClose={()=>setSection(null)}><p className="m-document-dialog-location">{section.location}</p><div className="m-document-section-content">{section.content}</div>{source&&<a className="m-button m-button-secondary m-document-dialog-source" href={source} target="_blank" rel="noopener noreferrer">{t('공식 원문 열기','Open official source')}<MIcon name="external" size={15}/></a>}</Dialog>}
 {fact&&<Dialog title={`${labels[fact.field]?.[value.locale==='ko'?0:1]??fact.field} · ${t('원문 근거','Source evidence')}`} onClose={()=>setFact(null)}><p className="m-document-fact-value">{exactValue(fact.value_raw)} {fact.unit}</p><p className="m-document-dialog-location">{[fact.period,fact.basis,fact.location].filter(Boolean).join(' · ')}</p><blockquote className="m-document-section-content">{fact.quote}</blockquote>{safeSource(fact.source_url)&&<a className="m-button m-button-secondary m-document-dialog-source" href={safeSource(fact.source_url)} target="_blank" rel="noopener noreferrer">{t('공식 원문 열기','Open official source')}<MIcon name="external" size={15}/></a>}<Link className="m-document-more" href={`/events/${encodeURIComponent(fact.event_id)}?panel=evidence`}>{t('연결된 이벤트 근거','Linked event evidence')}<MIcon name="chevron" size={13}/></Link></Dialog>}
 {chooseEvent&&data&&<Dialog title={t('질문할 이벤트 선택','Choose an event to ask about')} onClose={()=>setChooseEvent(false)}><p className="m-muted">{t('답변은 선택한 이벤트에 저장된 근거를 사용합니다.','Answers use the evidence stored for the selected event.')}</p><div className="m-document-event-options">{data.events.map(event=><Link className="m-card" key={event.id} href={`/questions?event=${encodeURIComponent(event.id)}`}><strong>{event.title}</strong><MIcon name="chevron" size={17}/></Link>)}</div></Dialog>}
 </div>;
}
