'use client';

import Link from 'next/link';
import {useRef,useState} from 'react';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {initializeSupabase} from '@/lib/supabase';
import {usePrefs} from '@/workspace/preferences';
import {useData,useMutation} from '@/workspace/ui';
import {workspace,validateAttachment} from '@/workspace/client';
import {ticketSchema} from '@/workspace/contracts';
import {helpArticles,helpCategories,searchHelp} from '@/workspace/help-content';
import {ActionNotice,Dialog,EmptyState,LoadState,MIcon} from './ui';
import './help.css';

const ticketsSchema=z.array(ticketSchema),attachedSchema=z.object({attached:z.boolean()});
const defaultIds=['pricing','watchlist','alerts','returns','calendar','sources'];
const categories=helpCategories.filter(category=>category.id!=='data');
const icons:Record<string,string>={start:'book',portfolio:'pie',alerts:'bell',account:'person',issues:'wrench'};
type TicketType='general'|'data'|'bug'|'feedback'|'privacy';
export default function MobileHelp({initialCategory=''}:{initialCategory?:string}){
 const auth=useAuth(),{text:t,date}=usePrefs(),action=useMutation();
 const [category,setCategory]=useState(initialCategory),[query,setQuery]=useState(''),[draft,setDraft]=useState(''),[all,setAll]=useState(false),[expanded,setExpanded]=useState(initialCategory?'':'pricing');
 const [dialog,setDialog]=useState<'contact'|'history'|null>(null),[admin,setAdmin]=useState(false),[type,setType]=useState<TicketType>(initialCategory==='privacy'?'privacy':'general'),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[file,setFile]=useState<File|null>(null),[pending,setPending]=useState<string|null>(null),[saved,setSaved]=useState<string|null>(null);
 const requestKey=useRef<string|null>(null),uploadedPath=useRef<string|null>(null),input=useRef<HTMLInputElement>(null);
 const tickets=useData(dialog==='history'?{action:'tickets',p:{admin:admin&&!!auth.me?.is_admin}}:null,ticketsSchema);
 const filtered=searchHelp(query,category),articles=!query&&!category&&!all?defaultIds.flatMap(id=>{const article=helpArticles.find(item=>item.id===id);return article?[article]:[];}):filtered;
 const close=()=>{if(!action.busy)setDialog(null);};
 function search(text:string){setQuery(text.trim());setDraft(text);setCategory('');setAll(true);setExpanded('');}
 function reset(){setPending(null);setTitle('');setMessage('');setFile(null);requestKey.current=null;uploadedPath.current=null;if(input.current)input.current.value='';}
 function contact(nextType:TicketType='general'){if(!pending)setType(nextType);setDialog('contact');}
 async function submit(){await action.run(async()=>{
  if(!auth.me)throw new Error(t('로그인을 확인해 주세요.','Verify your sign-in.'));
  if(!title.trim()||!message.trim())throw new Error(t('제목과 문의 내용을 입력해 주세요.','Enter a subject and message.'));
  const checked=file?await validateAttachment(file):null;requestKey.current??=crypto.randomUUID();
  const ticket=await workspace(auth.token,{action:'ticket_create',p:{request_key:requestKey.current,category:type,title:title.trim(),message:message.trim()}},ticketSchema);
  setPending(ticket.id);setSaved(ticket.id);
  if(file&&checked){const db=await initializeSupabase(),path=uploadedPath.current??`${auth.me.id}/${ticket.id}/${crypto.randomUUID()}.${checked.extension}`;
   if(!uploadedPath.current){const uploaded=await db.storage.from('signalbrief-support').upload(path,file,{contentType:checked.mime,upsert:false});if(uploaded.error)throw new Error(t('문의는 저장되었지만 첨부 업로드가 실패했습니다. 첨부 다시 전송을 눌러 주세요.','Your request was saved, but attachment upload failed. Retry the attachment.'));uploadedPath.current=path;}
   const attached=await workspace(auth.token,{action:'ticket_attach',p:{ticket_id:ticket.id,object_path:path,filename:file.name.slice(0,150),mime_type:checked.mime,size_bytes:file.size}},attachedSchema);
   if(!attached.attached)throw new Error(t('첨부 연결을 완료하지 못했습니다. 첨부 다시 전송을 눌러 주세요.','Attachment linking did not complete. Retry the attachment.'));
  }
  reset();tickets.reload();setDialog('history');
 },t('문의가 저장되었습니다. 내 문의 내역에서 처리 상태를 확인하세요.','Your request was saved. Check its state in My requests.'));}
 async function openAttachment(path:string){await action.run(async()=>{const db=await initializeSupabase(),response=await db.storage.from('signalbrief-support').createSignedUrl(path,60);if(response.error||!response.data?.signedUrl||new URL(response.data.signedUrl).protocol!=='https:')throw new Error(t('첨부파일을 열지 못했습니다.','Could not open attachment.'));const anchor=document.createElement('a');anchor.href=response.data.signedUrl;anchor.target='_blank';anchor.rel='noopener noreferrer';anchor.click();});}
 return <div className="m-help-page"><h1 className="m-visually-hidden">{t('도움말 및 지원','Help & support')}</h1>
  <section className="m-help-hero"><h2>{t('무엇을 도와드릴까요?','How can we help?')}</h2><p>{t('궁금한 점을 검색하면 빠르게 답변을 찾을 수 있습니다.','Search your question to find an answer.')}</p><form onSubmit={event=>{event.preventDefault();search(draft);}}><button type="submit" aria-label={t('도움말 검색 실행','Submit help search')}><MIcon name="search" size={21}/></button><input aria-label={t('도움말 검색','Search help')} maxLength={100} value={draft} onChange={event=>setDraft(event.target.value)} placeholder={t('예) 종목 추가 방법, 알림 설정, 계정 변경 등','Try adding companies, alerts or account settings')}/></form><small>{t('추천 검색어','Suggested searches')}</small><div className="m-help-chips">{[['종목 추가','Add companies','관심종목','watch'],['알림 설정','Alerts','알림','alert'],['포트폴리오 관리','Portfolio','포트폴리오','portfolio'],['계정 변경','Account','계정','account'],['데이터 출처','Sources','출처','source']].map(([ko,en,qko,qen])=><button type="button" key={ko} onClick={()=>search(t(qko,qen))}>{t(ko,en)}</button>)}</div></section>
  <section className="m-help-categories-section"><h2>{t('도움말 카테고리','Help categories')}</h2><div className="m-help-categories">{categories.map(item=><button type="button" className={`m-card m-help-category cat-${item.id}`} key={item.id} aria-pressed={category===item.id} onClick={()=>{setCategory(category===item.id?'':item.id);setQuery('');setDraft('');setExpanded('');setAll(true);}}><span className="m-help-category-icon"><MIcon name={icons[item.id]} size={25}/></span><span><strong>{t(item.ko,item.en)}</strong><small>{t(item.description,item.english)}</small></span><MIcon name="chevron" size={14}/></button>)}</div></section>
  <section className="m-help-faq-section"><header><h2>{query||category?t('검색한 도움말','Matching help'):t('자주 묻는 질문','Frequently asked questions')}</h2>{(query||category)&&<button type="button" onClick={()=>{setQuery('');setDraft('');setCategory('');setAll(false);setExpanded('pricing');}}>{t('초기화','Reset')}</button>}</header><div className="m-card m-help-faq-list">{articles.map((article,index)=><article className={`m-help-faq ${expanded===article.id?'open':''}`} key={article.id}><h3><button type="button" aria-expanded={expanded===article.id} aria-controls={`mobile-help-${article.id}`} onClick={()=>setExpanded(expanded===article.id?'':article.id)}><span>{index+1}</span><strong>{t(article.q,article.en)}</strong><MIcon name="chevron" size={16}/></button></h3>{expanded===article.id&&<div id={`mobile-help-${article.id}`}><p>{t(article.a,article.english)}</p><Link href={article.href}>{t('관련 화면 열기','Open related page')}<MIcon name="chevron" size={12}/></Link>{article.id==='privacy'&&<button type="button" onClick={()=>contact('privacy')}>{t('삭제 요청 작성','Write deletion request')}</button>}</div>}</article>)}</div>{!articles.length&&<EmptyState title={t('일치하는 도움말이 없습니다.','No matching help articles.')} description={t('다른 검색어를 사용하거나 문의를 남겨 주세요.','Try another query or contact support.')}/>}{!query&&!category&&!all&&<button type="button" className="m-help-all" onClick={()=>setAll(true)}>{t('전체 도움말 보기','All help articles')}<MIcon name="chevron" size={13}/></button>}</section>
  <section className="m-help-contact-cards"><article className="m-card"><div><span className="m-help-contact-icon"><MIcon name="headset" size={30}/></span><span><h2>{t('문의하기','Contact support')}</h2><p>{t('더 궁금한 점이 있으신가요? 문의 내용을 남겨주세요.','Have another question? Send us a request.')}</p></span></div><button type="button" onClick={()=>contact()}>{pending?t('첨부 전송 이어하기','Resume attachment'):t('문의하기','Contact support')}<MIcon name="chevron" size={15}/></button></article><article className="m-card"><div><span className="m-help-contact-icon history"><MIcon name="file" size={29}/></span><span><h2>{t('내 문의 내역','My requests')}</h2><p>{t('이전에 문의한 내용과 처리 상태를 확인할 수 있습니다.','Review previous requests and their current state.')}</p></span></div><button type="button" onClick={()=>setDialog('history')}>{t('내 문의 내역','My requests')}<MIcon name="chevron" size={15}/></button></article></section>
  <section className="m-card m-help-status"><span><MIcon name="info" size={19}/></span><div><h2>{t('서비스 운영 상태 확인','Check service status')}</h2><p>{t('최신 진단 결과와 점검 시각을 확인하세요.','Review the latest diagnostics and check times.')}</p></div><Link href="/status">{t('서비스 상태 보기','View status')}<MIcon name="chevron" size={14}/></Link></section>
  <footer className="m-help-footer"><Link href="/privacy">{t('개인정보처리방침','Privacy')}</Link><Link href="/terms">{t('이용약관','Terms')}</Link><Link href="/disclaimer">{t('투자 유의사항','Investment notice')}</Link></footer>

  {dialog==='contact'&&<Dialog title={t('문의하기','Contact support')} onClose={close}><ActionNotice action={action}/><p className="m-help-form-note">{t('문의는 비공개로 저장됩니다. 비밀번호·인증 코드·API 키는 보내지 마세요.','Requests are stored privately. Never send passwords, authentication codes or API keys.')}</p>{pending&&<p role="status" className="m-help-pending">{t('문의는 접수되었습니다. 첨부 전송을 완료해 주세요.','Your request was received. Complete its attachment.')}<code>{pending}</code></p>}<form className="m-help-form" onSubmit={event=>{event.preventDefault();void submit();}}><label>{t('문의 유형','Type')}<select value={type} disabled={action.busy||!!pending} onChange={event=>{setType(event.target.value as TicketType);requestKey.current=null;}}>{[['general','일반 문의','General'],['data','데이터 문의','Data'],['bug','오류 신고','Bug report'],['feedback','개선 제안','Feedback'],['privacy','개인정보 / 삭제 요청','Privacy / deletion']].map(([key,ko,en])=><option key={key} value={key}>{t(ko,en)}</option>)}</select></label><label>{t('제목','Subject')}<input autoFocus required maxLength={120} value={title} disabled={action.busy||!!pending} onChange={event=>{setTitle(event.target.value);requestKey.current=null;}}/></label><label><span id="mobile-support-message-label">{t('문의 내용','Message')}</span><textarea aria-labelledby="mobile-support-message-label" required maxLength={2000} rows={5} value={message} disabled={action.busy||!!pending} onChange={event=>{setMessage(event.target.value);requestKey.current=null;}}/></label><small>{message.length} / 2,000</small><label>{t('파일 첨부 (선택)','Attachment (optional)')}<input ref={input} type="file" accept="image/png,image/jpeg,image/webp,application/pdf" disabled={action.busy||!!pending} onChange={event=>setFile(event.target.files?.[0]??null)}/></label><p className="m-help-form-note">{t('PNG·JPEG·WebP·PDF / 최대 5 MB. 실제 파일 형식을 확인합니다.','PNG, JPEG, WebP or PDF / up to 5 MB. Actual file content is checked.')}</p><button className="m-button" disabled={action.busy}>{action.busy?t('저장 중…','Saving…'):pending?t('첨부 다시 전송','Retry attachment'):t('문의 내용 제출하기','Submit request')}</button>{pending&&<button type="button" className="m-help-reset" disabled={action.busy} onClick={reset}>{t('저장된 문의는 유지하고 새 문의 작성','Keep saved request and start a new one')}</button>}</form></Dialog>}
  {dialog==='history'&&<Dialog title={admin?t('지원 요청 관리','Manage support requests'):t('내 문의 내역','My requests')} onClose={close}><ActionNotice action={action}/><div className="m-help-history-toolbar"><button type="button" disabled={tickets.loading||action.busy} onClick={tickets.reload}>{t('새로고침','Refresh')}<MIcon name="refresh" size={14}/></button>{auth.me?.is_admin&&<button type="button" disabled={action.busy} onClick={()=>setAdmin(!admin)}>{admin?t('내 문의만','My requests only'):t('운영자 관리','Operator view')}</button>}</div>{saved&&<p className="m-help-form-note">{t('최근 접수 번호','Latest request ID')}: {saved}</p>}<LoadState {...tickets} retry={tickets.reload}/>{tickets.data?.map(ticket=><article className="m-help-ticket" key={ticket.id}><header><span className={`state-${ticket.state}`}>{ticket.state==='open'?t('접수됨','Received'):ticket.state==='in_progress'?t('처리 중','In progress'):t('처리 완료','Resolved')}</span><time>{date(ticket.created_at)}</time></header><h3>{ticket.title}</h3>{ticket.message&&<p>{ticket.message}</p>}<small>{ticket.id}</small>{ticket.attachments?.map(attachment=><button type="button" key={attachment.object_path} disabled={action.busy} onClick={()=>void openAttachment(attachment.object_path)}><MIcon name="file" size={15}/>{attachment.filename}<MIcon name="external" size={13}/></button>)}{admin&&auth.me?.is_admin&&<label>{t('처리 상태','Status')}<select aria-label={`${ticket.title} ${t('처리 상태','status')}`} value={ticket.state} disabled={action.busy} onChange={event=>void action.run(async()=>{await workspace(auth.token,{action:'ticket_update',p:{id:ticket.id,state:event.target.value as 'open'|'in_progress'|'resolved'}},z.unknown());tickets.reload();})}><option value="open">{t('접수됨','Received')}</option><option value="in_progress">{t('처리 중','In progress')}</option><option value="resolved">{t('처리 완료','Resolved')}</option></select></label>}</article>)}{tickets.data&&!tickets.data.length&&<EmptyState title={t('아직 접수한 문의가 없습니다.','No requests submitted yet.')} description={t('문의하기에서 요청을 작성할 수 있습니다.','Use Contact support to send a request.')}/>}</Dialog>}
 </div>;
}
