'use client';
import Link from 'next/link';
import {useEffect,useState,type FormEvent} from 'react';
import {useAuth} from '@/components/auth';
import {useResource} from '@/components/ui';
import {companiesSchema,feedSchema,portfolioSchema} from '@/lib/contracts';
import {body,emptySchema,errorMessage,request} from '@/lib/api';
import {decimalInput} from '@/lib/decimal-input';
import {usePrefs} from '@/workspace/preferences';
import {useMutation} from '@/workspace/ui';
import {useQuotes} from '@/workspace/market';
import {CompanyLogo,MIcon,SectionTitle,EmptyState,LoadState,ActionNotice,relativeTime,Dialog} from '@/mobile/ui';
import {valuePortfolio,referenceRateSchema,formatExactMoney,compareAmount,amountSign,type Holding,type ReferenceRate} from './portfolio-math';
import './collections.css';

const holdingCurrencies=['USD','KRW','EUR','JPY','GBP','AUD','CAD','HKD','CNY','CHF'];
const colors=['#45cc78','#4b94ff','#ff555e','#ffba4c','#a5abba','#9b75ef','#36b8b2'];
const pct=(v:number|null)=>v===null?'—':`${v>0?'+':''}${v.toFixed(2)}%`;
export default function MobilePortfolio(){
 const {token}=useAuth(),{text:t,value:preferences,date}=usePrefs(),action=useMutation(),portfolio=useResource('/v1/portfolio',portfolioSchema),feed=useResource('/v1/feed?days=180&limit=100',feedSchema);
 const [fx,setFx]=useState<ReferenceRate|null>(null),[fxLoading,setFxLoading]=useState(true),[fxRevision,setFxRevision]=useState(0),[basisOpen,setBasisOpen]=useState(false),[sort,setSort]=useState('value'),[allWeights,setAllWeights]=useState(false),[allEvents,setAllEvents]=useState(false),[editor,setEditor]=useState<Holding|'new'|null>(null),[remove,setRemove]=useState<Holding|null>(null);
 const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[company,setCompany]=useState(''),[quantity,setQuantity]=useState(''),[cost,setCost]=useState(''),[currency,setCurrency]=useState('USD'),[now]=useState(()=>Date.now());
 const positions=portfolio.data?.positions??[],market=useQuotes(positions.map(p=>p.company.ticker),'1m'),valuation=valuePortfolio(positions,market.quotes,fx,now),locale=preferences.locale==='ko'?'ko-KR':'en-US';
 const catalog=useResource(editor?`/v1/companies?q=${encodeURIComponent(search)}&limit=50`:null,companiesSchema);
 useEffect(()=>{const timer=setTimeout(()=>setSearch(query.trim()),250);return()=>clearTimeout(timer);},[query]);
 useEffect(()=>{const ctrl=new AbortController();let active=true;setFxLoading(true);fetch('/api/us/reference-rate',{cache:'no-store',signal:AbortSignal.any([ctrl.signal,AbortSignal.timeout(25000)])}).then(async response=>{if(!response.ok)throw new Error('unavailable');return referenceRateSchema.parse(await response.json());}).then(value=>{if(active)setFx(value);}).catch(()=>{if(active)setFx(null);}).finally(()=>{if(active)setFxLoading(false);});return()=>{active=false;ctrl.abort();};},[fxRevision]);
 const money=(amount:string|null,unit=valuation.currency??'KRW',signed=false)=>formatExactMoney(amount,unit,locale,signed);
 const rows=[...valuation.rows].sort((a,b)=>sort==='name'?a.position.company.name.localeCompare(b.position.company.name,preferences.locale):sort==='return'?(b.returnPct??-Infinity)-(a.returnPct??-Infinity):valuation.currency?compareAmount(b.value,a.value):a.currency.localeCompare(b.currency)||compareAmount(b.value,a.value));
 const ordered=[...valuation.rows].sort((a,b)=>(b.weight??0)-(a.weight??0)),allocation=(allWeights?ordered:ordered.slice(0,4)).map((r,i)=>({id:r.position.company.id,name:r.position.company.name,weight:r.weight??0,value:r.value,color:colors[i%colors.length]}));
 if(!allWeights&&ordered.length>4){const rest=ordered.slice(4),weight=rest.reduce((sum,r)=>sum+(r.weight??0),0);allocation.push({id:'other',name:t('기타','Other'),weight,value:null,color:colors[4]});}
 const held=new Set(positions.map(p=>p.company.id)),changes=(feed.data?.items??[]).filter(e=>held.has(e.company.id)).sort((a,b)=>b.published_at.localeCompare(a.published_at));
 function openEditor(position?:Holding){setEditor(position??'new');setCompany(position?.company.id??'');setQuantity(decimalInput(position?.quantity));setCost(decimalInput(position?.average_cost));setCurrency(position?.currency??'USD');setQuery(position?.company.ticker??'');}
 function submit(event:FormEvent){event.preventDefault();void action.run(async()=>{if(!company)throw new Error(t('기업을 선택해 주세요.','Choose a company.'));if(!holdingCurrencies.includes(currency))throw new Error(t('취득가 통화를 선택해 주세요.','Choose the cost currency.'));if(!/^\d{1,20}(\.\d{1,8})?$/.test(quantity)||!/[1-9]/.test(quantity))throw new Error(t('보유 수량은 소수점 8자리 이내의 양수로 입력해 주세요.','Enter a positive quantity with up to eight decimal places.'));if(cost&&!/^\d{1,20}(\.\d{1,8})?$/.test(cost))throw new Error(t('평균 취득가를 확인해 주세요.','Check the average cost.'));await request(`/v1/portfolio/positions/${encodeURIComponent(company)}`,token,emptySchema,body('PUT',{quantity,average_cost:cost||null,currency})).catch(e=>{throw new Error(errorMessage(e));});portfolio.reload();feed.reload();setEditor(null);},t('보유 정보를 저장했습니다.','Your holding has been saved.'));}
 return <div className="m-portfolio-page"><header className="m-portfolio-heading"><div><h1>{t('포트폴리오','Portfolio')}</h1><p>{t('내가 보유한 종목과 수익 현황을 한눈에 확인하세요.','Your holdings and performance at a glance.')}</p></div><button className="m-button-secondary" onClick={()=>openEditor()}><MIcon name="plus" size={18}/>{t('보유 종목 추가','Add holding')}</button></header><ActionNotice action={action}/><LoadState loading={portfolio.loading} error={portfolio.error??undefined} retry={portfolio.reload}/>
 <section className="m-portfolio-metrics" aria-label={t('포트폴리오 요약','Portfolio summary')}><div><span>{t('총 평가금액','Market value')}</span><button className="m-portfolio-basis-icon" aria-label={t('시세 기준과 계산 안내','Valuation basis')} onClick={()=>setBasisOpen(true)}><MIcon name="coins" size={22}/></button><strong>{money(valuation.value)}</strong><small>{t('매수금액','Cost basis')} {money(valuation.cost)}</small></div><div className={amountSign(valuation.dailyChange)}><span>{t('최근 거래 손익','Latest-session change')}</span><i><MIcon name="trend" size={22}/></i><strong>{money(valuation.dailyChange,valuation.currency??'KRW',true)}</strong><small>({pct(valuation.dailyPct)})</small></div><div className={amountSign(valuation.gain)}><span>{t('누적 평가수익률','Unrealized return')}</span><i><MIcon name="trend" size={22}/></i><strong>{pct(valuation.returnPct)}</strong><small>({money(valuation.gain,valuation.currency??'KRW',true)})</small></div></section>
 {basisOpen&&<Dialog title={t('시세 기준과 계산 안내','Valuation basis')} onClose={()=>setBasisOpen(false)}><div className="m-portfolio-basis"><LoadState loading={market.loading||fxLoading}/><p>{t('평가금액은 보유 수량과 공급자 시세로 계산합니다. 시세가 없는 종목을 0원으로 계산하지 않습니다.','Value is calculated from your quantity and provider quotes. Missing quotes are never treated as zero.')}</p><p>{t('손익은 현재 보유 수량 기준이며, 실현손익·배당·수수료·환차손익을 포함하지 않습니다. 취득가와 시세 통화가 다르면 수익률을 표시하지 않습니다.','Changes use current quantities and exclude realized returns, dividends, fees and FX gains. Returns are unavailable when cost and quote currencies differ.')}</p>{valuation.fx&&<p>{t('환율','FX')}: 1 USD = {new Intl.NumberFormat(locale,{maximumFractionDigits:4}).format(valuation.fx.rate)} KRW · {valuation.fx.date} · {valuation.fx.source} {t('일별 기준환율','daily reference rate')}</p>}{!valuation.currency&&valuation.groups.map(g=><p key={g.currency}>{g.currency}: {money(g.value,g.currency)} ({g.count}{t('종목',' holdings')})</p>)}{valuation.rows.map(row=><p key={row.position.company.id}><strong>{row.position.company.name}</strong> · {row.quote?`${row.quote.source} · ${date(row.quote.as_of)}`:t('시세 확인 전','Quote unavailable')}</p>)}<button onClick={()=>{portfolio.reload();setFxRevision(v=>v+1);}}>{t('다시 확인','Refresh')}</button></div></Dialog>}
 <section><SectionTitle title={t('보유 종목 비중','Allocation')} action={<button className="m-portfolio-text-action" onClick={()=>setAllWeights(v=>!v)}>{allWeights?t('접기','Show less'):t('전체 보기','View all')}<MIcon name="chevron" size={16}/></button>}/><div className="m-card m-portfolio-allocation">{valuation.complete&&compareAmount(valuation.value,'0')>0?<><div className="m-portfolio-donut"><svg viewBox="0 0 200 200" role="img" aria-label={t('평가금액 기준 보유 종목 비중','Holdings by market value')}><circle cx="100" cy="100" r="78" fill="none" stroke="var(--m-line,#edf0f4)" strokeWidth="31"/>{allocation.map((a,index)=>{const start=allocation.slice(0,index).reduce((sum,entry)=>sum+entry.weight,0);return <circle key={a.id} cx="100" cy="100" r="78" fill="none" stroke={a.color} strokeWidth="31" pathLength="100" strokeDasharray={`${Math.max(0,a.weight-.16)} ${100-Math.max(0,a.weight-.16)}`} strokeDashoffset={-start} transform="rotate(-90 100 100)"/>;})}</svg><div><small>{t('총 평가금액','Market value')}</small><strong>{money(valuation.value)}</strong></div></div><div className="m-portfolio-legend">{allocation.map(a=><div key={a.id}><i style={{background:a.color}}/>{a.id==='other'?<button onClick={()=>setAllWeights(true)}>{a.name}</button>:<Link href={`/companies/${a.id}`}>{a.name}</Link>}<span>{a.weight.toFixed(1)}%</span><strong>{a.value===null?a.id==='other'?t('합산 비중','Combined weight'):'—':money(a.value)}</strong></div>)}</div></>:<div className="m-portfolio-allocation-empty"><MIcon name="pie" size={44}/><strong>{positions.length?t('비중을 계산할 시세가 필요해요.','Market quotes are needed for allocation.'):t('보유 종목을 추가해 주세요.','Add your holdings.')}</strong><p>{positions.length?`${t('가격 확인','Priced')}: ${valuation.pricedCount} / ${positions.length} · ${t('모든 종목의 같은 통화 평가금액이 필요합니다.','Every holding needs a value in a shared currency.')}`:t('수량과 평균 취득가를 입력하면 내 포트폴리오를 관리할 수 있어요.','Manage your portfolio by entering quantities and average costs.')}</p>{!positions.length&&<button className="m-button" onClick={()=>openEditor()}>{t('첫 보유 종목 추가','Add your first holding')}</button>}</div>}</div></section>
 <section><SectionTitle title={t('보유 종목 목록','Holdings')} action={<label className="m-portfolio-sort"><select value={sort} aria-label={t('보유 종목 정렬','Sort holdings')} onChange={e=>setSort(e.target.value)}><option value="value">{valuation.currency?t('평가금액 순','Market value'):t('통화·평가금액 순','Currency / value')}</option><option value="name">{t('기업 이름 순','Company name')}</option><option value="return">{t('수익률 순','Return')}</option></select></label>}/><div className="m-portfolio-holdings">{rows.map(row=>{const p=row.position,event=changes.find(e=>e.company.id===p.company.id);return <article className="m-card m-portfolio-holding" key={p.id}><Link className="m-portfolio-holding-main" href={`/companies/${p.company.id}`}><CompanyLogo ticker={p.company.ticker} size={45}/><div className="m-portfolio-holding-name"><strong>{p.company.name} <span>{p.company.ticker}</span></strong><p>{p.quantity}{t('주',' shares')} <i/> {row.weight===null?t('비중 확인 전','Weight unavailable'):`${t('비중','Weight')} ${row.weight.toFixed(1)}%`}</p></div><div className="m-portfolio-holding-value"><strong>{money(row.value,row.currency)}</strong><span className={amountSign(row.dailyChange)}>{money(row.dailyChange,row.currency,true)} {row.quote?.change_pct===null||row.quote?.change_pct===undefined?'':`(${pct(row.quote.change_pct)})`}</span></div><MIcon name="chevron" size={17}/></Link>{event?<Link className="m-portfolio-holding-event" href={`/events/${event.id}`}>{event.headline}</Link>:<p className="m-portfolio-holding-event">{t('평균 취득가','Average cost')}: {p.average_cost===null?'—':money(p.average_cost,p.currency)}</p>}<footer><button onClick={()=>openEditor(p)}>{t('수정','Edit')}</button><button onClick={()=>setRemove(p)} aria-label={`${p.company.name} ${t('보유 정보 삭제','remove holding')}`}>{t('삭제','Delete')}</button></footer></article>;})}</div>{!portfolio.loading&&!positions.length&&<EmptyState title={t('등록한 보유 종목이 없습니다.','No holdings yet.')}/>}</section>
 <section><SectionTitle title={t('보유 종목의 최근 변화','Recent holding changes')} action={<button className="m-portfolio-text-action" onClick={()=>setAllEvents(v=>!v)}>{allEvents?t('접기','Show less'):t('전체 보기','View all')}<MIcon name="chevron" size={16}/></button>}/><LoadState loading={feed.loading} error={feed.error??undefined} retry={feed.reload}/><div className="m-portfolio-events">{(allEvents?changes:changes.slice(0,3)).map(e=><Link className="m-card m-portfolio-event" key={e.id} href={`/events/${e.id}`}><CompanyLogo ticker={e.company.ticker} size={43}/><div><header><strong>{e.company.name} <span>{e.company.ticker}</span></strong><time dateTime={e.published_at}>{relativeTime(e.published_at,preferences.locale)}</time></header><b>{e.headline}</b><p>{e.what_happened}</p></div></Link>)}</div>{!feed.loading&&!changes.length&&<EmptyState title={t('아직 확인된 변화가 없습니다.','No verified changes available.')}/>}</section>
 {editor&&<Dialog title={editor==='new'?t('보유 종목 추가','Add a holding'):t('보유 정보 수정','Edit holding')} onClose={()=>setEditor(null)}><ActionNotice action={action}/><form className="m-portfolio-form" onSubmit={submit}><label className="m-field"><span>{t('기업 검색','Find company')}</span><input autoFocus value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} placeholder={t('기업명 또는 종목코드','Company name or ticker')}/></label><LoadState loading={catalog.loading} error={catalog.error??undefined} retry={catalog.reload}/><label className="m-field"><span>{t('기업','Company')}</span><select required disabled={editor!=='new'} value={company} onChange={e=>{setCompany(e.target.value);const c=catalog.data?.find(item=>item.id===e.target.value);if(c)setCurrency(c.provider==='dart'||/KOSPI|KOSDAQ|KRX/.test(c.market)?'KRW':'USD');}}><option value="">{t('기업을 선택해 주세요','Select a company')}</option>{editor!=='new'&&!catalog.data?.some(c=>c.id===editor.company.id)&&<option value={editor.company.id}>{editor.company.name} · {editor.company.ticker}</option>}{catalog.data?.map(c=><option key={c.id} value={c.id}>{c.name} · {c.ticker}</option>)}</select></label><div className="m-portfolio-form-row"><label className="m-field"><span>{t('보유 수량','Quantity')}</span><input required inputMode="decimal" value={quantity} maxLength={29} pattern="[0-9]+(\.[0-9]{1,8})?" onChange={e=>setQuantity(e.target.value)} placeholder="0"/></label><label className="m-field"><span>{t('취득가 통화','Cost currency')}</span><select value={currency} onChange={e=>setCurrency(e.target.value)}>{holdingCurrencies.map(code=><option key={code} value={code}>{code}</option>)}</select></label></div><label className="m-field"><span>{t('평균 취득가 · 선택','Average cost · optional')}</span><input inputMode="decimal" value={cost} maxLength={29} pattern="[0-9]+(\.[0-9]{1,8})?" onChange={e=>setCost(e.target.value)} placeholder={t('입력하지 않아도 됩니다','May be left blank')}/></label><p className="m-muted">{editor==='new'&&positions.some(p=>p.company.id===company)?t('이미 보유한 기업입니다. 저장하면 기존 수량과 취득가를 변경합니다.','This company is already held. Saving replaces its existing quantity and average cost.'):t('수량은 추가 매수 수량이 아닌 현재 총 보유 수량입니다.','Enter your total current quantity.')}</p><button className="m-button" disabled={action.busy||!company}>{action.busy?t('저장 중…','Saving…'):t('보유 정보 저장','Save holding')}</button></form></Dialog>}
 {remove&&<Dialog title={t('보유 정보를 삭제할까요?','Remove this holding?')} onClose={()=>setRemove(null)}><ActionNotice action={action}/><p>{remove.company.name} ({remove.company.ticker}) · {remove.quantity}{t('주',' shares')}</p><button className="m-button m-portfolio-delete" disabled={action.busy} onClick={()=>void action.run(async()=>{await request(`/v1/portfolio/positions/${encodeURIComponent(remove.company.id)}`,token,emptySchema,body('DELETE')).catch(e=>{throw new Error(errorMessage(e));});portfolio.reload();setRemove(null);},t('보유 정보를 삭제했습니다.','Holding removed.'))}>{t('보유 정보 삭제','Remove holding')}</button></Dialog>}
 </div>;
}
