'use client';
import Link from 'next/link';
import {useEffect,useId,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {useResource} from '@/components/ui';
import {useMutation} from '@/workspace/ui';
import {usePrefs} from '@/workspace/preferences';
import {safeSource} from '@/workspace/contracts';
import {answerSchema,detailSchema,feedSchema,type Answer} from '@/lib/contracts';
import {request,body,emptySchema} from '@/lib/api';
import {ActionNotice,CompanyLogo,EmptyState,LoadState,MIcon,eventLabel} from './ui';
import './research.css';

const historySchema=z.array(z.object({id:z.string(),event_id:z.string(),question:z.string(),answer:answerSchema,created_at:z.string()}));
type HistoryItem=z.infer<typeof historySchema>[number];
type LocalMessage={id:string;question:string;answer:Answer;knownIds:string[];created_at:string};
function persistedMessage(message:LocalMessage,items:HistoryItem[]){
 return items.some(item=>!message.knownIds.includes(item.id)&&item.question===message.question&&JSON.stringify(item.answer)===JSON.stringify(message.answer));
}
export default function MobileQuestions({eventId=''}:{eventId?:string}){
 return <QuestionsContent key={eventId} eventId={eventId}/>;
}
function QuestionsContent({eventId}:{eventId:string}){
 const auth=useAuth(),router=useRouter(),{text:t,date,value}=usePrefs(),action=useMutation(),[question,setQuestion]=useState('');
 const controls=useRef<HTMLElement>(null),eventSelect=useRef<HTMLSelectElement>(null),questionLabelId=useId();
 const selectedQuestion=useSearchParams().get('question')??'';
 const [localMessages,setLocalMessages]=useState<LocalMessage[]>([]),[clearedIds,setClearedIds]=useState<string[]>([]);
 const feed=useResource('/v1/feed?days=180&limit=100',feedSchema),history=useResource(auth.me?.demo_mode?null:'/v1/questions',historySchema),detail=useResource(eventId?`/v1/events/${encodeURIComponent(eventId)}`:null,detailSchema);
 const savedHistory=(history.data??[]).filter(item=>!clearedIds.includes(item.id));
 const selectedHistory=savedHistory.filter(item=>item.event_id===eventId).sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at)||a.id.localeCompare(b.id));
 const conversation=[...selectedHistory,...localMessages.filter(message=>!persistedMessage(message,selectedHistory))];
 const canAsk=detail.data?.event.id===eventId&&!detail.loading&&!detail.error&&!history.loading&&!action.busy;
 useEffect(()=>{if(!history.data)return;const saved=history.data.filter(item=>item.event_id===eventId);setLocalMessages(previous=>{const pending=previous.filter(message=>!persistedMessage(message,saved));return pending.length===previous.length?previous:pending;});},[eventId,history.data]);
 useEffect(()=>{if(selectedQuestion&&history.data?.some(item=>item.id===selectedQuestion&&item.event_id===eventId))document.getElementById(`mobile-question-${selectedQuestion}`)?.scrollIntoView({block:'center'});},[selectedQuestion,eventId,history.data]);
 function choose(id:string,questionId=''){const params=new URLSearchParams({event:id});if(questionId)params.set('question',questionId);router.replace(id?`/questions?${params}`:'/questions',{scroll:false});}
 function ask(){const sent=question.trim();if(!sent||!canAsk)return;const knownIds=savedHistory.map(item=>item.id);if(selectedQuestion)choose(eventId);void action.run(async()=>{const answer=await request(`/v1/events/${encodeURIComponent(eventId)}/questions`,auth.token,answerSchema,body('POST',{question:sent}));setLocalMessages(old=>[...old,{id:`pending-${crypto.randomUUID()}`,question:sent,answer,knownIds,created_at:new Date().toISOString()}]);setQuestion('');history.reload();});}
 function time(iso:string){const instant=new Date(iso);return Number.isFinite(instant.getTime())?new Intl.DateTimeFormat(value.locale,{timeZone:value.timezone,hour:'numeric',minute:'2-digit'}).format(instant):date(iso);}
 return <div className="m-questions"><h1 className="m-research-sr">{t('AI 후속 질문','Evidence follow-up')}</h1>
 <LoadState {...detail} retry={detail.reload}/>{detail.data&&<section className="m-card m-question-context"><Link href={`/companies/${detail.data.event.company.id}`} aria-label={`${detail.data.event.company.name} ${t('기업 개요','Company overview')}`}><CompanyLogo ticker={detail.data.event.company.ticker} size={54}/></Link><div className="m-question-context-body"><div className="m-question-company"><strong>{detail.data.event.company.name}</strong><span>{detail.data.event.company.ticker}</span></div><Link href={`/events/${eventId}`} aria-label={`${detail.data.event.headline} ${t('이벤트 상세 보기','Open event details')}`}><h2>{detail.data.event.headline}</h2></Link><span className={`m-pill m-type-${detail.data.event.event_type}`}>{eventLabel(detail.data.event.event_type,value.locale)}</span><p>{detail.data.event.what_happened}</p><time dateTime={detail.data.event.published_at}>{date(detail.data.event.published_at,detail.data.event.publication_precision)}</time></div></section>}
 <ActionNotice action={action}/>
 {!eventId&&<EmptyState title={t('이벤트를 선택해 주세요','Select an event')} description={t('게시된 이벤트를 선택하면 관련 근거를 질문할 수 있어요.','Select a published event to ask about its evidence.')}/>}
 <div className="m-conversation" aria-live="polite">{conversation.map(message=><div key={message.id} id={`mobile-question-${message.id}`} className={selectedQuestion===message.id?'is-selected':''}><div className="m-question-user-row"><p className="m-question-user">{message.question}</p><span className="m-question-user-avatar" aria-hidden="true"><MIcon name="person" size={21}/></span><time dateTime={message.created_at}>{time(message.created_at)}</time></div><div className="m-question-ai-row"><span className="m-question-ai-avatar" aria-hidden="true"><svg viewBox="0 0 32 32" fill="none"><path d="M16 4v4M8 11h16a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H8a3 3 0 0 1-3-3V14a3 3 0 0 1 3-3Z" stroke="currentColor" strokeWidth="3"/><path d="M2 17v5M30 17v5M12 18v2M20 18v2M13 24h6" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg></span><div><span className="m-question-ai-label">AI</span><article className="m-card m-question-answer" aria-label={t('AI 근거 답변','AI evidence answer')}><p>{message.answer.message}</p>{message.answer.status!=='answered'&&<span className="m-question-status">{message.answer.status==='abstained'?t('근거 부족','Insufficient evidence'):message.answer.status==='policy_blocked'?t('답변 범위 제한','Outside answer scope'):t('현재 답변 불가','Currently unavailable')}</span>}{message.answer.evidence.length>0&&<ol className="m-question-citations">{message.answer.evidence.map((e,j)=><li key={`${e.source_id}-${j}`}><span className="m-research-number" aria-hidden="true">{j+1}</span><div><h3>{e.location||t('확인된 원문 근거','Verified source evidence')}</h3><blockquote>{e.quote}</blockquote>{safeSource(e.source_url)?<a href={safeSource(e.source_url)} target="_blank" rel="noopener noreferrer"><MIcon name="file" size={15}/>{t('원문 근거','Source evidence')}<MIcon name="chevron" size={13}/></a>:<span className="m-muted">{t('원문 링크 확인 필요','Source link unavailable')}</span>}</div></li>)}</ol>}</article><time className="m-question-answer-time" dateTime={message.created_at}>{time(message.created_at)}</time></div></div></div>)}</div>
 {eventId&&<><section className="m-question-suggestions"><h2>{t('이런 내용도 궁금하지 않으세요?','What else would you like to explore?')}</h2><div>{[['이전 공시와 비교','Compare prior filings','이전 공시와 무엇이 달라졌나요?','What changed from the prior filing?'],['매출 수치 근거','Revenue evidence','매출 수치의 근거를 보여줘','Show the evidence for revenue figures.'],['위험 요인','Risk disclosures','위험 요인의 원문을 보여줘','Show the source risk disclosures.']].map(([ko,en,promptKo,promptEn])=><button className="m-pill" type="button" key={ko} disabled={!canAsk} onClick={()=>setQuestion(t(promptKo,promptEn))}><MIcon name="search" size={14}/>{t(ko,en)}</button>)}</div></section><p className="m-note">{t('답변은 선택한 이벤트의 근거에 한정됩니다. 근거가 부족하면 확인할 수 없다고 안내합니다.','Answers are limited to the selected event’s evidence and state when evidence is insufficient.')}</p></>}
 <section className="m-question-history" ref={controls}><LoadState {...feed} retry={feed.reload}/><label className="m-field"><span>{t('질문할 이벤트','Event to ask about')}</span><select ref={eventSelect} value={eventId} disabled={action.busy} onChange={e=>choose(e.target.value)}><option value="">{t('이벤트를 선택하세요','Choose an event')}</option>{detail.data&&!feed.data?.items.some(e=>e.id===eventId)&&<option value={eventId}>{detail.data.event.company.name} · {detail.data.event.headline}</option>}{feed.data?.items.map(e=><option value={e.id} key={e.id}>{e.company.name} · {e.headline}</option>)}</select></label><div className="m-section-title"><h2>{t('최근 질문 기록','Recent questions')}</h2><button type="button" disabled={action.busy||history.loading||!savedHistory.length} onClick={()=>{if(window.confirm(t('내 질문 기록을 모두 삭제할까요?','Delete all your question history?')))void action.run(async()=>{await request('/v1/questions',auth.token,emptySchema,body('DELETE'));setClearedIds(old=>[...new Set([...old,...savedHistory.map(item=>item.id)])]);setLocalMessages([]);history.reload();});}}>{t('기록 삭제','Clear history')}</button></div><LoadState {...history} retry={history.reload}/>{savedHistory.slice(0,20).map(item=><button className="m-card m-question-history-item" type="button" key={item.id} disabled={action.busy} onClick={()=>choose(item.event_id,item.id)}><strong>{item.question}</strong><span>{date(item.created_at)}</span><MIcon name="chevron" size={16}/></button>)}{history.data?.length===100&&<p className="m-note">{t('최근 100개 질문에서 선택한 이벤트의 대화를 표시합니다.','The conversation includes this event’s questions from the latest 100 saved questions.')}</p>}{!history.loading&&!history.error&&!savedHistory.length&&<p className="m-note">{t('저장된 질문이 없습니다.','No saved questions.')}</p>}</section>
 <form className="m-question-compose" onSubmit={e=>{e.preventDefault();ask();}}><button className="m-question-more" type="button" aria-label={t('이벤트 선택 및 질문 기록','Choose event and question history')} onClick={()=>{controls.current?.scrollIntoView({block:'start'});eventSelect.current?.focus({preventScroll:true});}}><MIcon name="plus" size={24}/></button><label><span id={questionLabelId} className="m-research-sr">{t('공시에 관한 질문','Question about the filing')}</span><textarea aria-labelledby={questionLabelId} rows={1} value={question} maxLength={2000} disabled={!canAsk} onChange={e=>setQuestion(e.target.value)} placeholder={t('추가 질문을 입력하세요.','Enter a follow-up question.')}/></label><button className="m-question-send" aria-label={action.busy?t('근거 확인 중…','Checking evidence…'):t('질문 보내기','Send question')} disabled={!canAsk||!question.trim()}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 3 17 9L4 21l3-8 8-1-8-1Z" fill="currentColor"/></svg></button></form>
 </div>;
}
