'use client';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {Suspense,useEffect,useState} from 'react';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {usePrefs} from '@/workspace/preferences';
import {workspace} from '@/workspace/client';
import {useData,useMutation} from '@/workspace/ui';
import {savedSchema,resourceHref,type Resource} from '@/workspace/contracts';
import {CompanyLogo,MIcon,EmptyState,LoadState,ActionNotice,Dialog} from '@/mobile/ui';
import {typeLabels} from '@/lib/format';
import './collections.css';

type SavedTab='event'|'document'|'history';
export default function MobileSaved(){
 return <Suspense fallback={<LoadState loading/>}><SavedContent/></Suspense>;
}
function SavedContent(){
 const params=useSearchParams(),requestedKind=params.get('kind'),requestedCompany=params.get('company')??'',initialTab:SavedTab=requestedKind==='document'||requestedKind==='history'?requestedKind:'event';
 const {token}=useAuth(),prefs=usePrefs(),{text:t,date,value}=prefs,action=useMutation(),[tab,setTab]=useState<SavedTab>(initialTab),[company,setCompany]=useState(requestedCompany),[category,setCategory]=useState(''),[days,setDays]=useState(0),[clear,setClear]=useState(false),[now]=useState(()=>Date.now());
 useEffect(()=>{setTab(initialTab);setCompany(requestedCompany);setCategory('');setDays(0);},[initialTab,requestedCompany]);
 const saved=useData({action:'saved_list',p:{kind:'',sort:'newest'}},savedSchema),history=useData(tab==='history'?{action:'saved_list',p:{kind:'history',sort:'newest'}}:null,savedSchema),resource=tab==='history'?history:saved;
 const all=resource.data?.items??[],typed=all.filter(item=>tab==='history'||tab==='event'&&item.kind==='event'||tab==='document'&&(item.kind==='document'||item.kind==='filing'));
 const companies=[...new Map(typed.map(item=>[item.company_id,{id:item.company_id,name:item.company_name}])).values()].sort((a,b)=>a.name.localeCompare(b.name,value.locale)),categories=[...new Set(typed.map(item=>item.category).filter(Boolean))].sort();
 const items=typed.filter(item=>(!company||item.company_id===company)&&(!category||item.category===category)&&(!days||!!item.saved_at&&Date.parse(item.saved_at)>=now-days*86400000));
 const savedItems=saved.data?.items??[],total=saved.data?saved.data.counts.event+saved.data.counts.document:null,weekly=savedItems.filter(item=>item.saved_at&&Date.parse(item.saved_at)>=now-7*86400000).length,latest=savedItems.map(item=>item.saved_at??'').filter(iso=>Number.isFinite(Date.parse(iso))).sort((a,b)=>Date.parse(a)-Date.parse(b)).at(-1)??null;
 const groups=new Map<string,number>();for(const item of savedItems)if(item.category)groups.set(item.category,(groups.get(item.category)??0)+1);const frequent=[...groups].sort((a,b)=>b[1]-a[1])[0];
 const label=(key:string)=>value.locale==='ko'?typeLabels[key]??key:key;
 const localDay=(input:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:value.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(input));
 const latestIsToday=latest&&localDay(latest)===localDay(new Date(now).toISOString());
 function track(item:Resource){if(value.history_enabled)void workspace(token,{action:'visit',p:{kind:item.kind,id:item.id}},z.unknown()).catch(()=>{});}
 function switchTab(next:SavedTab){setTab(next);setCompany('');setCategory('');setDays(0);}
 async function toggleSaved(item:Resource){if(item.kind==='company')return;await workspace(token,{action:'save',p:{kind:item.kind,id:item.id,saved:!item.is_saved}},z.object({saved:z.boolean()}));saved.reload();if(tab==='history')history.reload();}
 return <div className="m-saved-page"><header className="m-saved-heading"><h1>{t('저장 / 기록','Saved / history')}</h1><p>{t('관심 있는 정보를 저장하고, 언제든 다시 확인하세요.','Save useful information and return whenever you need it.')}</p></header>
 <nav className="m-saved-tabs" aria-label={t('저장 유형','Saved content types')}>{[['event',t('저장한 이벤트','Saved events')],['document',t('북마크한 문서','Bookmarked sources')],['history',t('최근 본 항목','Recently viewed')]].map(([key,title])=><button key={key} className={tab===key?'active':''} aria-pressed={tab===key} onClick={()=>switchTab(key as SavedTab)}>{title}</button>)}</nav><ActionNotice action={action}/>
 <section className="m-saved-stats" aria-label={t('저장 활동 요약','Saved activity summary')}><div className="m-card"><i className="blue"><MIcon name="bookmark" size={23}/></i><div><span>{t('총 저장 수','Total saved')}</span><strong>{total??'—'}{total!==null?t('개',''):''}</strong><small>{saved.data?`+${weekly} (${t('최근 7일','last 7 days')})`:'—'}</small></div></div><div className="m-card"><i className="green"><MIcon name="clock" size={23}/></i><div><span>{t('최근 활동','Latest save')}</span><strong>{latestIsToday?t('오늘','Today'):latest?date(latest,'date'):t('아직 없음','None yet')}</strong><small>{latest?date(latest,'date'):'—'}</small></div></div><div className="m-card"><i className="purple"><MIcon name="trend" size={23}/></i><div><span>{t('자주 저장하는 유형','Most saved type')}</span><strong>{frequent?label(frequent[0]):'—'}</strong><small>{frequent&&savedItems.length?`${t('전체의 ','')}${Math.round(frequent[1]/savedItems.length*100)}%${t('',' of saves')}`:'—'}</small></div></div></section>
 <div className="m-saved-filters"><strong>{t('필터','Filter')}</strong><label><MIcon name="home" size={21}/><span><small>{t('기업','Company')}</small><select aria-label={t('저장 항목 기업','Saved company filter')} value={company} onChange={e=>setCompany(e.target.value)}><option value="">{t('전체','All')}</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></span></label><label><MIcon name="file" size={21}/><span><small>{t('유형','Type')}</small><select aria-label={t('저장 항목 유형','Saved type filter')} value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t('전체','All')}</option>{categories.map(c=><option key={c} value={c}>{label(c)}</option>)}</select></span></label><label><MIcon name="calendar" size={21}/><span><small>{t('기간','Period')}</small><select aria-label={t('저장 기간','Saved date filter')} value={days} onChange={e=>setDays(Number(e.target.value))}><option value={0}>{t('전체 기간','All time')}</option><option value={7}>{t('최근 7일','7 days')}</option><option value={30}>{t('최근 30일','30 days')}</option><option value={90}>{t('최근 90일','90 days')}</option><option value={365}>{t('최근 1년','1 year')}</option></select></span></label></div>
 {tab==='history'&&<aside className="m-saved-history-note"><p>{value.history_enabled?t('최근에 열어 본 기업·이벤트·문서를 확인하세요.','Return to companies, events and sources you recently opened.'):t('방문 기록 저장이 꺼져 있습니다. 설정에서 켤 수 있어요.','Browsing history is off. Enable it in account settings.')}</p><Link href="/settings/account">{t('기록 설정','History settings')}</Link>{history.data?.items.length?<button onClick={()=>setClear(true)}>{t('기록 지우기','Clear history')}</button>:null}</aside>}
 <LoadState loading={resource.loading} error={resource.error||undefined} retry={resource.reload}/>
 <div className="m-saved-list">{!resource.loading&&items.map(item=><article className="m-card m-saved-card" key={`${item.kind}:${item.id}`}><CompanyLogo ticker={item.ticker} size={47}/><div className="m-saved-content"><Link className="m-saved-company" href={`/companies/${item.company_id}`}><strong>{item.company_name}</strong><span>{item.ticker}</span></Link><Link className="m-saved-title" href={resourceHref(item)} onClick={()=>track(item)}>{item.title}</Link>{item.summary&&<p>{item.summary}</p>}<div className="m-saved-tags">{item.category&&<span>{label(item.category)}</span>}<span className={item.kind==='event'?'purple':'green'}>{item.kind==='company'?t('기업','Company'):item.kind==='event'?t('이벤트','Event'):t('문서','Source')}</span>{item.market&&<span>{item.market}</span>}</div></div><div className="m-saved-side"><time dateTime={item.saved_at}>{item.saved_at?`${date(item.saved_at,'date')} ${tab==='history'?t('열람','viewed'):t('저장','saved')}`:'—'}</time><div><Link href={resourceHref(item)} onClick={()=>track(item)} aria-label={`${item.title} ${t('다시 보기','open')}`}><MIcon name="eye" size={19}/><span>{t('다시 보기','View')}</span></Link>{item.kind!=='company'&&<button className={tab==='history'&&!item.is_saved?'save':'delete'} disabled={action.busy} aria-label={`${item.title} ${item.is_saved?t('저장 취소','unsave'):t('저장','save')}`} aria-pressed={item.is_saved} onClick={()=>void action.run(()=>toggleSaved(item),item.is_saved?t('저장을 취소했습니다.','Removed from saved items.'):t('자료를 저장했습니다.','Item saved.'))}><MIcon name={tab==='history'&&!item.is_saved?'bookmark':'trash'} size={19}/><span>{tab==='history'&&!item.is_saved?t('저장','Save'):t('삭제','Delete')}</span></button>}</div></div></article>)}</div>
 {!resource.loading&&resource.data&&!items.length&&<EmptyState title={typed.length?t('조건에 맞는 항목이 없습니다.','No items match these filters.'):tab==='history'?t('아직 방문 기록이 없습니다.','No browsing history yet.'):t('아직 저장된 항목이 없습니다.','No saved items yet.')} description={t('이벤트와 문서의 저장 버튼을 눌러 다시 확인할 정보를 모아 보세요.','Bookmark events and sources you want to revisit.')} href="/explore" label={t('탐색하기','Explore')}/>}
 {clear&&<Dialog title={t('방문·검색 기록을 지울까요?','Clear browsing and search history?')} onClose={()=>setClear(false)}><ActionNotice action={action}/><p>{t('이 계정의 최근 방문과 검색어가 삭제됩니다. 저장한 이벤트와 문서는 유지됩니다.','Your recent visits and search queries will be removed. Saved events and sources are retained.')}</p><button className="m-button" disabled={action.busy} onClick={()=>void action.run(async()=>{await workspace(token,{action:'history_clear',p:{}},z.unknown());setClear(false);history.reload();},t('방문·검색 기록을 지웠습니다.','Browsing and search history cleared.'))}>{t('기록 지우기','Clear history')}</button></Dialog>}
 </div>;
}
