'use client';

import Link from 'next/link';
import Image from 'next/image';
import {useEffect,useState,type FormEvent} from 'react';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {initializeSupabase} from '@/lib/supabase';
import {useIdentity} from '@/workspace/account';
import {usePrefs} from '@/workspace/preferences';
import {useData,useMutation} from '@/workspace/ui';
import {securitySchema} from '@/workspace/contracts';
import {ActionNotice,Dialog,LoadState,MIcon} from './ui';
import {AccountIcon,AccountToggle,providerName} from './account';
import './account-security.css';

type Factor={id:string;friendly_name?:string;status:string;factor_type?:string};
type Session=z.infer<typeof securitySchema>['sessions'][number];
type Modal='password'|'providers'|'mfa'|'history'|'sessions'|'end-sessions'|null;
export function sessionDevice(agent:string|null,unknown:string){
 if(!agent)return unknown;
 const os=/iPhone|iPad/.test(agent)?(/iPad/.test(agent)?'iPad':'iPhone'):/Android/.test(agent)?'Android':/Windows/.test(agent)?'Windows':/Macintosh|Mac OS/.test(agent)?'Mac':/Linux/.test(agent)?'Linux':'';
 const browser=/Edg\//.test(agent)?'Edge':/Firefox\//.test(agent)?'Firefox':/Chrome\/|CriOS\//.test(agent)?'Chrome':/Safari\//.test(agent)?'Safari':'';
 return [os,browser].filter(Boolean).join(' · ')||unknown;
}
export default function MobileSecurity(){const {me}=useAuth();return <SecurityContent key={me?.id??'anonymous'}/>;}
function SecurityContent(){
 const {text:t,date}=usePrefs(),identity=useIdentity(),result=useData({action:'security',p:{}},securitySchema),action=useMutation();
 const [factors,setFactors]=useState<Factor[]>([]),[mfaLoading,setMfaLoading]=useState(true),[mfaError,setMfaError]=useState(''),[revision,setRevision]=useState(0);
 const [modal,setModal]=useState<Modal>(null),[setup,setSetup]=useState<{id:string;qr:string;secret:string}|null>(null),[remove,setRemove]=useState<Factor|null>(null),[code,setCode]=useState(''),[unlink,setUnlink]=useState<string|null>(null),[session,setSession]=useState<Session|null>(null);
 const [current,setCurrent]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[passwordCode,setPasswordCode]=useState(''),[show,setShow]=useState(false),[passwordFocus,setPasswordFocus]=useState('current');
 useEffect(()=>{let active=true;setMfaLoading(true);setMfaError('');initializeSupabase().then(db=>db.auth.mfa.listFactors()).then(r=>{if(r.error)throw r.error;if(active)setFactors(r.data.all??r.data.totp);}).catch(()=>{if(active)setMfaError(t('2단계 인증 상태를 확인하지 못했습니다.','Could not verify two-step authentication status.'));}).finally(()=>{if(active)setMfaLoading(false);});return()=>{active=false;};},[revision,t]);
 const verified=factors.filter(f=>f.status==='verified'),totp=verified.filter(f=>!f.factor_type||f.factor_type==='totp'),providers=identity.user?.identities??[],hasEmailLogin=providers.some(i=>i.provider==='email');
 const identityLoading=!identity.user&&!identity.error,ready=!!identity.user&&!identity.error&&!mfaLoading&&!mfaError&&!action.busy;
 const close=()=>{if(action.busy)return;setModal(null);setSetup(null);setRemove(null);setUnlink(null);setSession(null);setCode('');setCurrent('');setPassword('');setRepeat('');setPasswordCode('');setRevision(n=>n+1);};
 const freshFactors=async()=>{const db=await initializeSupabase(),r=await db.auth.mfa.listFactors();if(r.error)throw new Error(t('인증 상태를 다시 확인해 주세요.','Refresh authentication status.'));const all=r.data.all??r.data.totp;setFactors(all);return all.filter(f=>f.status==='verified');};
 async function begin(){if(!ready)return;await action.run(async()=>{const db=await initializeSupabase(),r=await db.auth.mfa.listFactors();if(r.error)throw new Error(t('인증 상태를 확인하지 못했습니다.','Could not check authentication status.'));const all=r.data.all??r.data.totp;if(all.some(f=>f.status==='verified')){setFactors(all);setModal('mfa');return;}for(const f of all.filter(f=>f.status!=='verified'&&(!f.factor_type||f.factor_type==='totp'))){const removed=await db.auth.mfa.unenroll({factorId:f.id});if(removed.error)throw new Error(t('미완료 설정을 정리하지 못했습니다.','Could not clear incomplete enrollment.'));}const enrolled=await db.auth.mfa.enroll({factorType:'totp',friendlyName:'SignalBrief Authenticator'});if(enrolled.error)throw new Error(t('2단계 인증 설정을 시작하지 못했습니다.','Could not start enrollment.'));setSetup({id:enrolled.data.id,qr:enrolled.data.totp.qr_code,secret:enrolled.data.totp.secret});setCode('');});}
 async function verifyMfa(event:FormEvent){event.preventDefault();await action.run(async()=>{if(!/^\d{6}$/.test(code))throw new Error(t('6자리 코드를 입력해 주세요.','Enter a six-digit code.'));const id=setup?.id??remove?.id;if(!id)throw new Error(t('인증 설정을 다시 열어 주세요.','Reopen authentication settings.'));const db=await initializeSupabase(),check=await db.auth.mfa.challengeAndVerify({factorId:id,code});if(check.error)throw new Error(t('인증 코드가 잘못되었거나 만료되었습니다.','The code is invalid or expired.'));if(remove){const removed=await db.auth.mfa.unenroll({factorId:id});if(removed.error)throw new Error(t('2단계 인증을 해제하지 못했습니다.','Could not disable verification.'));}setSetup(null);setRemove(null);setModal(null);setCode('');setRevision(n=>n+1);result.reload();},t('2단계 인증 설정을 업데이트했습니다.','Two-step verification updated.'));}
 async function changePassword(event:FormEvent){event.preventDefault();if(!ready)return;await action.run(async()=>{if(!hasEmailLogin||!identity.user?.email||!identity.user.email_confirmed_at)throw new Error(t('비밀번호 재설정 메일에서 계정을 확인해 주세요.','Verify your account through the password reset email.'));if(password.length<12||password.length>128||password!==repeat)throw new Error(t('12~128자와 비밀번호 확인을 점검해 주세요.','Use 12–128 characters and matching confirmation.'));const active=await freshFactors(),factor=active.find(f=>!f.factor_type||f.factor_type==='totp');if(active.length&&!factor)throw new Error(t('현재 인증 방식으로 추가 인증이 필요합니다.','Additional verification with your current authentication method is required.'));if(factor&&!/^\d{6}$/.test(passwordCode))throw new Error(t('현재 인증 앱의 6자리 코드를 입력해 주세요.','Enter the current six-digit authenticator code.'));const db=await initializeSupabase(),reauth=await db.auth.signInWithPassword({email:identity.user.email,password:current});if(reauth.error||reauth.data.user?.id!==identity.user.id)throw new Error(t('현재 비밀번호를 확인해 주세요.','Check your current password.'));if(factor){const check=await db.auth.mfa.challengeAndVerify({factorId:factor.id,code:passwordCode});if(check.error)throw new Error(t('현재 인증 앱의 코드를 확인해 주세요.','Check your authenticator code.'));}const changed=await db.auth.updateUser({password});if(changed.error)throw new Error(t('추가 인증 또는 비밀번호 재설정 메일이 필요합니다.','Additional verification or a password reset email is required.'));setCurrent('');setPassword('');setRepeat('');setPasswordCode('');setModal(null);identity.reload();result.reload();},t('비밀번호를 변경했습니다.','Password changed.'));}
 const openPassword=(focus:string)=>{setPasswordFocus(focus);setModal('password');};
 const sessionRows=(items:Session[])=>items.map(item=><button type="button" className="m-security-record" key={item.id} onClick={()=>setSession(item)}><MIcon name="monitor" size={23}/><span><strong>{sessionDevice(item.user_agent,t('기기 정보 미확인','Device unavailable'))}</strong><small>{date(item.last_seen)}{item.current?` · ${t('현재 세션','Current session')}`:''}</small></span>{item.current?<em>{t('현재 사용 중','Current')}</em>:<MIcon name="chevron" size={16}/>}</button>);
 return <div className="m-security-page"><h1 className="m-visually-hidden">{t('보안 및 로그인','Security & sign-in')}</h1>
  <ActionNotice action={action}/><LoadState loading={identityLoading} error={identity.error} retry={identity.reload}/>
  <section className="m-card m-security-summary"><AccountIcon name="shield" tone="green"/><div><h2>{mfaLoading?t('보안 설정 확인 중','Checking security settings'):mfaError?t('보안 상태 확인이 필요합니다','Security status needs checking'):verified.length?t('2단계 인증이 설정되어 있습니다','Two-step verification is enabled'):t('계정의 보안 설정을 확인하세요','Review your account security')}</h2><p>{t('마지막 로그인','Last sign-in')}: {date(identity.user?.last_sign_in_at??null)}</p><div className="m-security-status"><span data-verified={!identity.error&&!!identity.user?.email_confirmed_at}><MIcon name={identity.user?.email_confirmed_at?'check':'info'} size={13}/>{identityLoading?t('이메일 확인 중','Checking email'):identity.user?.email_confirmed_at?t('이메일 인증됨','Email verified'):t('이메일 미확인','Email unverified')}</span><span data-verified={!mfaLoading&&!mfaError&&verified.length>0}><MIcon name={!mfaLoading&&!mfaError&&verified.length?'check':'info'} size={13}/>{mfaLoading||mfaError?t('2단계 인증 확인 중','Checking verification'):verified.length?t('2단계 인증 사용 중','Verification enabled'):t('2단계 인증 미설정','Verification not enabled')}</span></div></div></section>
  <section className="m-card m-security-password"><header><AccountIcon name="lock" tone="purple"/><div><h2>{t('비밀번호 변경','Change password')}</h2><p>{t('계정을 확인한 후 새 비밀번호를 설정합니다.','Verify your account before changing the password.')}</p></div></header><div className="m-security-password-rows">{[['current',t('현재 비밀번호','Current password'),t('현재 사용 중인 비밀번호를 입력하세요.','Enter your current password.')],['new',t('새 비밀번호','New password'),t('새 비밀번호를 입력하세요.','Enter a new password.')],['repeat',t('새 비밀번호 확인','Confirm new password'),t('새 비밀번호를 한 번 더 입력하세요.','Enter the new password again.')]].map(([key,label,hint])=><button type="button" disabled={!ready} key={key} onClick={()=>openPassword(key)}><span><strong>{label}</strong><small>{hint}</small></span><MIcon name="chevron" size={17}/></button>)}</div></section>
  <button type="button" className="m-card m-security-setting" disabled={identityLoading||!!identity.error||action.busy} onClick={()=>setModal('providers')}><AccountIcon name={providers.some(i=>i.provider==='google')?'google':'lock'}/><span><strong>{t('연결된 계정','Connected accounts')}{providers.length?`: ${providers.map(i=>providerName(i.provider)).join(', ')}`:''}</strong><small>{providers.length?t('연결된 로그인 수단을 확인하고 관리합니다.','Review and manage connected sign-in methods.'):t('계정 정보를 확인해 주세요.','Check your account information.')}</small></span>{providers.length>0&&<em>{t('연결됨','Connected')}</em>}<MIcon name="chevron" size={17}/></button>
  <section className="m-card m-security-setting"><AccountIcon name="shield"/><div><h2>{t('2단계 인증','Two-step verification')}</h2><p>{t('로그인 시 추가 인증으로 계정을 보호합니다.','Protect sign-ins with additional verification.')}</p></div><AccountToggle label={t('2단계 인증','Two-step verification')} checked={!mfaError&&verified.length>0} disabled={!ready} onChange={()=>{if(verified.length)setModal('mfa');else void begin();}}/></section>
  <LoadState loading={mfaLoading} error={mfaError} retry={()=>setRevision(n=>n+1)}/>
  <section className="m-card m-security-notifications"><header><AccountIcon name="bell" tone="amber"/><div><h2>{t('보안 알림','Security notifications')}</h2><p>{t('보안 이메일 알림은 아직 제공하지 않습니다.','Security notification emails are not yet available.')}</p></div></header><div className="m-security-notification-rows">{[[t('새로운 로그인 알림','New sign-in alerts'),t('새 기기 로그인 알림 · 준비 중','New-device alerts · not available')],[t('계정 보안 주요 변경 알림','Account security changes'),t('보안 설정 변경 알림 · 준비 중','Security change alerts · not available')]].map(([label,hint])=><div key={label}><span><strong>{label}</strong><small>{hint}</small></span><AccountToggle label={label} checked={false} disabled/></div>)}</div></section>
  <section className="m-card m-security-records"><header><AccountIcon name="clock"/><h2>{t('최근 계정 활동','Recent account activity')}</h2><button type="button" onClick={()=>setModal('history')}>{t('전체 보기','View all')}<MIcon name="chevron" size={14}/></button></header><LoadState {...result} retry={result.reload}/>{result.data?.history.slice(0,3).map((item,index)=><div className="m-security-record" key={`${item.created_at}-${index}`}><MIcon name="clock" size={21}/><span><strong>{item.action}</strong><small>{date(item.created_at)}</small></span></div>)}{result.data&&!result.data.history.length&&<p className="m-security-empty">{t('기록된 계정 활동이 없습니다.','No recorded account activity.')}</p>}</section>
  <section className="m-card m-security-records"><header><AccountIcon name="monitor"/><h2>{t('활성 세션 / 기기','Active sessions / devices')}</h2><button type="button" onClick={()=>setModal('sessions')}>{t('전체 기기 관리','Manage devices')}<MIcon name="chevron" size={14}/></button></header>{result.loading?<LoadState loading/>:result.error?<LoadState loading={false} error={result.error} retry={result.reload}/>:sessionRows(result.data?.sessions.slice(0,3)??[])}{result.data&&!result.data.sessions.length&&<p className="m-security-empty">{t('활성 세션 기록이 없습니다.','No active session records.')}</p>}</section>

  {modal==='password'&&<Dialog title={t('비밀번호 변경','Change password')} onClose={close}><ActionNotice action={action}/>{hasEmailLogin?<form onSubmit={changePassword}><label>{t('현재 비밀번호','Current password')}<input autoFocus={passwordFocus==='current'} required type={show?'text':'password'} autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} maxLength={128} disabled={action.busy}/></label><label>{t('새 비밀번호','New password')}<input autoFocus={passwordFocus==='new'} required type={show?'text':'password'} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} maxLength={128} disabled={action.busy}/></label><label>{t('새 비밀번호 확인','Confirm new password')}<input autoFocus={passwordFocus==='repeat'} required type={show?'text':'password'} autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)} maxLength={128} disabled={action.busy}/></label>{totp.length>0&&<label>{t('인증 앱 코드','Authenticator code')}<input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={passwordCode} onChange={e=>setPasswordCode(e.target.value.replace(/\D/g,''))} disabled={action.busy}/></label>}<label className="m-account-checkbox"><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/>{t('비밀번호 보기','Show passwords')}</label><p className="m-account-dialog-note">{t('12~128자의 다른 서비스와 다른 비밀번호를 사용하세요.','Use a unique password with 12–128 characters.')}</p><button className="m-button" disabled={!ready}>{t('비밀번호 저장','Save password')}</button></form>:<p className="m-account-dialog-note">{t('외부 계정으로 로그인했습니다. 비밀번호를 설정하려면 재설정 메일에서 계정을 먼저 확인하세요.','You use an external sign-in provider. Verify your account through a reset email before setting a password.')}</p>}<Link className="m-account-dialog-link" href="/forgot-password">{t('비밀번호 재설정 메일 받기','Request password reset email')}<MIcon name="chevron" size={15}/></Link></Dialog>}
  {modal==='providers'&&!unlink&&<Dialog title={t('연결된 로그인 수단','Connected sign-in methods')} onClose={close}><ActionNotice action={action}/>{providers.map(item=><div className="m-security-provider" key={item.identity_id}><AccountIcon name={item.provider==='google'?'google':'mail'}/><div><strong>{providerName(item.provider)}</strong><small>{typeof item.identity_data?.email==='string'?item.identity_data.email:identity.user?.email??t('이메일 미확인','Email unavailable')}</small></div>{item.provider!=='email'&&<button type="button" disabled={providers.length<2||!ready} onClick={()=>{setUnlink(item.identity_id);setCode('');}}>{t('연결 해제','Unlink')}</button>}</div>)}{!providers.length&&<p>{t('연결된 로그인 수단을 확인할 수 없습니다.','Connected sign-in methods are unavailable.')}</p>}<p className="m-account-dialog-note">{t('마지막 로그인 수단은 해제할 수 없습니다. 연결 해제에는 추가 인증이 필요할 수 있습니다.','The last sign-in method cannot be removed. Unlinking may require additional authentication.')}</p></Dialog>}
  {modal==='mfa'&&!remove&&<Dialog title={t('2단계 인증 관리','Manage two-step verification')} onClose={close}><ActionNotice action={action}/>{verified.map(factor=><div className="m-security-provider" key={factor.id}><AccountIcon name="shield"/><div><strong>{factor.friendly_name||t('추가 인증','Additional verification')}</strong><small>{t('인증됨','Verified')}</small></div>{(!factor.factor_type||factor.factor_type==='totp')&&<button type="button" disabled={!ready} onClick={()=>{setCode('');setRemove(factor);}}>{t('해제','Disable')}</button>}</div>)}<p className="m-account-dialog-note">{t('인증 앱 코드를 확인한 후에만 해제됩니다.','Disabling requires verification of your authenticator code.')}</p></Dialog>}
  {(setup||remove)&&<Dialog title={setup?t('인증 앱 연결','Connect authenticator'):t('2단계 인증 해제','Disable two-step verification')} onClose={close}><ActionNotice action={action}/>{setup?<><p className="m-account-dialog-note">{t('QR 코드를 인증 앱으로 스캔하고 6자리 코드를 입력하세요.','Scan the QR code with your authenticator and enter its six-digit code.')}</p>{setup.qr.startsWith('data:image/')&&<Image unoptimized className="m-security-qr" src={setup.qr} alt={t('인증 앱 등록 QR 코드','Authenticator enrollment QR code')} width={180} height={180}/>}<details className="m-security-secret"><summary>{t('수동 설정 키 보기','Show manual setup key')}</summary><code>{setup.secret}</code></details></>:<p className="m-account-dialog-note">{t('현재 인증 앱의 코드가 있어야 2단계 인증을 해제할 수 있습니다.','Your current authenticator code is required to disable verification.')}</p>}<form onSubmit={verifyMfa}><label>{t('인증 코드','Verification code')}<input autoFocus required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} disabled={action.busy}/></label><button className="m-button" disabled={action.busy}>{setup?t('인증 후 활성화','Verify and enable'):t('인증 후 해제','Verify and disable')}</button></form></Dialog>}
  {modal==='history'&&<Dialog title={t('최근 계정 활동','Recent account activity')} onClose={close}><LoadState {...result} retry={result.reload}/>{result.data?.history.map((item,index)=><div className="m-security-record" key={`${item.created_at}-${index}`}><MIcon name="clock"/><span><strong>{item.action}</strong><small>{date(item.created_at)}</small></span></div>)}{result.data&&!result.data.history.length&&<p>{t('기록된 활동이 없습니다.','No recorded activity.')}</p>}<button className="m-button m-button-secondary" disabled={result.loading} onClick={result.reload}>{t('새로고침','Refresh')}</button></Dialog>}
  {modal==='sessions'&&!session&&<Dialog title={t('활성 세션 / 기기','Active sessions / devices')} onClose={close}><LoadState {...result} retry={result.reload}/>{sessionRows(result.data?.sessions??[])}<p className="m-account-dialog-note">{t('기기 표시는 기록된 브라우저 정보에 기반합니다. 위치는 확인되지 않았습니다.','Device labels use recorded browser information. Locations are not available.')}</p><button className="m-button m-button-secondary" disabled={action.busy} onClick={()=>setModal('end-sessions')}>{t('다른 모든 기기 로그아웃','Sign out all other sessions')}</button></Dialog>}
  {session&&<Dialog title={t('로그인 세션 상세','Sign-in session details')} onClose={()=>{if(!action.busy)setSession(null);}}><dl className="m-security-session-details"><dt>{t('기기 정보','Device information')}</dt><dd>{session.user_agent||t('확인되지 않았습니다','Not available')}</dd><dt>{t('세션 시작','Session started')}</dt><dd>{date(session.created_at)}</dd><dt>{t('마지막 갱신','Last refreshed')}</dt><dd>{date(session.last_seen)}</dd><dt>{t('인증 수준','Authentication assurance')}</dt><dd>{session.aal??t('확인 전','Not available')}</dd><dt>{t('현재 세션','Current session')}</dt><dd>{session.current?t('예','Yes'):t('아니요','No')}</dd></dl></Dialog>}
  {modal==='end-sessions'&&<Dialog title={t('다른 세션을 종료할까요?','End other sessions?')} onClose={close}><ActionNotice action={action}/><p className="m-account-dialog-note">{t('현재 기기는 로그인 상태를 유지합니다. 다른 세션의 갱신 권한을 해제하며, 이미 발급된 접근 토큰은 만료까지 유효할 수 있습니다.','This device stays signed in. Other sessions lose refresh access; issued access tokens may remain valid until expiry.')}</p><button className="m-button m-account-danger" disabled={action.busy} onClick={()=>void action.run(async()=>{const db=await initializeSupabase(),response=await db.auth.signOut({scope:'others'});if(response.error)throw new Error(t('다른 세션을 종료하지 못했습니다.','Could not end other sessions.'));setModal(null);result.reload();},t('다른 세션의 갱신 권한을 해제했습니다.','Other session refresh access was revoked.'))}>{t('다른 세션 종료','End other sessions')}</button></Dialog>}
  {unlink&&<Dialog title={t('계정 연결 해제','Unlink account')} onClose={close}><ActionNotice action={action}/><p className="m-account-dialog-note">{t('이 로그인 수단을 해제합니다. 다른 로그인 방법을 먼저 확인하세요.','This sign-in method will be removed. Confirm another method first.')}</p>{totp.length>0&&<label className="m-field">{t('인증 코드','Verification code')}<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label>}<button className="m-button m-account-danger" disabled={!ready} onClick={()=>void action.run(async()=>{const db=await initializeSupabase(),user=await db.auth.getUser();if(user.error||user.data.user?.id!==identity.user?.id)throw new Error(t('계정을 다시 확인해 주세요.','Verify your account again.'));const methods=user.data.user.identities??[],method=methods.find(item=>item.identity_id===unlink);if(!method||methods.length<2)throw new Error(t('다른 로그인 수단이 필요합니다.','Another sign-in method is required.'));const active=await freshFactors();if(active.length){const factor=active.find(f=>!f.factor_type||f.factor_type==='totp');if(!factor||!/^\d{6}$/.test(code))throw new Error(t('인증 앱 코드를 확인해 주세요.','Check the authenticator code.'));const checked=await db.auth.mfa.challengeAndVerify({factorId:factor.id,code});if(checked.error)throw new Error(t('인증 코드가 잘못되었거나 만료되었습니다.','The code is invalid or expired.'));}const response=await db.auth.unlinkIdentity(method);if(response.error)throw new Error(t('추가 인증이 필요하거나 연결 해제가 허용되지 않습니다.','Additional verification is required or unlinking is not allowed.'));setUnlink(null);identity.reload();result.reload();},t('로그인 수단의 연결을 해제했습니다.','Sign-in method unlinked.'))}>{t('연결 해제','Unlink')}</button></Dialog>}
 </div>;
}
