'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useAuth} from '@/components/auth';
import {useResource} from '@/components/ui';
import {companiesSchema,feedSchema,watchlistSchema,type Company} from '@/lib/contracts';
import {body,emptySchema,errorMessage,request} from '@/lib/api';
import {usePrefs} from '@/workspace/preferences';
import {useMutation} from '@/workspace/ui';
import {useQuotes} from '@/workspace/market';
import {CompanyLogo,MIcon,EmptyState,LoadState,ActionNotice,SmallChart,formatMoney,relativeTime,Dialog} from '@/mobile/ui';
import './collections.css';

const korean=(c:Company)=>c.provider==='dart'||/KOSPI|KOSDAQ|KRX|KONEX/i.test(c.market);
const american=(c:Company)=>c.provider==='sec'||/NASDAQ|NYSE|AMEX|NYSEARCA/i.test(c.market);
export default function MobileWatchlist(){
 const {token}=useAuth(),prefs=usePrefs(),{text:t}=prefs,action=useMutation(),list=useResource('/v1/watchlist',watchlistSchema),feed=useResource('/v1/feed?days=180&limit=100',feedSchema);
 const [country,setCountry]=useState('all'),[sort,setSort]=useState('importance'),[add,setAdd]=useState(false),[query,setQuery]=useState(''),[search,setSearch]=useState('');
 const catalog=useResource(add?`/v1/companies?q=${encodeURIComponent(search)}&limit=50`:null,companiesSchema);
 useEffect(()=>{const timer=setTimeout(()=>setSearch(query.trim()),250);return()=>clearTimeout(timer);},[query]);
 const items=list.data?.items??[],prices=useQuotes(items.map(c=>c.ticker),'1m'),quoteMap=new Map(prices.quotes.map(q=>[q.symbol.toUpperCase(),q]));
 const latest=new Map<string,NonNullable<typeof feed.data>['items'][number]>(),importance=new Map<string,number>();
 for(const event of feed.data?.items??[]){const previous=latest.get(event.company.id);if(!previous||event.published_at>previous.published_at)latest.set(event.company.id,event);importance.set(event.company.id,Math.max(importance.get(event.company.id)??0,event.ranking.score));}
 const filtered=items.filter(c=>country==='all'||country==='kr'&&korean(c)||country==='us'&&american(c)).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,prefs.value.locale):sort==='newest'?(latest.get(b.id)?.published_at??'').localeCompare(latest.get(a.id)?.published_at??''):(importance.get(b.id)??-1)-(importance.get(a.id)??-1)||a.name.localeCompare(b.name,prefs.value.locale));
 async function mutate(id:string,method:'PUT'|'DELETE'){await request(`/v1/watchlist/${encodeURIComponent(id)}`,token,emptySchema,body(method)).catch(e=>{throw new Error(errorMessage(e));});list.reload();feed.reload();}
 return <div className="m-watch-page">
  <header className="m-watch-heading"><div><h1>{t('관심종목','Watchlist')}</h1><p>{t('총 ','Tracking ')}<strong>{list.data?items.length:'—'}{t('개','')}</strong>{t(' 종목을 추적 중이에요.',' companies.')}</p></div><button className="m-watch-add" onClick={()=>setAdd(true)}><span><MIcon name="plus" size={28}/></span>{t('종목 추가','Add stock')}</button></header>
  <ActionNotice action={action}/>
  <div className="m-watch-toolbar"><div className="m-watch-countries" role="group" aria-label={t('시장 필터','Market filter')}>{[['all',t('전체','All'),items.length],['kr',t('한국','Korea'),items.filter(korean).length],['us',t('미국','US'),items.filter(american).length]].map(([key,label,count])=><button key={key} className={country===key?'active':''} aria-pressed={country===key} onClick={()=>setCountry(String(key))}>{label} ({list.data?count:'—'})</button>)}</div><label className="m-watch-sort"><MIcon name="filter" size={17}/><select aria-label={t('관심종목 정렬','Watchlist sort')} value={sort} onChange={e=>setSort(e.target.value)}><option value="importance">{t('중요도 높은 순','Importance')}</option><option value="newest">{t('최근 변화 순','Latest change')}</option><option value="name">{t('기업 이름 순','Company name')}</option></select></label></div>
  <LoadState loading={list.loading} error={list.error??undefined} retry={list.reload}/>
  <div className="m-watch-list">{!list.loading&&filtered.map(company=>{const quote=quoteMap.get(company.ticker.toUpperCase()),event=latest.get(company.id),change=quote?.change_pct??null,muted=prefs.value.muted_companies.includes(company.id),delta=quote?.price!==null&&quote?.price!==undefined&&change!==null&&change>-100?quote.price-quote.price/(1+change/100):null;return <article className="m-card m-watch-card" key={company.id}>
   <div className="m-watch-card-top"><Link className="m-watch-company" href={`/companies/${company.id}`} aria-label={company.name}><CompanyLogo ticker={company.ticker} size={50}/><div><div className="m-watch-name"><strong>{company.name}</strong><span>{company.ticker}</span></div><b className="m-watch-price">{quote?.price!==null&&quote?.price!==undefined?formatMoney(quote.price,quote.currency,prefs.value.locale==='ko'?'ko-KR':'en-US'):'—'}</b><span className={`m-watch-change ${change===null?'':change>=0?'positive':'negative'}`}>{change===null?t('시세 확인 전','Quote unavailable'):<>{change>=0?'▲':'▼'} {delta===null?'':`${delta>=0?'+':''}${new Intl.NumberFormat(prefs.value.locale,{maximumFractionDigits:2}).format(delta)} `}({change>=0?'+':''}{change.toFixed(2)}%)</>}</span></div></Link>
   <div className={`m-watch-spark ${change!==null&&change<0?'negative':'positive'}`}><SmallChart values={quote?.history.map(h=>h.close)??[]}/></div>
   <div className="m-watch-actions"><button disabled={action.busy} onClick={()=>void action.run(()=>mutate(company.id,'DELETE'),t('관심종목에서 삭제했습니다.','Removed from your watchlist.'))} aria-label={`${company.name} ${t('관심종목 삭제','remove from watchlist')}`}><span><MIcon name="trash" size={18}/></span><small>{t('삭제','Delete')}</small></button><button className={muted?'muted':'enabled'} disabled={!prefs.loaded||prefs.busy||action.busy} aria-pressed={!muted} aria-label={`${company.name} ${t('알림','notifications')}`} title={muted?t('알림 다시 켜기','Unmute notifications'):t('알림 끄기','Mute notifications')} onClick={()=>void action.run(()=>prefs.save({muted_companies:muted?prefs.value.muted_companies.filter(id=>id!==company.id):[...prefs.value.muted_companies,company.id]}),muted?t('기업 알림을 켰습니다.','Company notifications enabled.'):t('기업 알림을 껐습니다.','Company notifications muted.'))}><span><MIcon name="bell" size={19}/>{muted&&<i/>}</span><small>{muted?t('알림 꺼짐','Muted'):t('알림','Alerts')}</small></button><Link href={`/companies/${company.id}`} aria-label={`${company.name} ${t('상세 보기','details')}`}><span className="detail"><MIcon name="chevron" size={20}/></span><small>{t('상세 보기','Details')}</small></Link></div></div>
   {event?<Link className="m-watch-event" href={`/events/${event.id}`}><i/><span>{event.headline}</span><time dateTime={event.published_at}>{relativeTime(event.published_at,prefs.value.locale)}</time></Link>:<p className="m-watch-event m-muted"><i/><span>{feed.loading?t('변화를 확인하고 있어요.','Loading changes.'):t('아직 확인된 변화가 없습니다.','No verified changes available.')}</span></p>}
   {quote&&<span className="m-watch-source">{quote.source} · {prefs.date(quote.as_of)}</span>}
  </article>;})}</div>
  {!list.loading&&list.data&&!filtered.length&&<EmptyState title={items.length?t('선택한 시장의 관심종목이 없습니다.','No watched companies in this market.'):t('관심종목을 추가해 보세요.','Add your first company.')} description={t('기업을 선택하면 중요한 변화와 근거를 모아 볼 수 있어요.','Follow a company to see its important changes and sources.')}/>}
  {feed.error&&<LoadState loading={false} error={feed.error} retry={feed.reload}/>}
  {prices.reason&&!prices.loading&&items.length>0&&<p className="m-watch-data-note">{t('현재 연결된 시세가 없는 종목은 —로 표시합니다.','Companies without an available market quote display —.')}</p>}
  <aside className="m-watch-cta"><span className="m-watch-cta-icon"><MIcon name="trend" size={25}/></span><div><strong>{t('관심종목을 추가하고 중요한 변화를 놓치지 마세요.','Keep important company changes in view.')}</strong><p>{t('종목 추가 버튼으로 관심 있는 종목을 등록할 수 있어요.','Add the companies you want to follow.')}</p></div><button onClick={()=>setAdd(true)}>{t('종목 추가하기','Add company')}<MIcon name="chevron" size={16}/></button></aside>
  {add&&<Dialog title={t('관심종목 추가','Add a company')} onClose={()=>setAdd(false)}><ActionNotice action={action}/><label className="m-field"><span>{t('기업명 또는 종목코드','Company name or ticker')}</span><input autoFocus maxLength={100} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('기업 검색','Search companies')}/></label><LoadState loading={catalog.loading} error={catalog.error??undefined} retry={catalog.reload}/><div className="m-watch-results">{!catalog.loading&&catalog.data?.map(c=><div key={c.id}><CompanyLogo ticker={c.ticker} size={36}/><Link href={`/companies/${c.id}`}><strong>{c.name}</strong><small>{c.ticker} · {c.market}</small></Link><button className="m-button-secondary" disabled={action.busy||items.some(i=>i.id===c.id)} onClick={()=>void action.run(()=>mutate(c.id,'PUT'),t('관심종목에 추가했습니다.','Added to your watchlist.'))}>{items.some(i=>i.id===c.id)?t('추가됨','Added'):t('+ 추가','+ Add')}</button></div>)}</div>{catalog.data&&!catalog.loading&&!catalog.data.length&&<EmptyState title={t('검색 결과가 없습니다.','No matching companies.')}/>}</Dialog>}
 </div>;
}
