/** Interactive controllers for the ten uploaded presentation templates.
 * All mutable/financial data comes from the authenticated API. This file never
 * receives service-role credentials and never executes the uploaded HTTP servers.
 */
import { hydrateLegacySummaries } from './legacy-summaries';
export type Row = Record<string, unknown>;
export type ReferenceContext = {
  user: Row | null;
  id?: string;
  api: (path: string, method?: string, payload?: unknown) => Promise<unknown>;
  rpc: (name: string, args?: Row) => Promise<unknown>;
  auth: (kind: string, fields?: Row) => Promise<unknown>;
  go: (path: string) => void;
  download: (path: string, name: string) => Promise<void>;
  demo: boolean;
};
const record = (v: unknown): Row => v !== null && typeof v === 'object' && !Array.isArray(v) ? v as Row : {};
const list = (v: unknown): Row[] => Array.isArray(v) ? v.map(record) : [];
const text = (v: unknown): string => v == null ? '' : String(v);
const number = (v: unknown): number | null => v == null || v === '' || !Number.isFinite(Number(v)) ? null : Number(v);
export const escapeHTML = (v: unknown): string => text(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function safeURL(v: unknown): string | null { try {const u = new URL(text(v));return u.protocol === 'https:' && !u.username && !u.password && !u.hostname.endsWith('.invalid') ? u.href : null;} catch {return null;} }
const E = escapeHTML;
const money = (v: unknown, currency: unknown = 'USD'): string => {const n=number(v);if(n===null)return '—';try{return new Intl.NumberFormat('ko-KR',{style:'currency',currency:text(currency),maximumFractionDigits:text(currency)==='KRW'?0:2}).format(n);}catch{return '—';}};
const fmt = (v: unknown): string => number(v)===null?'—':new Intl.NumberFormat('ko-KR',{maximumFractionDigits:2}).format(Number(v));
const pct = (v: unknown): string => number(v)===null?'':`${Number(v)>0?'+':''}${Number(v).toFixed(1)}%`;
const dateTime = (v: unknown): string => {const d=new Date(text(v));return Number.isNaN(+d)?'날짜 미확인':new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'long',day:'numeric'}).format(d);};
export function koreaDate(now=Date.now()): string {return new Date(now+9*3600000).toISOString().slice(0,10);}
export function monthCells(year:number,month:number): {date:string;day:number;current:boolean}[]{
 const shift=new Date(Date.UTC(year,month,1)).getUTCDay();
 return Array.from({length:42},(_,i)=>{const d=new Date(Date.UTC(year,month,1-shift+i));return {date:d.toISOString().slice(0,10),day:d.getUTCDate(),current:d.getUTCMonth()===month};});
}
const eventTypes:Record<string,string>={earnings:'실적 발표',guidance:'가이던스',product:'제품/기술',supply:'생산/공급',capex:'투자/설비',policy:'규제/정책',regulation:'규제/정책',management:'경영/기타',dividend:'배당',buyback:'자사주',other:'기타'};
function tagType(v:unknown){return eventTypes[text(v)]??text(v);}
const message = (v:unknown): string => v instanceof Error?v.message:'요청을 완료하지 못했습니다. 다시 시도해 주세요.';
const nav:Record<string,string>={today:'/today',watch:'/watchlist',portfolio:'/portfolio',timeline:'/timeline',calendar:'/calendar',alerts:'/alerts',settings:'/settings',ops:'/ops',data:'/ops?view=data',model:'/ops?view=model',users:'/ops?view=users',status:'/status',audit:'/ops?view=audit'};
const iconPaths:Record<string,string>={today:'M3 10 12 3l9 7M5 9v12h5v-7h4v7h5V9',watch:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z',portfolio:'M12 3v9h9M9 3.5A9 9 0 1 0 20.5 15M15 3.5A9 9 0 0 1 20.5 9H15Z',timeline:'M5 3v18M9 5h11M9 12h8M9 19h11M3 5h4M3 12h4M3 19h4',calendar:'M5 5h14v16H5ZM8 3v4M16 3v4M5 10h14',alerts:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5ZM10 21h4',settings:'m9 3-.5 3-2 1.2-2.8-1-2 3.6L4 12l-2.3 2.2 2 3.6 2.8-1 2 1.2.5 3h6l.5-3 2-1.2 2.8 1 2-3.6L20 12l2.3-2.2-2-3.6-2.8 1-2-1.2-.5-3ZM12 9a3 3 0 1 1 0 6 3 3 0 0 1 0-6',search:'M10 3a7 7 0 1 1 0 14 7 7 0 0 1 0-14M15 15l6 6',check:'m5 12 4 4 10-10',close:'m6 6 12 12M6 18 18 6',arrow:'M4 12h16m-6-6 6 6-6 6',file:'M5 3h10l4 4v14H5ZM14 3v5h5M8 12h8M8 16h8',shield:'m12 3 8 3v6c0 5-8 9-8 9S4 17 4 12V6ZM8 12l3 3 5-6',menu:'M4 6h16M4 12h16M4 18h16',plus:'M12 4v16M4 12h16'};
const icon=(name:string,size=20)=>`<svg aria-hidden="true" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${iconPaths[name]??iconPaths.file}"/></svg>`;
const brandAssets=new Set(['005930','000660','005380','035420','035720','373220','005490','TSLA','NVDA','AAPL']);
function companyLogo(c:Row):string {const symbol=text(c.ticker||c.symbol);return `<span class="coLogo" aria-hidden="true">${brandAssets.has(symbol)?`<img src="/reference-assets/logos/${symbol}.webp" alt="" loading="lazy">`:E(text(symbol||c.name).slice(0,2))}</span>`;}
function empty(label:string,description=''):string{return `<div class="empty"><span class="empty-icon">${icon('file',30)}</span><strong>${E(label)}</strong>${description?`<p>${E(description)}</p>`:''}</div>`;}
function sourceLink(url:unknown,label:unknown):string {const safe=safeURL(url);return safe?`<a class="sourceLink" href="${E(safe)}" target="_blank" rel="noopener noreferrer">${E(label)} ↗</a>`:`<span class="muted">${E(label)}</span>`;}
export function sparkline(values:unknown,large=false):string {
 const ns=(Array.isArray(values)?values:[]).map(v=>number(typeof v==='object'?record(v).close:v)).filter((v):v is number=>v!==null);
 if(ns.length<2)return `<div class="priceUnavailable ${large?'large':''}">${icon('timeline',large?28:16)}<span>시세 데이터 미연결</span></div>`;
 const w=large?320:112,h=large?170:42,min=Math.min(...ns),max=Math.max(...ns),d=max-min||1;
 const points=ns.map((v,i)=>`${3+i*(w-6)/(ns.length-1)},${h-4-(v-min)/d*(h-9)}`).join(' ');
 const color=ns[ns.length-1]>=ns[0]?'#10b981':'#ff4255';
 return `<svg role="img" aria-label="제공된 가격 이력" class="${large?'priceChart':'spark'}" viewBox="0 0 ${w} ${h}"><polyline points="${points}" fill="none" stroke="${color}" stroke-width="${large?2.2:1.6}" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
}
export function parsePortfolioCSV(input:string): Row[] {
 if(new TextEncoder().encode(input).length>131072)throw new Error('CSV 파일은 128KB 이하로 올려 주세요.');
 const text=input.replace(/^\uFEFF/,''),out:string[][]=[];let row:string[]=[],cell='',quote=false,closed=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(quote){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++;}else{quote=false;closed=true;}}else cell+=c;}
 else if(c==='"'){if(cell||closed)throw new Error('CSV 따옴표 형식을 확인해 주세요.');quote=true;}
 else if(c===','){row.push(cell);cell='';closed=false;}
 else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))out.push(row);row=[];cell='';closed=false;}
 else{if(closed&&!/\s/.test(c))throw new Error('CSV 구분자를 확인해 주세요.');if(!closed)cell+=c;}}
 if(quote)throw new Error('CSV 따옴표가 닫히지 않았습니다.');row.push(cell);if(row.some(x=>x.trim()))out.push(row);
 if(out.length<2||out.length>201)throw new Error('CSV에는 열 이름과 1~200개의 보유종목이 필요합니다.');
 const aliases:Record<string,string>={symbol:'ticker',avg_price:'average_cost',name:'name'};
 const headers=out[0].map(x=>aliases[x.trim().toLowerCase()]??x.trim().toLowerCase());
 for(const key of ['ticker','quantity','average_cost'])if(!headers.includes(key))throw new Error(`${key} 열이 필요합니다.`);
 if(new Set(headers).size!==headers.length)throw new Error('CSV 열 이름이 중복되었습니다.');
 const seen=new Set<string>();return out.slice(1).map((cells,i)=>{if(cells.length!==headers.length)throw new Error(`${i+2}행 열 개수를 확인해 주세요.`);const o=Object.fromEntries(headers.map((key,j)=>[key,cells[j].trim()]));
 const ticker=o.ticker.toUpperCase();if(!/^[A-Z0-9.:-]{1,32}$/.test(ticker)||seen.has(ticker))throw new Error(`${i+2}행: 종목코드가 유효하지 않거나 중복되었습니다.`);seen.add(ticker);
 if(!/^\d{1,20}(\.\d{1,8})?$/.test(o.quantity)||!/[1-9]/.test(o.quantity))throw new Error(`${i+2}행: 수량은 0보다 큰 숫자여야 합니다.`);
 if(o.average_cost&&!/^\d{1,20}(\.\d{1,8})?$/.test(o.average_cost))throw new Error(`${i+2}행: 평균단가를 확인해 주세요.`);
 if(o.currency&&!['USD','KRW','EUR','JPY','GBP','AUD','CAD','HKD','CNY','CHF'].includes(o.currency))throw new Error(`${i+2}행: 지원하지 않는 통화입니다.`);
 return {...o,ticker,average_cost:o.average_cost||null};});
}
export function portfolioCSV(items:Row[]):string {const cell=(v:unknown)=>'"'+text(v).replace(/^[=+\-@\t\r]/,m=>"'"+m).replace(/"/g,'""')+'"';return '\uFEFFticker,quantity,average_cost,currency\r\n'+items.map(x=>[x.ticker,x.quantity,x.average_cost,x.currency].map(cell).join(',')).join('\r\n');}
function downloadText(value:string,name:string,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);}

export function mountReference(root:HTMLElement,screen:string,ctx:ReferenceContext):()=>void {
 const silentNavigationError=(e:unknown)=>e instanceof Error&&['auth_redirect','Navigation cancelled'].includes(e.message);
 const abort=new AbortController();let toastTimer:ReturnType<typeof setTimeout>|undefined;const timers:ReturnType<typeof setTimeout>[]=[];
 const $=<T extends HTMLElement=HTMLElement>(selector:string):T=>{const e=root.querySelector<T>(selector);if(!e)throw new Error(`Missing presentation target: ${selector}`);return e;};
 const $$=<T extends HTMLElement=HTMLElement>(selector:string):T[]=>Array.from(root.querySelectorAll<T>(selector));
 const html=(selector:string,value:string)=>{if(!abort.signal.aborted)$(selector).innerHTML=value;};
 const put=(selector:string,value:unknown)=>{if(!abort.signal.aborted)$(selector).textContent=text(value);};
 const on=(selector:string,event:string,fn:(e:Event)=>void)=>$$(selector).forEach(el=>el.addEventListener(event,fn,{signal:abort.signal}));
 const delegate=(event:string,selector:string,fn:(el:HTMLElement,e:Event)=>void)=>root.addEventListener(event,e=>{const t=e.target instanceof Element?e.target.closest<HTMLElement>(selector):null;if(t&&root.contains(t))fn(t,e);},{signal:abort.signal});
 const toast=(v:unknown)=>{if(abort.signal.aborted)return;const el=$('#toast');el.textContent=typeof v==='string'?v:message(v);el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.style.display='none';},6500);};
 const run=async(fn:()=>Promise<void>,button?:HTMLElement)=>{if(button?.getAttribute('aria-busy')==='true')return;button?.setAttribute('aria-busy','true');if(button instanceof HTMLButtonElement)button.disabled=true;try{await fn();}catch(e){if(!silentNavigationError(e))toast(e);}finally{button?.removeAttribute('aria-busy');if(button instanceof HTMLButtonElement)button.disabled=false;}};
 const api=async(path:string,method='GET',payload?:unknown)=>{const r=await ctx.api(path,method,payload);if(abort.signal.aborted)throw new Error('Navigation cancelled');return r;};
 const rpc=async(name:string,args:Row={})=>{const r=await ctx.rpc(name,args);if(abort.signal.aborted)throw new Error('Navigation cancelled');return r;};
 function modal(title:string,content:string){root.querySelector('#referenceDialog')?.remove();const d=document.createElement('dialog');d.id='referenceDialog';d.className='referenceDialog';d.setAttribute('aria-label',title);d.innerHTML=`<div class="dialogHead"><h2>${E(title)}</h2><button type="button" class="iconButton" data-close-dialog aria-label="닫기">${icon('close')}</button></div>${content}`;root.append(d);d.addEventListener('click',e=>{if(e.target===d)d.close();},{signal:abort.signal});d.showModal();return d;}
 delegate('click','[data-close-dialog]',()=>root.querySelector<HTMLDialogElement>('#referenceDialog')?.close());
 const routeId=()=>ctx.id||new URLSearchParams(location.search).get('event')||'';
 let markets:Map<string,Row>=new Map();let marketVersion=0;
 async function market(companies:Row[],period='6m'){if(!companies.length)return;const version=++marketVersion;try{const result=record(await api(`/market?symbols=${encodeURIComponent([...new Set(companies.map(x=>text(x.ticker)))].slice(0,40).join(','))}&period=${encodeURIComponent(period)}`));if(version===marketVersion)markets=new Map(list(result.quotes).map(q=>[text(q.symbol),q]));}catch{if(version===marketVersion)markets=new Map();}}
 const quote=(company:Row)=>markets.get(text(company.ticker))??{};
 const valueQuote=(company:Row)=>{const q=quote(company);return `<strong>${E(money(q.price,q.currency))}</strong> <span class="${Number(q.change_pct)<0?'red':'green'}">${E(pct(q.change_pct))}</span>`;};
 const companyDate=(value:unknown)=>text(value).slice(0,10);
 const statusNote=()=>`<p class="dataNote">${icon('shield',13)} 가격·차트·분석은 확인 가능한 데이터만 표시합니다. <a href="/status">연결 상태</a></p>`;

 // Shared navigation is real navigation, not merely an active CSS class.
 $$('.nav [data-route]').forEach(a=>{const route=a.dataset.route??'';a.setAttribute('href',nav[route]??'/today');const i=a.querySelector('.ico');if(i)i.innerHTML=icon(route);if(['ops','data','model','users','audit'].includes(route)&&!ctx.user?.is_admin)a.remove();});
 $$('.brand').forEach(el=>{el.setAttribute('role','link');el.tabIndex=0;el.addEventListener('click',()=>ctx.go(ctx.user?'/today':'/'),{signal:abort.signal});el.addEventListener('keydown',e=>{if(e.key==='Enter')ctx.go(ctx.user?'/today':'/');},{signal:abort.signal});});
 if(screen==='onboarding'&&root.querySelector('.profile')&&!root.querySelector('.profile .mode'))$('.profile').insertAdjacentHTML('afterbegin','<div class="mode"><button>초보자 모드</button><button>고급 모드</button></div>');
 const t=$('#toast');t.setAttribute('role','status');t.setAttribute('aria-live','polite');
 if(location.pathname==='/portfolio'){$$('.nav [data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route==='portfolio'));}
 if(root.querySelector('.profile')){
  html('.profile .avatar',E(text(ctx.user?.display_name||'투자자').slice(0,1)));
  const strong=root.querySelector('.profile strong');if(strong)strong.textContent=text(ctx.user?.display_name||'투자자')+'님';
  const p=root.querySelector('.profile');p?.insertAdjacentHTML('beforeend','<button type="button" class="iconButton" data-logout aria-label="로그아웃" title="로그아웃">↪</button>');
  delegate('click','[data-logout]',b=>{void run(async()=>{await ctx.auth('logout');ctx.go('/login');},b);});
 }
 $$('.mode button').forEach((b,i)=>{const mode=i===0?'beginner':'advanced';b.dataset.density=mode;b.classList.toggle('active',text(ctx.user?.density||'advanced')===mode);b.setAttribute('aria-pressed',String(b.classList.contains('active')));});
 root.dataset.density=text(ctx.user?.density||'advanced');
 delegate('click','button[data-density]',b=>{void run(async()=>{await api('/v1/me','PATCH',{density:b.dataset.density});root.dataset.density=b.dataset.density;$$('button[data-density]').forEach(x=>{const active=x.dataset.density===b.dataset.density;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active));});toast('정보 밀도를 저장했습니다.');},b);});
 if(root.querySelector('.topbar')){$('.topbar').insertAdjacentHTML('afterbegin',`<button class="iconButton menuButton" data-menu aria-label="메뉴 열기" aria-expanded="false">${icon('menu')}</button>`);root.insertAdjacentHTML('afterbegin','<button class="menuBackdrop" data-menu aria-label="메뉴 닫기"></button>');delegate('click','[data-menu]',()=>{root.classList.toggle('menuOpen');$$('[data-menu]').forEach(b=>b.setAttribute('aria-expanded',String(root.classList.contains('menuOpen'))));});}
 // Application search remains keyboard accessible.
 const search=root.querySelector<HTMLInputElement>('#globalSearch');
 async function showSearch(term=''){
  if(!ctx.user){ctx.go('/login');return;}const d=modal('기업 검색',`<label class="dialogField">종목명 또는 코드<input id="dialogSearch" value="${E(term)}" maxlength="100" placeholder="예: 삼성전자, AAPL"></label><div id="dialogSearchResults"></div>`);
  let serial=0,delay:ReturnType<typeof setTimeout>;const render=async(q:string)=>{const version=++serial;try{const data=list(await api(`/v1/companies?q=${encodeURIComponent(q)}&limit=30`));if(version!==serial||!d.open)return;html('#dialogSearchResults',data.map(c=>`<a class="searchOption" href="/companies/${E(c.id)}">${companyLogo(c)}<span><strong>${E(c.name)}</strong><small>${E(c.ticker)} · ${E(c.market)}</small></span>${icon('arrow',16)}</a>`).join('')||empty('검색 결과가 없습니다.'));}catch(e){toast(e);}};
  const input=$<HTMLInputElement>('#dialogSearch');input.focus();input.addEventListener('input',()=>{clearTimeout(delay);delay=setTimeout(()=>{void render(input.value);},300);timers.push(delay);},{signal:abort.signal});await render(term);
 }
 search?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();void run(()=>showSearch(search.value));}},{signal:abort.signal});
 window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();void run(()=>showSearch());}},{signal:abort.signal});
 delegate('click','[data-open-status]',()=>ctx.go('/status'));
 delegate('click','[data-share]',b=>{void run(async()=>{await navigator.clipboard.writeText(location.origin+location.pathname+location.search);toast('현재 페이지 주소를 복사했습니다.');},b);});
 function wireLink(button:HTMLElement|undefined,path:string){if(button)button.addEventListener('click',()=>ctx.go(path),{signal:abort.signal});}
 const getDetail=async(id:string)=>record(await api(`/v1/events/${encodeURIComponent(id)}`));
 const contextLinks=(d:Row)=>list(d.evidence).map((x,i)=>`<article class="evi" id="evidence-${E(x.fact_id)}"><div class="evidenceHead"><span class="badge">${i+1}</span><strong>${E(x.source_name)}</strong><span class="badge green">Tier ${E(x.source_tier)}</span><span class="muted">${E(dateTime(x.published_at))}</span></div><h4>${E(record(d.document).title)}</h4><p>“${E(x.quote)}”</p><div class="evidenceFoot"><span>${E(x.location)}</span>${sourceLink(x.source_url,'원문 확인')}</div></article>`).join('');

 async function initLanding(){
  $$('.landActions [data-auth-cta]').forEach(a=>a.setAttribute('href',ctx.user?'/today':a.dataset.authCta==='signup'?'/signup':'/login'));
  const paths=['/about','/features','/sources','/pricing','/customers','/privacy'];
  $$('.landNav span').forEach((x,i)=>{const a=document.createElement('a');a.href=paths[i];a.textContent=x.textContent;a.className=x.className;x.replaceWith(a);});
  const searchAction=root.querySelector('.landActions>span');if(searchAction){const a=document.createElement('a');a.href=ctx.user?'/today':'/login';a.setAttribute('aria-label','기업 검색');a.innerHTML=icon('search');searchAction.replaceWith(a);}
  $$('.landActions button').forEach((b,i)=>{const a=document.createElement('a');a.className=b.className;a.textContent=b.textContent;a.href=ctx.user?'/today':i===0?'/login':'/signup';b.replaceWith(a);});
  $('.auth>.card')?.insertAdjacentHTML('beforebegin',`<div class="authTrust"><div><span class="coLogo">${icon('shield')}</span><span><strong>안전한 로그인</strong><small>검증된 계정 인증과<br>사용자별 접근 제어</small></span></div><div><span class="coLogo">${icon('shield')}</span><span><strong>개인정보 보호</strong><small>보유 정보는 본인 계정에<br>안전하게 저장됩니다.</small></span></div></div>`);
  const source=$('.hero>aside>.card');source.innerHTML='<strong>신뢰할 수 있는 데이터 출처</strong><div class="sourceCards"><span><b>DART</b><small>연결 보류</small></span><span><b>SEC</b><small>미국 기업 공시</small></span><span><b>IR</b><small>공식 자료 확인</small></span><span><b>자료</b><small>출처 연결</small></span></div><p>연결 및 수집·검토가 완료된 자료만 표시합니다. <a href="/status">연결 상태 →</a></p>';
  const email=$<HTMLInputElement>('#email'),pass=$<HTMLInputElement>('#password');email.setAttribute('aria-label','이메일 주소');email.autocomplete='email';pass.setAttribute('aria-label','비밀번호');pass.autocomplete='current-password';pass.minLength=1;pass.maxLength=128;
  pass.parentElement?.insertAdjacentHTML('beforeend','<button class="plainButton" type="button" data-show-pass aria-label="비밀번호 보기">◉</button>');
  delegate('click','[data-show-pass]',b=>{pass.type=pass.type==='password'?'text':'password';b.setAttribute('aria-label',pass.type==='password'?'비밀번호 보기':'비밀번호 숨기기');});
  $('#signup').parentElement?.insertAdjacentHTML('beforeend',' <button class="plainButton blue" data-reset>비밀번호 찾기</button>');
  const userAction=(kind:string,b:HTMLElement)=>{void run(async()=>{if(kind!=='google'&&(!email.reportValidity()||!email.value.trim()))return;if(kind==='signup'&&pass.value.length<12)throw new Error('비밀번호는 12자 이상이어야 합니다.');if(kind==='login'&&!pass.value)throw new Error('비밀번호를 입력해 주세요.');const result=record(await ctx.auth(kind,{email:email.value.trim(),password:pass.value}));if(kind==='signup')toast(result.session?'가입되었습니다.':'가입 확인 메일을 확인하세요. 이메일 발송이 제한되면 Google 로그인을 이용하세요.');if(kind==='reset')toast('해당 주소로 복구 가능한 계정이 있으면 안내 메일을 보냅니다.');},b);};
  on('#googleLogin','click',e=>userAction('google',e.currentTarget as HTMLElement));on('#emailLogin','click',e=>userAction('login',e.currentTarget as HTMLElement));const signup=$('#signup');signup.replaceWith(Object.assign(document.createElement('a'),{href:'/signup',className:signup.className,textContent:signup.textContent}));root.querySelector('[data-reset]')?.replaceWith(Object.assign(document.createElement('a'),{href:'/forgot-password',className:'plainButton blue',textContent:'비밀번호 찾기'}));pass.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();userAction('login',$('#emailLogin'));}},{signal:abort.signal});
  if(ctx.demo){$('.auth').insertAdjacentHTML('beforeend','<button class="btn ghost demoOnly" data-demo>로컬 테스트 계정으로 시작</button><button class="btn ghost demoOnly" data-demo-admin>로컬 운영자 테스트</button>');delegate('click','[data-demo]',b=>{void run(()=>ctx.auth('demo').then(()=>ctx.go('/today')),b);});delegate('click','[data-demo-admin]',b=>{void run(()=>ctx.auth('demo-admin').then(()=>ctx.go('/ops')),b);});}
  if(ctx.user){$('#googleLogin').textContent='내 브리핑으로 이동';$('#googleLogin').replaceWith(Object.assign(document.createElement('a'),{href:'/today',className:'btn primary full',textContent:'내 브리핑으로 이동 →'}));}
  const stats=await api('/v1/public/stats').catch(()=>null);const values=record(stats);['stat1','stat2','stat3','stat4'].forEach((id,i)=>put('#'+id,[fmt(values.documents),fmt(values.companies),fmt(values.users),values.uptime_pct==null?'측정 전':pct(values.uptime_pct)][i]));
  $('.statbar').insertAdjacentHTML('afterend','<footer class="referenceFooter"><a href="/privacy">개인정보 처리 안내</a> · <a href="/status">서비스 연결 상태</a> · SignalBrief</footer>');
 }

 async function initOnboarding(){
  const defaults={experience:'',markets:[] as string[],sectors:[] as string[],has_holdings:null as boolean|null,alert_frequency:''};
  let p={...defaults};let step=1;
  const saved=record(await api('/v1/preferences').catch(()=>({})));if(saved.experience){p={experience:text(saved.experience),markets:Array.isArray(saved.markets)?saved.markets.map(text):[],sectors:Array.isArray(saved.sectors)?saved.sectors.map(text):[],has_holdings:typeof saved.has_holdings==='boolean'?saved.has_holdings:null,alert_frequency:text(saved.alert_frequency)};}
  p.markets=['US'];
  const exps=[['beginner','🌱','초보','이제 막 시작했어요'],['intermediate','📊','중급','1년 이상 경험이 있어요'],['advanced','🎓','고급','여러 해의 투자 경험이 있어요'],['professional','👑','전문가','깊이 있는 분석이 필요해요']];
  const sectors=['반도체','AI / 소프트웨어','전기차','2차전지','바이오·헬스케어','금융','소비재','에너지','방산','통신','부동산·리츠','기타'];
  function choice(value:string,label:string,sub:string,field:string,selected:boolean){return `<button type="button" class="choice ${selected?'selected':''}" data-choice="${field}" data-value="${E(value)}" aria-pressed="${selected}"><strong>${E(label)}</strong><small>${E(sub)}</small>${selected?`<span class="choiceCheck">${icon('check',13)}</span>`:''}</button>`;}
  function render(){html('#onboardingForm',`<div class="q"><h3>1. 투자 경험은 어느 정도이신가요?</h3><p class="questionHelp">투자 경험에 맞는 콘텐츠와 설명 수준을 준비합니다.</p><div class="choiceGrid">${exps.map(([v,i,l,s])=>choice(v,i+' '+l,s,'experience',p.experience===v)).join('')}</div></div><div class="q"><h3>2. 주로 투자하는 시장은 어디인가요?</h3><p class="questionHelp">관심 있는 시장을 선택하세요. (복수 선택 가능)</p><div class="choiceGrid two">${[['US','🇺🇸 미국주식','NASDAQ · NYSE · 초기 지원']].map(([v,l,s])=>choice(v,l,s,'markets',p.markets.includes(v))).join('')}</div></div><div class="q"><h3>3. 관심 있는 섹터를 선택해주세요.</h3><p class="questionHelp">최대 5개까지 선택할 수 있어요.</p><div class="sectorChoices">${sectors.map(v=>`<button type="button" class="chipChoice ${p.sectors.includes(v)?'selected':''}" data-choice="sectors" data-value="${E(v)}" aria-pressed="${p.sectors.includes(v)}">${E(v)} ${p.sectors.includes(v)?'✓':''}</button>`).join('')}</div></div><div class="q"><h3>4. 현재 보유 중인 종목이 있으신가요?</h3><p class="questionHelp">보유종목을 등록하면 더 관련 있는 변화를 확인할 수 있어요.</p><div class="choiceGrid two">${choice('yes','네, 보유 종목이 있어요','다음 단계에서 직접 입력할게요','has_holdings',p.has_holdings===true)}${choice('no','아니요, 아직 없어요','관심종목부터 선택할게요','has_holdings',p.has_holdings===false)}</div></div><div class="q"><h3>5. 알림을 얼마나 받고 싶으신가요?</h3><div class="choiceGrid three">${[['essential','필수 알림만','중요한 이슈 중심'],['normal','일반 알림','주요 변화와 보유종목'],['all','모든 알림','게시된 변화 전체']].map(([v,l,s])=>choice(v,l,s,'alert_frequency',p.alert_frequency===v)).join('')}</div></div>`);}
  delegate('click','[data-choice]',b=>{const v=b.dataset.value??'',k=b.dataset.choice;if(k==='experience')p.experience=v;if(k==='alert_frequency')p.alert_frequency=v;if(k==='has_holdings')p.has_holdings=v==='yes';if(k==='markets')p.markets=['US'];if(k==='sectors'){if(p.sectors.includes(v))p.sectors=p.sectors.filter(x=>x!==v);else if(p.sectors.length<5)p.sectors.push(v);else{toast('섹터는 최대 5개까지 선택할 수 있습니다.');return;}}render();});
  wireLink($$('button').find(b=>b.textContent==='취소하기'),'/today');
  on('#nextStep','click',e=>{void run(async()=>{if(!p.experience||!p.markets.length||!p.alert_frequency||p.has_holdings===null)throw new Error('투자 경험, 시장, 보유 여부와 알림 수준을 선택해 주세요.');await rpc('sb_reference_preferences',{p});step++;if(step===2)ctx.go('/watchlist?onboarding=1');},e.currentTarget as HTMLElement);});render();
 }

 async function initSetup(){
  type Position={company:Row;quantity:string;average_cost:string;currency:string};
  let watched:Row[]=[],positions:Position[]=[],results:Row[]=[],popular:Row[]=[],dirty=false,view='manual',sort='name',searchSeq=0;
  const fromOnboarding=new URLSearchParams(location.search).has('onboarding');
  const [w,p,c]=await Promise.all([api('/v1/watchlist'),api('/v1/portfolio'),api('/v1/companies?limit=50')]);watched=list(record(w).items);positions=list(record(p).positions).map(x=>({company:record(x.company),quantity:text(x.quantity),average_cost:text(x.average_cost),currency:text(x.currency)}));results=list(c);popular=results.slice(0,10);await market(results);
  const search=$<HTMLInputElement>('#stockSearch');search.setAttribute('aria-label','관심종목 검색');
  $('.main > div').classList.add('setupHeading');$('.main > div + div')?.classList.add('setupGrid');
  const selectBox=$('#selected');const selectionTitle=selectBox.previousElementSibling;selectBox.insertAdjacentHTML('beforebegin','<div class="popularHeader"><strong>연결된 기업 둘러보기</strong><button class="plainButton blue" data-more-companies>다른 종목 보기 ›</button></div><div id="popularCompanies" class="popularCompanies"></div>');
  if(selectionTitle)selectBox.before(selectionTitle);selectBox.insertAdjacentHTML('afterend','<div class="selectedActions"><button class="btn sm" data-clear-watch>전체 삭제</button></div>');
  const resultTitle=$('#searchResults').previousElementSibling;if(resultTitle)resultTitle.innerHTML='<strong>종목 검색 결과</strong><select id="companySort" aria-label="종목 정렬"><option value="name">이름 순</option><option value="ticker">종목코드 순</option></select>';
  const tabs=$$<HTMLButtonElement>('.main .seg button');tabs.forEach((b,i)=>{b.dataset.setupTab=['manual','csv','broker'][i];b.setAttribute('aria-pressed',String(i===0));if(i===2){b.disabled=false;b.classList.add('pendingFeature');b.title='증권사 연결 없이 직접 입력과 CSV를 사용할 수 있습니다.';}});
  const info=$$('.main span').find(x=>x.textContent?.includes('포트폴리오란?'));info?.setAttribute('data-portfolio-help','true');info?.setAttribute('role','button');if(info)info.tabIndex=0;
  $('#holdings').insertAdjacentHTML('beforebegin','<div id="holdingHeader" class="holdingTableHeader"><span>종목</span><span>수량</span><span>평균단가</span><span>통화</span><span>현재가</span><span>평가금액</span><span>비중</span><span>작업</span></div>');
  $('#holdings').insertAdjacentHTML('afterend','<div id="csvPanel" hidden><p class="sub">열 이름은 ticker, quantity, average_cost, currency를 사용하세요. 평균단가와 수량은 소수점 8자리까지 지원합니다.</p><button class="btn" data-template>CSV 양식 다운로드</button><label class="btn primary">CSV 파일 선택<input data-csv-file type="file" accept=".csv,text/csv" hidden></label></div>');
  $('#saveAll').insertAdjacentHTML('beforebegin',statusNote()+'<div class="buttonPair"><button class="btn sm" data-export>CSV 내보내기</button><button class="btn sm" data-template>CSV 양식 다운로드</button></div>');
  if(!fromOnboarding)$('#saveAll').textContent='설정 완료 →';
  function changed(){dirty=true;$('#saveAll').textContent='변경사항 저장 →';}
  function renderWatch(){put('#watchCount',watched.length);html('#selected',watched.map(c=>`<span class="watchChip">${companyLogo(c)}${E(c.name)}<button type="button" data-remove-watch="${E(c.id)}" aria-label="${E(c.name)} 관심종목 삭제">×</button></span>`).join('')||'<span class="muted small">아직 선택한 관심종목이 없습니다.</span>');
   html('#popularCompanies',popular.map(c=>`<button class="popularCompany" data-add-watch="${E(c.id)}" aria-label="${E(c.name)} 관심종목 추가">${companyLogo(c)}<span><strong>${E(c.name)}</strong><small>${E(c.ticker)}</small></span><b>${watched.some(x=>x.id===c.id)?'✓':'＋'}</b></button>`).join(''));
   const sorted=[...results].sort((a,b)=>text(a[sort]).localeCompare(text(b[sort]),'ko'));
   html('#searchResults',sorted.map(c=>`<div class="resultRow"><div class="resultCompany">${companyLogo(c)}<span><strong>${E(c.name)}</strong><small>${E(c.ticker)} · ${E(c.market)}</small></span></div><div class="resultQuote">${valueQuote(c)}</div>${sparkline(quote(c).history)}<button class="btn sm ${watched.some(x=>x.id===c.id)?'ghost':'outlineBlue'}" data-add-watch="${E(c.id)}" ${watched.some(x=>x.id===c.id)?'disabled':''}>${watched.some(x=>x.id===c.id)?'✓ 추가됨':'＋ 추가'}</button></div>`).join('')||empty('검색 결과가 없습니다.','다른 기업명 또는 종목코드를 입력하세요.'));
  }
  function renderPositions(){
   html('#holdings',positions.length?positions.map((p,i)=>`<div class="holdingRow" data-holding-row="${i}"><div class="holdingName">${companyLogo(p.company)}<span><strong>${E(p.company.name)}</strong><small>${E(p.company.ticker)}</small></span></div><label><span class="srOnly">${E(p.company.name)} 보유 수량</span><input inputmode="decimal" value="${E(p.quantity)}" data-position="${i}" data-field="quantity" placeholder="수량" maxlength="29"></label><label><span class="srOnly">${E(p.company.name)} 평균단가</span><input inputmode="decimal" value="${E(p.average_cost)}" data-position="${i}" data-field="average_cost" placeholder="평균단가" maxlength="29"></label><select data-position="${i}" data-field="currency" aria-label="${E(p.company.name)} 통화">${['KRW','USD','EUR','JPY','GBP','AUD','CAD','HKD','CNY','CHF'].map(v=>`<option ${p.currency===v?'selected':''}>${v}</option>`).join('')}</select><span class="holdingPrice">${E(money(quote(p.company).price,quote(p.company).currency))}</span><span class="muted">—</span><span class="muted">—</span><button class="plainButton" data-remove-position="${i}" aria-label="${E(p.company.name)} 보유종목 삭제">×</button></div>`).join(''):empty('아직 등록된 보유 종목이 없습니다.','보유 종목을 추가하여 포트폴리오를 설정해보세요.<br>수동 입력 또는 CSV 파일로 간편하게 등록할 수 있습니다.').replace(/&lt;br&gt;/g,'<br>')+'<button class="btn primary firstHolding" data-add-position>＋ 첫 번째 종목 추가하기</button>');
   $('#holdings').hidden=view!=='manual';$('#holdingHeader').hidden=view!=='manual';$('#csvPanel').hidden=view!=='csv';
  }
  async function addPosition(){const d=modal('보유종목 추가','<label class="dialogField">기업명 또는 종목코드<input id="positionSearch" placeholder="예: 삼성전자, AAPL" maxlength="100"></label><div id="positionMatches"></div>');let seq=0,delay:ReturnType<typeof setTimeout>;const draw=async(q='')=>{const n=++seq;const found=list(await api(`/v1/companies?q=${encodeURIComponent(q)}&limit=30`));if(n!==seq||!d.open)return;html('#positionMatches',found.map(c=>`<button class="searchOption" data-select-position="${E(c.id)}" ${positions.some(p=>p.company.id===c.id)?'disabled':''}>${companyLogo(c)}<span><strong>${E(c.name)}</strong><small>${E(c.ticker)} · ${E(c.market)}</small></span><b>＋</b></button>`).join('')||empty('검색 결과가 없습니다.'));
   d.querySelectorAll<HTMLButtonElement>('[data-select-position]').forEach(b=>b.addEventListener('click',()=>{const c=found.find(c=>c.id===b.dataset.selectPosition);if(!c)return;if(positions.length>=200){toast('보유종목은 최대 200개까지 등록할 수 있습니다.');return;}positions.push({company:c,quantity:'',average_cost:'',currency:['KOSPI','KOSDAQ'].includes(text(c.market))?'KRW':'USD'});view='manual';tabs.forEach((x,i)=>x.classList.toggle('active',i===0));d.close();changed();renderPositions();},{signal:abort.signal}));};
   const input=$<HTMLInputElement>('#positionSearch');input.focus();input.addEventListener('input',()=>{clearTimeout(delay);delay=setTimeout(()=>{void run(()=>draw(input.value));},300);timers.push(delay);},{signal:abort.signal});await draw();}
  async function importCSV(file:File){const parsed=parsePortfolioCSV(await file.text());const resolved=ctx.demo?list(await api('/v1/companies?limit=100')):list(await rpc('sb_resolve_companies',{tickers:parsed.map(p=>p.ticker)}));const next:Position[]=parsed.map(p=>{const c=resolved.find(c=>text(c.ticker).toUpperCase()===p.ticker);if(!c)throw new Error(`연결된 기업 목록에 없는 종목: ${p.ticker}`);return {company:c,quantity:text(p.quantity),average_cost:text(p.average_cost),currency:text(p.currency)||(['KOSPI','KOSDAQ'].includes(text(c.market))?'KRW':'USD')};});const merged=new Map(positions.map(p=>[text(p.company.id),p]));next.forEach(p=>merged.set(text(p.company.id),p));if(merged.size>200)throw new Error('보유종목은 최대 200개입니다.');positions=[...merged.values()];view='manual';tabs.forEach((b,i)=>b.classList.toggle('active',i===0));changed();renderPositions();toast(`${next.length}종목을 가져왔습니다. 설정 완료를 눌러 저장하세요.`);}
  delegate('click','[data-add-watch]',b=>{const c=[...results,...popular].find(c=>c.id===b.dataset.addWatch);if(!c||watched.some(x=>x.id===c.id))return;if(watched.length>=50){toast('관심종목은 최대 50개입니다.');return;}watched.push(c);changed();renderWatch();});
  delegate('click','[data-remove-watch]',b=>{watched=watched.filter(c=>c.id!==b.dataset.removeWatch);changed();renderWatch();});
  delegate('click','[data-clear-watch]',()=>{if(watched.length&&confirm('선택한 관심종목을 모두 지울까요? 저장 전까지는 계정에 반영되지 않습니다.')){watched=[];changed();renderWatch();}});
  delegate('click','[data-remove-position]',b=>{positions.splice(Number(b.dataset.removePosition),1);changed();renderPositions();});
  delegate('input','[data-position]',b=>{const index=Number(b.dataset.position),field=b.dataset.field;if(positions[index]&&['quantity','average_cost','currency'].includes(field??'')){positions[index][field as 'quantity'|'average_cost'|'currency']=(b as HTMLInputElement).value;changed();}});
  delegate('change','[data-position]',b=>{if(b instanceof HTMLSelectElement){positions[Number(b.dataset.position)].currency=b.value;changed();}});
  on('#addHolding','click',()=>{void run(addPosition);});delegate('click','[data-add-position]',()=>{void run(addPosition);});
  delegate('click','[data-setup-tab]',b=>{const v=b.dataset.setupTab;if(v==='broker'){modal('증권사 연동 안내','<p class="sub">현재 직접 입력과 CSV 가져오기를 사용할 수 있습니다. 증권사 OAuth 및 계약된 데이터 연결은 아직 구성되지 않았습니다. 계좌 비밀번호를 입력하지 마세요.</p>');return;}view=v??'manual';tabs.forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active));});renderPositions();});
  on('#csv','change',e=>{const input=e.currentTarget as HTMLInputElement;const f=input.files?.[0];input.value='';if(f)void run(()=>importCSV(f));});delegate('change','[data-csv-file]',b=>{const input=b as HTMLInputElement;const f=input.files?.[0];input.value='';if(f)void run(()=>importCSV(f));});
  delegate('click','[data-template]',()=>downloadText('ticker,quantity,average_cost,currency\r\n','signalbrief-template.csv','text/csv;charset=utf-8'));
  delegate('click','[data-export]',()=>downloadText(portfolioCSV(positions.map(p=>({ticker:p.company.ticker,quantity:p.quantity,average_cost:p.average_cost,currency:p.currency}))),'signalbrief-portfolio.csv','text/csv;charset=utf-8'));
  delegate('click','[data-portfolio-help]',()=>modal('포트폴리오란?','<p class="sub">내가 보유한 기업과 수량, 평균 취득가를 정리한 목록입니다. 저장된 보유 여부는 정보의 우선순위에 반영됩니다. 실시간 가격과 환율이 연결되지 않은 상태에서는 평가금액과 비중을 계산하지 않습니다.</p>'));
  let delay:ReturnType<typeof setTimeout>;search.addEventListener('input',()=>{clearTimeout(delay);const seq=++searchSeq;delay=setTimeout(()=>{void run(async()=>{const response=list(await api(`/v1/companies?q=${encodeURIComponent(search.value)}&limit=50`));if(seq!==searchSeq)return;results=response;await market(results);if(seq===searchSeq)renderWatch();});},300);timers.push(delay);},{signal:abort.signal});
  on('#companySort','change',e=>{sort=(e.target as HTMLSelectElement).value;renderWatch();});delegate('click','[data-more-companies]',()=>{search.focus();search.scrollIntoView({block:'center'});});
  on('#saveAll','click',e=>{void run(async()=>{
   const payload={company_ids:watched.map(c=>c.id),positions:positions.map(p=>({company_id:p.company.id,quantity:p.quantity,average_cost:p.average_cost||null,currency:p.currency})),complete_onboarding:fromOnboarding};
   for(const p of positions){if(!/^\d{1,20}(\.\d{1,8})?$/.test(p.quantity)||!/[1-9]/.test(p.quantity))throw new Error(`${p.company.name}: 0보다 큰 수량을 입력하세요.`);if(p.average_cost&&!/^\d{1,20}(\.\d{1,8})?$/.test(p.average_cost))throw new Error(`${p.company.name}: 평균단가 형식을 확인하세요.`);}
   await rpc('sb_reference_setup',{p:payload});dirty=false;$('#saveAll').textContent='설정 완료 ✓';toast('관심종목과 포트폴리오를 저장했습니다.');if(fromOnboarding){sessionStorage.setItem('signalbrief.setup-complete','1');location.assign('/today');}
  },e.currentTarget as HTMLElement);});
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}},{signal:abort.signal});
  renderWatch();renderPositions();
 }

 async function initToday(){
  const renderSummary=(e:Row)=>{const changes=list(e.change_summary);const change=changes.length?changes.slice(0,2).map(x=>`${tagType(x.field)}: ${text(x.previous_value)||'이전 근거 없음'} → ${text(x.current_value)}`).join(' · '):'비교 가능한 이전 근거 없음';return `<div class="mini"><b>${icon('file',13)} FACT</b><p>${E(e.fact_summary||e.what_happened)}</p></div><div class="mini"><b>${icon('timeline',13)} CHANGE</b><p>${E(change)}</p></div><div class="mini"><b class="amber">⚑ WHY IT MATTERS</b><p>${E(e.interpretation||'검토된 해석 없음')}</p></div>`;};
  const renderCalendar=(value:unknown)=>{
  const upcoming=list(value).filter(x=>text(x.occurs_on)>=koreaDate()).slice(0,5);html('#todayUpcoming',upcoming.map(e=>`<a class="upRow" href="${e.event_id?'/events/'+E(e.event_id):'/calendar'}"><div class="calendarDateBox"><span>${E(text(e.occurs_on).slice(5,7))}월</span><strong>${E(text(e.occurs_on).slice(8))}</strong></div><div><strong>${E(e.title)}</strong><div class="muted small">${e.origin==='user'?'직접 등록':'공식 근거 일정'}</div></div></a>`).join('')||empty('확인된 일정이 없습니다.'));
  };
  const renderPortfolio=(value:unknown)=>{
  const positions=list(record(value).positions);html('#portfolioSummary',`<div class="portfolioTotal"><small>총 평가금액</small><strong>—</strong><span class="muted small">시세 표시 권한·완전한 가격 자료 확인 필요</span></div><div class="allocationTrack"></div>${positions.slice(0,6).map(p=>`<a class="metricRow" href="/companies/${E(record(p.company).id)}"><span>${E(record(p.company).name)}</span><strong>${E(p.quantity)}주</strong></a>`).join('')}${!positions.length?empty('등록된 보유종목이 없습니다.') : ''}`);
  };
  void api('/v1/calendar').then(renderCalendar).catch(error=>{if(!abort.signal.aborted)html('#todayUpcoming',empty('일정을 불러오지 못했습니다.',message(error)));});
  void api('/v1/portfolio').then(renderPortfolio).catch(error=>{if(!abort.signal.aborted)html('#portfolioSummary',empty('보유종목을 불러오지 못했습니다.',message(error)));});
  const data=record(await api('/v1/feed?days=30&limit=12')),events=list(data.items);

  put('#todayDate',dateTime(new Date().toISOString()));put('#todayCount',`${data.total??events.length}건`);
  html('#todayList',events.map(e=>{const c=record(e.company),ranking=record(e.ranking);return `<article class="todayItem"><div class="stockSide"><a class="stockIdentity" href="/companies/${E(c.id)}">${companyLogo(c)}<span><strong>${E(c.name)}</strong><small>${E(c.ticker)} · ${E(c.market)}</small></span></a><div data-today-market="${E(c.id)}"><div class="stockPrice">${valueQuote(c)}</div>${sparkline(quote(c).history)}</div></div><div><div class="briefHeading"><a class="briefTitle" href="/events/${E(e.id)}">${E(e.headline)}</a><div class="muted small">${E(dateTime(e.published_at))} <span class="badge">${E(e.source_provider)}</span></div></div><div class="sub briefSubtitle">${E(e.what_happened)}</div><div class="tri" data-today-summary="${E(e.id)}">${renderSummary(e)}</div><div class="footMeta"><span>중요도 <strong>${Math.round(Number(e.materiality||0)*10)}/10</strong></span><span>근거 검증 <strong class="green">${Math.round(Number(e.confidence||0)*100)}점</strong></span><span>나와의 관련성 <strong>${E(ranking.reason)}</strong></span><a class="btn primary sm" href="/events/${E(e.id)}">60초 Brief 보기 →</a></div></div></article>`;}).join('')||empty('오늘 확인할 새로운 변화가 없습니다.','관심종목을 저장한 뒤, 실제 공시 수집·검토가 완료되면 이곳에 표시됩니다.'));
  const aside=$$('.main aside .card');wireLink(aside[0]?.querySelector<HTMLButtonElement>('button')??undefined,'/calendar');wireLink(aside[1]?.querySelector<HTMLButtonElement>('button')??undefined,'/portfolio');if(aside[2]){aside[2].setAttribute('role','link');aside[2].tabIndex=0;aside[2].addEventListener('click',()=>ctx.go('/questions'),{signal:abort.signal});}
  $('#todayList').insertAdjacentHTML('afterend',statusNote());
  void hydrateLegacySummaries(events,getDetail,e=>{const el=$$('[data-today-summary]').find(el=>el.dataset.todaySummary===text(e.id));if(el)el.innerHTML=renderSummary(e);},abort.signal);
  void market(events.map(e=>record(e.company))).then(()=>{
   if(abort.signal.aborted)return;
   $$('[data-today-market]').forEach(el=>{const company=record(events.find(e=>record(e.company).id===el.dataset.todayMarket)?.company);el.innerHTML=`<div class="stockPrice">${valueQuote(company)}</div>${sparkline(quote(company).history)}`;});
  });
 }

 async function selectEvent(initial:string,selectId:string):Promise<string>{
  if(initial)return initial;const feed=record(await api('/v1/feed?days=180&limit=50')),items=list(feed.items);
  if(items.length){modal('확인할 이벤트를 선택하세요',`<label class="dialogField">게시된 이벤트<select id="${selectId}"><option value="">선택하세요</option>${items.map(e=>`<option value="${E(e.id)}">${E(record(e.company).name)} · ${E(e.headline)}</option>`).join('')}</select></label>`);return await new Promise(resolve=>{on('#'+selectId,'change',e=>{const id=(e.target as HTMLSelectElement).value;if(id){resolve(id);root.querySelector<HTMLDialogElement>('#referenceDialog')?.close();}});root.querySelector<HTMLDialogElement>('#referenceDialog')?.addEventListener('close',()=>resolve(''),{once:true});abort.signal.addEventListener('abort',()=>resolve(''),{once:true});});}return '';
 }
 async function initDetail(){
  const id=await selectEvent(routeId(),'detailEventSelect');if(!id){html('#detailHero',empty('확인할 공시를 먼저 선택하세요.','아직 게시된 공시가 없다면 관심종목을 추가하고 수집 상태를 확인하세요.'));html('#evidenceList',empty('근거 자료가 없습니다.'));return;}
  const d=await getDetail(id),e=record(d.event),c=record(e.company),b=record(d.brief);await market([c]);let selectedSource='all',expanded=true;
  $('.main>div').classList.add('detailLayout');$('.main>div>aside')?.classList.add('evidencePane');
  html('#detailHero',`<div class="detailToolbar"><a class="muted small" href="/today">‹ 오늘의 변화</a><span>${E(dateTime(e.published_at))}</span><button class="btn sm" data-share>공유 ↗</button></div><div class="heroTop"><div><a class="stockIdentity" href="/companies/${E(c.id)}">${companyLogo(c)}<strong>${E(c.name)}</strong><span class="muted">${E(c.ticker)} · ${E(c.market)}</span></a><h1 class="detailTitle">${E(e.headline)}</h1><div class="sub">${E(e.what_happened)}</div><div class="chips"><span class="badge">${E(tagType(e.event_type))}</span><span class="badge">${E(e.source_provider)}</span></div></div><div class="card cardPad"><div class="stockPrice">${valueQuote(c)}</div>${sparkline(quote(c).history)}<div class="periodButtons">${['1d','1w','1m','3m','1y'].map(x=>`<button class="plainButton" data-price-period="${x}">${x.toUpperCase()}</button>`).join('')}</div></div></div>`);
  put('#oneLine',b.what_happened||e.what_happened);
  const facts=list(d.facts);for(const [selector,label,fields] of [['#sales','매출액',['revenue','sales']],['#op','영업이익',['operating_income','operating_profit']],['#ni','순이익',['net_income','net_profit']]] as [string,string,string[]][]){const f=facts.find(x=>fields.includes(text(x.field)));html(selector,`<div class="metricBig"><span class="muted small">${label}</span><strong>${f?E(f.value_raw)+' '+E(f.unit):'—'}</strong><small>${f?E(f.period):'확인된 수치 없음'}</small></div>`);}
  const changes=list(d.changes);const boxes:[string,string,string[]][]=[['무엇이 일어났나?','FACT',facts.map(f=>text(f.quote))],['무엇이 바뀌었나?','CHANGE',changes.map(x=>`${tagType(x.field)}: ${text(x.previous_value)||'이전 근거 없음'} → ${text(x.current_value)}${x.percentage_change!=null?' ('+x.percentage_change+'%)':''}`)],['왜 중요한가?','INTERPRETATION',[text(b.interpretation)]],['왜 나에게 관련 있는가?','PORTFOLIO',[text(record(e.ranking).reason),'시장가치 비중이 없으므로 구체적인 손익 영향은 계산하지 않습니다.']],['불확실한 부분은?','UNCERTAINTY',[text(b.uncertainty)]],['다음에 무엇을 확인할까?','NEXT',[text(b.monitor_next)]]];
  html('#analysisGrid',boxes.map(([title,badge,paragraphs],i)=>`<section class="analysisBox ${i===2?'advancedOnly':''}"><h3><span class="sectionNumber">${i+1}</span>${E(title)} <span class="badge">${badge}</span></h3><ul>${paragraphs.filter(Boolean).map(x=>`<li>${E(x)}</li>`).join('')||'<li class="muted">검토된 내용이 없습니다.</li>'}</ul>${i===0?facts.map(f=>`<a class="evidenceJump" href="#evidence-${E(f.id)}">원문 인용 확인 ↗</a>`).join(''):''}${i===3?'<a class="sourceLink" href="/portfolio">내 포트폴리오 보기 →</a>':''}</section>`).join(''));
  $('#analysisGrid').insertAdjacentHTML('afterend',`<div class="detailActions"><a class="btn primary" href="/questions?event=${encodeURIComponent(id)}">AI 근거 질문하기 →</a><button class="btn" data-feedback>근거 오류 신고</button><button class="btn" data-toggle-evidence>근거 창 닫기</button></div>${statusNote()}`);
  const renderEvidence=()=>{const filtered=list(d.evidence).filter(x=>selectedSource==='all'||(selectedSource==='filing'&&['dart','sec','OpenDART','SEC EDGAR'].includes(text(x.source_name))));html('#evidenceList',contextLinks({...d,evidence:filtered})||empty('이 유형의 검증된 근거가 없습니다.'));$$('#evidenceTabs button').forEach(btn=>{btn.classList.toggle('active',btn.dataset.source===selectedSource);btn.setAttribute('aria-pressed',String(btn.dataset.source===selectedSource));});};
  delegate('click','#evidenceTabs button',btn=>{selectedSource=btn.dataset.source??'all';renderEvidence();});delegate('click','[data-toggle-evidence]',btn=>{expanded=!expanded;$('.evidencePane').hidden=!expanded;$('.detailLayout').classList.toggle('evidenceClosed',!expanded);btn.textContent=expanded?'근거 창 닫기':'근거 창 열기';});
  const paneButton=$$('.evidencePane button').find(x=>x.textContent==='고급 모드');paneButton?.setAttribute('data-evidence-density','true');delegate('click','[data-evidence-density]',b=>{$('.evidencePane').classList.toggle('compactEvidence');b.textContent=$('.evidencePane').classList.contains('compactEvidence')?'전체 인용 보기':'간단히 보기';});
  delegate('click','[data-price-period]',btn=>{void run(async()=>{await market([c],btn.dataset.pricePeriod);const target=$('.heroTop .card');target.innerHTML=`<div class="stockPrice">${valueQuote(c)}</div>${sparkline(quote(c).history)}<p class="small muted">${quote(c).as_of?E(dateTime(quote(c).as_of))+' · '+E(quote(c).source):'제공자 시세 연결 필요'}</p><div class="periodButtons">${['1d','1w','1m','3m','1y'].map(x=>`<button class="plainButton ${x===btn.dataset.pricePeriod?'active':''}" data-price-period="${x}">${x.toUpperCase()}</button>`).join('')}</div>`;},btn);});
  delegate('click','[data-feedback]',()=>{modal('근거 오류 신고','<form id="feedbackForm"><label class="dialogField">확인이 필요한 내용<textarea id="feedbackComment" required maxlength="1000" placeholder="어떤 숫자나 출처에 문제가 있는지 알려주세요."></textarea></label><button class="btn primary" type="submit">신고 보내기</button></form>');on('#feedbackForm','submit',event=>{event.preventDefault();void run(async()=>{await api(`/v1/events/${encodeURIComponent(id)}/feedback`,'POST',{rating:'report',comment:$<HTMLTextAreaElement>('#feedbackComment').value});root.querySelector<HTMLDialogElement>('#referenceDialog')?.close();toast('신고를 저장했습니다.');});});});renderEvidence();
 }

 async function initTimeline(){
  let id=ctx.id||'',period='6m',type='all',events:Row[]=[],company:Row={};let requestVersion=0;
  const [catalogData,watchData]=await Promise.all([api('/v1/companies?limit=100'),id?Promise.resolve(null):api('/v1/watchlist')]);
  const catalog=list(catalogData);
  if(id)company=catalog.find(c=>c.id===id)??{};
  if(!id){const symbol=new URLSearchParams(location.search).get('symbol'),watch=record(watchData);company=catalog.find(c=>c.ticker===symbol)??list(watch.items)[0]??catalog[0]??{};id=text(company.id);}
  $('#companyName').insertAdjacentHTML('afterend',`<select class="companyPicker" id="timelineCompany" aria-label="타임라인 기업 선택"><option value="">기업 선택</option>${catalog.map(c=>`<option value="${E(c.id)}" ${c.id===id?'selected':''}>${E(c.name)} · ${E(c.ticker)}</option>`).join('')}</select>`);
  $('.main > a')?.setAttribute('href','/watchlist');
  function render(){put('#companyName',company.name?`${company.name} (${company.ticker} · ${company.market})`:'기업을 선택하세요');put('#tlLogo',text(company.ticker).slice(0,2)||'—');html('#quote',valueQuote(company));const filtered=events.filter(e=>type==='all'||text(e.event_type)===type||type==='policy'&&e.event_type==='regulation');put('#tlCount',filtered.length);
   html('#timeline',filtered.map(e=>{const change=list(e.change_summary)[0];return `<article class="tlItem"><div class="tlDate"><small>${E(companyDate(e.published_at).slice(0,4))}</small>${E(companyDate(e.published_at).slice(5,7))}월 ${E(companyDate(e.published_at).slice(8))}일</div><div class="tlCard"><div class="briefHeading"><a href="/events/${E(e.id)}"><h3><span class="badge">${E(tagType(e.event_type))}</span> ${E(e.headline)}</h3></a><small class="muted">${E(e.source_provider)}</small></div><div class="sub small">${E(e.what_happened)}</div><div class="timelineDetails">${change?`<div class="beforeAfter"><div><small>이전</small><strong>${E(change.previous_value||'비교 근거 없음')}</strong></div><span>→</span><div><small>현재</small><strong>${E(change.current_value)}</strong></div></div>`:'<div class="beforeAfter"><div><small>이전·현재 비교</small><span class="muted">비교 가능한 검증 근거 없음</span></div></div>'}<div><div class="impact">${E(e.interpretation||'검토된 의미 확인 필요')}</div>${sourceLink(e.source_url,'공식 원문')}</div></div></div></article>`;}).join('')||empty('선택한 기간과 유형에 게시된 변화가 없습니다.'));
   html('#bigChart',sparkline(quote(company).history,true));put('#priceTitle',`${text(company.name)||'기업'} 주가 추이`);html('#metrics',`<div class="metricRow"><span>현재가</span>${valueQuote(company)}</div><div class="metricRow"><span>시가총액</span><strong>${E(money(quote(company).market_cap,quote(company).currency))}</strong></div><div class="metricRow"><span>기준 시각</span><strong>${quote(company).as_of?E(dateTime(quote(company).as_of)):'—'}</strong></div><p class="dataNote">실시간 시세 및 재무지표는 제공자 연결 시 표시됩니다.</p>`);
   const docs=events.map(e=>record(e.source_document)).filter(d=>safeURL(d.source_url));const uniq=[...new Map(docs.map(d=>[text(d.id),d])).values()];html('#reports',uniq.slice(0,6).map(r=>`<div class="reportRow"><div>${sourceLink(r.source_url,r.title)}<small class="muted">${E(r.provider)} · ${E(companyDate(r.published_at))}</small></div><span class="badge">원문</span></div>`).join('')||empty('연결된 원문 자료가 없습니다.'));
  }
  async function load(){const v=++requestVersion;if(!id){events=[];render();return;}const selectedCompany=company,selectedPeriod=period;const result=list(await api(`/v1/companies/${encodeURIComponent(id)}/timeline?days=${({ '3m':90,'6m':180,'1y':365,'3y':1095} as Record<string,number>)[period]??180}&limit=100`));if(v!==requestVersion)return;events=result;render();void hydrateLegacySummaries(result.slice(0,30),getDetail,()=>{if(v===requestVersion)render();},abort.signal);void market([selectedCompany],selectedPeriod).then(()=>{if(v===requestVersion&&!abort.signal.aborted)render();});}
  delegate('click','#eventTypes button',b=>{type=b.dataset.type??'all';$$('#eventTypes button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});render();});delegate('click','[data-period]',b=>{period=b.dataset.period??'6m';$$('[data-period]').forEach(x=>x.classList.toggle('active',x===b));void run(load,b);});
  on('#timelineCompany','change',e=>{id=(e.target as HTMLSelectElement).value;company=catalog.find(c=>c.id===id)??{};void run(load);});
  on('#watchBtn','click',e=>{void run(async()=>{if(!id)throw new Error('기업을 선택해 주세요.');await api(`/v1/watchlist/${encodeURIComponent(id)}`,'PUT');toast('관심종목에 저장했습니다.');$('#watchBtn').textContent='✓ 관심종목 추가됨';},e.currentTarget as HTMLElement);});
  const buttons=$$('.main aside button');buttons.forEach((b,i)=>b.addEventListener('click',()=>{if(i===0)modal('가격 데이터',sparkline(quote(company).history,true)+`<p class="sub">선택 기간: ${E(period)}. 확인된 시세가 없으면 차트를 임의로 만들지 않습니다.</p>`);else if(i===1)modal('주요 지표',$('#metrics').innerHTML);else modal('관련 원문 자료',$('#reports').innerHTML);},{signal:abort.signal}));await load();
 }

 async function initChat(){
  let eventId=await selectEvent(routeId(),'chatEventSelect'),d:Row={},messages:{role:string;body:string;answer?:Row}[]=[],history:Row[]=[],sending=false;
  $('.main>div').classList.add('chatLayout');$('.main>div>aside>a').setAttribute('href','/today');
  $('#question').setAttribute('aria-label','공시에 관한 질문');$('#question').setAttribute('maxlength','2000');$('#askForm button').setAttribute('aria-label','질문 보내기');
  const historyButton=$$('.main section button').find(b=>b.textContent?.includes('대화 히스토리'));historyButton?.setAttribute('data-chat-history','true');
  function render(){html('#chat',messages.map(m=>`<article class="msg ${m.role==='user'?'user':'ai'}">${m.role==='user'?'':`<h4>${record(m.answer).status==='answered'?'검증된 근거 검색 결과':'확인 가능한 범위'}</h4>`}<div>${E(m.body).replace(/\n/g,'<br>')}</div>${list(record(m.answer).evidence).map((c,i)=>`<blockquote>${E(c.quote)}</blockquote><div class="evidencePill">${sourceLink(c.source_url,`${i+1}. ${text(c.location)}`)}</div>`).join('')}</article>`).join('')||empty('궁금한 점을 질문해 보세요.','저장된 근거 안에서 답을 찾습니다. 생성형 AI가 연결되지 않은 상태에서는 새 분석을 만들지 않습니다.'));$('#chat').scrollTop=$('#chat').scrollHeight;}
  async function load(){if(!eventId){put('#eventTitle','게시된 공시가 없습니다.');html('#companyBlock',empty('먼저 관심종목을 등록하세요.'));$<HTMLInputElement>('#question').disabled=true;$<HTMLButtonElement>('#askForm button').disabled=true;render();return;}d=await getDetail(eventId);const e=record(d.event),c=record(e.company);put('#eventTitle',e.headline);put('#eventDate',dateTime(e.published_at));await market([c]);html('#companyBlock',`<a class="stockIdentity" href="/companies/${E(c.id)}">${companyLogo(c)}<span><strong>${E(c.name)}</strong><small>${E(c.ticker)} · ${E(c.market)}</small></span></a><div class="chatQuote">${valueQuote(c)}</div>${sparkline(quote(c).history)}`);html('#keySummary',[text(e.what_happened),text(record(d.brief).interpretation)].filter(Boolean).map(t=>`<li>${E(t)}</li>`).join(''));html('#evidenceDocs',list(d.evidence).slice(0,5).map(x=>`<div class="doc"><strong>${sourceLink(x.source_url,record(d.document).title)}</strong><small class="muted">${E(x.location)}</small></div>`).join('')||empty('검증된 원문이 없습니다.'));
   history=list(await api('/v1/questions').catch(()=>[]));messages=history.filter(x=>x.event_id===eventId).slice(0,10).reverse().flatMap(x=>[{role:'user',body:text(x.question)},{role:'assistant',body:text(record(x.answer).message),answer:record(x.answer)}]);render();html('#suggestions',['이전 공시와 무엇이 달라졌나요?','매출 수치의 근거를 보여줘','위험 요인의 원문을 보여줘'].map(q=>`<button class="btn sm" data-question="${E(q)}">${E(q)}</button>`).join(''));}
  delegate('click','[data-question]',b=>{$<HTMLInputElement>('#question').value=b.dataset.question??'';$('#question').focus();});
  on('#askForm','submit',event=>{event.preventDefault();if(sending)return;const input=$<HTMLInputElement>('#question'),question=input.value.trim();if(!question||!eventId)return;sending=true;void run(async()=>{messages.push({role:'user',body:question});input.value='';render();try{const answer=record(await api(`/v1/events/${encodeURIComponent(eventId)}/questions`,'POST',{question}));messages.push({role:'assistant',body:text(answer.message),answer});history=list(await api('/v1/questions').catch(()=>[]));}catch(err){messages.push({role:'assistant',body:message(err)});}finally{sending=false;render();}},$('#askForm button'));});
  delegate('click','[data-chat-history]',()=>{const dlg=modal('대화 히스토리',`<button class="btn sm" data-clear-history>내 기록 모두 삭제</button><div class="historyItems">${history.map(h=>`<button class="searchOption" data-history-event="${E(h.event_id)}"><span><strong>${E(h.question)}</strong><small>${E(dateTime(h.created_at))}</small></span></button>`).join('')||empty('저장된 대화가 없습니다.')}</div>`);dlg.querySelector('[data-clear-history]')?.addEventListener('click',()=>{if(confirm('내 질문 기록을 모두 삭제할까요?'))void run(async()=>{await api('/v1/questions','DELETE');history=[];messages=[];dlg.close();render();toast('질문 기록을 삭제했습니다.');});},{signal:abort.signal});});
  delegate('click','[data-history-event]',b=>{eventId=b.dataset.historyEvent??'';root.querySelector<HTMLDialogElement>('#referenceDialog')?.close();void run(load);});await load();
 }

 async function initCalendar(){
  const today=koreaDate();let year=Number(today.slice(0,4)),month=Number(today.slice(5,7))-1,scope='portfolio',selected='',eventType='all',items:Row[]=[],allItems:Row[]=[],reminders=new Set<string>(),allUpcoming=false;
  const [cal,p,w,r]=await Promise.all([api('/v1/calendar'),api('/v1/portfolio'),api('/v1/watchlist'),rpc('sb_reference_reminders',{p:{action:'list'}}).catch(()=>[])]);allItems=list(cal);const holdings=new Set(list(record(p).positions).map(x=>text(record(x.company).id))),watched=new Set(list(record(w).items).map(x=>text(x.id)));reminders=new Set(list(r).map(x=>text(x.calendar_id)));
  const headerButtons=$$('.main>div:first-of-type button');headerButtons.forEach(b=>b.setAttribute('data-subscribe','true'));
  $('#monthLabel').insertAdjacentHTML('afterend','<input class="monthPicker" id="monthPicker" type="month" aria-label="캘린더 월 선택">');
  $('#scopeSeg').insertAdjacentHTML('beforeend','<select id="eventTypeFilter" aria-label="이벤트 유형"><option value="all">전체 이벤트 유형</option><option value="earnings">실적 발표</option><option value="guidance">가이던스</option><option value="capex">투자/설비</option><option value="regulation">규제/정책</option><option value="personal">내 일정</option></select><button class="btn sm" data-new-calendar>＋ 일정 추가</button>');
  const eids=[...new Set(allItems.map(x=>text(x.event_id)).filter(Boolean))].slice(0,40);const details=await Promise.all(eids.map(id=>getDetail(id).catch(()=>({} as Row))));const eventMap=new Map(details.map(d=>[text(record(d.event).id),record(d.event)]));
  function updateItems(){items=allItems.filter(x=>{const e=eventMap.get(text(x.event_id)),c=record(e?.company);const origin=x.origin==='user';const scopeOK=origin||(scope==='portfolio'?holdings.has(text(x.company_id)):scope==='watchlist'?watched.has(text(x.company_id)):scope==='kr'?['KOSPI','KOSDAQ'].includes(text(c.market)):scope==='us'?['NASDAQ','NYSE'].includes(text(c.market)):true);return scopeOK&&(eventType==='all'||eventType==='personal'&&origin||text(e?.event_type)===eventType);});}
  function render(){updateItems();put('#monthLabel',`${year}년 ${month+1}월`);$<HTMLInputElement>('#monthPicker').value=`${year}-${String(month+1).padStart(2,'0')}`;
   html('#calendar',`<h2 class="calendarMonthTitle">${year}년 ${month+1}월</h2><div class="calGrid">${['일','월','화','수','목','금','토'].map(s=>`<div class="calHead">${s}</div>`).join('')}${monthCells(year,month).map(cell=>{const ev=items.filter(x=>text(x.occurs_on)===cell.date);return `<div class="calCell ${cell.current?'':'mutedCell'} ${selected===cell.date?'selectedDay':''}"><button class="calDate ${cell.date===today?'isToday':''}" data-day="${cell.date}" aria-label="${cell.date} 일정">${cell.day}</button>${ev.slice(0,2).map(x=>`<button class="calEvent ${x.origin==='user'?'purple':''}" data-calendar-id="${E(x.id)}"><i></i>${E(x.title)}</button>`).join('')}${ev.length>2?`<button class="plainButton muted small" data-day="${cell.date}">+${ev.length-2}개</button>`:''}</div>`;}).join('')}</div>`);
   const upcoming=items.filter(x=>selected?x.occurs_on===selected:text(x.occurs_on)>=today).sort((a,b)=>text(a.occurs_on).localeCompare(text(b.occurs_on))).slice(0,allUpcoming?500:8);html('#upcoming',upcoming.map(x=>{const e=eventMap.get(text(x.event_id));return `<div class="upEvent"><button class="plainButton calendarDateBox" data-day="${E(x.occurs_on)}"><strong>${E(text(x.occurs_on).slice(5))}</strong></button><button class="plainButton upcomingText" data-calendar-id="${E(x.id)}"><strong>${E(record(e?.company).name||x.title)}</strong><small>${E(x.title)}</small><span class="badge">${x.origin==='user'?'내 일정':E(tagType(e?.event_type||'other'))}</span><span class="muted small">${x.origin==='user'?'직접 등록':'공식 원문'}</span></button><button class="toggle ${reminders.has(text(x.id))?'on':''}" role="switch" aria-checked="${reminders.has(text(x.id))}" data-reminder="${E(x.id)}" aria-label="${E(x.title)} 관심 일정"><i></i></button></div>`;}).join('')||empty('이 조건에 해당하는 일정이 없습니다.'));
   const heading=$('#upcoming').previousElementSibling?.querySelector('strong');if(heading)heading.textContent=selected?selected+' 일정':'다가오는 주요 이벤트';
  }
  function addForm(initial=today){const dlg=modal('확인 일정 추가',`<form id="calendarAdd"><label class="dialogField">제목<input id="newCalendarTitle" required maxlength="200" placeholder="예: 분기 공시 다시 확인"></label><label class="dialogField">날짜<input id="newCalendarDate" required type="date" value="${initial}"></label><button class="btn primary" type="submit">일정 저장</button></form>`);on('#calendarAdd','submit',event=>{event.preventDefault();void run(async()=>{const item=record(await api('/v1/calendar','POST',{title:$<HTMLInputElement>('#newCalendarTitle').value.trim(),occurs_on:$<HTMLInputElement>('#newCalendarDate').value,company_id:null}));allItems.push(item);selected=text(item.occurs_on);year=Number(selected.slice(0,4));month=Number(selected.slice(5,7))-1;dlg.close();render();toast('일정을 저장했습니다.');},$<HTMLButtonElement>('#calendarAdd button'));});}
  delegate('click','[data-new-calendar]',()=>addForm(selected||today));delegate('click','[data-day]',b=>{selected=b.dataset.day??'';render();});
  delegate('click','[data-calendar-id]',b=>{const x=allItems.find(i=>i.id===b.dataset.calendarId);if(!x)return;modal(text(x.title),`<p class="sub">${E(x.occurs_on)} · ${x.origin==='user'?'직접 등록한 일정':'공식 근거에 등록된 일정'}</p>${sourceLink(x.source_url,'원문 확인')}<div class="buttonPair">${x.event_id?`<a class="btn primary" href="/events/${E(x.event_id)}">관련 브리핑</a>`:''}${x.origin==='user'?`<button class="btn" data-delete-calendar="${E(x.id)}">일정 삭제</button>`:''}</div><p class="dataNote">관심 일정 스위치는 목록에 저장됩니다. 외부 푸시 발송을 의미하지 않습니다.</p>`);});
  delegate('click','[data-delete-calendar]',b=>{void run(async()=>{await api(`/v1/calendar/${encodeURIComponent(text(b.dataset.deleteCalendar))}`,'DELETE');allItems=allItems.filter(x=>x.id!==b.dataset.deleteCalendar);root.querySelector<HTMLDialogElement>('#referenceDialog')?.close();render();toast('일정을 삭제했습니다.');},b);});
  delegate('click','[data-reminder]',b=>{void run(async()=>{const id=b.dataset.reminder??'',enabled=!reminders.has(id);await rpc('sb_reference_reminders',{p:{action:'set',calendar_id:id,enabled}});if(enabled)reminders.add(id);else reminders.delete(id);render();toast(enabled?'관심 일정에 저장했습니다.':'관심 일정 표시를 해제했습니다.');},b);});
  on('#prev','click',()=>{const d=new Date(Date.UTC(year,month-1,1));year=d.getUTCFullYear();month=d.getUTCMonth();selected='';render();});on('#next','click',()=>{const d=new Date(Date.UTC(year,month+1,1));year=d.getUTCFullYear();month=d.getUTCMonth();selected='';render();});on('#todayBtn','click',()=>{year=Number(today.slice(0,4));month=Number(today.slice(5,7))-1;selected=today;render();});
  on('#monthPicker','change',e=>{const v=(e.target as HTMLInputElement).value;if(/^\d{4}-\d{2}$/.test(v)){year=Number(v.slice(0,4));month=Number(v.slice(5,7))-1;selected='';render();}});on('#eventTypeFilter','change',e=>{eventType=(e.target as HTMLSelectElement).value;render();});delegate('click','#scopeSeg [data-scope]',b=>{scope=b.dataset.scope??'portfolio';$$('#scopeSeg [data-scope]').forEach(x=>x.classList.toggle('active',x===b));render();});
  const upcomingButton=$('#upcoming').previousElementSibling?.querySelector('button');upcomingButton?.addEventListener('click',()=>{selected='';allUpcoming=!allUpcoming;upcomingButton.textContent=allUpcoming?'간단히 보기':'모두 보기 →';render();},{signal:abort.signal});
  delegate('click','[data-subscribe]',()=>{const dlg=modal('캘린더 구독',`<p class="sub">일정을 파일로 내보내거나 캘린더 앱에서 자동 갱신하는 비공개 주소를 만들 수 있습니다.</p><button class="btn" data-ics-export>ICS 파일 내보내기</button> <button class="btn primary" data-ics-create>비공개 구독 주소 생성</button><div id="subscriptionResult"></div>`);dlg.querySelector('[data-ics-export]')?.addEventListener('click',()=>{void run(()=>ctx.download('/v1/calendar/export','signalbrief.ics'));},{signal:abort.signal});dlg.querySelector('[data-ics-create]')?.addEventListener('click',()=>{void run(async()=>{const data=record(await api('/v1/calendar/subscription','POST'));html('#subscriptionResult',`<p class="dataNote">이 주소를 아는 사람은 일정을 읽을 수 있습니다. 90일 후 만료되며 재생성 시 기존 주소는 폐기됩니다.</p><label class="dialogField">비공개 주소<input readonly value="${E(data.url)}" id="subscriptionURL"></label><button class="btn" data-copy-sub>복사</button> <button class="btn" data-revoke-sub>구독 폐기</button>`);});},{signal:abort.signal});});
  delegate('click','[data-copy-sub]',()=>{void run(async()=>{await navigator.clipboard.writeText($<HTMLInputElement>('#subscriptionURL').value);toast('구독 주소를 복사했습니다.');});});delegate('click','[data-revoke-sub]',b=>{void run(async()=>{await api('/v1/calendar/subscription','DELETE');html('#subscriptionResult','<p>구독 주소를 폐기했습니다.</p>');},b);});render();
 }

 async function initAlerts(){
  let filter='all',notifications:Row[]=[],rules:Row[]=[],settings:Row={};
  async function refresh(){[notifications,rules,settings]=await Promise.all([api('/v1/notifications').then(list),api('/v1/alerts').then(list),api('/v1/preferences').then(record)]);render();renderSettings();}
  const severity=(n:Row)=>{const score=Number(record(record(n.event).ranking).score??record(n.event).materiality??0);return score>=.85?'critical':score>=.7?'high':'normal';};
  function render(){put('#allN',`(${notifications.length})`);put('#unreadN',`(${notifications.filter(x=>!x.read_at).length})`);put('#rulesN',`(${rules.length})`);
   if(filter==='rules'){html('#alertList',`<section class="card cardPad"><div class="sectionHeader"><strong>알림 규칙 관리</strong><button class="btn primary sm" data-new-rule>＋ 규칙 만들기</button></div>${rules.map(r=>`<div class="settingRow"><div><strong>${E(r.name)}</strong><small>중요도 ${Math.round(Number(r.min_score)*100)}점 이상 · ${Array.isArray(r.event_types)&&r.event_types.length?r.event_types.map(tagType).map(E).join(', '):'전체 유형'}</small></div><button class="toggle ${r.enabled?'on':''}" role="switch" aria-checked="${!!r.enabled}" data-toggle-rule="${E(r.id)}" aria-label="${E(r.name)} 사용"><i></i></button><button class="btn sm" data-edit-rule="${E(r.id)}">수정</button><button class="plainButton" data-delete-rule="${E(r.id)}" aria-label="${E(r.name)} 삭제">×</button></div>`).join('')||empty('알림 규칙을 만들어 주세요.')}</section>`);}
   else{const visible=notifications.filter(x=>filter!=='unread'||!x.read_at);html('#alertList',visible.map(n=>{const e=record(n.event),c=record(e.company),level=severity(n);return `<article class="alertItem ${n.read_at?'':'unread'}"><a class="logoBox" href="/companies/${E(c.id)}">${companyLogo(c)}<div><strong>${E(c.name)}</strong><small class="muted">${E(c.ticker)} · ${E(c.market)}</small><span class="badge ${level==='critical'?'red':level==='high'?'amber':''}">${level==='critical'?'매우 중요':level==='high'?'높음':'일반'}</span></div></a><div><button class="plainButton alertTitle" data-open-notification="${E(n.id)}">${E(e.headline)}</button><div class="alertDesc">${E(e.what_happened)}</div><div class="chips"><span class="badge">${E(tagType(e.event_type))}</span><span class="badge green">${E(record(e.ranking).reason)}</span><span class="badge">근거 검증 ${Math.round(Number(e.confidence??0)*100)}점</span></div></div><div class="muted small"><span>${E(dateTime(n.created_at))}</span>${!n.read_at?`<button class="plainButton blue" data-read-notification="${E(n.id)}">읽음 표시</button>`:''}</div></article>`;}).join('')||empty('표시할 알림이 없습니다.','설정한 규칙에 맞는 실제 공시가 게시되면 알림이 추가됩니다.'));}
   const cutoff=Date.now()-7*864e5,weekly=notifications.filter(n=>Date.parse(text(n.created_at))>=cutoff),counts=['critical','high','normal'].map(s=>weekly.filter(x=>severity(x)===s).length),total=weekly.length;let angle=0;const colors=['#ff4255','#ff9d14','#52a0ff'];const segments=counts.map((n,i)=>{const start=angle;angle+=total?n/total*360:0;return `${colors[i]} ${start}deg ${angle}deg`;});html('#weekSummary',`<div class="weekChart"><div class="donut" style="background:${total?'conic-gradient('+segments.join(',')+')':'#e7edf5'}"><span><strong>${total}</strong><small>최근 7일 알림</small></span></div><div>${['매우 중요','높음','일반'].map((label,i)=>`<div class="legendRow"><i style="background:${colors[i]}"></i><span>${label}</span><strong>${counts[i]}</strong><small>${total?(counts[i]/total*100).toFixed(1):'0.0'}%</small></div>`).join('')}</div></div>`);
  }
  function renderSettings(){html('#settings',`<div class="settingRow"><div><strong>${icon('alerts')} 실시간 알림</strong><small>새로 게시된 알림을 앱 안에서 확인합니다.</small></div><button class="toggle ${settings.realtime_enabled!==false?'on':''}" role="switch" aria-checked="${settings.realtime_enabled!==false}" data-notify-setting="realtime_enabled" aria-label="실시간 알림"><i></i></button></div><div class="settingRow"><div><strong>${icon('file')} 일간 요약</strong><small>이메일 발송 서비스 연결 후 제공됩니다.</small></div><button class="toggle" disabled aria-label="일간 요약 발송 미연결" title="메일 발송 서비스가 연결되지 않았습니다"><i></i></button></div><div class="settingRow threshold"><div><strong>중요도 임계값</strong><small>새로 게시되는 알림에 적용됩니다.</small></div><div class="thresholdButtons">${[[0,'전체'],[.4,'일반 이상'],[.7,'높음 이상'],[.85,'매우 중요만']].map(([value,label])=>`<button class="btn sm ${Number(settings.notify_min_score??.4)===value?'primary':''}" data-threshold="${value}" aria-pressed="${Number(settings.notify_min_score??.4)===value}">${label}</button>`).join('')}</div></div><h4>알림 채널</h4><div class="settingRow"><div><strong>✉ 이메일 알림</strong><small>서버의 메일 발송 서비스 연결이 필요합니다.</small></div><button class="toggle" disabled aria-label="이메일 발송 미연결"><i></i></button></div><div class="settingRow"><div><strong>▣ 브라우저 알림</strong><small>이 페이지가 열려 있는 동안 새 알림을 표시합니다.</small></div><button class="toggle ${settings.browser_notifications?'on':''}" role="switch" aria-checked="${!!settings.browser_notifications}" data-notify-setting="browser_notifications" aria-label="브라우저 알림"><i></i></button></div><button class="btn ruleManager" data-manage-rules>${icon('settings')} 알림 규칙 관리 <span>›</span></button><p class="dataNote">외부 이메일 및 백그라운드 앱 푸시는 아직 발송되지 않습니다. <a href="/status">연결 상태</a></p>`);}
  function ruleForm(id=''){const r=rules.find(x=>x.id===id)??{};const dlg=modal(id?'알림 규칙 수정':'알림 규칙 만들기',`<form id="ruleForm"><label class="dialogField">규칙 이름<input id="ruleName" required maxlength="100" value="${E(r.name)}"></label><label class="dialogField">중요도<select id="ruleThreshold">${[[0,'전체'],[.4,'일반 이상'],[.7,'높음 이상'],[.85,'매우 중요만']].map(([n,l])=>`<option value="${n}" ${Number(r.min_score??.4)===n?'selected':''}>${l}</option>`).join('')}</select></label><fieldset class="ruleTypes"><legend>유형 · 선택하지 않으면 전체</legend>${Object.entries(eventTypes).filter(([v])=>v!=='policy').map(([v,l])=>`<label><input type="checkbox" name="ruleType" value="${v}" ${Array.isArray(r.event_types)&&r.event_types.includes(v)?'checked':''}>${l}</label>`).join('')}</fieldset><button class="btn primary" type="submit">규칙 저장</button></form>`);on('#ruleForm','submit',e=>{e.preventDefault();void run(async()=>{await api(id?`/v1/alerts/${encodeURIComponent(id)}`:'/v1/alerts',id?'PUT':'POST',{name:$<HTMLInputElement>('#ruleName').value,event_types:$$<HTMLInputElement>('[name="ruleType"]:checked').map(x=>x.value),min_score:Number($<HTMLSelectElement>('#ruleThreshold').value),enabled:r.enabled??true});dlg.close();await refresh();toast('규칙을 저장했습니다.');},$('#ruleForm button'));});}
  delegate('click','#alertTabs [data-filter]',b=>{filter=b.dataset.filter??'all';$$('#alertTabs button').forEach(x=>x.classList.toggle('active',x===b));render();});delegate('click','[data-manage-rules]',()=>{filter='rules';$$('#alertTabs button').forEach(x=>x.classList.toggle('active',x.dataset.filter==='rules'));render();});delegate('click','[data-new-rule]',()=>ruleForm());delegate('click','[data-edit-rule]',b=>ruleForm(b.dataset.editRule));
  delegate('click','[data-delete-rule]',b=>{void run(async()=>{await api(`/v1/alerts/${encodeURIComponent(text(b.dataset.deleteRule))}`,'DELETE');await refresh();toast('규칙을 삭제했습니다.');},b);});delegate('click','[data-toggle-rule]',b=>{void run(async()=>{const r=rules.find(x=>x.id===b.dataset.toggleRule);if(!r)return;await api(`/v1/alerts/${encodeURIComponent(text(r.id))}`,'PUT',{name:r.name,event_types:r.event_types,min_score:r.min_score,enabled:!r.enabled});await refresh();},b);});
  on('#markRead','click',e=>{void run(async()=>{await api('/v1/notifications/all/read','PUT');await refresh();toast('모두 읽음으로 표시했습니다.');},e.currentTarget as HTMLElement);});delegate('click','[data-read-notification]',b=>{void run(async()=>{await api(`/v1/notifications/${encodeURIComponent(text(b.dataset.readNotification))}/read`,'PUT');await refresh();},b);});delegate('click','[data-open-notification]',b=>{void run(async()=>{const n=notifications.find(x=>x.id===b.dataset.openNotification);if(!n)return;await api(`/v1/notifications/${encodeURIComponent(text(n.id))}/read`,'PUT');ctx.go('/events/'+text(record(n.event).id));},b);});
  delegate('click','[data-threshold]',b=>{void run(async()=>{await rpc('sb_reference_preferences',{p:{notify_min_score:Number(b.dataset.threshold)}});await refresh();toast('중요도 임계값을 저장했습니다.');},b);});delegate('click','[data-notify-setting]',b=>{void run(async()=>{const key=b.dataset.notifySetting??'',enabled=key==='realtime_enabled'?settings.realtime_enabled===false:!settings[key];if(key==='browser_notifications'&&enabled){if(typeof Notification==='undefined')throw new Error('이 브라우저는 알림을 지원하지 않습니다.');if(await Notification.requestPermission()!=='granted')throw new Error('브라우저에서 알림 권한을 허용해 주세요.');}await rpc('sb_reference_preferences',{p:{[key]:enabled}});await refresh();toast('알림 설정을 저장했습니다.');},b);});
  const sidebarButtons=$$('.main aside .card>div>button');sidebarButtons.forEach(b=>b.addEventListener('click',()=>{filter='rules';render();}, {signal:abort.signal}));
  await refresh();let lastIds=new Set(notifications.map(n=>text(n.id)));const poll=setInterval(()=>{if(document.visibilityState!=='visible')return;void (async()=>{try{const current=list(await api('/v1/notifications'));if(settings.browser_notifications&&typeof Notification!=='undefined'&&Notification.permission==='granted'){for(const n of current)if(!lastIds.has(text(n.id))&&!n.read_at)new Notification('SignalBrief',{body:'관심종목에 새로운 검토된 브리핑이 있습니다.',tag:text(n.id)});}lastIds=new Set(current.map(n=>text(n.id)));notifications=current;render();}catch{/* Next visible refresh will retry without duplicate notifications. */}})();},60000);abort.signal.addEventListener('abort',()=>clearInterval(poll),{once:true});
 }

 async function initOps(){
  if(!ctx.user?.is_admin){html('.main',empty('운영자만 접근할 수 있습니다.','모든 운영 데이터와 작업은 서버에서도 관리자 권한을 확인합니다.'));return;}
  let range='24h',customStart='',customEnd='',snapshot:Row={},view=new URLSearchParams(location.search).get('view')||'';let generation=0;
  const defs=[['documents','오늘 수집된 문서','file'],['events','감지된 이벤트','timeline'],['ai_runs','AI 실행 건수','today'],['ai_failures','AI 실패 건수','alerts'],['low_confidence','저신뢰도 분석','shield'],['citation_failures','인용 출처 실패','file'],['number_mismatch','수치 불일치','portfolio'],['duplicates','중복 이벤트 후보','file'],['pipeline_latency','파이프라인 지연시간','calendar'],['ai_cost','예상 AI 비용','portfolio']];
  $('.profile .mode')?.remove();$('.main').insertAdjacentHTML('beforeend','<div id="opsView"></div>');
  function table(id:string,data:Row[],kind:string,headers:string[]){const filters=`<div class="tableFilters"><input data-filter-table="${id}" placeholder="제목·종목 검색" aria-label="${E(headers[1]||kind)} 검색"><select data-state-table="${id}" aria-label="상태 필터"><option value="">전체 상태</option>${[...new Set(data.map(x=>text(x.state||x.status)).filter(Boolean))].map(v=>`<option>${E(v)}</option>`).join('')}</select></div>`;html('#'+id,filters+`<div class="tableScroll"><table class="table"><thead><tr><th><input type="checkbox" data-check-all="${id}" aria-label="표 전체 선택"></th>${headers.map(h=>`<th>${E(h)}</th>`).join('')}<th>작업</th></tr></thead><tbody>${data.map(r=>`<tr data-search-text="${E(text(r.title||r.question||r.comment)+' '+text(r.symbol))}" data-row-state="${E(r.state||r.status)}"><td><input type="checkbox" aria-label="행 선택" data-row-id="${E(r.id)}"></td><td>${E(text(r.created_at).slice(11,16)||text(r.time))}</td><td class="tableTitle">${E(r.title||r.comment||r.question||'—')}</td><td>${E(r.symbol||r.error_code||r.rating||'—')}</td><td><span class="badge ${['failed','rejected','dead'].includes(text(r.state||r.status))?'red':'amber'}">${E(r.state||r.status||'검토 필요')}</span></td><td><button class="btn primary sm" data-ops-review="${E(r.id)}" data-ops-kind="${kind}">${kind==='run'?'실행 보기':kind==='report'?'검토하기':'검토하기'}</button></td></tr>`).join('')||`<tr><td colspan="${headers.length+2}">${empty('해당 항목이 없습니다.')}</td></tr>`}</tbody></table></div>`);}
  function render(){const metrics=record(snapshot.metrics);html('#opsKpis',defs.map(([key,label,ico])=>{const m=record(metrics[key]);return `<div class="card kpi"><div class="label">${icon(ico,20)}${E(label)}</div><div class="kpiBody"><div><strong class="value">${m.value===null?'—':E(m.display??fmt(m.value))}</strong><span class="delta ${Number(m.delta)<0?'green':'red'}">${E(pct(m.delta))}</span><small>${E(m.note||'선택 기간 기준')}</small></div>${sparkline(m.spark)}</div></div>`;}).join(''));put('#reviewCount',list(snapshot.review).length);put('#failCount',list(snapshot.failures).length);
   table('reviewTable',list(snapshot.review),'event',['시간','제목 / 이벤트 요약','종목','상태']);table('failTable',list(snapshot.failures),'run',['시간','문서 제목','오류 유형','상태']);table('citationTable',list(snapshot.citations),'event',['시간','제목','문제 유형','상태']);table('dupTable',list(snapshot.duplicates),'event',['시간','이벤트 요약','종목','상태']);table('reportTable',list(snapshot.reports),'report',['시간','신고 내용','구분','상태']);
   const reviewButtons=$$('.main section.card > div:first-child > button');reviewButtons.forEach((b,i)=>{b.dataset.opsExpand=['reviewTable','failTable'][i]||'reviewTable';});
  }
  async function load(){const v=++generation;const data=record(await rpc('sb_reference_ops',{p:{range,start:customStart||null,end:customEnd||null}}));if(v!==generation)return;snapshot=data;render();if(view)await showView(view);}
  async function showView(which:string){view=which;let content='';if(which==='audit'){const rows=list(await api('/v1/ops/audit?limit=100'));content=`<h2>감사 로그</h2><div class="tableScroll"><table class="table"><thead><tr><th>시각</th><th>작업</th><th>대상</th><th>사유</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${E(dateTime(r.created_at))}</td><td>${E(r.action)}</td><td>${E(r.target_id)}</td><td>${E(record(r.details).reason)}</td></tr>`).join('')}</tbody></table></div>`;}
   else if(which==='data'){const docs=list(await api('/v1/ops/documents?limit=100'));content=`<h2>데이터 관리</h2><p class="sub">원문과 분석 실행 이력을 확인하세요.</p>${docs.map(d=>`<a class="searchOption" href="/ops/documents/${E(d.id)}"><span><strong>${E(d.title)}</strong><small>${E(d.provider)} · ${E(d.state)}</small></span>${icon('arrow')}</a>`).join('')||empty('수집된 문서가 없습니다.')}`;}
   else if(which==='model'){const queues=record(await api('/v1/ops/queues'));content=`<h2>모델 및 분석 실행</h2><p class="sub">실제 기록된 실행만 표시합니다. 모델 변경은 코드와 서버 환경 설정에 따라 적용됩니다.</p>${list(queues.failed_runs).map(r=>`<a class="searchOption" href="/ops/runs/${E(r.id)}"><span><strong>${E(r.model)} · ${E(r.status)}</strong><small>프롬프트 ${E(r.prompt_version)} · ${E(r.error_code)}</small></span></a>`).join('')||empty('기록된 실패 실행이 없습니다.')}`;}
   else if(which==='users'){const users=list(await rpc('sb_reference_users'));content=`<h2>사용자 관리</h2><p class="sub">운영에 필요한 최소 정보입니다. 사용자 권한 상승이나 삭제는 이 화면에서 수행하지 않습니다.</p><table class="table"><thead><tr><th>표시 이름</th><th>가입일</th><th>설정 완료</th></tr></thead><tbody>${users.map(u=>`<tr><td>${E(u.display_name)}</td><td>${E(dateTime(u.created_at))}</td><td>${u.onboarding_completed?'완료':'진행 중'}</td></tr>`).join('')}</tbody></table>`;}
   if(content){html('#opsView',`<section class="card cardPad">${content}</section>`);$('#opsView').scrollIntoView({block:'start'});}}
  delegate('click','[data-route]',(b,event)=>{const which=b.dataset.route;if(which&&['data','model','users','audit'].includes(which)){event.preventDefault();void run(()=>showView(which));}});
  delegate('click','[data-range]',b=>{if(b.dataset.range==='custom'){modal('운영 집계 기간',`<form id="opsRangeForm"><label class="dialogField">시작일<input id="opsStart" type="date" required value="${koreaDate(Date.now()-7*864e5)}"></label><label class="dialogField">종료일<input id="opsEnd" type="date" required value="${koreaDate()}"></label><p class="small muted">최대 90일의 실제 기록을 집계합니다.</p><button class="btn primary" type="submit">적용</button></form>`);on('#opsRangeForm','submit',e=>{e.preventDefault();customStart=$<HTMLInputElement>('#opsStart').value;customEnd=$<HTMLInputElement>('#opsEnd').value;range='custom';root.querySelector<HTMLDialogElement>('#referenceDialog')?.close();void run(load);});}else{range=b.dataset.range||'24h';$$('[data-range]').forEach(x=>x.classList.toggle('active',x===b));void run(load,b);}});
  const filterTable=(id:string)=>{const input=root.querySelector<HTMLInputElement>(`[data-filter-table="${id}"]`),select=root.querySelector<HTMLSelectElement>(`[data-state-table="${id}"]`);$$(`#${id} tbody tr[data-search-text]`).forEach(r=>{r.hidden=!!(input?.value&&!text(r.dataset.searchText).toLowerCase().includes(input.value.toLowerCase()))||!!(select?.value&&r.dataset.rowState!==select.value);});};delegate('input','[data-filter-table]',b=>filterTable(text(b.dataset.filterTable)));delegate('change','[data-state-table]',b=>filterTable(text(b.dataset.stateTable)));delegate('change','[data-check-all]',b=>{$$<HTMLInputElement>(`#${b.dataset.checkAll} tbody tr:not([hidden]) input`).forEach(x=>x.checked=(b as HTMLInputElement).checked);});
  delegate('click','[data-ops-expand]',b=>{const target=$('#'+text(b.dataset.opsExpand));target.closest('section')?.classList.toggle('expandedTable');target.scrollIntoView({block:'center'});});
  delegate('click','[data-ops-review]',b=>{const id=b.dataset.opsReview??'',kind=b.dataset.opsKind??'';if(kind==='run'){ctx.go('/ops/runs/'+id);return;}const item=[...list(snapshot.review),...list(snapshot.citations),...list(snapshot.duplicates),...list(snapshot.reports)].find(x=>x.id===id)??{};
   modal(kind==='report'?'사용자 의견 검토':'이벤트 검토',`<p class="sub">${E(item.title||item.comment)}</p>${item.document_id?`<a class="btn" href="/ops/documents/${E(item.document_id)}">원문과 검증 이력 확인 →</a>`:''}<label class="dialogField">검토 사유 (5자 이상)<textarea id="reviewReason" required minlength="5" maxlength="500"></textarea></label><div class="buttonPair">${(kind==='report'?[['resolve_report','검토 완료']]:[['approve','승인'],['reject','거절'],['rerun','재분석 요청']]).map(([action,label])=>`<button class="btn ${action==='approve'?'primary':''}" data-review-action="${action}" data-id="${E(id)}">${label}</button>`).join('')}</div><p class="dataNote">승인은 근거 검증을 우회하지 않습니다. 재분석 요청은 Worker 연결 후 실행됩니다.</p>`);
  });
  delegate('click','[data-review-action]',b=>{void run(async()=>{const reason=$<HTMLTextAreaElement>('#reviewReason').value.trim();if(reason.length<5)throw new Error('검토 사유를 5자 이상 입력하세요.');const action=b.dataset.reviewAction,id=b.dataset.id;if(action==='resolve_report')await api(`/v1/ops/reports/${encodeURIComponent(text(id))}/resolve`,'POST');else await api(`/v1/ops/events/${encodeURIComponent(text(id))}/action`,'POST',{action,reason});root.querySelector<HTMLDialogElement>('#referenceDialog')?.close();await load();toast('운영 작업을 기록했습니다.');},b);});
  await load();
 }
 const initializers:Record<string,()=>Promise<void>>={landing:initLanding,onboarding:initOnboarding,setup:initSetup,today:initToday,detail:initDetail,timeline:initTimeline,chat:initChat,calendar:initCalendar,alerts:initAlerts,ops:initOps};
 const pending=initializers[screen]?.();pending?.catch(e=>{if(abort.signal.aborted||silentNavigationError(e))return;toast(e);const target=root.querySelector('.main');if(target){const notice=document.createElement('div');notice.className='referenceError';notice.setAttribute('role','alert');notice.textContent=message(e);const retry=document.createElement('button');retry.className='btn sm';retry.textContent='다시 시도';retry.onclick=()=>location.reload();notice.append(retry);target.prepend(notice);}});
 return ()=>{abort.abort();clearTimeout(toastTimer);timers.forEach(clearTimeout);root.querySelector<HTMLDialogElement>('#referenceDialog')?.close();};
}
