import MarketingLayout,{ClosingBanner} from '@/components/marketing/layout';
import {DesignCard,DesignHeading,DesignHero} from '@/components/marketing/design';
import {WalkthroughButton} from '@/components/marketing/interactive';
export const metadata={title:'고객 사례',description:'SignalBrief의 서비스 활용 흐름과 검증된 고객 사례 게시 원칙을 확인하세요.'};
const examples=[['매일의 변화','관심 기업의 새 공시에서 중요한 사실을 읽고, 다음으로 확인할 내용을 정리합니다.','매일 확인하는 투자자'],['보유종목의 맥락','보유종목에 관련된 이벤트를 모아 타임라인에서 이전과 현재의 흐름을 살펴봅니다.','여러 종목을 관리하는 투자자'],['원문에서 확인','요약을 읽고 궁금한 내용을 질문한 뒤 연결된 인용 근거에서 맥락을 확인합니다.','근거를 확인하는 투자자'],['다음 확인을 준비','확인된 일정과 직접 등록한 일정을 관리하고, 새 이벤트와 알림을 확인합니다.','확인 루틴을 만드는 투자자']];
export default function Customers(){return <MarketingLayout current="/customers"><DesignHero eyebrow="CUSTOMERS & EVERYDAY USE" title={<>투자 정보를 읽는,<br/><em>나만의 루틴.</em></>} art={<article className="d-featured-quote public-info-card"><span className="d-quote-symbol">“</span><h2>요약에서 시작해,<br/>원문에서 확인하세요.</h2><p>내 종목의 사실, 변화와 근거를 하나의 흐름으로 읽는 활용 예시입니다.</p><div className="d-quote-person"><span className="d-avatar">S</span><div><strong>SignalBrief 활용 안내</strong><small>실제 고객 후기나 투자 성과가 아닙니다.</small></div></div><WalkthroughButton/></article>} secondary={{href:'#examples',label:'활용 예시 살펴보기'}}>검증된 공식 고객 사례를 준비하고 있습니다. 먼저 서비스가 투자 정보 탐색에 어떻게 쓰이는지 살펴보세요.</DesignHero>
 <div className="d-band"><div className="public-info-container d-metrics">{[['FACT','확인한 사실'],['CHANGE','이전과의 차이'],['EVIDENCE','연결된 원문'],['ROUTINE','다음 확인']].map(([label,text])=><div key={label}><strong>{label}</strong><span>{text}</span></div>)}</div></div>
 <div className="public-info-container d-content"><section id="examples"><DesignHeading eyebrow="SERVICE EXAMPLES" title="이렇게 활용할 수 있습니다">다음 내용은 서비스의 사용 흐름을 설명하는 예시입니다.</DesignHeading><div className="d-quotes-grid">{examples.map(([title,copy,role],i)=><article className="d-use-quote public-info-card" key={title}><span className="d-avatar">{i+1}</span><div><h3>{title}</h3><p>{copy}</p><strong>{role}</strong><small>활용 예시 · 실제 고객 후기가 아닙니다</small></div></article>)}</div></section>
 <section><DesignHeading eyebrow="OUR PROMISE" title="고객 사례는 사실과 동의를 바탕으로"/><div className="d-card-grid"><DesignCard icon="user" title="사용자 동의" href="/privacy">실제 사용자의 사전 동의와 공개 범위를 확인한 뒤 게시합니다.</DesignCard><DesignCard icon="shield" title="검증된 경험" href="/sources">확인 가능한 사용 경험만 소개하고, 투자 수익률이나 성과를 보장하지 않습니다.</DesignCard><DesignCard icon="grid" title="직접 경험하기" href="/features">실제 동작하는 화면 예시에서 기능을 살펴보고 나만의 브리핑을 시작하세요.</DesignCard></div></section>
 <ClosingBanner title="나만의 투자 정보 루틴을 시작하세요.">공시의 사실과 변화를 읽고, 원문에서 확인하는 시간을 만들어 보세요.</ClosingBanner></div></MarketingLayout>;}
