// @vitest-environment jsdom
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {z} from 'zod';
import type {AnchorHTMLAttributes,ReactNode} from 'react';
import MobileCalendar,{calendarDateKey} from '../src/mobile/calendar';
import MobileNotifications from '../src/mobile/notifications';
import MobileAlerts,{notificationDateGroup} from '../src/mobile/alerts';
import {defaults} from '../src/workspace/contracts';

const mocks=vi.hoisted(()=>({request:vi.fn(),workspace:vi.fn(),rpc:vi.fn(),prefSave:vi.fn(),badge:vi.fn(),text:(ko:string)=>ko,resource:vi.fn(),prefs:{} as Record<string,unknown>}));
vi.mock('next/link',()=>({default:({children,href,...rest}:AnchorHTMLAttributes<HTMLAnchorElement>)=><a href={href} {...rest}>{children}</a>}));
vi.mock('@/components/auth',()=>({useAuth:()=>({token:'synthetic-only',me:{id:'test-user'}})}));
vi.mock('@/mobile/shell',()=>({useMobileAlertBadge:()=>mocks.badge}));
vi.mock('@/components/ui',async()=>{const {useCallback,useState}=await import('react');return {useResource:(path:string)=>{const [,setVersion]=useState(0),reload=useCallback(()=>setVersion(n=>n+1),[]);return {data:mocks.resource(path),loading:false,error:null,reload};}};});
vi.mock('@/workspace/preferences',async()=>{const {useState}=await import('react');return {usePrefs:()=>{const [value,setValue]=useState(mocks.prefs);return {value,loaded:true,busy:false,error:'',reload:vi.fn(),text:mocks.text,date:(iso:string)=>iso,save:async(patch:Record<string,unknown>)=>{await mocks.prefSave(patch);mocks.prefs={...mocks.prefs,...patch};setValue(mocks.prefs);}};}};});
vi.mock('@/workspace/client',()=>({workspace:(...args:unknown[])=>mocks.workspace(...args)}));
vi.mock('@/lib/api',async original=>({...await original<typeof import('../src/lib/api')>(),request:(...args:unknown[])=>mocks.request(...args)}));
vi.mock('@/lib/supabase',()=>({initializeSupabase:async()=>({rpc:(_name:string,args:unknown)=>({abortSignal:()=>mocks.rpc(args)})})}));
vi.mock('@/mobile/ui',()=>({
 MIcon:()=>null,CompanyLogo:()=>null,
 ActionNotice:({action}:{action:{error:string;success?:string}})=><>{action.error&&<p role="alert">{action.error}</p>}{action.success&&<p role="status">{action.success}</p>}</>,
 EmptyState:({title,description}:{title:string;description?:string})=><section><strong>{title}</strong><p>{description}</p></section>,
 LoadState:({loading,error}:{loading:boolean;error?:string})=><>{loading&&<span role="status">Loading</span>}{error&&<span role="alert">{error}</span>}</>,
 Dialog:({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void})=><section role="dialog" aria-label={title}><h2>{title}</h2><button onClick={onClose}>닫기</button>{children}</section>,
 eventLabel:(type:string)=>({earnings:'실적',dividend:'배당'}[type]??type),relativeTime:()=> '2시간 전',
}));
const a={id:'20000000-0000-4000-8000-000000000001',name:'Synthetic Alpha',ticker:'TESTA',market:'NASDAQ',provider:'sec',is_demo:false,last_ingested_at:null},b={...a,id:'20000000-0000-4000-8000-000000000002',name:'Synthetic Beta',ticker:'TESTB'};
const events=[{id:'e1',company:a,event_type:'earnings',headline:'Synthetic earnings',fact_summary:'Synthetic source summary',what_happened:'Synthetic change'},{id:'e2',company:b,event_type:'dividend',headline:'Synthetic dividend',fact_summary:'Synthetic source',what_happened:'Synthetic change'}];
let calendar:{id:string;title:string;occurs_on:string;company_id:string|null;event_id:string|null;origin:string;quote:string|null;source_url:string|null;is_demo:boolean}[],notices:{id:string;read_at:string|null;created_at:string;event:typeof events[number]}[],rules:{id:string;name:string;event_types:string[];min_score:number;enabled:boolean;created_at:string}[],base:{realtime_enabled:boolean;notify_min_score:number},saved:Set<string>;
beforeEach(()=>{
 vi.clearAllMocks();vi.spyOn(Date,'now').mockReturnValue(Date.parse('2026-10-06T05:00:00Z'));mocks.prefs={...defaults,quiet_enabled:true,daily_cap:3};base={realtime_enabled:true,notify_min_score:.75};saved=new Set(['c1']);
 calendar=[{id:'c1',title:'Synthetic Alpha review',occurs_on:'2026-10-06',company_id:a.id,event_id:'e1',origin:'official',quote:'Synthetic official source date',source_url:'https://example.com/source',is_demo:false},{id:'c2',title:'Synthetic personal date',occurs_on:'2026-10-07',company_id:null,event_id:null,origin:'user',quote:null,source_url:null,is_demo:false}];
 notices=events.map((event,i)=>({id:`n${i+1}`,event,read_at:null,created_at:`2026-10-0${6-i}T02:00:00Z`}));rules=[{id:'r1',name:'Synthetic rule',event_types:['earnings'],min_score:.4,enabled:true,created_at:'2026-10-01T00:00:00Z'}];
 mocks.resource.mockImplementation((path:string)=>path?.startsWith('/v1/calendar?')?calendar.filter(item=>{const p=new URLSearchParams(path.split('?')[1]);return item.occurs_on>=p.get('from_date')!&&item.occurs_on<=p.get('until_date')!;}):path==='/v1/watchlist'?{items:[a]}:path==='/v1/portfolio'?{positions:[{company:a}]}:path?.startsWith('/v1/feed?')?{items:events}:path?.startsWith('/v1/notifications')?notices:path==='/v1/alerts'?rules:path?.startsWith('/v1/companies')?[a,b]:null);
 mocks.prefSave.mockResolvedValue(undefined);
 mocks.workspace.mockImplementation(async(_token,req:{action:string;p:Record<string,unknown>},schema:z.ZodType<unknown>)=>{if(req.action==='notifications')return schema.parse(base);if(req.action==='notification_save'){base={...base,...req.p};return schema.parse(base);}if(req.action==='catalog')return {items:[{id:a.id,title:a.name,ticker:a.ticker},{id:b.id,title:b.name,ticker:b.ticker}]};throw new Error('Unexpected workspace action');});
 mocks.rpc.mockImplementation(async({p}:{p:{action:string;calendar_id:string;enabled:boolean}})=>{if(p.action==='list')return {data:[...saved].map(calendar_id=>({calendar_id})),error:null};if(p.enabled)saved.add(p.calendar_id);else saved.delete(p.calendar_id);return {data:{saved:true,delivery:'saved_interest_only'},error:null};});
 mocks.request.mockImplementation(async(path:string,_token:unknown,_schema:unknown,init:RequestInit)=>{if(path.includes('/notifications/')){const id=path.split('/')[3];notices=notices.map(n=>id==='all'||n.id===id?{...n,read_at:'2026-10-06T05:00:00Z'}:n);return;}if(path==='/v1/calendar'){const value=JSON.parse(String(init.body));const item={...calendar[1],id:'new',...value};calendar=[...calendar,item];return item;}if(path.startsWith('/v1/calendar/')){calendar=calendar.filter(item=>item.id!==path.split('/').at(-1));return;}if(path==='/v1/alerts/r1'){if(init.method==='DELETE'){rules=[];return;}rules=rules.map(rule=>({...rule,...JSON.parse(String(init.body))}));return rules[0];}throw new Error('Unexpected API request');});
});
afterEach(()=>{cleanup();vi.restoreAllMocks();});

describe('mobile notification policies persist actual settings',()=>{
 it('keeps exact saved values, and unavailable delivery controls disabled',async()=>{render(<MobileNotifications/>);await waitFor(()=>expect(screen.getByRole('switch',{name:'앱 내 알림'}).getAttribute('aria-checked')).toBe('true'));expect((screen.getByRole('slider',{name:'중요도 임계값'}) as HTMLInputElement).value).toBe('.75'.replace(/^\./,'0.'));expect((screen.getByRole('slider',{name:'일일 최대 알림 수'}) as HTMLInputElement).value).toBe('3');expect((screen.getByRole('switch',{name:'이메일 알림 — 미제공'}) as HTMLButtonElement).disabled).toBe(true);expect(mocks.workspace.mock.calls.every(call=>call[1].action!=='notification_save')).toBe(true);});
 it('does not flip an in-app switch when the server rejects the write',async()=>{render(<MobileNotifications/>);const toggle=await screen.findByRole('switch',{name:'앱 내 알림'});await waitFor(()=>expect(toggle.getAttribute('aria-checked')).toBe('true'));mocks.workspace.mockRejectedValueOnce(new Error('설정 저장 실패'));fireEvent.click(toggle);await screen.findByRole('alert');expect(toggle.getAttribute('aria-checked')).toBe('true');expect(base.realtime_enabled).toBe(true);});
 it('saves in-app settings and reads them after remount',async()=>{const view=render(<MobileNotifications/>);await waitFor(()=>expect(screen.getByRole('switch',{name:'앱 내 알림'}).getAttribute('aria-checked')).toBe('true'));fireEvent.click(screen.getByRole('switch',{name:'앱 내 알림'}));await waitFor(()=>expect(base.realtime_enabled).toBe(false));view.unmount();render(<MobileNotifications/>);await waitFor(()=>expect(screen.getByRole('switch',{name:'앱 내 알림'}).getAttribute('aria-checked')).toBe('false'));});
 it('only persists explicitly applied sliders and retains them after remount',async()=>{const view=render(<MobileNotifications/>);await waitFor(()=>expect((screen.getByRole('slider',{name:'중요도 임계값'}) as HTMLInputElement).disabled).toBe(false));fireEvent.change(screen.getByRole('slider',{name:'중요도 임계값'}),{target:{value:'.63'}});expect(base.notify_min_score).toBe(.75);fireEvent.click(screen.getByRole('button',{name:'기준 적용'}));await waitFor(()=>expect(base.notify_min_score).toBe(.63));fireEvent.change(screen.getByRole('slider',{name:'일일 최대 알림 수'}),{target:{value:'17'}});fireEvent.click(screen.getByRole('button',{name:'최대 수 적용'}));await waitFor(()=>expect(mocks.prefs.daily_cap).toBe(17));view.unmount();render(<MobileNotifications/>);await waitFor(()=>expect((screen.getByRole('slider',{name:'중요도 임계값'}) as HTMLInputElement).value).toBe('0.63'));expect((screen.getByRole('slider',{name:'일일 최대 알림 수'}) as HTMLInputElement).value).toBe('17');});
 it('failed quiet-hour save leaves the persisted policy and switch intact',async()=>{render(<MobileNotifications/>);await screen.findByRole('switch',{name:'방해 금지 시간'});mocks.prefSave.mockRejectedValueOnce(new Error('시간 저장 실패'));fireEvent.click(screen.getByRole('switch',{name:'방해 금지 시간'}));await screen.findByRole('alert');expect(screen.getByRole('switch',{name:'방해 금지 시간'}).getAttribute('aria-checked')).toBe('true');expect(mocks.prefs.quiet_enabled).toBe(true);});
 it('persists muted companies through the real preference field',async()=>{const view=render(<MobileNotifications/>);fireEvent.click(screen.getByRole('button',{name:'기업 추가하기'}));const dialog=await screen.findByRole('dialog');fireEvent.click(await within(dialog).findByRole('button',{name:'Synthetic Beta · TESTB'}));await waitFor(()=>expect(mocks.prefs.muted_companies).toEqual([b.id]));view.unmount();render(<MobileNotifications/>);await screen.findByRole('button',{name:'Synthetic Beta 알림 제외 해제'});});
 it('reports partial reset and does not show full reset success when the second store fails',async()=>{render(<MobileNotifications/>);await waitFor(()=>expect((screen.getByRole('button',{name:'설정 초기화'}) as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByRole('button',{name:'설정 초기화'}));mocks.prefSave.mockRejectedValueOnce(new Error('동시 변경 충돌'));fireEvent.click(screen.getByRole('button',{name:'초기화 적용'}));await waitFor(()=>expect(screen.getAllByRole('alert')[0].textContent).toContain('나머지 정책은 저장하지 못했습니다'));expect(base.realtime_enabled).toBe(false);expect(mocks.prefs.quiet_enabled).toBe(true);expect(screen.queryByText('알림 정책을 초기화했습니다.')).toBeNull();});
});

describe('mobile calendar date precision and persisted reminder bindings',()=>{
 it('honors the preference time zone without reinterpreting date-only sources',()=>{expect(calendarDateKey(Date.parse('2026-10-01T01:00:00Z'),'America/Los_Angeles')).toBe('2026-09-30');expect(calendarDateKey(Date.parse('2026-10-01T01:00:00Z'),'Asia/Seoul')).toBe('2026-10-01');});
 it('loads saved bindings and persists their removal across remount',async()=>{const view=render(<MobileCalendar/>),name='Synthetic Alpha review 관심 일정';await waitFor(()=>expect(screen.getByRole('switch',{name}).getAttribute('aria-checked')).toBe('true'));fireEvent.click(screen.getByRole('switch',{name}));await waitFor(()=>expect(saved.has('c1')).toBe(false));expect(mocks.rpc).toHaveBeenCalledWith({p:{action:'set',calendar_id:'c1',enabled:false}});view.unmount();render(<MobileCalendar/>);await waitFor(()=>expect((screen.getByRole('switch',{name}) as HTMLButtonElement).disabled).toBe(false));expect(screen.getByRole('switch',{name}).getAttribute('aria-checked')).toBe('false');expect(screen.getAllByText('종일').length).toBe(2);expect(screen.getByRole('link',{name:'Synthetic Alpha review'}).getAttribute('href')).toBe('/events/e1');});
 it('keeps reminder selection after a rejected save and permits retry',async()=>{render(<MobileCalendar/>);const name='Synthetic Alpha review 관심 일정';await waitFor(()=>expect((screen.getByRole('switch',{name}) as HTMLButtonElement).disabled).toBe(false));mocks.rpc.mockResolvedValueOnce({data:null,error:{message:'denied'}});fireEvent.click(screen.getByRole('switch',{name}));await screen.findByRole('alert');expect(screen.getByRole('switch',{name}).getAttribute('aria-checked')).toBe('true');expect(saved.has('c1')).toBe(true);});
 it('does not treat a failed reminder read as an empty saved list',async()=>{mocks.rpc.mockResolvedValueOnce({data:null,error:{message:'read_failed'}});render(<MobileCalendar/>);await screen.findByRole('alert');expect((screen.getByRole('switch',{name:'Synthetic Alpha review 관심 일정'}) as HTMLButtonElement).disabled).toBe(true);expect(mocks.rpc).toHaveBeenCalledTimes(1);});
 it('queries a complete seven-day range across the end of a month',async()=>{vi.spyOn(Date,'now').mockReturnValue(Date.parse('2026-10-31T05:00:00Z'));calendar=[{...calendar[0],occurs_on:'2026-11-02'}];render(<MobileCalendar/>);await waitFor(()=>expect(mocks.resource).toHaveBeenCalledWith('/v1/calendar?from_date=2026-10-31&until_date=2026-11-06'));fireEvent.click(screen.getByRole('button',{name:'주간 일정 보기'}));await screen.findByRole('link',{name:'Synthetic Alpha review'});});
 it('does not close or acknowledge a failed date creation',async()=>{render(<MobileCalendar/>);fireEvent.click(screen.getByRole('button',{name:'일정 추가'}));fireEvent.change(screen.getByLabelText('제목'),{target:{value:'Synthetic new date'}});mocks.request.mockRejectedValueOnce(new Error('일정 저장 실패'));fireEvent.click(screen.getByRole('button',{name:'일정 저장'}));await waitFor(()=>expect(screen.getAllByRole('alert').length).toBeGreaterThan(0));expect(screen.getByRole('dialog')).toBeTruthy();expect(calendar).toHaveLength(2);});
});

describe('mobile notification center derives real groups and read state',()=>{
 it('groups midnight timestamps by user timezone and calendar week',()=>{const now=Date.parse('2026-10-06T01:00:00Z');expect(notificationDateGroup('2026-10-05T23:30:00Z',now,'Asia/Seoul')).toBe('today');expect(notificationDateGroup('2026-10-05T23:30:00Z',now,'America/Los_Angeles')).toBe('today');expect(notificationDateGroup('2026-10-04T12:00:00Z',now,'Asia/Seoul')).toBe('older');});
 it('filters holdings, event type and period using actual event-backed notifications',()=>{render(<MobileAlerts/>);fireEvent.click(screen.getByRole('button',{name:'포트폴리오 (1)'}));expect(screen.getByRole('link',{name:'Synthetic earnings'})).toBeTruthy();expect(screen.queryByRole('link',{name:'Synthetic dividend'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'전체 (2)'}));fireEvent.change(screen.getByRole('combobox',{name:'알림 유형 필터'}),{target:{value:'dividend'}});expect(screen.getByRole('link',{name:'Synthetic dividend'})).toBeTruthy();fireEvent.change(screen.getByRole('combobox',{name:'알림 기간 필터'}),{target:{value:'today'}});expect(screen.queryByRole('link',{name:'Synthetic dividend'})).toBeNull();});
 it('keeps an unread notification and badge on write failure',async()=>{render(<MobileAlerts/>);mocks.request.mockRejectedValueOnce(new Error('읽음 저장 실패'));fireEvent.click(screen.getByRole('button',{name:'Synthetic earnings 읽음으로 표시'}));await screen.findByRole('alert');expect(screen.getByRole('button',{name:'Synthetic earnings 읽음으로 표시'})).toBeTruthy();expect(notices[0].read_at).toBeNull();expect(mocks.badge).toHaveBeenLastCalledWith(2);});
 it('marks all read, updates shell badge, and reloads persisted read state',async()=>{const view=render(<MobileAlerts/>);fireEvent.click(screen.getByRole('button',{name:'모두 확인하기'}));await waitFor(()=>expect(mocks.badge).toHaveBeenLastCalledWith(0));expect(notices.every(item=>item.read_at)).toBe(true);view.unmount();render(<MobileAlerts/>);expect(screen.getByRole('button',{name:'읽지 않음 (0)'})).toBeTruthy();expect((screen.getByRole('button',{name:'모두 확인하기'}) as HTMLButtonElement).disabled).toBe(true);});
 it('keeps persisted rule enabled when an update is rejected',async()=>{render(<MobileAlerts/>);fireEvent.click(screen.getByRole('button',{name:'알림 규칙 관리'}));mocks.request.mockRejectedValueOnce(new Error('규칙 저장 실패'));fireEvent.click(screen.getByRole('switch',{name:'Synthetic rule 사용'}));await screen.findByRole('alert');expect(screen.getByRole('switch',{name:'Synthetic rule 사용'}).getAttribute('aria-checked')).toBe('true');expect(rules[0].enabled).toBe(true);});
});
