import { describe,it,expect,vi } from 'vitest';
import { polishReference,googleMark } from '../src/reference/publication';
import type { ReferenceContext } from '../src/reference/controller';
const context=():ReferenceContext=>({user:null,api:vi.fn(),rpc:vi.fn(),go:vi.fn(),auth:vi.fn(),download:vi.fn(),demo:false});
describe('publication refinements',()=>{
 it('adds a verifiable release identity',()=>{const root=document.createElement('div');polishReference(root,'today',context());expect(root.dataset.uiRelease).toBe('reference-screen-r2');});
 it('labels search inputs',()=>{const root=document.createElement('div');root.innerHTML='<input id="globalSearch"><input id="stockSearch">';polishReference(root,'setup',context());expect(root.querySelector('#globalSearch')?.getAttribute('aria-label')).toBe('기업 검색');});
 it('activates inherited role controls with Space and removes handlers on unmount',()=>{const root=document.createElement('div');root.innerHTML='<span role="button" tabindex="0">Services</span>';const span=root.firstElementChild!,click=vi.fn();span.addEventListener('click',click);const unmount=polishReference(root,'today',context());span.dispatchEvent(new KeyboardEvent('keydown',{key:' ',bubbles:true}));expect(click).toHaveBeenCalledTimes(1);unmount();span.dispatchEvent(new KeyboardEvent('keydown',{key:' ',bubbles:true}));expect(click).toHaveBeenCalledTimes(1);});
 it('does not double-activate native buttons',()=>{const root=document.createElement('div');root.innerHTML='<button role="button">Native</button>';const click=vi.fn();root.firstElementChild!.addEventListener('click',click);polishReference(root,'today',context());root.firstElementChild!.dispatchEvent(new KeyboardEvent('keydown',{key:' ',bubbles:true}));expect(click).not.toHaveBeenCalled();});
 it('keeps preview links real and marks the preview illustrative',()=>{const root=document.createElement('div');root.innerHTML='<div class="productShot"></div>';polishReference(root,'landing',context());expect(root.querySelectorAll('.publicationPreview nav a')).toHaveLength(6);expect(root.innerHTML).not.toContain('href="#"');expect(root.textContent).toContain('실시간 데이터 아님');expect(root.textContent).not.toMatch(/78,500|52,320,000|1,200만|300,000/);});
 it('preserves the original Google auth handler',()=>{const root=document.createElement('div');root.innerHTML='<button id="googleLogin">G</button>';const click=vi.fn();root.firstElementChild!.addEventListener('click',click);polishReference(root,'landing',context());(root.firstElementChild as HTMLButtonElement).click();expect(click).toHaveBeenCalledTimes(1);expect(root.querySelector('svg')).toBeTruthy();expect(googleMark).not.toContain('script');});
 it('never invents an operator identity',()=>{const root=document.createElement('div');root.innerHTML='<div class="profile"><strong>Authenticated user</strong></div>';polishReference(root,'ops',context());expect(root.textContent).toBe('Authenticated user');});
});
