import Link from 'next/link';
import type {ReactNode} from 'react';
import {Brand,PublicFooter} from './marketing/layout';
import MarketingHeader from './marketing/header';
import {ScreenshotPreview,VisualIcon} from './marketing/screenshot-preview';
import {Handnote} from './marketing/reference-pages';
import './marketing/screenshot-design.css';

export default function AuthLayout({children,recovery=false,passwordReset=false,mode='login'}:{children:ReactNode;recovery?:boolean;passwordReset?:boolean;mode?:'login'|'signup'}){
 const variant=passwordReset?'password-reset':recovery?'recovery':mode;
 return <div className={'reference-auth v-account is-'+variant} data-design="prelogin-20261005"><a href="#account-main" className="public-info-skip">본문으로 건너뛰기</a>{recovery?<MarketingHeader current="/"/>:<header className="v-auth-header"><div className="v-container"><Brand/><div>{mode==='login'?<><span>처음이신가요?</span><Link href="/signup" className="public-info-button secondary">회원가입</Link></>:<Link href="/login">로그인</Link>}</div></div></header>}<main className="reference-auth-grid" id="account-main"><div className="v-background-bars" aria-hidden="true"/>{recovery&&<Handnote>좋은 투자에는<br/>더 좋은 정보가 필요합니다.</Handnote>}{passwordReset&&<Link className="v-back-login" href="/login">← 로그인으로 돌아가기</Link>}<aside className="reference-auth-story" aria-label="SignalBrief 소개"><p className="v-eyebrow">{mode==='signup'?'데이터가 만드는 더 나은 투자':'더 나은 투자, 데이터로부터'}</p><h2>{passwordReset?<>더 안전한<br/>투자 여정을 위해</>:mode==='signup'?<>누구나 쉽게,<br/>더 나은 투자 습관을</>:<>중요한 투자 변화를<br/>더 빠르게, 더 정확하게</>}</h2><p className="v-auth-intro">{passwordReset?<>회원님의 소중한 정보는<br/>계정별 접근 권한으로 보호합니다.</>:mode==='signup'?<>SignalBrief와 함께라면 복잡한 데이터를<br/>간단하고 명확한 인사이트로 확인할 수 있습니다.<br/>지금, 더 스마트한 투자를 시작해 보세요.</>:<>SignalBrief는 공시와 기업 자료를 AI가 분석해<br/>핵심만 선별하여, 투자 판단에 필요한 근거를<br/>빠르고 정확하게 제공합니다.</>}</p><div className="v-auth-benefits">{(passwordReset?['계정별 접근 보호','개인정보 보호','더 안전한 투자 환경']:mode==='signup'?['AI가 분석한 핵심 인사이트','복잡한 정보를 쉽고 빠르게','누구나 시작할 수 있는 투자 파트너']:['시간을 아끼는 요약','신뢰할 수 있는 데이터','더 나은 투자 습관']).map((title,i)=><div className="reference-auth-benefit" key={title}><VisualIcon name={(passwordReset?['shield','lock','user'] as const:mode==='signup'?['bars','spark','user'] as const:['spark','bars','shield'] as const)[i]} tone={!passwordReset&&i<2?'teal':'blue'}/><div><h3>{title}</h3>{mode!=='signup'&&<p>{(passwordReset?['소중한 데이터에 접근 권한을 적용합니다.','인증과 동의 설정을 확인할 수 있습니다.','원문 근거와 함께 서비스를 이용하세요.']:['복잡한 정보를 한눈에 정리해 더 중요한 것에 집중할 수 있습니다.','공식 원문과 검증 가능한 인용을 바탕으로 정보를 확인합니다.','데이터에 기반한 인사이트로 지속 가능한 투자 습관을 돕습니다.'])[i]}</p>}</div></div>)}</div>{!recovery&&<><div className="reference-auth-preview"><ScreenshotPreview kind={mode}/></div><Handnote>{mode==='signup'?<>데이터가 만드는<br/>더 좋은 투자 경험입니다.</>:<>좋은 투자에는<br/>더 좋은 정보가 필요합니다.</>}</Handnote></>}</aside><div className="v-auth-form-column">{children}</div></main><PublicFooter/></div>;
}
