"use client";
import { useEffect, useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useAuth } from "./auth";
import { getSupabase } from "@/lib/supabase";
import { siteOrigin } from "@/lib/site-url";
import { Icon } from "./icons";
export default function LoginForm() {
 const auth=useAuth(), router=useRouter(); const [mode,setMode]=useState<"login"|"signup"|"reset">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{if(auth.me)router.replace(auth.me.onboarding_completed?"/today":"/onboarding");},[auth.me,router]);
 async function run(action:()=>Promise<void>){setBusy(true);setMessage("");setError("");try{await action();}catch{setError("로그인을 완료하지 못했습니다. 계정 정보와 이메일 인증 상태를 확인하고 다시 시도해 주세요.");}finally{setBusy(false);}}
 async function submit(e:FormEvent){e.preventDefault();await run(async()=>{const supabase=getSupabase();if(mode==="login"){const result=await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;location.assign("/today");}else if(mode==="signup"){const result=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${siteOrigin(location.href,process.env.NEXT_PUBLIC_SITE_URL,process.env.NODE_ENV === "production")}/auth/callback`}});if(result.error)throw result.error;if(result.data.session)location.assign("/onboarding");else setMessage("가입 요청을 접수했습니다. 인증 메일이 도착하면 링크를 열어 주세요. 메일 발송 제한이 있으면 Google 로그인을 이용하세요.");}else{const result=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${siteOrigin(location.href,process.env.NEXT_PUBLIC_SITE_URL,process.env.NODE_ENV === "production")}/auth/callback?next=reset-password`});if(result.error)throw result.error;setMessage("해당 이메일로 복구가 가능한 경우 안내 메일이 발송됩니다.");}});}
 return <section className="login-box" aria-label="계정 로그인"><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>{mode==="signup"?"나만의 브리핑을 시작하세요":mode==="reset"?"비밀번호를 재설정하세요":"중요한 변화부터 확인하세요"}</h2><p className="muted">내 종목, 이전과의 차이, 확인 가능한 원문.</p><button className="button google full" disabled={busy} onClick={()=>run(()=>auth.googleLogin())}><span className="google-g">G</span>Google로 시작하기</button><div className="divider"><span>또는 이메일로</span></div><form className="form-stack" onSubmit={submit}><label className="field"><span>이메일</span><input autoComplete="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com" required maxLength={254}/></label>{mode!=="reset"&&<label className="field"><span>비밀번호</span><div className="password-field"><input autoComplete={mode==="signup"?"new-password":"current-password"} type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} minLength={mode==="signup"?12:1} maxLength={128} placeholder={mode==="signup"?"12자 이상 입력":"비밀번호 입력"} required/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"비밀번호 숨기기":"비밀번호 보기"}>{show?"숨김":"보기"}</button></div></label>}<button className="button primary full" disabled={busy}>{busy?"확인 중…":mode==="signup"?"계정 만들기":mode==="reset"?"복구 메일 요청":"로그인"}<Icon name="arrow" size={17}/></button></form>{error&&<p className="notice danger" role="alert">{error}</p>}{message&&<p className="notice success" role="status">{message}</p>}<div className="auth-links"><button className="text-button" onClick={()=>{setMode(mode==="signup"?"login":"signup");setError("");setMessage("");}}>{mode==="signup"?"로그인으로 돌아가기":"회원가입"}</button><button className="text-button" onClick={()=>{setMode(mode==="reset"?"login":"reset");setError("");setMessage("");}}>{mode==="reset"?"로그인으로 돌아가기":"비밀번호 찾기"}</button></div>{auth.config?.demo_mode&&<button className="button secondary full" onClick={()=>run(()=>auth.demoLogin())}>로컬 합성 데모로 시작하기</button>}{auth.config?.demo_mode&&auth.config?.demo_admin_enabled&&<button className="button secondary full" onClick={()=>run(()=>auth.demoLogin(true))}>개발용 운영자 데모</button>}<p className="login-security"><Icon name="shield" size={17}/> 개인정보는 계정별 접근 권한으로 보호합니다.</p><Link href="/privacy" className="small muted">개인정보 처리 및 서비스 범위</Link></section>;
}
