"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState, useEffect, useCallback, useRef, type ReactNode } from "react";
import { z } from "zod";
import { request,errorMessage,externalUrl,body } from "@/lib/api";
import { meSchema, companiesSchema, type EventCard } from "@/lib/contracts";
import { dateText,score,typeLabels } from "@/lib/format";
import { useAuth } from "./auth";
import { BrandMark, Icon, type IconName } from "./icons";
export function useResource<T>(path:string|null,schema:z.ZodType<T>) {
  const {token}=useAuth();const [data,setData]=useState<T|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[revision,setRevision]=useState(0);
  const reload=useCallback(()=>setRevision(v=>v+1),[]);
  useEffect(()=>{if(!token||!path){setLoading(false);setData(null);return;}const ctrl=new AbortController();let active=true;
    setLoading(true);setError(null);request(path,token,schema,{signal:ctrl.signal}).then(value=>{if(active)setData(value);}).catch(e=>{if(active)setError(errorMessage(e));}).finally(()=>{if(active)setLoading(false);});
    return ()=>{active=false;ctrl.abort();};},[token,path,schema,revision]);
  return {data,loading,error,reload};
}
export function useAction(){const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
  async function run(action:()=>Promise<unknown>,success?:string){setBusy(true);setError(null);setMessage(null);try{await action();if(success)setMessage(success);return true;}catch(e){setError(errorMessage(e));return false;}finally{setBusy(false);}}
  return {busy,error,message,run};
}
export function Loading({label="데이터를 불러오고 있습니다."}:{label?:string}){return <div className="loading" role="status"><span className="spinner"/>{label}<div className="skeleton"/><div className="skeleton narrow"/></div>;}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}){return <div className="notice danger" role="alert"><strong>확인이 필요합니다</strong><p>{message}</p>{retry&&<button className="button secondary" onClick={retry}>다시 시도</button>}</div>;}
export function ActionNotice({action}:{action:ReturnType<typeof useAction>}){return <>{action.error&&<ErrorState message={action.error}/ >}{action.message&&<div className="notice success" role="status">{action.message}</div>}</>;}
export function Empty({title,children}:{title:string;children:ReactNode}){return <div className="empty"><span className="empty-symbol" aria-hidden="true">◎</span><h2>{title}</h2><div>{children}</div></div>;}
export function PageHeading({eyebrow="SIGNALBRIEF",title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <header className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{actions&&<div>{actions}</div>}</header>;}
export function SourceLink({url,demo,label="원문 열기"}:{url:string;demo?:boolean;label?:string}){const safe=externalUrl(url);return demo||!safe ? <span className="badge muted-badge">합성 자료 · 실제 원문 아님</span> : <a href={safe} target="_blank" rel="noopener noreferrer" className="source-link">{label} <span aria-hidden="true">↗</span></a>;}
const links: [string,string,IconName][]=[["/today","오늘의 변화","home"],["/watchlist","관심종목","star"],["/portfolio","포트폴리오","pie"],["/timeline","타임라인","timeline"],["/questions","근거 질문","spark"],["/calendar","캘린더","calendar"],["/alerts","알림 센터","bell"],["/settings","설정","settings"]];
function GlobalSearch(){const modal=useRef<HTMLDialogElement>(null),input=useRef<HTMLInputElement>(null),[open,setOpen]=useState(false),[text,setText]=useState(""),[query,setQuery]=useState("");const result=useResource(open?`/v1/companies?q=${encodeURIComponent(query)}&limit=20`:null,companiesSchema);
 useEffect(()=>{const timer=setTimeout(()=>setQuery(text),250);return()=>clearTimeout(timer);},[text]);
 const show=useCallback(()=>{modal.current?.showModal();setOpen(true);setTimeout(()=>input.current?.focus(),0);},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();show();}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[show]);
 function close(){modal.current?.close();setOpen(false);}
 return <><button className="global-search" onClick={show}><Icon name="search"/><span>종목명, 종목코드로 검색하세요</span><kbd>⌘ K</kbd></button><dialog ref={modal} className="search-dialog" onClose={()=>setOpen(false)} aria-label="기업 검색"><div className="section-heading"><h2>기업 검색</h2><button aria-label="검색 닫기" className="icon-button" onClick={close}><Icon name="close"/></button></div><label className="field"><span>기업명 또는 종목코드</span><input ref={input} value={text} maxLength={100} onChange={e=>setText(e.target.value)} placeholder="예: 삼성전자, AAPL"/></label>{result.loading?<Loading/>:result.error?<ErrorState message={result.error} retry={result.reload}/>:result.data?.length?<ul className="search-results">{result.data.map(c=><li key={c.id}><Link href={`/companies/${c.id}`} onClick={close}><span className="company-token">{c.ticker.slice(0,2)}</span><span><strong>{c.name}</strong><small>{c.ticker} · {c.market}</small></span><Icon name="arrow" size={16}/></Link></li>)}</ul>:<p className="muted">일치하는 기업이 없습니다. 현재 연결된 기업 목록에서 검색합니다.</p>}</dialog></>;
}
export function AppShell({children}:{children:ReactNode}) {
 const auth=useAuth(),router=useRouter(),path=usePathname(),action=useAction(),[menu,setMenu]=useState(false);
 useEffect(()=>{if(!auth.loading&&!auth.token&&!auth.error)router.replace("/login");else if(!auth.loading&&auth.me&&!auth.me.onboarding_completed&&path!=="/onboarding")router.replace("/onboarding");},[auth.loading,auth.token,auth.me,auth.error,path,router]);
 if(auth.loading)return <main className="auth-wrap"><Loading label="세션을 확인하고 있습니다."/></main>;
 if(auth.error)return <main className="auth-wrap"><ErrorState message={auth.error} retry={()=>location.reload()}/><Link className="button secondary" href="/login">로그인으로 이동</Link></main>;
 if(!auth.me)return <main className="auth-wrap"><Loading/></main>;
 const me=auth.me;
 return <div className={`workspace ${menu?"menu-open":""}`}><a className="skip-link" href="#main">본문으로 건너뛰기</a>{menu&&<button className="menu-scrim" onClick={()=>setMenu(false)} aria-label="메뉴 닫기"/>}<aside className="sidebar"><Link className="brand" href="/today" onClick={()=>setMenu(false)}><BrandMark/><span>SignalBrief<small>근거 있는 투자, 더 나은 판단</small></span></Link><nav aria-label="주 메뉴">{links.map(([href,label,icon])=>{const active=path===href||(href==="/timeline"&&path.startsWith("/companies/"))||(href==="/today"&&path.startsWith("/events/"));return <Link key={href} className={`nav-item ${active?"active":""}`} href={href} aria-current={active?"page":undefined} onClick={()=>setMenu(false)}><Icon name={icon}/>{label}</Link>;})}{me.is_admin&&<><p className="nav-caption">운영 도구 · ADMIN</p><Link href="/ops" onClick={()=>setMenu(false)} className={`nav-item ${path.startsWith("/ops")?"active":""}`}><Icon name="settings"/>Ops 콘솔</Link></>}</nav><div className="sidebar-bottom"><BrandMark/><p>더 좋은 판단을 위해,<br/>확인할 수 있는 정보.</p><strong>SignalBrief</strong><small>Evidence first.<br/>A clearer perspective.</small></div></aside><div className="workspace-body"><header className="topbar"><button className="icon-button mobile-menu" aria-label="주 메뉴 열기" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Icon name="menu"/></button><GlobalSearch/><div className="top-actions"><div className="density-control" aria-label="정보 밀도">{[["beginner","초보자 모드"],["advanced","고급 모드"]].map(([density,label])=><button key={density} aria-pressed={me.density===density} className={me.density===density?"selected":""} disabled={action.busy} onClick={()=>action.run(async()=>{await request("/v1/me",auth.token,meSchema,body("PATCH",{density}));await auth.refresh();})}>{label}</button>)}</div><span className="avatar" aria-hidden="true">{me.display_name.slice(0,1)}</span><span className="user-name"><strong>{me.display_name}</strong><small>{me.is_admin?"관리자":"나의 브리핑"}</small></span><button className="icon-button" aria-label="로그아웃" title="로그아웃" disabled={action.busy} onClick={()=>action.run(async()=>{await auth.logout();router.replace("/login");})}><Icon name="logout"/></button></div></header>{me.demo_mode&&<div className="demo-banner">로컬 데모 · 기업·수치·공시는 합성 예시입니다. 실제 투자 판단에 사용하지 마세요.</div>}<main id="main" className="main-content"><ActionNotice action={action}/>{children}</main><footer className="footer"><Icon name="shield" size={14}/> 공개 근거에 기반한 정보 탐색 · 매매 추천 및 주가 예측을 제공하지 않습니다.</footer></div></div>;
}
export function EventTile({item}:{item:EventCard}){const {track}=useAuth();return <article className="event-card"><div className="event-company"><div className="company-token">{item.company.ticker.slice(0,2)}</div><Link className="company-name" href={`/companies/${item.company.id}`}>{item.company.name}</Link><span className="small muted">{item.company.ticker} · {item.company.market}</span><span className="badge">{item.source_provider.toUpperCase()}</span><Link href={`/companies/${item.company.id}`} className="small text-button">기업 타임라인 ↗</Link></div><div className="event-body"><div className="event-heading"><Link href={`/events/${item.id}`} className="headline-link" onClick={()=>track("brief_opened",{event_id:item.id})}><h2>{item.headline}</h2></Link><span className="badge">{typeLabels[item.event_type]??item.event_type}</span></div><p className="card-summary">{item.what_happened}</p><div className="signal-facts"><div><span><Icon name="file" size={14}/> FACT</span><p>{item.is_demo?"합성 테스트 공시":"공식 공시에서 확인한 사실"}</p></div><div><span><Icon name="timeline" size={14}/> CHANGE</span><p>{item.change_count>0?`${item.change_count}개 변경 항목을 근거와 비교` : "이전 비교 근거 확인 필요"}</p></div><div><span><Icon name="star" size={14}/> RELEVANCE</span><p>{item.ranking.reason}</p></div></div><div className="card-meta"><span>우선순위 <b>{score(item.ranking.score)}/100</b></span><span>구조적 검증 <b>{score(item.confidence)}/100</b></span><span>출처 {item.is_demo?"합성":`Tier ${item.source_tier??"미상"}`}</span></div><div className="card-bottom"><time dateTime={item.published_at}><Icon name="clock" size={13}/>{dateText(item.published_at,item.publication_precision)}</time><Link href={`/events/${item.id}`} className="button primary small-button" onClick={()=>track("brief_opened",{event_id:item.id})}>60초 Brief 보기 <Icon name="arrow" size={15}/></Link></div><details className="why"><summary>왜 이 변화가 표시되나요?</summary><p>{item.ranking.reason}. 점수는 수익 가능성이나 정확도 확률이 아닙니다. 시세·환율이 없으므로 시장가치 비중은 계산하지 않습니다.</p></details></div></article>;}
