'use client';

import Link from 'next/link';
import {useEffect,useId,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {Icon} from '@/components/icons';
import {usePcResource as useResource} from './data';
import {useMutation} from '@/workspace/ui';
import {usePrefs} from '@/workspace/preferences';
import {safeSource} from '@/workspace/contracts';
import {answerSchema,detailSchema,feedSchema,type Answer,type EventDetail} from '@/lib/contracts';
import {body,emptySchema,request} from '@/lib/api';
import {typeLabels} from '@/lib/format';
import {PcLogo,PcModal,PcDataState,PcNotice} from './ui';
import './questions.css';

const historySchema=z.array(z.object({id:z.string(),event_id:z.string(),question:z.string(),answer:answerSchema,created_at:z.string()}));
type SavedQuestion=z.infer<typeof historySchema>[number];
type PendingQuestion=SavedQuestion&{knownIds:string[]};
type Citation=Answer['evidence'][number];
const citationKey=(e:Citation)=>JSON.stringify([e.source_id,e.source_url,e.location,e.quote]);
function persisted(message:PendingQuestion,items:SavedQuestion[]){return items.some(item=>!message.knownIds.includes(item.id)&&item.question===message.question&&JSON.stringify(item.answer)===JSON.stringify(message.answer));}
function sourceMetadata(e:Citation,detail:EventDetail|null){
 const match=detail?.evidence.find(item=>item.source_url===e.source_url&&item.location===e.location&&(item.fact_id===e.source_id||item.document_id===e.source_id));
 const url=safeSource(e.source_url),host=url?new URL(url).hostname.replace(/^www\./,''):'';
 return {url,name:match?.source_name||host,title:match?.document_id===detail?.document.id?detail?.document.title:e.location,date:match?.published_at??null,precision:match?.publication_precision??'timestamp'};
}
function ChatIcon({type}:{type:'bot'|'person'|'send'|'copy'|'swap'}){
 const paths={bot:'M12 2v3M6 6h12a3 3 0 0 1 3 3v10H3V9a3 3 0 0 1 3-3ZM1 11v5M23 11v5M8 11v2M16 11v2M9 16h6',person:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM4 22v-3a8 8 0 0 1 16 0v3Z',send:'m3 3 19 9-19 9 3-8 10-1-10-1Z',copy:'M8 7h12v15H8ZM16 7V2H3v15h5',swap:'M3 7h17l-4-4M21 17H4l4 4'};
 return <svg aria-hidden="true" viewBox="0 0 24 24" fill={type==='send'||type==='person'?'currentColor':'none'} stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={paths[type]}/></svg>;
}
export default function DesktopQuestions({eventId=''}:{eventId?:string}){
 const {me}=useAuth();return <QuestionsContent key={`${me?.id??'anonymous'}:${eventId}`} eventId={eventId}/>;
}
function QuestionsContent({eventId}:{eventId:string}){
 const auth=useAuth(),router=useRouter(),params=useSearchParams(),{text:t,date,value}=usePrefs(),action=useMutation();
 const [question,setQuestion]=useState(''),[pending,setPending]=useState<PendingQuestion[]>([]),[cleared,setCleared]=useState<string[]>([]),[modal,setModal]=useState<'events'|'history'|null>(null),[confirmClear,setConfirmClear]=useState(false),[copyMessage,setCopyMessage]=useState(''),[copyError,setCopyError]=useState('');
 const input=useRef<HTMLTextAreaElement>(null),sourceList=useRef<HTMLElement>(null),labelId=useId(),mounted=useRef(true),scope=useRef(auth.token);
 const detail=useResource(eventId?`/v1/events/${encodeURIComponent(eventId)}`:null,detailSchema),history=useResource(auth.me?.demo_mode?null:'/v1/questions',historySchema),feed=useResource('/v1/feed?days=180&limit=100',feedSchema);
 const current=detail.data?.event.id===eventId&&!detail.error?detail.data:null;
 const saved=(history.data??[]).filter(item=>!cleared.includes(item.id)),selected=saved.filter(item=>item.event_id===eventId).sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at)||a.id.localeCompare(b.id));
 const conversation=[...selected,...pending.filter(item=>!persisted(item,selected))],selectedQuestion=params.get('question')??'';
 const canAsk=!!current&&!detail.loading&&!history.loading&&!history.error&&!action.busy;
 const sourceMap=new Map<string,Citation>();
 for(const message of conversation)for(const evidence of message.answer.evidence)sourceMap.set(citationKey(evidence),evidence);
 if(!conversation.length&&current)for(const evidence of current.evidence)sourceMap.set(citationKey({source_id:evidence.fact_id,...evidence}),{source_id:evidence.fact_id,...evidence});
 const sources=[...sourceMap.values()],sourceIndex=new Map(sources.map((e,i)=>[citationKey(e),i+1]));
 useEffect(()=>{scope.current=auth.token;},[auth.token]);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{if(!history.data)return;const owned=history.data.filter(item=>item.event_id===eventId);setPending(previous=>{const kept=previous.filter(item=>!persisted(item,owned));return kept.length===previous.length?previous:kept;});},[eventId,history.data]);
 useEffect(()=>{if(selectedQuestion&&history.data?.some(item=>item.id===selectedQuestion&&item.event_id===eventId))document.getElementById(`pc-question-${selectedQuestion}`)?.scrollIntoView({block:'center'});},[selectedQuestion,eventId,history.data]);
 function choose(id:string,questionId=''){const next=new URLSearchParams({event:id});if(questionId)next.set('question',questionId);router.replace(id?`/questions?${next}`:'/questions',{scroll:false});setModal(null);}
 function suggest(prompt:string){setQuestion(prompt);input.current?.focus();}
 function ask(){const sent=question.trim();if(!sent||!canAsk)return;const knownIds=saved.map(item=>item.id),token=auth.token;if(selectedQuestion)choose(eventId);void action.run(async()=>{const answer=await request(`/v1/events/${encodeURIComponent(eventId)}/questions`,token,answerSchema,body('POST',{question:sent}));if(!mounted.current||scope.current!==token)return;setPending(old=>[...old,{id:`pending-${crypto.randomUUID()}`,event_id:eventId,question:sent,answer,knownIds,created_at:new Date().toISOString()}]);setQuestion('');history.reload();});}
 async function copy(answer:Answer){setCopyMessage('');setCopyError('');try{if(!navigator.clipboard?.writeText)throw new Error('unavailable');await navigator.clipboard.writeText([answer.message,...answer.evidence.map((e,i)=>`[${i+1}] ${e.location}\n${e.quote}\n${safeSource(e.source_url)??''}`)].join('\n\n'));setCopyMessage(t('답변과 원문 근거를 복사했습니다.','Answer and source evidence copied.'));}catch{setCopyError(t('복사하지 못했습니다. 답변을 직접 선택해 복사해 주세요.','Could not copy. Select and copy the answer text.'));}}
 function time(iso:string){const instant=new Date(iso);return Number.isFinite(+instant)?new Intl.DateTimeFormat(value.locale,{timeZone:value.timezone,hour:'numeric',minute:'2-digit'}).format(instant):date(iso);}
 async function clearHistory(){const removed=saved.map(item=>item.id);await action.run(async()=>{await request('/v1/questions',auth.token,emptySchema,body('DELETE'));setCleared(old=>[...new Set([...old,...removed])]);setPending([]);setConfirmClear(false);history.reload();},t('내 질문 기록을 삭제했습니다.','Your question history was cleared.'));}
 const suggestions=[['이전 공시와 비교','Compare prior filings','이전 공시와 무엇이 달라졌나요?','What changed from the prior filing?'],['매출 수치 근거','Revenue evidence','매출 수치의 근거를 보여줘','Show the evidence for revenue figures.'],['위험 요인 확인','Risk disclosures','위험 요인의 원문을 보여줘','Show the source risk disclosures.']];
 return <div className="pc-questions">
  <header className="pc-question-heading"><div><span>{t('AI 후속 질문','Evidence follow-up')}</span><h1>{t('AI와 함께 더 깊이 있는 인사이트를 찾아보세요.','Explore the evidence with follow-up questions.')}</h1><p>{t('선택한 공시의 실적과 기업 이슈를 원문 근거로 확인해 보세요.','Explore results and company disclosures using their source evidence.')}</p></div><div><button type="button" className="pc-question-history-open" onClick={()=>setModal('history')}><Icon name="clock" size={18}/>{t('질문 기록','Question history')}</button><button type="button" className="pc-question-new" disabled={action.busy} onClick={()=>{setQuestion('');choose('');setModal('events');}}><Icon name="plus"/>{t('새 대화','New question')}</button></div></header>
  <PcNotice action={action}/>{copyMessage&&<p className="pc-question-copy-state" role="status">{copyMessage}</p>}{copyError&&<p className="pc-question-copy-error" role="alert">{copyError}</p>}
  <div className="pc-question-grid"><div className="pc-question-main">
   <PcDataState loading={detail.loading&&!!eventId} error={detail.error??''} retry={detail.reload}/>
   {current?<section className="pc-question-context"><Link href={`/companies/${current.event.company.id}`} aria-label={`${current.event.company.name} ${t('기업 개요','Company overview')}`}><PcLogo ticker={current.event.company.ticker} size={76}/></Link><div><p><strong>{current.event.company.name}</strong><span>{current.event.company.ticker}</span></p><div><Link href={`/events/${eventId}`}><h2>{current.event.headline}</h2></Link><span className="pc-question-type">{value.locale==='ko'?typeLabels[current.event.event_type]??current.event.event_type:current.event.event_type}</span></div><time dateTime={current.event.published_at}>{date(current.event.published_at,current.event.publication_precision)}</time></div><button type="button" disabled={action.busy} onClick={()=>setModal('events')}><ChatIcon type="swap"/>{t('다른 주제로 질문하기','Change topic')}</button></section>:!detail.loading&&!detail.error&&<section className="pc-question-empty"><Icon name="spark" size={34}/><h2>{t('질문할 이벤트를 선택해 주세요.','Select an event to ask about.')}</h2><p>{t('게시된 이벤트의 원문에서 근거를 확인합니다. 질문 기록은 그대로 보관됩니다.','Answers use a published event’s evidence. Existing question history is retained.')}</p><button type="button" onClick={()=>setModal('events')}>{t('이벤트 선택','Choose an event')}</button></section>}
   <PcDataState loading={history.loading} error={history.error??''} retry={history.reload}/>
   <div className="pc-question-conversation" aria-live="polite">{conversation.map(message=><section key={message.id} id={`pc-question-${message.id}`} className={`pc-question-turn ${selectedQuestion===message.id?'selected':''}`}>
    <div className="pc-question-user"><p>{message.question}</p><span aria-hidden="true"><ChatIcon type="person"/></span><time dateTime={message.created_at}>{time(message.created_at)}</time></div>
    <div className="pc-question-ai"><span className="pc-question-bot" aria-hidden="true"><ChatIcon type="bot"/></span><div><span className="pc-question-ai-label">AI</span><article className="pc-question-answer" aria-label={t('AI 근거 답변','AI evidence answer')}><p className="pc-question-message">{message.answer.message}</p>{message.answer.status!=='answered'&&<p className="pc-question-answer-state">{message.answer.status==='abstained'?t('근거 부족','Insufficient evidence'):message.answer.status==='policy_blocked'?t('답변 범위 제한','Outside answer scope'):t('현재 답변 불가','Currently unavailable')}</p>}
     {message.answer.evidence.length>0&&<ol className="pc-question-citations">{message.answer.evidence.map((e,i)=>{const number=sourceIndex.get(citationKey(e))!,source=sourceMetadata(e,current);return <li key={`${citationKey(e)}-${i}`}><button type="button" aria-label={`${t('근거','Evidence')} ${number} ${t('보기','view')}`} onClick={()=>document.getElementById(`pc-source-${number}`)?.scrollIntoView({block:'nearest'})}>{number}</button><div><h3>{e.location||t('확인된 원문 근거','Verified source evidence')}</h3><blockquote>{e.quote}</blockquote>{source.url?<a href={source.url} target="_blank" rel="noopener noreferrer">{t('원문 근거','Source evidence')}<Icon name="arrow" size={13}/></a>:<span className="pc-question-muted">{t('원문 링크 확인 필요','Source link unavailable')}</span>}</div></li>;})}</ol>}
     <footer><button type="button" onClick={()=>void copy(message.answer)}><ChatIcon type="copy"/>{t('복사하기','Copy')}</button><small>{t('답변은 선택한 공시의 근거에 한정되며 투자 판단을 대신하지 않습니다.','Answers are limited to the selected disclosure’s evidence and do not replace your investment judgment.')}</small></footer>
    </article></div></div>
   </section>)}</div>
   {current&&!conversation.length&&!history.loading&&!history.error&&<div className="pc-question-first"><span className="pc-question-bot" aria-hidden="true"><ChatIcon type="bot"/></span><div><strong>{t('어떤 근거가 궁금하신가요?','Which evidence would you like to explore?')}</strong><p>{t('실적 수치, 이전 공시와의 변화, 위험 요인을 질문해 보세요. 확인할 수 없는 내용은 추측하지 않습니다.','Ask about reported figures, changes or risks. Unsupported answers are not guessed.')}</p></div></div>}
  </div>
  <aside className="pc-question-sources" ref={sourceList}><h2>{t('참고한 주요 자료','Referenced source material')}</h2>{sources.length?<ol>{sources.map((e,i)=>{const source=sourceMetadata(e,current);return <li key={citationKey(e)} id={`pc-source-${i+1}`}><span className="pc-question-source-number">{i+1}</span><Icon name="file" size={30}/><div><strong>{source.title||t('원문 근거','Source evidence')}</strong><p>{source.name||t('출처 확인 필요','Source not identified')}</p>{source.date&&<time dateTime={source.date}>{date(source.date,source.precision)}</time>}{e.location&&e.location!==source.title&&<small>{e.location}</small>}</div>{source.url&&<a href={source.url} target="_blank" rel="noopener noreferrer" aria-label={`${i+1} ${t('원문 열기','Open original')}`}><Icon name="arrow" size={16}/></a>}</li>;})}</ol>:<p className="pc-question-sources-empty">{t('공개된 근거가 있으면 이곳에서 확인할 수 있습니다.','Published evidence will appear here when available.')}</p>}{current&&<Link className="pc-question-all-sources" href={`/events/${eventId}?panel=evidence`}>{t('모든 출처 보기','View all evidence')}<Icon name="arrow" size={16}/></Link>}<p className="pc-question-scope">{t('자료 업로드와 답변 평가는 현재 제공하지 않습니다.','Source uploads and answer ratings are not currently available.')}</p></aside></div>
  <div className="pc-question-bottom"><section className="pc-question-suggestions" aria-label={t('추천 질문','Suggested questions')}><strong>{t('이런 질문도 해보세요','Try these questions')}</strong>{suggestions.map(([ko,en,promptKo,promptEn])=><button type="button" key={ko} disabled={!canAsk} onClick={()=>suggest(t(promptKo,promptEn))}>{t(ko,en)}</button>)}</section><form className="pc-question-compose" onSubmit={e=>{e.preventDefault();ask();}}><button type="button" className="pc-question-context-menu" aria-label={t('이벤트 선택 및 질문 기록','Choose event and question history')} onClick={()=>setModal('events')}><Icon name="plus" size={26}/></button><label><span className="pc-question-sr" id={labelId}>{t('공시에 관한 질문','Question about the filing')}</span><textarea ref={input} aria-labelledby={labelId} value={question} maxLength={2000} rows={1} disabled={!canAsk} placeholder={t('궁금한 점을 질문해보세요. (예: 이전 공시와 무엇이 달라졌나요?)','Ask a follow-up question about the selected disclosure.')} onChange={e=>setQuestion(e.target.value)}/></label><button type="submit" className="pc-question-send" aria-label={action.busy?t('근거 확인 중…','Checking evidence…'):t('질문 보내기','Send question')} disabled={!canAsk||!question.trim()}><ChatIcon type="send"/></button></form></div>
  {modal==='events'&&<PcModal title={t('질문할 이벤트 선택','Choose an event')} onClose={()=>setModal(null)}><PcDataState loading={feed.loading} error={feed.error??''} retry={feed.reload}/><label className="pc-question-event-select">{t('질문할 이벤트','Event to ask about')}<select value={eventId} disabled={action.busy} onChange={e=>choose(e.target.value)}><option value="">{t('이벤트를 선택하세요','Choose an event')}</option>{current&&!feed.data?.items.some(e=>e.id===eventId)&&<option value={eventId}>{current.event.company.name} · {current.event.headline}</option>}{feed.data?.items.map(event=><option key={event.id} value={event.id}>{event.company.name} · {event.headline}</option>)}</select></label>{feed.data&&!feed.data.items.length&&<p>{t('질문할 수 있는 게시된 이벤트가 없습니다. 관심종목에서 공시를 확인해 주세요.','No published events are available. Review disclosures in your watchlist.')}</p>}<button className="pc-question-modal-history" type="button" onClick={()=>setModal('history')}><Icon name="clock"/>{t('최근 질문 기록 열기','Open recent question history')}</button></PcModal>}
  {modal==='history'&&<PcModal title={t('최근 질문 기록','Recent questions')} onClose={()=>{if(!action.busy){setModal(null);setConfirmClear(false);}}}><PcNotice action={action}/><PcDataState loading={history.loading} error={history.error??''} retry={history.reload}/>{!history.loading&&!history.error&&!saved.length&&<p>{t('저장된 질문이 없습니다.','No saved questions.')}</p>}<div className="pc-question-history-list">{saved.map(item=><button type="button" key={item.id} disabled={action.busy} onClick={()=>choose(item.event_id,item.id)}><strong>{item.question}</strong><time dateTime={item.created_at}>{date(item.created_at)}</time><Icon name="arrow" size={16}/></button>)}</div>{history.data?.length===100&&<p className="pc-question-muted">{t('서버가 제공한 최근 100개 질문을 표시합니다.','Showing the latest 100 questions returned by the server.')}</p>}{confirmClear?<div className="pc-question-clear"><p>{t('내 질문 기록을 모두 삭제할까요? 삭제 후 되돌릴 수 없습니다.','Delete all your question history? This cannot be undone.')}</p><button type="button" disabled={action.busy} onClick={()=>void clearHistory()}>{t('모든 질문 기록 삭제','Delete all question history')}</button><button type="button" disabled={action.busy} onClick={()=>setConfirmClear(false)}>{t('취소','Cancel')}</button></div>:<button type="button" className="pc-question-clear-open" disabled={action.busy||history.loading||!saved.length} onClick={()=>setConfirmClear(true)}>{t('기록 삭제','Clear history')}</button>}</PcModal>}
 </div>;
}
