'use client';

import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useEffect, useRef, useState} from 'react';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {Icon, type IconName} from '@/components/icons';
import {workspace} from '@/workspace/client';
import {catalogSchema, resourceHref, resourceKind, searchesSchema, type Resource} from '@/workspace/contracts';
import {useQuotes} from '@/workspace/market';
import {usePrefs} from '@/workspace/preferences';
import {useData, useMutation} from '@/workspace/ui';
import {PcPanel, PcHeading, PcLogo, PcChart, PcEmpty, PcDataState, PcNotice} from './ui';
import './search.css';

const industries: {ko:string;en:string;q:string;icon:IconName}[] = [
 {ko:'반도체',en:'Semiconductors',q:'semiconductor',icon:'pie'}, {ko:'소프트웨어',en:'Software',q:'software',icon:'file'},
 {ko:'하드웨어',en:'Hardware',q:'hardware',icon:'settings'}, {ko:'자동차',en:'Automotive',q:'automotive',icon:'calendar'},
 {ko:'헬스케어',en:'Healthcare',q:'healthcare',icon:'plus'}, {ko:'금융',en:'Finance',q:'financial',icon:'home'},
 {ko:'에너지',en:'Energy',q:'energy',icon:'spark'}, {ko:'소비재',en:'Consumer',q:'consumer',icon:'star'},
 {ko:'산업재',en:'Industrials',q:'industrial',icon:'settings'}, {ko:'통신',en:'Telecom',q:'telecom',icon:'timeline'},
 {ko:'AI / 로봇',en:'AI / Robotics',q:'artificial intelligence',icon:'shield'},
];
const shortcuts = ['AI 반도체','전기차','2차전지','바이오','금리 인하','미중 갈등','배당주','원자력 발전','자동차','HBM'];
const eventNames:Record<string,string>={earnings:'실적 발표',guidance:'실적 전망',filing:'공시',capital:'자본 변동',governance:'지배구조',risk:'위험 요인',product:'제품 / 서비스',contract:'계약',dividend:'배당'};
function IndustryIcon({index}:{index:number}){const paths=['M7 7h10v10H7ZM10 10h4v4h-4M4 8h3M4 12h3M4 16h3M17 8h3M17 12h3M17 16h3M8 4v3M12 4v3M16 4v3M8 17v3M12 17v3M16 17v3','M3 4h18v13H3ZM8 21h8M12 17v4','M4 3h16v7H4ZM4 14h16v7H4ZM7 6h1M7 17h1M11 6h6M11 17h6','m4 10 2-6h12l2 6M3 10h18v9H3ZM6 19v2M18 19v2M6 14h2M16 14h2','M4 7h16v14H4ZM8 7V3h8v4M12 11v6M9 14h6','M3 5h18v15H3ZM3 10h18M7 16h4','m14 2-9 12h7l-2 8 9-13h-7Z','M2 3h3l3 12h11l3-9H6M9 20h1M18 20h1','M3 21V9h5v12M8 21V3h7v18M15 21v-8h6v8M11 7h1M11 11h1M11 15h1','M12 4v17M8 21h8M9 5a5 5 0 0 0 0 8M15 5a5 5 0 0 1 0 8M6 2a9 9 0 0 0 0 14M18 2a9 9 0 0 1 0 14','M5 8h14v12H5ZM12 3v5M10 3h4M8 12h1M15 12h1M9 17h6M2 11v6M22 11v6'];return <svg width="33" height="33" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.1" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[index]}/></svg>;}
function money(value:number|null|undefined,currency:string,locale:string){return value==null?'—':new Intl.NumberFormat(locale==='ko'?'ko-KR':'en-US',{style:'currency',currency,maximumFractionDigits:currency==='KRW'?0:2}).format(value);}
function SearchDate(){const {value,text:t}=usePrefs();return <div className="pc-search-date"><strong>{new Intl.DateTimeFormat(value.locale==='ko'?'ko-KR':'en-US',{year:'numeric',month:'long',day:'numeric',weekday:'long',timeZone:value.timezone}).format(new Date())}</strong><span>{t('오늘도 좋은 투자 인사이트를 발견해 보세요.','Discover a new perspective today.')}</span></div>;}
function SearchForm({initial='',market=''}:{initial?:string;market?:string}){const router=useRouter(),{text:t}=usePrefs(),[query,setQuery]=useState(initial);return <form className="pc-discovery-form" onSubmit={e=>{e.preventDefault();const q=query.trim();if(q)router.push(`/search?${new URLSearchParams({q,...(market?{market}:{})})}`);}}><Icon name="search" size={29}/><input aria-label={t('기업, 키워드 또는 산업 검색','Search companies, keywords or industries')} value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} placeholder={t('기업명, 종목코드 또는 키워드를 입력하세요','Enter a company, ticker or keyword')}/>{query&&<button type="button" className="pc-discovery-clear" aria-label={t('검색어 지우기','Clear query')} onClick={()=>setQuery('')}><Icon name="close"/></button>}<button className="pc-discovery-submit" disabled={!query.trim()}><Icon name="search" size={20}/>{t('검색','Search')}</button></form>;}

export function DesktopExplore(){
 const {token}=useAuth(),prefs=usePrefs(),{text:t}=prefs,router=useRouter(),action=useMutation();
 const [market,setMarket]=useState(''),[rotation,setRotation]=useState(0);
 const companies=useData({action:'catalog',p:{kind:'company',limit:50,market}},catalogSchema),events=useData({action:'catalog',p:{kind:'event',limit:50,market,sort:'newest'}},catalogSchema),searches=useData({action:'searches',p:{}},searchesSchema);
 const companyItems=companies.data?.items??[],prices=useQuotes(companyItems.slice(0,5).map(item=>item.ticker),'1m');
 const quoteMap=new Map(prices.quotes.map(quote=>[quote.symbol.toUpperCase(),quote]));
 const terms=[...new Set(companyItems.map(item=>item.ticker).filter(Boolean).concat((events.data?.items??[]).map(item=>item.category).filter(Boolean)))];
 const suggestions=terms.length?[...terms.slice(rotation%terms.length),...terms.slice(0,rotation%terms.length)].slice(0,6):[];
 const types=new Map<string,number>();for(const event of events.data?.items??[])types.set(event.category,(types.get(event.category)??0)+1);
 const go=(q:string)=>router.push(`/search?${new URLSearchParams({q,...(market?{market}:{})})}`);
 async function removeSearch(query?:string){await workspace(token,query?{action:'search_delete',p:{query}}:{action:'searches_clear',p:{}},z.unknown());searches.reload();}
 return <div className="pc-explore" data-screen="desktop-explore">
  <PcHeading eyebrow={t('관심 있는 기업, 키워드, 산업을 검색해보세요.','Explore companies, keywords and industries.')} title={t('검색 / 탐색','Search / Explore')} description={t('기업, 산업, 이슈를 한눈에 검색하고 새로운 투자 인사이트를 발견하세요.','Explore companies, industries and the evidence behind their changes.')} action={<SearchDate/>}/>
  <SearchForm market={market}/><div className="pc-discovery-shortcuts" aria-label={t('검색 키워드 예시','Example search keywords')}><span>{t('예시 키워드','Examples')}</span>{shortcuts.map(q=><button key={q} onClick={()=>go(q)}>{q}</button>)}</div>
  <PcNotice action={action}/>
  <div className="pc-discovery-history-grid">
   <PcPanel title={t('최근 검색어','Recent searches')} icon="clock" className="pc-discovery-history" action={<button className="pc-discovery-text" disabled={action.busy||!searches.data?.length} onClick={()=>void action.run(()=>removeSearch())}>{t('전체 삭제','Clear all')}</button>}>
    <PcDataState loading={searches.loading} error={searches.error} retry={searches.reload}/><div className="pc-discovery-recents">{searches.data?.slice(0,6).map(item=><div key={item.query}><button onClick={()=>go(item.query)}>{item.query}</button><button disabled={action.busy} aria-label={`${item.query} ${t('검색 기록 삭제','delete recent search')}`} onClick={()=>void action.run(()=>removeSearch(item.query))}><Icon name="close" size={14}/></button></div>)}</div>{searches.data&&!searches.data.length&&<p className="pc-discovery-empty-note">{t('최근 검색어가 없습니다','No recent searches')}{!prefs.value.history_enabled&&<> · <Link href="/settings/appearance">{t('기록 설정','History preferences')}</Link></>}</p>}
   </PcPanel>
   <PcPanel title={t('추천 검색어','Search suggestions')} icon="timeline" className="pc-discovery-suggestions" action={<button className="pc-discovery-text" disabled={terms.length<2} onClick={()=>setRotation(n=>n+1)}>{t('새로운 추천','Refresh suggestions')} ↻</button>}>
    <PcDataState loading={companies.loading} error={companies.error} retry={companies.reload}/><div className="pc-discovery-terms">{suggestions.map((term,index)=><button key={term} onClick={()=>go(term)}><b>{index+1}</b><span>{term}</span><Icon name="arrow" size={14}/></button>)}</div>{companies.data&&!suggestions.length&&<p className="pc-discovery-empty-note">{t('연결된 기업과 자료가 아직 없습니다.','No connected companies or sources yet.')}</p>}
   </PcPanel>
  </div>
  <section className="pc-discovery-industries"><div className="pc-discovery-section-heading"><div><h2><Icon name="timeline"/>{t('산업 섹터로 탐색하기','Explore industries')}</h2><p>{t('관심 있는 산업 키워드로 연결된 기업과 자료를 찾아보세요.','Find connected companies and sources with industry keywords.')}</p></div><Link href="/search">{t('전체 보기','View all')} ›</Link></div><div className="pc-discovery-industry-grid">{industries.map((industry,index)=><button key={industry.q} onClick={()=>go(industry.q)} className={`industry-${index%6}`}><span><IndustryIcon index={index}/></span>{t(industry.ko,industry.en)}</button>)}</div></section>
  <section className="pc-discovery-filters"><div className="pc-discovery-section-heading"><div><h2><Icon name="settings"/>{t('시장 필터','Market filters')}</h2><p>{t('수집된 자료의 시장을 선택하세요. 재무 지표와 산업 분류 필터는 아직 제공되지 않습니다.','Select a connected market. Valuation and industry classification filters are not available yet.')}</p></div></div><div className="pc-discovery-filter-row"><label><select aria-label={t('시장 필터','Market filter')} value={market} onChange={e=>setMarket(e.target.value)}><option value="">{t('전체 시장','All markets')}</option>{companies.data?.markets.map(m=><option key={m}>{m}</option>)}</select></label>{[['국가','Country'],['시가총액','Market cap'],['섹터','Sector'],['테마','Theme'],['배당수익률','Dividend yield'],['PER','P/E'],['PBR','P/B']].map(([ko,en])=><button key={ko} disabled title={t('연결된 지표가 없어 제공되지 않습니다.','Unavailable: no connected metric.')}>{t(ko,en)} ⌄</button>)}<button className="pc-discovery-reset" onClick={()=>setMarket('')}>↻ {t('필터 초기화','Reset filters')}</button></div></section>
  <div className="pc-discovery-bottom"><PcPanel title={t('연결된 기업','Connected companies')} icon="star" className="pc-discovery-companies" action={<Link href={`/search?${new URLSearchParams({kind:'company',...(market?{market}:{})})}`}>{t('전체 보기','View all')} ›</Link>}><PcDataState loading={companies.loading} error={companies.error} retry={companies.reload}/><div className="pc-discovery-company-grid">{companyItems.slice(0,5).map(item=>{const quote=quoteMap.get(item.ticker.toUpperCase());return <Link key={item.id} href={resourceHref(item)}><PcLogo ticker={item.ticker} size={45}/><strong>{item.ticker}</strong><span>{item.company_name}</span><b>{money(quote?.price,quote?.currency??'USD',prefs.value.locale)}</b><small className={quote?.change_pct==null?'':quote.change_pct>=0?'pc-up':'pc-down'}>{quote?.change_pct==null?t('시세 확인 전','Quote unavailable'):`${quote.change_pct>=0?'+':''}${quote.change_pct.toFixed(2)}%`}</small></Link>;})}</div>{companies.data&&!companyItems.length&&<PcEmpty title={t('해당 시장의 기업이 없습니다.','No connected companies in this market.')}/>}</PcPanel>
   <PcPanel title={t('수집된 이벤트 유형','Collected event types')} icon="file" className="pc-discovery-event-types"><PcDataState loading={events.loading} error={events.error} retry={events.reload}/>{[...types].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,count])=><button key={name} onClick={()=>router.push(`/search?${new URLSearchParams({q:name,kind:'event',...(market?{market}:{})})}`)}><span><Icon name="calendar" size={17}/>{prefs.value.locale==='ko'?(eventNames[name]??name):name}</span><b>{count}{t('건','')}</b></button>)}{events.data&&<small>{t(`최근 불러온 ${events.data.items.length}건 기준`,`Based on ${events.data.items.length} loaded events`)}</small>}</PcPanel>
  </div>
 </div>;
}

type SearchProps={initial:string;initialKind:string;initialMarket?:string;initialDays?:number;initialOffset?:number;initialSort?:'relevance'|'newest'};
export function DesktopSearchResults({initial,initialKind,initialMarket='',initialDays=0,initialOffset=0,initialSort='relevance'}:SearchProps){
 const {token}=useAuth(),prefs=usePrefs(),{text:t}=prefs,router=useRouter(),recorded=useRef('');
 const parsed=resourceKind.safeParse(initialKind),kind=parsed.success?parsed.data:'',filters={q:initial,market:initialMarket,days:initialDays,sort:initialSort};
 const all=useData({action:'catalog',p:{...filters,kind,offset:kind?initialOffset:0,limit:kind?12:1}},catalogSchema);
 const companies=useData(!kind?{action:'catalog',p:{...filters,kind:'company',limit:1}}:null,catalogSchema),events=useData(!kind?{action:'catalog',p:{...filters,kind:'event',limit:3}}:null,catalogSchema),documents=useData(!kind?{action:'catalog',p:{...filters,kind:'document',limit:2}}:null,catalogSchema);
 const related=useData({action:'catalog',p:{q:initial,market:initialMarket,kind:'company',limit:4}},catalogSchema);
 const companyItems=kind==='company'?all.data?.items??[]:companies.data?.items??[],quotes=useQuotes([...companyItems,...related.data?.items??[]].map(item=>item.ticker),'1m'),quoteMap=new Map(quotes.quotes.map(quote=>[quote.symbol.toUpperCase(),quote]));
 useEffect(()=>{const q=initial.trim();if(token&&prefs.loaded&&prefs.value.history_enabled&&q&&recorded.current!==`${token}:${q}`){recorded.current=`${token}:${q}`;void workspace(token,{action:'search_record',p:{query:q}},z.unknown()).catch(()=>{recorded.current='';});}},[token,initial,prefs.loaded,prefs.value.history_enabled]);
 const counts=all.data?.counts??{},documentCount=(counts.document??0)+(counts.filing??0),total=Object.values(counts).reduce((sum,n)=>sum+n,0);
 const countFor=(key:string)=>key==='document'?documentCount:key?counts[key]??0:total;
 const typeChoices=[['',t('전체','All')],['company',t('기업','Companies')],['event',t('이벤트','Events')],['document',t('문서','Documents')],...(kind==='filing'?[['filing',t('공시 문서','Filings')]]:[])];
 const tabs=kind==='filing'?[...typeChoices.slice(0,3),typeChoices[4]]:typeChoices;
 const periods:[number,string][]=[[0,t('전체 기간','All dates')],[7,t('최근 7일','Last 7 days')],[30,t('최근 30일','Last 30 days')],[90,t('최근 3개월','Last 3 months')],[365,t('최근 1년','Last year')]];
 if(!periods.some(([days])=>days===initialDays))periods.push([initialDays,t(`최근 ${initialDays}일`,`Last ${initialDays} days`)]);
 function change(patch:{kind?:string;market?:string;days?:number;sort?:string;offset?:number;q?:string}){const next={q:initial,kind,market:initialMarket,days:initialDays,sort:initialSort,offset:0,...patch},params=new URLSearchParams();Object.entries(next).forEach(([key,value])=>{if(value!==''&&value!==0)params.set(key,String(value));});router.push(`/search?${params}`);}
 const reset=()=>change({market:'',days:0,kind:'',sort:'relevance'});
 const track=(item:Resource)=>{if(prefs.value.history_enabled)void workspace(token,{action:'visit',p:{kind:item.kind,id:item.id}},z.unknown()).catch(()=>{});};
 const availableMarkets=all.data?.markets??[],keywords=[...new Set([...(related.data?.items??[]).map(i=>i.ticker),...(events.data?.items??[]).map(i=>i.category),...(documents.data?.items??[]).map(i=>i.category)])].filter(term=>term&&term.toLowerCase()!==initial.toLowerCase()).slice(0,6);
 function renderGroup(key:'company'|'event'|'document'|'filing',items:Resource[],loading:boolean,error:string,retry:()=>void){const title=key==='company'?t('기업','Companies'):key==='event'?t('이벤트','Events'):key==='filing'?t('공시 문서','Filings'):t('문서','Documents');return <section className={`pc-search-group pc-search-${key}`} key={key}><header><h2>{title}<small>{all.data?`${countFor(key)}${t('개','')}`:'—'}</small></h2>{!kind&&countFor(key)>items.length&&<button onClick={()=>change({kind:key})}>{t('전체 보기','View all')} ›</button>}</header><PcDataState loading={loading} error={error} retry={retry}/><div className="pc-search-result-list">{items.map(item=><SearchResult key={`${item.kind}:${item.id}`} item={item} quote={quoteMap.get(item.ticker.toUpperCase())} track={()=>track(item)}/>)}</div>{!loading&&!error&&!items.length&&<PcEmpty title={t('검색 결과가 없습니다.','No matching results.')}/>}</section>;}
 return <div className="pc-search-results" data-screen="desktop-search-results"><PcHeading title={t('검색 결과','Search results')} description={all.data?t(`'${initial||t('전체 자료','All resources')}'에 대한 ${total}개의 검색 결과를 찾았습니다.`,`Found ${total} results for '${initial||'All resources'}'.`):t('연결된 자료를 검색하고 있습니다.','Searching connected sources.')}/>
  <div className="pc-search-columns"><div className="pc-search-primary"><nav className="pc-search-tabs" aria-label={t('검색 결과 유형','Search result types')}>{tabs.map(([key,label])=><button key={key} aria-pressed={kind===key} className={kind===key?'active':''} onClick={()=>change({kind:key})}>{label}<small>({all.data?countFor(key):'—'})</small></button>)}</nav>
   <div className="pc-search-toolbar"><select aria-label={t('시장 필터','Market filter')} value={initialMarket} onChange={e=>change({market:e.target.value})}><option value="">{t('전체 시장','All markets')}</option>{[...new Set([...availableMarkets,...initialMarket?[initialMarket]:[]])].map(m=><option key={m}>{m}</option>)}</select><select aria-label={t('기간 필터','Date filter')} value={initialDays} onChange={e=>change({days:Number(e.target.value)})}>{periods.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select><select aria-label={t('자료 유형','Resource type')} value={kind} onChange={e=>change({kind:e.target.value})}>{typeChoices.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select><select className="pc-search-sort" aria-label={t('정렬 기준','Sort results')} value={initialSort} onChange={e=>change({sort:e.target.value})}><option value="relevance">{t('관련도순','Relevance')}</option><option value="newest">{t('최신순','Newest')}</option></select></div>
   <PcDataState loading={all.loading} error={all.error} retry={all.reload}/>
   {!kind?<>{renderGroup('company',companyItems,companies.loading,companies.error,companies.reload)}{renderGroup('event',events.data?.items??[],events.loading,events.error,events.reload)}{renderGroup('document',documents.data?.items??[],documents.loading,documents.error,documents.reload)}</>:renderGroup(kind,all.data?.items??[],false,'',all.reload)}
   {kind&&all.data&&(initialOffset>0||all.data.next_offset!==null)&&<nav className="pc-search-pagination" aria-label={t('검색 결과 페이지','Search result pages')}><button disabled={initialOffset===0} onClick={()=>change({offset:Math.max(0,initialOffset-12)})}>{t('이전','Previous')}</button><span>{Math.floor(initialOffset/12)+1}</span><button disabled={all.data.next_offset===null} onClick={()=>change({offset:all.data?.next_offset??0})}>{t('다음','Next')}</button></nav>}
  </div><aside className="pc-search-aside"><PcPanel title={t('검색 필터','Search filters')} icon="settings" action={<button className="pc-discovery-text" onClick={reset}>↻ {t('초기화','Reset')}</button>}><fieldset><legend>{t('시장','Market')}</legend>{['',...availableMarkets].map(m=><label key={m}><input type="radio" name="pc-search-market" checked={initialMarket===m} onChange={()=>change({market:m})}/>{m||t('전체 시장','All markets')}</label>)}</fieldset><fieldset><legend>{t('기간','Date')}</legend>{periods.map(([v,label])=><label key={v}><input type="radio" name="pc-search-days" checked={initialDays===v} onChange={()=>change({days:Number(v)})}/>{label}</label>)}</fieldset><fieldset><legend>{t('유형','Type')}</legend>{typeChoices.map(([key,label])=><label key={key}><input type="radio" name="pc-search-type" checked={kind===key} onChange={()=>change({kind:key})}/>{label}<small>{all.data?countFor(key):'—'}</small></label>)}</fieldset></PcPanel>
   <PcPanel title={t('관련 키워드','Related keywords')} icon="search"><div className="pc-search-keywords">{keywords.map(word=><button key={word} onClick={()=>change({q:word,kind:''})}>{word}</button>)}</div>{!keywords.length&&<p className="pc-discovery-empty-note">{t('확인된 관련 키워드가 없습니다.','No related keywords are available.')}</p>}</PcPanel>
   <PcPanel title={t('관련 기업','Related companies')} icon="star"><PcDataState loading={related.loading} error={related.error} retry={related.reload}/>{related.data?.items.map(item=>{const change=quoteMap.get(item.ticker.toUpperCase())?.change_pct;return <Link key={item.id} className="pc-search-related-company" href={resourceHref(item)}><PcLogo ticker={item.ticker} size={37}/><span><strong>{item.company_name}</strong><small>{item.ticker}</small></span><b className={change==null?'':change>=0?'pc-up':'pc-down'}>{change==null?'—':`${change>=0?'+':''}${change.toFixed(2)}%`}</b></Link>;})}{related.data&&!related.data.items.length&&<p className="pc-discovery-empty-note">{t('관련 기업이 없습니다.','No related companies.')}</p>}</PcPanel>
  </aside></div>
 </div>;
}

function SearchResult({item,quote,track}:{item:Resource;quote:ReturnType<typeof useQuotes>['quotes'][number]|undefined;track:()=>void}){
 const {token}=useAuth(),prefs=usePrefs(),{text:t}=prefs,action=useMutation(),[saved,setSaved]=useState(item.is_saved);
 useEffect(()=>setSaved(item.is_saved),[item.is_saved]);
 const date=item.published_at?new Date(item.published_at):null,validDate=date&&!Number.isNaN(+date),timezone=['date','date_only'].includes(item.publication_precision)?'UTC':prefs.value.timezone;
 const datePart=(part:'month'|'day')=>validDate?new Intl.DateTimeFormat(prefs.value.locale==='ko'?'ko-KR':'en-US',{timeZone:timezone,[part]:part==='month'?'short':'numeric'}).format(date):'—';
 const save=async()=>{if(item.kind==='company')return;const response=await workspace(token,{action:'save',p:{kind:item.kind,id:item.id,saved:!saved}},z.object({saved:z.boolean()}));setSaved(response.saved);};
 return <article className={`pc-search-result pc-search-result-${item.kind}`}>
  {item.kind==='company'?<PcLogo ticker={item.ticker} size={78}/>:item.kind==='event'?<div className="pc-search-date-tile"><span>{datePart('month')}</span><b>{datePart('day')}</b></div>:<span className="pc-search-file-tile"><Icon name="file" size={29}/><b>{/\.pdf(?:\?|$)/i.test(item.source_url??'')?'PDF':t('문서','DOC')}</b></span>}
  <div className="pc-search-result-body">{item.kind==='company'?<><Link href={resourceHref(item)} onClick={track} className="pc-search-result-title">{item.company_name}<small>{item.ticker}</small></Link><div className="pc-search-company-market">{item.market}</div></>:<><div className="pc-search-result-meta"><span>{item.kind==='event'?(eventNames[item.category]??item.category):t('공식 자료','Official source')}</span><time dateTime={item.published_at??undefined}>{prefs.date(item.published_at,item.publication_precision)}</time></div><Link href={resourceHref(item)} onClick={track} className="pc-search-result-title">{item.title}</Link></>}{item.summary&&<p>{item.summary}</p>}<div className="pc-search-result-tags"><Link href={`/companies/${item.company_id}`}>{item.ticker}</Link><span>{item.market}</span>{item.category!=='company'&&<span>{item.category}</span>}</div></div>
  <div className="pc-search-result-actions">{item.kind==='company'?<><div className={`pc-search-company-quote ${quote?.change_pct==null?'':quote.change_pct>=0?'pc-up':'pc-down'}`}><PcChart values={quote?.history.map(point=>point.close)??[]}/><strong>{money(quote?.price,quote?.currency??'USD',prefs.value.locale)}</strong><small>{quote?.change_pct==null?t('시세 확인 전','Quote unavailable'):`${quote.change_pct>=0?'+':''}${quote.change_pct.toFixed(2)}%`}</small></div><Link href={resourceHref(item)} onClick={track}>{t('기업 개요 보기','Company overview')} ›</Link></>:<button disabled={action.busy} onClick={()=>void action.run(save)} aria-label={`${item.title} ${saved?t('저장 취소','Unsave'):t('저장','Save')}`} aria-pressed={saved}><Icon name="star" size={19}/></button>}</div><PcNotice action={action}/>
 </article>;
}
