'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useAuth} from '@/components/auth';
import {Icon,type IconName} from '@/components/icons';
import {usePcResource as useResource} from './data';
import {calendarSchema,feedSchema,notificationsSchema,portfolioSchema,watchlistSchema,type EventCard} from '@/lib/contracts';
import {useQuotes} from '@/workspace/market';
import {usePrefs} from '@/workspace/preferences';
import {valuePortfolio,referenceRateSchema,formatExactMoney,type ReferenceRate} from '@/mobile/portfolio-math';
import {PcDataState,PcEmpty,PcHeading,PcLogo,PcPanel} from './ui';
import './today.css';

const percent=(value:number|null|undefined)=>value==null||!Number.isFinite(value)?'—':`${value>0?'+':''}${value.toFixed(2)}%`;
const types:Record<string,[string,string]>={earnings:['실적','Earnings'],product:['제품','Product'],guidance:['전망','Guidance'],contract:['계약','Contract'],partnership:['협업','Partnership'],regulation:['규제','Regulation'],risk:['위험','Risk'],capex:['투자','Investment'],dividend:['배당','Dividend'],management:['경영','Management'],business:['사업','Business']};
function CalendarDate({value}:{value:string}){const {value:preferences}=usePrefs();const timestamp=Date.parse(value.length===10?`${value}T00:00:00Z`:value);return Number.isNaN(timestamp)?<span>—</span>:<time dateTime={value}>{new Intl.DateTimeFormat(preferences.locale==='ko'?'ko-KR':'en-US',{month:'short',day:'numeric',timeZone:value.length===10?'UTC':preferences.timezone}).format(timestamp)}<small>{new Intl.DateTimeFormat(preferences.locale==='ko'?'ko-KR':'en-US',{weekday:'short',timeZone:value.length===10?'UTC':preferences.timezone}).format(timestamp)}</small></time>;}
function SummaryIcon({name,color}:{name:IconName;color:string}){return <span className={`pc-today-summary-icon ${color}`}><Icon name={name} size={27}/></span>;}
function Change({event}:{event:EventCard}){const {text:t,date}=usePrefs();return <article className="pc-today-change"><Link href={`/companies/${event.company.id}`} aria-label={`${event.company.name} ${t('기업 개요','company overview')}`}><PcLogo ticker={event.company.ticker} size={62}/></Link><div><div className="pc-today-company"><Link href={`/companies/${event.company.id}`}>{event.company.name}</Link><span>{event.company.ticker}</span></div><Link className="pc-today-event-title" href={`/events/${event.id}`}>{event.headline}</Link><p>{event.what_happened}</p></div><div className="pc-today-change-meta"><span className={`pc-today-tag ${event.event_type}`}>{types[event.event_type]?t(...types[event.event_type]):event.event_type}</span><time dateTime={event.published_at}>{date(event.published_at,event.publication_precision)}</time></div></article>;}
export function DesktopToday(){
 const {me}=useAuth(),{text:t,value:preferences,date}=usePrefs();
 const feed=useResource('/v1/feed?days=30&limit=5&offset=0',feedSchema),watch=useResource('/v1/watchlist',watchlistSchema),portfolio=useResource('/v1/portfolio',portfolioSchema),notifications=useResource('/v1/notifications',notificationsSchema);
 const [now]=useState(()=>Date.now()),[fx,setFx]=useState<ReferenceRate|null>(null),[fxLoading,setFxLoading]=useState(true),[fxRevision,setFxRevision]=useState(0);
 const dateParts=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:preferences.timezone}).formatToParts(now),part=(type:string)=>dateParts.find(p=>p.type===type)?.value??'',today=`${part('year')}-${part('month')}-${part('day')}`,until=new Date(Date.parse(`${today}T00:00:00Z`)+30*86400000).toISOString().slice(0,10);
 const calendar=useResource(`/v1/calendar?from_date=${today}&until_date=${until}`,calendarSchema);
 const positions=portfolio.data?.positions??[],watched=watch.data?.items??[],prices=useQuotes([...new Set([...positions.map(p=>p.company.ticker),...watched.map(c=>c.ticker)])],'1m'),valuation=valuePortfolio(positions,prices.quotes,fx,now),locale=preferences.locale==='ko'?'ko-KR':'en-US';
 useEffect(()=>{const ctrl=new AbortController();let active=true;setFxLoading(true);fetch('/api/us/reference-rate',{cache:'no-store',signal:AbortSignal.any([ctrl.signal,AbortSignal.timeout(25000)])}).then(async response=>{if(!response.ok)throw new Error('unavailable');return referenceRateSchema.parse(await response.json());}).then(value=>{if(active)setFx(value);}).catch(()=>{if(active)setFx(null);}).finally(()=>{if(active)setFxLoading(false);});return()=>{active=false;ctrl.abort();};},[fxRevision]);
 const watchQuotes=watched.map(company=>({company,quote:prices.quotes.find(q=>q.symbol===company.ticker&&q.price!==null&&q.price>=0&&Number.isFinite(Date.parse(q.as_of))&&Date.parse(q.as_of)<=now+300000&&now-Date.parse(q.as_of)<=7*86400000)})),priced=watchQuotes.filter(item=>item.quote?.change_pct!=null),average=priced.length?priced.reduce((sum,item)=>sum+item.quote!.change_pct!,0)/priced.length:null;
 const sameDay=(timestamp:string)=>{if(!Number.isFinite(Date.parse(timestamp)))return false;const parts=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:preferences.timezone}).formatToParts(new Date(timestamp));return ['year','month','day'].map(type=>parts.find(p=>p.type===type)?.value).join('-')===today;};
 const winners=priced.filter(item=>item.quote!.change_pct!>0).sort((a,b)=>b.quote!.change_pct!-a.quote!.change_pct!).slice(0,5),unread=notifications.data?.filter(item=>!item.read_at&&sameDay(item.created_at))??[],upcoming=(calendar.data??[]).filter(item=>/^\d{4}-\d{2}-\d{2}$/.test(item.occurs_on)&&item.occurs_on>=today&&item.occurs_on<=until&&Number.isFinite(Date.parse(item.occurs_on))&&new Date(item.occurs_on).toISOString().slice(0,10)===item.occurs_on).sort((a,b)=>a.occurs_on.localeCompare(b.occurs_on)).slice(0,4),currency=valuation.currency??'KRW';
 const hour=Number(new Intl.DateTimeFormat('en-US',{hour:'numeric',hourCycle:'h23',timeZone:preferences.timezone}).format(now)),greeting=hour<12?t('좋은 아침이에요!','Good morning!'):hour<18?t('좋은 오후예요!','Good afternoon!'):t('좋은 저녁이에요!','Good evening!');
 const more=(href:string)=> <Link className="pc-today-more" href={href}>{t('전체 보기','View all')}<span aria-hidden="true">›</span></Link>;
 return <div className="pc-today" data-testid="desktop-today"><PcHeading eyebrow={`${me?.display_name??''}${t('님, ',', ')}${greeting}`} title={t('오늘의 변화 ☀️','Today’s changes ☀️')} description={t('시장의 중요한 변화를 한눈에 확인하고, 근거로 더 깊이 이해하세요.','See important market changes at a glance and follow the evidence.')} action={<div className="pc-today-date"><time>{new Intl.DateTimeFormat(locale,{month:'long',day:'numeric',weekday:'short',timeZone:preferences.timezone}).format(now)}</time><p>{t('오늘도 현명한 한 걸음을','A clearer perspective,')}<br/>{t('응원합니다.','one day at a time.')}</p></div>}/>
 <section className="pc-today-market" aria-label={t('시장 지표','Market indicators')}>{[['코스피','KOSPI'],['코스닥','KOSDAQ'],['나스닥','NASDAQ'],['S&P 500','S&P 500']].map(([ko,en],index)=><Link key={en} href="/us" className={index<2?'warm':'cool'}><strong>{t(ko,en)}</strong><b>—</b><span>{t('지수 데이터 미연결','Index data unavailable')}</span><Icon name="timeline" size={48}/></Link>)}<div className="cool"><strong>{t('달러/원','USD/KRW')}</strong><b>{valuation.fx?valuation.fx.rate.toLocaleString(locale,{minimumFractionDigits:2,maximumFractionDigits:2}):'—'}</b><span>{fxLoading?t('기준환율 확인 중…','Loading reference rate…'):valuation.fx?`${date(valuation.fx.date,'date')} · ${t('일일 기준','Daily reference')}`:t('일일 기준환율 확인 전','Daily reference unavailable')}</span>{!fxLoading&&!valuation.fx&&<button className="pc-market-retry" onClick={()=>setFxRevision(v=>v+1)} aria-label={t('기준환율 다시 시도','Retry reference rate')}>↻</button>}</div></section>
 <section className="pc-today-summaries" aria-label={t('내 투자 요약','My investment summary')}>
 <PcPanel className="pc-today-summary"><SummaryIcon name="pie" color="blue"/><div className="pc-today-summary-main"><Link href="/portfolio">{t('내 포트폴리오','My portfolio')}<span>›</span></Link><b>{portfolio.loading?t('확인 중','Loading'):formatExactMoney(valuation.value,currency,locale)}</b><small className={valuation.dailyPct!=null&&valuation.dailyPct<0?'negative':'positive'}>{percent(valuation.dailyPct)} <span>{t('일간 등락','daily change')}</span></small></div><div className="pc-today-summary-aside"><p><span>{t('보유','Holdings')}</span><strong>{portfolio.data?positions.length:'—'}</strong></p><p><span>{t('평가 가능','Priced')}</span><strong>{valuation.pricedCount}/{positions.length}</strong></p><p><span>{t('기준 통화','Currency')}</span><strong>{valuation.currency??'—'}</strong></p></div></PcPanel>
 <PcPanel className="pc-today-summary"><SummaryIcon name="star" color="blue"/><div className="pc-today-summary-main"><Link href="/watchlist">{t('관심종목','Watchlist')}<span>›</span></Link><b>{watch.data?`${watched.length}${t('개','')}`:'—'}</b><small className={average!=null&&average<0?'negative':'positive'}>{percent(average)} <span>{t('평균 일간','avg. daily')} · {priced.length}/{watched.length}</span></small></div><div className="pc-today-summary-aside">{watchQuotes.slice(0,4).map(({company,quote})=><p key={company.id}><Link href={`/companies/${company.id}`}>{company.ticker}</Link><strong title={quote?`${date(quote.as_of)} · ${quote.source}`:t('시세 확인 전','Quote unavailable')} className={quote?.change_pct!=null&&quote.change_pct<0?'negative':'positive'}>{percent(quote?.change_pct)}</strong></p>)}{!watched.length&&<Link href="/explore">{t('기업 추가','Add companies')} ›</Link>}</div></PcPanel>
 <PcPanel className="pc-today-summary"><SummaryIcon name="bell" color="gold"/><div className="pc-today-summary-main"><Link href="/alerts">{t('오늘의 알림','Your notifications')}<span>›</span></Link><b>{notifications.data?`${unread.length}${t('개','')}`:'—'}</b><small>{t('오늘 도착한 안 읽은 알림','Unread arrivals today')}</small></div><div className="pc-today-summary-aside">{[['earnings',t('실적 발표','Earnings')],['product',t('제품','Products')],['guidance',t('전망','Guidance')]].map(([type,label],index)=><p key={type}><span><i className={`dot-${index}`}/>{label}</span><strong>{notifications.data?unread.filter(item=>item.event.event_type===type).length:'—'}</strong></p>)}<p><span><i className="dot-3"/>{t('기타','Other')}</span><strong>{notifications.data?unread.filter(item=>!['earnings','product','guidance'].includes(item.event.event_type)).length:'—'}</strong></p></div></PcPanel>
 </section>
 <div className="pc-today-resource-errors">{[watch,portfolio,notifications].map((result,index)=>result.error&&<PcDataState key={index} loading={false} error={result.error} retry={result.reload}/>)}</div>
 {(!prices.loading&&(prices.reason||priced.length<watched.length||valuation.pricedCount<positions.length))&&<p className="pc-today-coverage" role="status">{t('연결된 시세만 평가에 반영합니다. 미제공 종목은 —로 표시하며, 전체 시세가 없으면 총 평가액을 계산하지 않습니다.','Valuations use available quotes only. Unavailable prices remain —; the total requires complete quote coverage.')}</p>}
 <div className="pc-today-content">
 <PcPanel title={t('최근 중요 변화','Recent important changes')} icon="spark" action={more('/search?kind=event&sort=newest')} className="pc-today-changes"><div id="changes"/><PcDataState {...feed} retry={feed.reload}/>{!feed.loading&&!feed.error&&feed.data?.items.map(event=><Change key={event.id} event={event}/>)}{!feed.loading&&!feed.error&&!feed.data?.items.length&&<PcEmpty title={t('아직 확인된 변화가 없습니다.','No verified changes yet.')} description={t('게시된 공시와 근거가 준비되면 관심종목의 변화를 보여드립니다.','Changes will appear when verified filings and evidence are published.')} href="/explore" label={t('기업 탐색','Explore companies')}/>}{feed.data?.stale&&<p className="pc-today-feed-status">{t('새 자료를 기다리고 있습니다.','Waiting for new source information.')} {feed.data.latest_ingested_at&&date(feed.data.latest_ingested_at)}</p>}</PcPanel>
 <PcPanel title={t('주요 일정','Upcoming events')} icon="calendar" action={more('/calendar')} className="pc-today-calendar"><PcDataState {...calendar} retry={calendar.reload}/>{!calendar.loading&&!calendar.error&&upcoming.map(item=>{const company=watched.find(c=>c.id===item.company_id)??positions.find(p=>p.company.id===item.company_id)?.company;return <Link className="pc-today-calendar-row" key={item.id} href={item.event_id?`/events/${item.event_id}`:item.company_id?`/companies/${item.company_id}`:'/calendar'}><CalendarDate value={item.occurs_on}/>{company?<PcLogo ticker={company.ticker} size={27}/>:<Icon name="calendar" size={25}/>}<div><strong>{item.title}</strong><p>{item.origin==='official'?t('공식 출처에서 확인한 일정','Date from an official source'):t('내가 등록한 일정','Your calendar entry')}</p></div></Link>;})}{!calendar.loading&&!calendar.error&&!upcoming.length&&<PcEmpty title={t('예정된 일정이 없습니다.','No upcoming events.')} description={t('앞으로 30일 동안 확인된 일정입니다.','Verified events for the next 30 days.')} href="/calendar" label={t('캘린더 열기','Open calendar')}/>}</PcPanel>
 <div className="pc-today-right"><PcPanel title={t('관심종목 상승률','Watchlist gainers')} icon="timeline" action={more('/watchlist')} className="pc-today-gainers">{winners.map(({company,quote},index)=><Link key={company.id} href={`/companies/${company.id}`}><span className="pc-today-rank">{index+1}</span><PcLogo ticker={company.ticker} size={30}/><span>{company.ticker}</span><span className="pc-today-gainer-name">{company.name}</span><strong title={quote?`${date(quote.as_of)} · ${quote.source}`:undefined}>{percent(quote?.change_pct)}</strong></Link>)}{!prices.loading&&!winners.length&&<PcEmpty title={t('확인된 상승 종목이 없습니다.','No gainers with available quotes.')} description={t('내 관심종목의 일간 등락 기준','Daily changes in your watchlist')}/>}<p className="pc-today-rank-note">{t(`시세 확인 ${priced.length}/${watched.length}종목 · 일간 등락`,`Quotes ${priced.length}/${watched.length} · daily change`)}{priced.length>0&&<span> · {t('시세 시각','Quote times')}: {[...new Set(priced.map(item=>date(item.quote!.as_of)))].join(' / ')}</span>}</p></PcPanel>
 <PcPanel title={t('알림 센터','Notification center')} icon="bell" action={more('/alerts')} className="pc-today-notification-list">{!notifications.loading&&!notifications.error&&notifications.data?.slice(0,3).map(item=><Link key={item.id} href={`/events/${item.event.id}`}><i className={item.read_at?'read':''}/><div><p>{item.event.headline}</p><time dateTime={item.created_at}>{date(item.created_at)}</time></div><span aria-hidden="true">›</span></Link>)}{!notifications.loading&&!notifications.error&&!notifications.data?.length&&<PcEmpty title={t('새 알림이 없습니다.','No notifications yet.')}/>}</PcPanel></div></div>
 <Link className="pc-today-alert-cta" href="/settings/notifications"><span><Icon name="timeline" size={29}/></span><div><strong>{t('시장의 중요한 변화를 놓치지 마세요.','Stay close to important changes.')}</strong><p>{t('관심종목과 포트폴리오에 맞춘 알림으로 더 빠르게 확인하세요.','Set alerts for the companies in your watchlist and portfolio.')}</p></div><b>{t('알림 설정하기','Set up alerts')}<span aria-hidden="true">›</span></b></Link>
 </div>;
}
