'use client';

import Link from 'next/link';
import {useEffect, useState} from 'react';
import {useAuth} from '@/components/auth';
import {Icon} from '@/components/icons';
import {usePcResource as useResource} from './data';
import {body, emptySchema, request} from '@/lib/api';
import {companiesSchema, feedSchema, notificationsSchema, watchlistSchema} from '@/lib/contracts';
import {useQuotes} from '@/workspace/market';
import {usePrefs} from '@/workspace/preferences';
import {useMutation} from '@/workspace/ui';
import {PcPanel, PcHeading, PcLogo, PcChart, PcEmpty, PcDataState, PcNotice, PcModal} from './ui';
import './watchlist.css';

function money(value:number|null|undefined,currency:string,locale:string){return value==null?'—':new Intl.NumberFormat(locale==='ko'?'ko-KR':'en-US',{style:'currency',currency,maximumFractionDigits:currency==='KRW'?0:2}).format(value);}

export default function DesktopWatchlist(){
 const {token,me}=useAuth(),prefs=usePrefs(),{text:t}=prefs,action=useMutation();
 const list=useResource('/v1/watchlist',watchlistSchema),feed=useResource('/v1/feed?days=180&limit=100',feedSchema),notifications=useResource('/v1/notifications?limit=100',notificationsSchema);
 const [market,setMarket]=useState(''),[sort,setSort]=useState('name'),[direction,setDirection]=useState('all'),[visible,setVisible]=useState(6),[selected,setSelected]=useState<string[]>([]),[add,setAdd]=useState(false),[query,setQuery]=useState(''),[search,setSearch]=useState('');
 const catalog=useResource(add?`/v1/companies?q=${encodeURIComponent(search)}&limit=50`:null,companiesSchema);
 useEffect(()=>{const timer=setTimeout(()=>setSearch(query.trim()),250);return()=>clearTimeout(timer);},[query]);
 const items=list.data?.items??[],ids=new Set(items.map(item=>item.id)),prices=useQuotes(items.map(item=>item.ticker),'1m'),quoteMap=new Map(prices.quotes.map(quote=>[quote.symbol.toUpperCase(),quote]));
 const priced=items.filter(item=>quoteMap.get(item.ticker.toUpperCase())?.price!=null),knownChanges=items.filter(item=>quoteMap.get(item.ticker.toUpperCase())?.change_pct!=null),rising=items.filter(item=>(quoteMap.get(item.ticker.toUpperCase())?.change_pct??0)>0),falling=items.filter(item=>(quoteMap.get(item.ticker.toUpperCase())?.change_pct??0)<0),markets=[...new Set(items.map(item=>item.market))].sort();
 const filtered=items.filter(item=>(!market||item.market===market)&&(direction==='all'||direction==='up'&&(quoteMap.get(item.ticker.toUpperCase())?.change_pct??0)>0||direction==='down'&&(quoteMap.get(item.ticker.toUpperCase())?.change_pct??0)<0)).sort((a,b)=>{if(sort==='change'){const av=quoteMap.get(a.ticker.toUpperCase())?.change_pct,bv=quoteMap.get(b.ticker.toUpperCase())?.change_pct;if(av!=null||bv!=null)return av==null?1:bv==null?-1:bv-av;}return a.name.localeCompare(b.name,prefs.value.locale);});
 const shown=filtered.slice(0,visible),allSelected=shown.length>0&&shown.every(item=>selected.includes(item.id)),watchedEvents=(feed.data?.items??[]).filter(item=>ids.has(item.company.id)),recentNotifications=(notifications.data??[]).filter(item=>ids.has(item.event.company.id)).slice(0,4),selectedExisting=selected.filter(id=>ids.has(id));
 async function mutate(id:string,method:'PUT'|'DELETE'){await request(`/v1/watchlist/${encodeURIComponent(id)}`,token,emptySchema,body(method));list.reload();feed.reload();notifications.reload();if(method==='DELETE')setSelected(values=>values.filter(value=>value!==id));}
 async function removeSelected(){try{for(const id of selectedExisting){await request(`/v1/watchlist/${encodeURIComponent(id)}`,token,emptySchema,body('DELETE'));setSelected(values=>values.filter(value=>value!==id));}}finally{list.reload();feed.reload();notifications.reload();}}
 function toggleShown(){setSelected(values=>allSelected?values.filter(id=>!shown.some(item=>item.id===id)):[...new Set([...values,...shown.map(item=>item.id)])]);}
 return <div className="pc-watch-page" data-screen="desktop-watchlist">
  <PcHeading eyebrow={t(`${me?.display_name??''}님, 관심 있는 기업의 변화를 확인해보세요.`,`${me?.display_name??''}, follow the companies that matter to you.`)} title={t('관심종목','Watchlist')} description={t('관심 있는 종목을 모아두고, 중요한 변화와 소식을 놓치지 마세요.','Keep your companies together and follow their verified changes.')} action={<div className="pc-watch-date"><strong>{new Intl.DateTimeFormat(prefs.value.locale==='ko'?'ko-KR':'en-US',{year:'numeric',month:'long',day:'numeric',weekday:'long',timeZone:prefs.value.timezone}).format(new Date())}</strong><span>{t('오늘도 좋은 투자 인사이트를 발견해 보세요.','Discover a new perspective today.')}</span></div>}/>
  <div className="pc-watch-summary">
   <button aria-pressed={direction==='all'} onClick={()=>{setDirection('all');setVisible(6);}}><span><Icon name="star" size={19}/>{t('관심종목','Watched companies')}</span><strong>{list.data?items.length:'—'}<small>{t('종목',' stocks')}</small></strong><p>{t('내가 등록한 기업','Companies you follow')}</p></button>
   <div><span><Icon name="pie" size={19}/>{t('시세 확인','Available quotes')}</span><strong>{list.data&&!prices.loading?priced.length:'—'}<small> / {list.data?items.length:'—'}</small></strong><p>{t('연결된 공급자 시세 기준','Quotes from connected providers')}</p></div>
   <button className="pc-watch-up-card" aria-pressed={direction==='up'} onClick={()=>{setDirection('up');setVisible(6);}}><span><i>↗</i>{t('상승 종목','Rising stocks')}</span><strong>{list.data&&!prices.loading&&knownChanges.length?rising.length:'—'}<small>{t('종목',' stocks')}</small></strong><p>{t(`확인된 ${knownChanges.length}개 일간 변동 기준`,`Based on ${knownChanges.length} verified daily changes`)}</p></button>
   <button className="pc-watch-down-card" aria-pressed={direction==='down'} onClick={()=>{setDirection('down');setVisible(6);}}><span><i>↘</i>{t('하락 종목','Falling stocks')}</span><strong>{list.data&&!prices.loading&&knownChanges.length?falling.length:'—'}<small>{t('종목',' stocks')}</small></strong><p>{t(`확인된 ${knownChanges.length}개 일간 변동 기준`,`Based on ${knownChanges.length} verified daily changes`)}</p></button>
  </div>
  <PcNotice action={action}/><PcDataState loading={list.loading} error={list.error} retry={list.reload}/>{prefs.error&&<PcDataState loading={false} error={prefs.error} retry={prefs.reload}/>}
  <div className="pc-watch-columns"><PcPanel className="pc-watch-list-panel" title={`${t('관심종목 목록','Your watchlist')} ${list.data?items.length:'—'}`} icon="star" action={<div className="pc-watch-toolbar"><select aria-label={t('관심종목 시장 필터','Watchlist market filter')} value={market} onChange={e=>{setMarket(e.target.value);setVisible(6);}}><option value="">{t('전체 시장','All markets')}</option>{markets.map(name=><option key={name}>{name}</option>)}</select><button disabled title={t('기업 산업 분류 데이터가 아직 제공되지 않습니다.','Industry classifications are not available.')}>{t('섹터','Sector')} ⌄</button><select aria-label={t('관심종목 정렬','Watchlist sort')} value={sort} onChange={e=>setSort(e.target.value)}><option value="name">{t('이름순','Name')}</option><option value="change">{t('등락률순','Daily change')}</option></select><button className="pc-button pc-button-primary" onClick={()=>setAdd(true)}><Icon name="plus" size={16}/>{t('종목 추가','Add stock')}</button></div>}>
   {(selectedExisting.length>0||direction!=='all')&&<div className="pc-watch-selection">{selectedExisting.length>0&&<><span>{selectedExisting.length}{t('개 선택',' selected')}</span><button disabled={action.busy} onClick={()=>void action.run(removeSelected,t('선택한 관심종목을 삭제했습니다.','Selected companies removed.'))}>{t('선택 삭제','Remove selected')}</button></>}{direction!=='all'&&<button onClick={()=>setDirection('all')}>{direction==='up'?t('상승 종목','Rising stocks'):t('하락 종목','Falling stocks')} ×</button>}</div>}
   <div className="pc-watch-table-scroll"><table className="pc-watch-table"><thead><tr><th><input type="checkbox" aria-label={t('표시된 관심종목 전체 선택','Select all visible companies')} checked={allSelected} disabled={!shown.length} onChange={toggleShown}/></th><th>{t('기업','Company')}</th><th>{t('현재가','Quote')}</th><th>{t('전일 대비','Daily change')}</th><th>{t('최근 1개월','Past month')}</th><th>{t('알림 설정','Alerts')}</th><th><span className="pc-watch-sr-only">{t('더 보기','More actions')}</span></th></tr></thead><tbody>{shown.map(company=>{const quote=quoteMap.get(company.ticker.toUpperCase()),change=quote?.change_pct??null,muted=prefs.value.muted_companies.includes(company.id),delta=quote?.price!=null&&change!==null&&change>-100?quote.price-quote.price/(1+change/100):null;return <tr key={company.id}>
    <td><input type="checkbox" aria-label={`${company.name} ${t('선택','select')}`} checked={selected.includes(company.id)} onChange={e=>setSelected(values=>e.target.checked?[...values,company.id]:values.filter(id=>id!==company.id))}/></td>
    <td><Link className="pc-watch-company" href={`/companies/${company.id}`}><PcLogo ticker={company.ticker} size={46}/><span><strong>{company.name}</strong><small>{company.ticker} · {company.market}</small></span></Link></td>
    <td className="pc-watch-price" title={quote?`${quote.source} · ${prefs.date(quote.as_of)}`:t('연결된 시세가 없습니다.','No connected quote.')}>{money(quote?.price,quote?.currency??'USD',prefs.value.locale)}</td>
    <td className={`pc-watch-change ${change===null?'':change>=0?'pc-watch-positive':'pc-watch-negative'}`}>{change===null?<span>—</span>:<><strong>{change>=0?'▲':'▼'} {delta===null?'':`${delta>=0?'+':''}${new Intl.NumberFormat(prefs.value.locale,{maximumFractionDigits:2}).format(delta)}`}</strong><span>{change>=0?'+':''}{change.toFixed(2)}%</span></>}</td>
    <td className={`pc-watch-chart ${change!==null&&change<0?'pc-watch-negative':'pc-watch-positive'}`}><PcChart values={quote?.history.map(point=>point.close)??[]}/></td>
    <td><button className={`pc-watch-alert ${muted?'muted':''}`} aria-label={`${company.name} ${t('알림','notifications')}`} aria-pressed={!muted} disabled={!prefs.loaded||prefs.busy||action.busy} title={muted?t('기업 알림 허용','Allow company notifications'):t('기업 알림 제외','Mute company notifications')} onClick={()=>void action.run(()=>prefs.save({muted_companies:muted?prefs.value.muted_companies.filter(id=>id!==company.id):[...prefs.value.muted_companies,company.id]}),muted?t('기업 알림 제외를 해제했습니다.','Company unmuted.'):t('기업을 알림에서 제외했습니다.','Company muted.'))}><Icon name="bell" size={21}/>{muted&&<i/>}</button></td>
    <td><details className="pc-watch-menu"><summary aria-label={`${company.name} ${t('더 보기','more actions')}`}>•••</summary><div><Link href={`/companies/${company.id}`}>{t('기업 개요','Company overview')}</Link><button disabled={action.busy} onClick={()=>void action.run(()=>mutate(company.id,'DELETE'),t('관심종목에서 삭제했습니다.','Company removed.'))}>{t('관심종목 삭제','Remove company')}</button></div></details></td>
   </tr>;})}</tbody></table></div>
   {!list.loading&&list.data&&!filtered.length&&<PcEmpty title={items.length?t('선택한 조건의 관심종목이 없습니다.','No companies match these filters.'):t('첫 관심종목을 추가해 보세요.','Add your first company.')} description={t('시세가 확인되지 않은 종목은 상승·하락 필터에 포함되지 않습니다.','Companies without verified changes are excluded from rising and falling filters.')}/>}
   {visible<filtered.length&&<button className="pc-watch-show-more" onClick={()=>setVisible(count=>count+6)}>{t('더 많은 종목 보기','Show more companies')} ⌄</button>}
   <div className="pc-watch-table-note"><span>{t('알림은 알림 설정과 기업별 제외 여부를 함께 적용합니다.','Company notification preferences apply together with your notification settings.')}</span><Link href="/settings/notifications">{t('알림 설정','Notification settings')} ›</Link></div>
  </PcPanel><aside className="pc-watch-aside"><PcPanel title={t('최근 알림','Recent notifications')} icon="clock" action={<Link href="/alerts">{t('전체 보기','View all')} ›</Link>}><PcDataState loading={notifications.loading} error={notifications.error} retry={notifications.reload}/><div className="pc-watch-activity">{recentNotifications.map(item=><Link key={item.id} href={`/events/${item.event.id}`}><span><Icon name="bell" size={17}/></span><div><strong>{item.event.company.name}</strong><p>{item.event.headline}</p><time dateTime={item.created_at}>{prefs.date(item.created_at)}</time></div></Link>)}</div>{notifications.data&&!recentNotifications.length&&<p className="pc-watch-empty-note">{t('관심종목의 최근 알림이 없습니다.','No recent notifications for your companies.')}</p>}</PcPanel>
   <PcPanel title={t('관심종목 주요 변화','Company changes')} icon="file" action={<Link href="/today">{t('전체 보기','View all')} ›</Link>}><PcDataState loading={feed.loading} error={feed.error} retry={feed.reload}/><div className="pc-watch-news">{watchedEvents.slice(0,5).map(item=><Link key={item.id} href={`/events/${item.id}`}><PcLogo ticker={item.company.ticker} size={36}/><div><strong>{item.company.name}</strong><p>{item.headline}</p><time dateTime={item.published_at}>{prefs.date(item.published_at,item.publication_precision)}</time></div></Link>)}</div>{feed.data&&!watchedEvents.length&&<p className="pc-watch-empty-note">{t('아직 확인된 변화가 없습니다.','No verified changes available yet.')}</p>}</PcPanel></aside></div>
  {!prices.loading&&items.length>0&&prices.reason&&<p className="pc-watch-data-note">{t('연결된 시세가 없는 종목은 —로 표시합니다. 시세와 변동률의 기준일은 종목별로 다를 수 있습니다.','Unavailable quotes display —. Quote dates may differ between companies.')}</p>}
  {prices.quotes.length>0&&<details className="pc-watch-sources"><summary>{t('시세 기준 및 출처','Quote dates and sources')}</summary>{prices.quotes.map(quote=><p key={quote.symbol}><strong>{quote.symbol}</strong> · {quote.source} · {prefs.date(quote.as_of)}</p>)}</details>}
  {add&&<PcModal title={t('관심종목 추가','Add a company')} onClose={()=>setAdd(false)}><PcNotice action={action}/><label className="pc-field"><span>{t('기업명 또는 종목코드','Company name or ticker')}</span><input className="pc-input" autoFocus maxLength={100} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('기업 검색','Search companies')}/></label><PcDataState loading={catalog.loading} error={catalog.error} retry={catalog.reload}/><div className="pc-watch-add-results">{!catalog.loading&&catalog.data?.map(company=><div key={company.id}><PcLogo ticker={company.ticker} size={39}/><Link href={`/companies/${company.id}`}><strong>{company.name}</strong><small>{company.ticker} · {company.market}</small></Link><button className="pc-button" disabled={action.busy||ids.has(company.id)} aria-label={`${company.name} ${ids.has(company.id)?t('추가됨','already added'):t('추가','add')}`} onClick={()=>void action.run(()=>mutate(company.id,'PUT'),t('관심종목에 추가했습니다.','Company added to your watchlist.'))}>{ids.has(company.id)?t('추가됨','Added'):t('+ 추가','+ Add')}</button></div>)}</div>{catalog.data&&!catalog.loading&&!catalog.data.length&&<PcEmpty title={t('검색 결과가 없습니다.','No matching companies.')}/>}</PcModal>}
 </div>;
}
export {DesktopWatchlist};
