import Link from 'next/link';
import MarketingLayout,{Hero,SectionTitle,ClosingBanner,Glyph,type GlyphName} from '@/components/marketing/layout';
import {AccountLink} from '@/components/marketing/actions';
import {Icon} from '@/components/icons';
export const metadata={title:'개인정보',description:'SignalBrief에서 처리하는 개인정보와 목적, 동의 설정 및 사용자 권리를 확인하세요.'};
const policies:readonly {id:string;icon:GlyphName;title:string;description:string;label:string;detail:string;tone:string}[]=[
 {id:'collection',icon:'bars',title:'수집하는 정보',description:'회원가입과 서비스 이용을 위해 필요한 계정 정보, 관심종목, 보유종목과 설정을 처리합니다.',label:'수집하는 정보 자세히 보기',detail:'인증 제공자는 이메일과 로그인 정보를 처리합니다. 앱은 사용자 ID, 표시 이름, 관심종목, 보유 수량과 평균 취득가, 질문, 알림·일정과 이용 설정을 저장합니다. 앱 데이터베이스에는 이메일을 별도로 저장하지 않습니다.',tone:'blue'},
 {id:'purpose',icon:'target',title:'사용 목적',description:'서비스 제공, 계정 관리와 사용자 설정에 맞는 정보 탐색을 위해 사용합니다.',label:'사용 목적 자세히 보기',detail:'계정 인증, 관심종목과 보유종목의 관련 이벤트 연결, 질문에 대한 근거 확인, 알림과 일정 관리에 사용합니다. 선택적 이용 통계는 동의한 경우에만 수집하고 설정에서 철회할 수 있습니다.',tone:'purple'},
 {id:'retention',icon:'database',title:'데이터 보관 및 보호',description:'계정별 접근 권한을 적용하고, 다른 사용자의 개인정보에 접근하지 못하도록 보호합니다.',label:'데이터 보관 정책 보기',detail:'사용자의 정보는 해당 계정의 접근 권한으로 보호합니다. 구체적인 보유기간, 처리위탁과 국외 이전 조건은 운영 정책에서 확정해 안내할 예정입니다. 계정 삭제 및 자료 삭제 요청 방법은 문의 안내에서 확인하세요.',tone:'green'},
 {id:'cookies',icon:'cookie',title:'쿠키 및 로그',description:'로그인 세션을 유지하고 서비스 이용을 돕는 브라우저 저장소와 필요한 로그를 사용합니다.',label:'쿠키 정책 보기',detail:'로그인 세션은 브라우저 저장소에 유지되며 로그아웃으로 해당 브라우저의 세션을 지울 수 있습니다. 선택적 이용 통계는 명시적으로 동의한 경우에만 수집합니다. 질문 내용과 보유 수량은 이용 통계로 보내지 않습니다.',tone:'blue'},
 {id:'sharing',icon:'user',title:'제3자 제공 및 처리',description:'계정 인증과 근거 질문 등 기능 제공에 필요한 범위에서 외부 제공자를 이용합니다.',label:'제3자 처리 정책 보기',detail:'Google 로그인과 Supabase 인증을 이용합니다. 근거 질문 처리 시 AI 제공자에게 질문과 공개 공시의 인용 후보를 보낼 수 있습니다. 보유 수량이나 취득가는 AI 요청에 보내지 않습니다. AI 요청의 저장 제한 설정이 제공자의 별도 보안 로그 보관 정책까지 없애는 것은 아닙니다.',tone:'purple'},
 {id:'rights',icon:'user',title:'사용자 권리',description:'개인정보와 동의 설정을 확인하고, 열람·정정·삭제를 요청할 수 있습니다.',label:'사용자 권리 자세히 보기',detail:'설정 페이지에서 선택적 이용 통계 동의를 변경할 수 있습니다. 동의 철회는 이후 이벤트에 적용됩니다. 이미 저장된 자료의 삭제, 계정 탈퇴와 개인정보 열람·정정 요청의 운영 접수 채널은 준비 중입니다.',tone:'green'},
];
export default function Privacy(){return <MarketingLayout current="/privacy"><Hero eyebrow="PRIVACY" title={<>소중한 당신의 정보를<br/>존중하고, <em>안전하게 지킵니다.</em></>} description={<>SignalBrief는 이용자 여러분의 개인정보를 소중히 생각하며,<br/>필요한 정보와 사용 목적을 투명하게 안내합니다.<br/>신뢰할 수 있는 서비스, 그 시작은 개인정보 보호입니다.</>} art="privacy" hideActions/><div className="public-info-container public-info-content"><SectionTitle eyebrow="OUR PRIVACY" title="신뢰를 바탕으로 하는 개인정보 보호 원칙">현재 앱에서 처리하는 정보와 설정을 확인하고,<br/>각 항목을 펼쳐 자세한 내용을 살펴보세요.</SectionTitle><div className="public-info-grid cols-3 privacy-policies">{policies.map(policy=><article key={policy.id} className="public-info-card" id={policy.id}><span className={'public-info-icon tone-'+policy.tone}><Glyph name={policy.icon}/></span><h3>{policy.title}</h3><p className="public-info-card-copy">{policy.description}</p><details><summary className="public-info-card-link">{policy.label} <Icon name="arrow" size={16}/></summary><div className="privacy-policy-detail"><p>{policy.detail}</p>{['rights','cookies','purpose'].includes(policy.id)&&<AccountLink href="/login" destination="/settings" className="public-info-card-link">동의 설정 관리 <Icon name="arrow" size={16}/></AccountLink>}{['rights','retention'].includes(policy.id)&&<Link href="#contact" className="public-info-card-link">문의 안내 보기 <Icon name="arrow" size={16}/></Link>}</div></details></article>)}</div><section className="public-info-contact" id="contact"><span className="public-info-icon tone-blue"><Glyph name="mail"/></span><div><h2>문의 방법</h2><p>개인정보 열람·정정·삭제와 서비스 이용에 관한 문의 채널을 준비 중입니다.<br/>공식 연락처와 응대 시간이 확정되면 이곳에 안내합니다.</p></div><div className="public-info-contact-info"><Glyph name="mail" size={28}/><div><span>문의 채널 준비 중</span><AccountLink href="/login" destination="/settings">계정 및 동의 설정 확인 <Icon name="arrow" size={15}/></AccountLink></div></div></section><section className="public-info-policy-scope" id="scope"><h2>서비스 범위와 안내 상태</h2><p>SignalBrief는 투자 정보 탐색과 근거 확인을 돕습니다. 매매 추천, 목표주가 또는 수익 보장을 제공하지 않습니다. 운영 연락처, 구체적인 보유기간, 처리위탁과 국외 이전 안내는 준비 중이며, 확정된 운영 정책을 이 페이지에 게시합니다.</p></section><ClosingBanner title="더 안전한 투자 환경, 함께 만들어갑니다." eyebrow="A TRUSTED TOMORROW" secondary={{href:'/about',label:'서비스 소개 보기'}}>여러분의 신뢰를 소중히 생각합니다.<br/>개인정보와 그 사용 목적을 확인하고 서비스를 시작하세요.</ClosingBanner></div></MarketingLayout>;}
