import Link from 'next/link';
import MarketingLayout,{ClosingBanner,type GlyphName} from '@/components/marketing/layout';
import {AccountLink} from '@/components/marketing/actions';
import {SecurityArt} from '@/components/marketing/design';
import {LegalToc,LegalSection} from '@/components/marketing/legal';
export const metadata={title:'개인정보',description:'SignalBrief에서 처리하는 개인정보와 목적, 동의 설정 및 사용자 권리를 확인하세요.'};
const policies:readonly {id:string;icon:GlyphName;title:string;description:string;label:string;detail:string;tone:string}[]=[
 {id:'collection',icon:'bars',title:'수집하는 정보',description:'회원가입과 서비스 이용을 위해 필요한 계정 정보, 관심종목, 보유종목과 설정을 처리합니다.',label:'수집하는 정보 자세히 보기',detail:'인증 제공자는 이메일과 로그인 정보를 처리합니다. 앱은 사용자 ID, 표시 이름, 관심종목, 보유 수량과 평균 취득가, 질문, 알림·일정과 이용 설정을 저장합니다. 앱 데이터베이스에는 이메일을 별도로 저장하지 않습니다.',tone:'blue'},
 {id:'purpose',icon:'target',title:'사용 목적',description:'서비스 제공, 계정 관리와 사용자 설정에 맞는 정보 탐색을 위해 사용합니다.',label:'사용 목적 자세히 보기',detail:'계정 인증, 관심종목과 보유종목의 관련 이벤트 연결, 질문에 대한 근거 확인, 알림과 일정 관리에 사용합니다. 선택적 이용 통계는 동의한 경우에만 수집하고 설정에서 철회할 수 있습니다.',tone:'purple'},
 {id:'retention',icon:'database',title:'데이터 보관 및 보호',description:'계정별 접근 권한을 적용하고, 다른 사용자의 개인정보에 접근하지 못하도록 보호합니다.',label:'데이터 보관 정책 보기',detail:'사용자의 정보는 해당 계정의 접근 권한으로 보호합니다. 구체적인 보유기간, 처리위탁과 국외 이전 조건은 운영 정책에서 확정해 안내할 예정입니다. 계정 삭제 및 자료 삭제 요청 방법은 문의 안내에서 확인하세요.',tone:'green'},
 {id:'cookies',icon:'cookie',title:'쿠키 및 로그',description:'로그인 세션을 유지하고 서비스 이용을 돕는 브라우저 저장소와 필요한 로그를 사용합니다.',label:'쿠키 정책 보기',detail:'로그인 세션은 브라우저 저장소에 유지되며 로그아웃으로 해당 브라우저의 세션을 지울 수 있습니다. 선택적 이용 통계는 명시적으로 동의한 경우에만 수집합니다. 질문 내용과 보유 수량은 이용 통계로 보내지 않습니다.',tone:'blue'},
 {id:'sharing',icon:'user',title:'제3자 제공 및 처리',description:'계정 인증과 근거 질문 등 기능 제공에 필요한 범위에서 외부 제공자를 이용합니다.',label:'제3자 처리 정책 보기',detail:'Google 로그인과 Supabase 인증을 이용합니다. 근거 질문 처리 시 AI 제공자에게 질문과 공개 공시의 인용 후보를 보낼 수 있습니다. 보유 수량이나 취득가는 AI 요청에 보내지 않습니다. AI 요청의 저장 제한 설정이 제공자의 별도 보안 로그 보관 정책까지 없애는 것은 아닙니다.',tone:'purple'},
 {id:'rights',icon:'user',title:'사용자 권리',description:'개인정보와 동의 설정을 확인하고, 열람·정정·삭제를 요청할 수 있습니다.',label:'사용자 권리 자세히 보기',detail:'설정 페이지에서 선택적 이용 통계 동의를 변경할 수 있습니다. 동의 철회는 이후 이벤트에 적용됩니다. 이미 저장된 자료의 삭제, 계정 탈퇴와 개인정보 열람·정정 요청의 운영 접수 채널은 준비 중입니다.',tone:'green'},
 {id:'account',icon:'lock',title:'계정 인증',description:'이메일과 Google 로그인을 Supabase 인증으로 처리합니다.',label:'계정 인증 자세히 보기',detail:'이메일 가입 시 인증 메일의 안내를 따라 완료합니다. 비밀번호 찾기는 등록한 이메일로 복구 링크를 요청합니다. 오류 또는 복구 안내는 계정 존재 여부를 노출하지 않도록 표시합니다.',tone:'blue'},
 {id:'analytics',icon:'bars',title:'선택적 이용 통계',description:'이용 통계는 선택적으로 동의한 경우에만 수집합니다.',label:'이용 통계 자세히 보기',detail:'선택적 이용 통계 동의는 설정에서 관리하고 철회할 수 있습니다. 개인 보유 수량과 질문 내용은 이용 통계에 보내지 않습니다. 동의 철회는 이후 이벤트에 적용됩니다.',tone:'blue'},
 {id:'changes',icon:'clock',title:'안내의 변경',description:'확정된 운영 정책과 실제 처리 범위를 이 페이지에 반영합니다.',label:'변경 안내 자세히 보기',detail:'운영 연락처, 구체적인 보유기간, 처리위탁과 국외 이전 조건은 준비 중입니다. 확정 시 이 안내를 갱신하며 아직 확정되지 않은 조건을 확정된 정책으로 표시하지 않습니다.',tone:'blue'},
 {id:'scope',icon:'book',title:'서비스 범위',description:'투자 정보 탐색과 근거 확인을 돕는 공개 베타입니다.',label:'서비스 범위 자세히 보기',detail:'매매 추천, 목표주가 또는 수익 보장을 제공하지 않습니다. 화면에 표시하는 합성 예시는 실제 기업의 자료나 투자 성과가 아닙니다. 정식 이용약관은 준비 중이며 현재 이용 범위는 서비스 이용 안내에서 확인할 수 있습니다.',tone:'blue'},
 {id:'contact',icon:'mail',title:'문의 방법',description:'개인정보 열람·정정·삭제와 서비스 문의 채널을 준비 중입니다.',label:'문의 방법 자세히 보기',detail:'공식 연락처와 응대 시간이 확정되면 이곳에 안내합니다. 현재 운영 접수 채널은 준비 중이며 확인되지 않은 연락처를 안내하지 않습니다. 계정과 선택적 동의 설정은 로그인 후 설정에서 확인하세요.',tone:'blue'},
];
export default function Privacy(){return <MarketingLayout current="/privacy"><section className="d-legal-hero"><div className="public-info-container public-info-hero-grid"><div className="public-info-hero-copy"><p className="d-eyebrow">PRIVACY</p><h1>개인정보 처리 안내</h1><p className="d-lead">어떤 정보를 처리하고, 어디에 사용하며, 어떻게 설정을 관리할 수 있는지 투명하게 안내합니다.</p><span className="d-legal-date">안내 갱신 · 2026년 10월 4일</span><p className="d-legal-status">보유기간과 운영 연락처 등 미확정 항목은 준비 상태를 함께 표시합니다.</p></div><div className="public-info-hero-art"><SecurityArt/></div></div></section><div className="public-info-container d-content"><div className="d-legal-layout"><LegalToc items={policies}/><div className="privacy-policies">{policies.map((policy,i)=><LegalSection key={policy.id} id={policy.id} number={i+1} title={policy.title} summary={policy.description}><p>{policy.detail}</p>{['rights','cookies','purpose','analytics','contact'].includes(policy.id)&&<AccountLink href="/login" destination="/settings" className="public-info-card-link">동의 설정 관리 →</AccountLink>}{['rights','retention'].includes(policy.id)&&<Link href="#contact" className="public-info-card-link">문의 안내 보기 →</Link>}{policy.id==='scope'&&<Link href="/terms" className="d-card-link">서비스 이용 안내 →</Link>}</LegalSection>)}</div></div><ClosingBanner title="내 정보와 이용 범위를 확인하고 시작하세요." secondary={{href:'/terms',label:'서비스 이용 안내'}}>선택적 동의 설정은 로그인 후 계정 설정에서 관리할 수 있습니다.</ClosingBanner></div></MarketingLayout>;}
