"use client";
import { useState,type FormEvent } from "react";
import Link from "next/link";
import { alertsSchema,alertSchema,notificationsSchema } from "@/lib/contracts";
import { useResource,PageHeading,Loading,ErrorState,Empty,useAction,ActionNotice } from "@/components/ui";
import { useAuth } from "@/components/auth";
import { body,request,emptySchema } from "@/lib/api";
import { dateText,typeLabels } from "@/lib/format";
export default function Alerts(){const {token}=useAuth(),rules=useResource("/v1/alerts",alertsSchema),notifications=useResource("/v1/notifications",notificationsSchema),action=useAction(),[name,setName]=useState(""),[score,setScore]=useState("0.4"),[type,setType]=useState("");
function add(e:FormEvent){e.preventDefault();void action.run(async()=>{await request("/v1/alerts",token,alertSchema,body("POST",{name,min_score:Number(score),event_types:type?[type]:[],enabled:true}));rules.reload();setName("");},"알림 규칙을 만들었습니다.");}
return <><PageHeading title="알림 센터" description="새로 게시되는 중요 이벤트를 앱 안에서 확인합니다. 이메일·푸시 발송은 포함하지 않습니다."/><ActionNotice action={action}/><div className="two-column"><section className="panel"><h2>받은 알림</h2>{notifications.loading?<Loading/>:notifications.error?<ErrorState message={notifications.error} retry={notifications.reload}/>:notifications.data?.length?notifications.data.map(item=><article key={item.id} className={`notification ${item.read_at?"":"unread"}`}><p className="small muted">{dateText(item.created_at)} · {item.read_at?"읽음":"새 알림"}</p><Link className="company-name" href={`/events/${item.event.id}`}>{item.event.headline}</Link><p>{item.event.company.name}</p>{!item.read_at&&<button className="button subtle" disabled={action.busy} onClick={()=>action.run(async()=>{await request(`/v1/notifications/${item.id}/read`,token,emptySchema,body("PUT"));notifications.reload();})}>읽음 처리</button>}</article>):<Empty title="새 알림이 없습니다."><p>규칙을 만든 이후 새로 게시된 관련 이벤트부터 알림이 생성됩니다.</p></Empty>}</section><div className="stack"><section className="panel"><h2>내 알림 규칙</h2>{rules.loading?<Loading/>:rules.error?<ErrorState message={rules.error} retry={rules.reload}/>:rules.data?.map(rule=><div className="list-row" key={rule.id}><div className="grow"><strong>{rule.name}</strong><p className="small muted">최소 점수 {Math.round(rule.min_score*100)}/100 · {rule.event_types.map(x=>typeLabels[x]??x).join(", ")||"모든 공시 유형"}</p></div><button className="button secondary" disabled={action.busy} aria-pressed={rule.enabled} onClick={()=>action.run(async()=>{const {id:unusedId,created_at:unusedCreated,...data}=rule;void unusedId;void unusedCreated;await request(`/v1/alerts/${rule.id}`,token,alertSchema,body("PUT",{...data,enabled:!rule.enabled}));rules.reload();})}>{rule.enabled?"켜짐":"꺼짐"}</button><button className="button subtle" disabled={action.busy} aria-label={`${rule.name} 삭제`} onClick={()=>action.run(async()=>{await request(`/v1/alerts/${rule.id}`,token,emptySchema,body("DELETE"));rules.reload();})}>삭제</button></div>)}</section><form onSubmit={add} className="panel form-stack"><h2>새 규칙</h2><label className="field"><span>규칙 이름</span><input required value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><label className="field"><span>이벤트 유형</span><select value={type} onChange={e=>setType(e.target.value)}><option value="">모든 유형</option>{Object.entries(typeLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="field"><span>최소 우선순위 {Math.round(Number(score)*100)}/100</span><input type="range" min="0" max="1" step="0.05" value={score} onChange={e=>setScore(e.target.value)}/></label><button className="button primary" disabled={action.busy}>규칙 만들기</button></form></div></div></>;}
