"use client";
import { useState,useEffect,type FormEvent } from "react";
import Link from "next/link";
import { calendarSchema } from "@/lib/contracts";
import { useResource,PageHeading,Loading,ErrorState,Empty,SourceLink,useAction,ActionNotice } from "@/components/ui";
import { useAuth } from "@/components/auth";
import { body,request,emptySchema } from "@/lib/api";
export default function Calendar(){const auth=useAuth(),result=useResource("/v1/calendar",calendarSchema),action=useAction(),[title,setTitle]=useState(""),[date,setDate]=useState("");
const track=auth.track; useEffect(()=>{track("calendar_opened",{screen:"calendar"});},[track]);
function add(e:FormEvent){e.preventDefault();void action.run(async()=>{await request("/v1/calendar",auth.token,calendarSchema.element,body("POST",{title,occurs_on:date,company_id:null}));setTitle("");setDate("");result.reload();},"일정을 저장했습니다.");}
return <><PageHeading title="이벤트 캘린더" description="원문에서 날짜가 확인된 예정 이벤트와 직접 등록한 일정을 구분해 보여드립니다."/><ActionNotice action={action}/><div className="two-column"><section className="panel"><h2>앞으로 90일</h2>{result.loading?<Loading/>:result.error?<ErrorState message={result.error} retry={result.reload}/>:result.data?.length?result.data.map(item=><article className="calendar-row" key={item.id}><time className="date-pill">{item.occurs_on}</time><div className="grow"><strong>{item.title}</strong><p><span className="badge">{item.origin==="user"?"내 일정":item.is_demo?"합성 공시 일정":"공식 공시 일정"}</span></p>{item.quote&&<blockquote>{item.quote}</blockquote>}{item.source_url&&<SourceLink url={item.source_url} demo={item.is_demo}/>} {item.event_id&&<Link className="text-button" href={`/events/${item.event_id}`}>관련 브리핑 →</Link>}</div>{item.origin==="user"&&<button className="button subtle" disabled={action.busy} onClick={()=>action.run(async()=>{await request(`/v1/calendar/${item.id}`,auth.token,emptySchema,body("DELETE"));result.reload();})}>삭제</button>}</article>):<Empty title="등록된 미래 일정이 없습니다."><p>자료에 명시되지 않은 실적 발표일을 추측하지 않습니다.</p></Empty>}</section><form className="panel form-stack" onSubmit={add}><h2>내 확인 일정</h2><label className="field"><span>제목</span><input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} placeholder="예: 새 공시 다시 확인하기"/></label><label className="field"><span>날짜</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><p className="small muted">직접 입력한 일정은 공식 공시 일정으로 표시되지 않습니다.</p><button className="button primary" disabled={action.busy}>일정 추가</button></form></div></>;}
