"use client";
import { useEffect,useState,type FormEvent } from "react";
import Link from "next/link";
import { useAuth } from "@/components/auth";
import { useResource,useAction,ActionNotice,Loading,ErrorState,PageHeading,SourceLink } from "@/components/ui";
import { detailSchema,answerSchema,type Answer } from "@/lib/contracts";
import { fieldLabels,changeLabels,dateText,pct,display,score } from "@/lib/format";
import { request,body,emptySchema } from "@/lib/api";
export default function Detail({id}:{id:string}){const auth=useAuth(),detail=useResource(`/v1/events/${encodeURIComponent(id)}`,detailSchema),ask=useAction(),feedback=useAction();const [question,setQuestion]=useState(""),[answer,setAnswer]=useState<Answer|null>(null),[comment,setComment]=useState("");
 const track=auth.track; useEffect(()=>{if(detail.data)track("brief_opened",{event_id:id,screen:"detail"});},[detail.data,id,track]);
 if(detail.loading)return <Loading/>;if(detail.error)return <ErrorState message={detail.error} retry={detail.reload}/>;if(!detail.data)return null;
 const d=detail.data,advanced=auth.me?.density==="advanced";
 function submit(e:FormEvent){e.preventDefault();void ask.run(async()=>{setAnswer(null);setAnswer(await request(`/v1/events/${id}/questions`,auth.token,answerSchema,body("POST",{question}),100000));});}
 const evidence=<div className="evidence-list">{d.evidence.map((ev,index)=><article className="evidence-card" key={`${ev.fact_id}-${ev.role}`} id={`evidence-${ev.fact_id}`}><div className="section-heading"><span className="badge">근거 {index+1} · {ev.role==="previous"?"이전 공시":"현재 공시"}</span><span className="small muted">{ev.is_demo?"합성 자료":`${ev.source_name} · Tier ${ev.source_tier}`}</span></div><blockquote>{ev.quote}</blockquote><div className="small muted">{dateText(ev.published_at,ev.publication_precision)} · {ev.location}</div><SourceLink url={ev.source_url} demo={ev.is_demo}/></article>)}</div>;
 return <><Link className="back-link" href="/today">← 오늘의 변화</Link><PageHeading eyebrow={`${d.event.company.name} · ${d.event.company.ticker}`} title={d.brief.headline} description={`${dateText(d.document.published_at,d.document.publication_precision)} · ${d.document.provider.toUpperCase()} · ${d.event.state==="published"?"게시됨":d.event.state}`}/>
 {d.event.state!=="published"&&<div className="notice">이 분석의 상태는 {d.event.state}입니다. 운영 검토 중이거나 이전 버전일 수 있습니다.</div>}
 <div className="detail-grid"><div className="detail-main"><section className="panel"><p className="eyebrow">FACT · 확인된 내용</p><h2>무슨 일이 있었나요?</h2><p className="lead">{d.brief.what_happened}</p><div className="fact-list">{d.facts.map(f=><div className="fact-row" key={f.id}><span className="badge">{fieldLabels[f.field]??f.field}</span><div className="grow">{f.value_raw!==null?<><strong>{f.value_raw} {f.unit}</strong>{advanced&&<p className="small muted">{f.period??"기간 미상"} · {f.scope} · {f.basis}</p>}</>:<p>{f.quote}</p>}</div><a className="source-link" href={`#evidence-${f.id}`} onClick={()=>track("evidence_opened",{event_id:id})}>근거 ↓</a></div>)}</div></section>
 <section className="panel"><p className="eyebrow">CHANGE · 이전과 비교</p><h2>무엇이 바뀌었나요?</h2>{d.changes.map(c=><div className="change-block" key={c.id}><div className="section-heading"><strong>{fieldLabels[c.field]??c.field}</strong><span className="badge">{changeLabels[c.change_type]??c.change_type}</span></div>{c.previous_fact_id?<><div className="comparison"><div><small>이전</small><p>{c.previous_value}</p><a className="small source-link" href={`#evidence-${c.previous_fact_id}`}>이전 근거 ↓</a></div><span className="compare-arrow" aria-hidden="true">→</span><div><small>현재</small><p>{c.current_value}</p><a className="small source-link" href={`#evidence-${c.current_fact_id}`}>현재 근거 ↓</a></div></div>{c.percentage_change!==null&&<p className="delta">{pct(c.percentage_change)} <span>동일 단위로 직접 계산한 변화율</span></p>}{advanced&&<p className="small muted">비교 기준: {c.comparison_kind} · 절대 변화: {display(c.absolute_change)} · 단위는 현재 수치 기준</p>}</>:<p className="muted">신뢰할 수 있는 동일 기준의 이전 근거가 부족합니다. 비교 수치를 만들지 않았습니다.</p>}</div>)}</section>
 <section className="panel"><p className="eyebrow">INTERPRETATION · 일반적 해석</p><h2>어떻게 읽어야 하나요?</h2><p>{d.brief.interpretation}</p><p className="small muted">이 항목은 원문 사실과 구분되는 일반적 읽기 안내이며 개별 투자 결론이 아닙니다.</p><div className="notice"><strong>UNCERTAINTY · 확인이 필요한 부분</strong><p>{d.brief.uncertainty}</p></div><h3>다음에 확인할 것</h3><p>{d.brief.monitor_next}</p></section>
 <section className="panel" id="evidence"><p className="eyebrow">EVIDENCE · 직접 확인하세요</p><h2>분석에 사용된 원문 근거</h2><p className="small muted">위치는 정규화한 문서 텍스트 기준입니다. PDF 페이지 번호나 원본 HTML 바이트 위치가 아닙니다.</p>{evidence}</section>
 <section className="panel"><p className="eyebrow">FOLLOW-UP · 근거 안에서 질문</p><h2>조금 더 확인하고 싶다면</h2><p className="muted">답변은 검증 가능한 원문 인용문으로 제한됩니다. 원문에 없으면 답변을 보류합니다.</p><form onSubmit={submit} className="form-stack"><label className="field"><span>공시에 관한 질문</span><textarea value={question} onChange={e=>setQuestion(e.target.value)} minLength={2} maxLength={1000} required placeholder="설비투자 계획의 근거를 보여줘" rows={3}/></label><button className="button primary" disabled={ask.busy}>{ask.busy?"근거를 찾는 중…":"근거 기반 질문하기"}</button></form><ActionNotice action={ask}/>{answer&&<div className="answer" role="status"><span className="badge">{answer.status==="answered"?"원문 근거 답변":answer.status==="policy_blocked"?"투자 추천 제외":"답변 보류"}</span><p>{answer.message}</p>{answer.evidence.map((ev,i)=><div key={i}><blockquote>{ev.quote}</blockquote><p className="small muted">{ev.location}</p><SourceLink url={ev.source_url} demo={d.event.is_demo}/></div>)}</div>}</section>
 <section className="panel"><h2>이 브리핑이 도움이 되었나요?</h2><label className="field"><span>의견 · 선택</span><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={1000} rows={2} placeholder="근거 또는 설명에서 개선할 부분을 알려주세요."/></label><div className="button-row">{[["helpful","도움이 됐어요"],["unclear","설명이 어려워요"],["wrong_evidence","근거가 잘못됐어요"]].map(([rating,label])=><button className="button secondary" disabled={feedback.busy} key={rating} onClick={()=>feedback.run(()=>request(`/v1/events/${id}/feedback`,auth.token,emptySchema,body("POST",{rating,comment})),"의견을 저장했습니다.")}>{label}</button>)}</div><ActionNotice action={feedback}/></section></div>
 <aside className="detail-aside"><section className="panel sticky-panel"><p className="eyebrow">WHY THIS MATTERS TO YOU</p><h2>나와의 관련성</h2><p>{d.event.ranking.reason}</p><div className="score-display">{score(d.event.ranking.score)}<small>/100</small></div><p className="small muted">개인화 우선순위입니다. 수익률 예측이나 정확도 확률이 아닙니다.</p><hr/><h3>출처 정보</h3><p>{d.document.title}</p><SourceLink url={d.document.source_url} demo={d.document.is_demo}/><p className="small muted">발행: {dateText(d.document.published_at,d.document.publication_precision)}{d.document.publication_precision==="date"?" (시각 미제공)":""}<br/>수집: {dateText(d.document.ingested_at)}</p><Link className="button secondary full" href={`/companies/${d.event.company.id}`}>기업 변화 타임라인 →</Link><details open={advanced}><summary>검증·모델·순위 상세</summary><p className="small">구조적 검증 지표: {score(d.event.confidence)}/100 · 통계적으로 보정된 정확도 아님</p><dl className="metadata"><dt>모델</dt><dd>{d.run.model_version??d.run.model}</dd><dt>프롬프트</dt><dd>{d.run.prompt_version}</dd><dt>분석 버전</dt><dd>{d.run.pipeline_version}</dd><dt>비용 USD</dt><dd>{display(d.run.cost_usd)}</dd><dt>처리 시간</dt><dd>{display(d.run.latency_ms)} ms</dd></dl><p className="small break-word">원본 SHA-256: {d.document.raw_sha256}</p>{d.validations.map((v,i)=><p className="small" key={i}>{v.status} · {v.reason}</p>)}<pre>{JSON.stringify(d.event.ranking,null,2)}</pre></details></section></aside></div></>;
}
