"use client";
import { useState,type FormEvent } from "react";
import Link from "next/link";
import { useAuth } from "@/components/auth";
import { useResource,PageHeading,Loading,ErrorState,useAction,ActionNotice } from "@/components/ui";
import { opsDashboardSchema,jsonObjectSchema,jsonArraySchema,companiesSchema } from "@/lib/contracts";
import { body,request,emptySchema } from "@/lib/api";
import { display } from "@/lib/format";
import { getSupabase } from "@/lib/supabase";
function rows(value:unknown):Record<string,unknown>[] {return Array.isArray(value)?value.filter((x):x is Record<string,unknown>=>Boolean(x)&&typeof x==="object"):[];}
export default function Ops(){const auth=useAuth(),allowed=Boolean(auth.me?.is_admin),action=useAction(),[reason,setReason]=useState(""),[duplicate,setDuplicate]=useState(""),[query,setQuery]=useState(""),[company,setCompany]=useState("");
 const dashboard=useResource(allowed?"/v1/ops/dashboard":null,opsDashboardSchema),queues=useResource(allowed?"/v1/ops/queues":null,jsonObjectSchema),docs=useResource(allowed?"/v1/ops/documents":null,jsonArraySchema),audit=useResource(allowed?"/v1/ops/audit?limit=30":null,jsonArraySchema),catalog=useResource(allowed?`/v1/companies?q=${encodeURIComponent(query)}`:null,companiesSchema);
 function reload(){dashboard.reload();queues.reload();docs.reload();audit.reload();}
 if(!allowed)return <ErrorState message="운영자만 접근할 수 있습니다. 클라이언트 화면과 별도로 모든 운영 API가 서버에서 권한을 검증합니다."/>;
 async function review(id:string,type:string){await action.run(async()=>{await request(`/v1/ops/events/${id}/action`,auth.token,jsonObjectSchema,body("POST",{action:type,reason,duplicate_of:type==="mark_duplicate"?duplicate:null}));reload();},"운영 작업을 감사 로그에 기록했습니다.");}
 function ingest(e:FormEvent){e.preventDefault();void action.run(async()=>{await request("/v1/ops/ingest",auth.token,jsonObjectSchema,body("POST",{company_id:company,lookback_days:7}));reload();},"수집 작업을 큐에 등록했습니다. Worker 연결 후 처리됩니다.");}
 const labels:Record<string,string>={documents_today:"오늘 수집 · 한국 시간",documents_today_utc:"오늘 수집 · UTC",documents_total:"전체 문서",events_total:"전체 이벤트",ai_runs_total:"분석 실행",low_confidence:"낮은 신뢰도",open_user_reports:"미처리 사용자 의견",average_pipeline_latency_ms:"평균 처리 시간 ms",known_cost_usd:"측정된 비용 USD",runs_with_unknown_cost:"비용 미측정 실행"};
 return <><PageHeading eyebrow="INTERNAL AI OPERATIONS" title="운영 콘솔" description="검토·원문·모델 실행·실패·비용과 운영 행동의 감사 기록을 확인합니다." actions={<button className="button secondary" onClick={reload}>새로고침</button>}/><ActionNotice action={action}/>{!auth.me?.demo_mode&&<div className="notice"><strong>공시·AI 처리 Worker는 아직 연결되지 않았습니다.</strong><p>작업은 데이터베이스 큐에 저장됩니다. 공급자 키와 승인된 Worker 환경을 연결하기 전에는 수집이나 유료 AI 실행이 시작되지 않습니다.</p></div>}{dashboard.loading?<Loading/>:dashboard.error?<ErrorState message={dashboard.error} retry={dashboard.reload}/>:dashboard.data&&<><div className="ops-metrics">{Object.entries(dashboard.data.metrics).map(([key,value])=><div className="panel" key={key}><span className="small muted">{labels[key]??key}</span><strong>{display(value)}</strong></div>)}</div><p className="small muted">{dashboard.data.cost_note}</p></>}
 <section className="panel"><h2>검토 대기 · 차단 · 중복</h2><div className="inline-fields"><label className="field"><span>운영 행동 사유 · 최소 5자</span><input value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={500} placeholder="예: 원문과 숫자 및 비교 기준을 확인했습니다"/></label><label className="field"><span>중복 대상 이벤트 ID · 중복 처리 시</span><input value={duplicate} onChange={e=>setDuplicate(e.target.value)}/></label></div>{queues.loading?<Loading/>:queues.error?<ErrorState message={queues.error} retry={queues.reload}/>:rows(queues.data?.events).length?rows(queues.data?.events).map(item=><article key={String(item.id)} className="review-row"><div><span className="badge">{String(item.state)}</span><h3><Link href={`/ops/documents/${item.document_id}`}>{String(item.title)}</Link></h3><Link className="source-link" href={`/ops/documents/${item.document_id}`}>원문·분석 이력 확인 →</Link></div><div className="button-row">{[["approve","승인"],["reject","거절"],["rerun","재실행"],["mark_duplicate","중복 처리"]].map(([type,label])=><button key={type} className="button secondary" disabled={action.busy||reason.trim().length<5||(type==="mark_duplicate"&&!duplicate)} onClick={()=>review(String(item.id),type)}>{label}</button>)}</div></article>):<p className="muted">현재 검토 대기 이벤트가 없습니다. 검증 실패는 승인 버튼으로 우회할 수 없습니다.</p>}</section>
 <div className="two-column"><section className="panel"><h2>실패·재시도 작업</h2>{rows(queues.data?.jobs).map(item=><div className="review-row" key={String(item.id)}><div><strong>{String(item.kind)} · {String(item.state)}</strong><p className="small break-word">{String(item.last_error??"")} · {String(item.attempts)}회</p></div>{["dead","retry"].includes(String(item.state))&&<button className="button secondary" disabled={action.busy} onClick={()=>action.run(async()=>{await request(`/v1/ops/jobs/${item.id}/retry`,auth.token,jsonObjectSchema,body("POST"));reload();})}>재시도</button>}</div>)}<details><summary>실패 AI 실행</summary><pre>{JSON.stringify(queues.data?.failed_runs??[],null,2)}</pre></details></section><section className="panel"><h2>사용자 의견</h2>{rows(queues.data?.reports).map(item=><div className="review-row" key={String(item.id)}><Link href={`/events/${item.event_id}`}>{String(item.rating)}</Link><p>{String(item.comment)}</p><button className="button secondary" disabled={action.busy} onClick={()=>action.run(async()=>{await request(`/v1/ops/reports/${item.id}/resolve`,auth.token,emptySchema,body("POST"));reload();})}>검토 완료</button></div>)}</section></div>
 <section className="panel"><h2>실제 데이터 수집</h2><p className="muted">먼저 공식 기업 목록을 동기화한 뒤 기업을 검색하세요. 합성 데모 기업에는 실제 수집을 실행하지 않습니다.</p><div className="button-row">{["dart","sec"].map(provider=><button key={provider} className="button secondary" disabled={action.busy||auth.me?.demo_mode} onClick={()=>action.run(async()=>{const result=await getSupabase().rpc("sb_admin_catalog_sync",{provider});if(result.error)throw new Error("기업 목록 동기화 작업을 등록하지 못했습니다.");reload();},"기업 목록 동기화를 큐에 등록했습니다.")}>{provider.toUpperCase()} 기업 목록 동기화</button>)}</div><form className="form-stack" onSubmit={ingest}><label className="field"><span>기업 검색</span><input value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="field"><span>수집 대상 기업</span><select required value={company} onChange={e=>setCompany(e.target.value)}><option value="">선택하세요</option>{catalog.data?.filter(c=>!c.is_demo).map(c=><option key={c.id} value={c.id}>{c.name} · {c.ticker}</option>)}</select></label><p className="small muted">최근 7일의 공식 공시를 대상으로 작업을 등록합니다.</p><button className="button primary" disabled={action.busy||!company||auth.me?.demo_mode}>수집 작업 등록</button></form></section>
 <section className="panel"><h2>최근 원본 문서</h2>{docs.error?<ErrorState message={docs.error} retry={docs.reload}/>:docs.data?.map(item=><div className="list-row" key={String(item.id)}><div className="grow"><Link href={`/ops/documents/${item.id}`} className="company-name">{String(item.title)}</Link><p className="small muted">{String(item.provider)} · {String(item.publication_date)} · {String(item.state)}</p></div><span className="badge">{item.is_demo?"합성":"실제"}</span></div>)}</section><section className="panel"><h2>감사 로그 · 원본 변경 충돌</h2>{audit.error&&<ErrorState message={audit.error} retry={audit.reload}/>}<details><summary>최근 운영 행동 {audit.data?.length??0}건</summary><pre>{JSON.stringify(audit.data??[],null,2)}</pre></details><details><summary>동일 접수번호의 원본 변경 후보</summary><pre>{JSON.stringify(audit.data?.filter(item=>item.action==="source_content_changed")??[],null,2)}</pre></details></section></>;
}
