"use client";
import { useState,type FormEvent } from "react";
import Link from "next/link";
import { useAuth } from "@/components/auth";
import { useResource,useAction,ActionNotice,Loading,ErrorState,Empty,PageHeading } from "@/components/ui";
import { portfolioSchema,companiesSchema } from "@/lib/contracts";
import { body,request,emptySchema } from "@/lib/api";
export default function Portfolio(){const {token}=useAuth(),action=useAction(),portfolio=useResource("/v1/portfolio",portfolioSchema),[query,setQuery]=useState(""),catalog=useResource(`/v1/companies?q=${encodeURIComponent(query)}&limit=50`,companiesSchema);
 const [company,setCompany]=useState(""),[quantity,setQuantity]=useState(""),[cost,setCost]=useState(""),[currency,setCurrency]=useState("USD");
 function submit(e:FormEvent){e.preventDefault();void action.run(async()=>{await request(`/v1/portfolio/positions/${encodeURIComponent(company)}`,token,emptySchema,body("PUT",{quantity,average_cost:cost||null,currency}));portfolio.reload();setQuantity("");setCost("");},"보유 정보를 저장했습니다.");}
 return <><PageHeading title="포트폴리오" description="보유 기업을 표시해 브리핑 우선순위에 반영합니다."/><ActionNotice action={action}/><div className="notice">{portfolio.data?.weighting_note??"실시간 가격과 환율은 제공하지 않습니다. 수량·평균 취득가를 저장하되 평가손익이나 시가 비중을 추정하지 않습니다."}</div><div className="two-column"><section className="panel"><h2>보유 기업</h2>{portfolio.loading?<Loading/>:portfolio.error?<ErrorState message={portfolio.error} retry={portfolio.reload}/>:portfolio.data?.positions.length?portfolio.data.positions.map(p=><div className="position-row" key={p.id}><div className="grow"><Link className="company-name" href={`/companies/${p.company.id}`}>{p.company.name}</Link><p className="small muted">{p.company.ticker}</p></div><div className="position-values"><strong>{p.quantity}주</strong><small>평균 {p.average_cost??"미입력"} {p.average_cost?p.currency:""}</small></div><button className="button subtle" disabled={action.busy} onClick={()=>{setCompany(p.company.id);setQuantity(p.quantity);setCost(p.average_cost??"");setCurrency(p.currency);setQuery(p.company.ticker);}}>수정</button><button className="button subtle" disabled={action.busy} aria-label={`${p.company.name} 보유 정보 삭제`} onClick={()=>action.run(async()=>{await request(`/v1/portfolio/positions/${p.company.id}`,token,emptySchema,body("DELETE"));portfolio.reload();},"보유 정보를 삭제했습니다.")}>삭제</button></div>):<Empty title="보유 정보를 추가해 주세요."><p>관심종목과 별도로 보유 여부를 우선순위에 반영합니다.</p></Empty>}</section><form className="panel form-stack" onSubmit={submit}><h2>보유 정보 추가 · 수정</h2><label className="field"><span>기업 검색</span><input value={query} onChange={e=>setQuery(e.target.value)} maxLength={100} placeholder="기업명 또는 종목코드"/></label>{catalog.error&&<ErrorState message={catalog.error} retry={catalog.reload}/>}<label className="field"><span>기업</span><select required value={company} onChange={e=>setCompany(e.target.value)}><option value="">기업을 선택하세요</option>{catalog.data?.map(c=><option key={c.id} value={c.id}>{c.name} · {c.ticker}</option>)}</select></label><label className="field"><span>보유 수량</span><input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)} pattern="[0-9]+(\.[0-9]{1,8})?" maxLength={29} placeholder="예: 10.5"/></label><label className="field"><span>평균 취득가 · 선택</span><input inputMode="decimal" value={cost} onChange={e=>setCost(e.target.value)} pattern="[0-9]+(\.[0-9]{1,8})?" maxLength={29} placeholder="입력하지 않아도 됩니다"/></label><label className="field"><span>통화</span><select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="USD">USD</option><option value="KRW">KRW</option></select></label><button className="button primary" disabled={action.busy||!company}>{action.busy?"저장 중…":"보유 정보 저장"}</button></form></div></>;
}
