"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { useAuth } from "@/components/auth";
import { useResource,Loading,ErrorState,Empty,PageHeading,EventTile } from "@/components/ui";
import { feedSchema,calendarSchema,watchlistSchema,portfolioSchema } from "@/lib/contracts";
import { koreanToday } from "@/lib/product";
import { dateText } from "@/lib/format";
export default function Today(){const [days,setDays]=useState(30),[offset,setOffset]=useState(0);const {track}=useAuth();
 const feed=useResource(`/v1/feed?days=${days}&offset=${offset}&limit=12`,feedSchema),calendar=useResource("/v1/calendar",calendarSchema),watch=useResource("/v1/watchlist",watchlistSchema),portfolio=useResource("/v1/portfolio",portfolioSchema);
 useEffect(()=>{feed.data?.items.forEach(item=>track("brief_impression",{event_id:item.id}));},[feed.data,track]);
 return <><PageHeading title="오늘 내 종목에서 중요한 변화" description="공식 공시의 변경점과 근거를 먼저 읽으세요. 가격 움직임이나 매매 신호가 아닙니다." actions={<label className="filter-select"><span>기간</span><select value={days} onChange={e=>{setDays(Number(e.target.value));setOffset(0);}}><option value={7}>최근 7일</option><option value={30}>최근 30일</option><option value={90}>최근 90일</option></select></label>}/>
 <div className="stat-strip"><div><span>중요 변화</span><strong>{feed.data?.total??"—"}<small>건</small></strong></div><div><span>관심 기업</span><strong>{watch.data?.items.length??"—"}<small>개</small></strong></div><div><span>마지막 수집</span><strong className="stat-date">{feed.data?.latest_ingested_at?dateText(feed.data.latest_ingested_at):"확인되지 않음"}</strong></div></div>
 {feed.data?.stale&&<div className="notice">{feed.data.latest_ingested_at?"최근 72시간 내 확인된 수집 기록이 없어 최신성 확인이 필요합니다.":"아직 수집·검토된 실제 공시가 없습니다. 관심종목을 저장할 수 있으며, 공시가 게시되면 이곳에 표시됩니다."}</div>}
 <div className="content-with-aside"><div>{feed.loading?<Loading/>:feed.error?<ErrorState message={feed.error} retry={feed.reload}/>:feed.data?.items.length?<div className="event-grid">{feed.data.items.map(item=><EventTile key={item.id} item={item}/>)}</div>:<Empty title="선택한 기간에 게시된 변화가 없습니다."><p>관심종목을 등록하거나 기간을 넓혀 보세요. 검토 중인 분석은 게시되지 않습니다.</p><Link className="button primary" href="/watchlist">관심종목 관리</Link></Empty>}
 {!!feed.data?.total&&<div className="pagination"><button className="button secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-12))}>이전</button><span>{Math.floor(offset/12)+1} / {Math.ceil(feed.data.total/12)}</span><button className="button secondary" disabled={!feed.data.has_more} onClick={()=>setOffset(offset+12)}>다음</button></div>}
 {feed.data?.truncated&&<p className="notice">분석 대상이 많아 일부 기간만 반환되었습니다. 기간을 좁혀 주세요.</p>}
 <section className="upcoming"><div className="section-heading"><h2>다음 확인 일정</h2><Link href="/calendar" className="text-button">캘린더 보기 →</Link></div><div className="panel">{calendar.loading?<Loading/>:calendar.error?<ErrorState message={calendar.error} retry={calendar.reload}/>:calendar.data?.some(item=>item.occurs_on>=koreanToday())?calendar.data.filter(item=>item.occurs_on>=koreanToday()).slice(0,4).map(item=><div className="list-row" key={item.id}><span className="date-pill">{item.occurs_on}</span><div className="grow"><strong>{item.title}</strong><p className="small muted">{item.is_demo?"합성 일정":item.origin==="user"?"직접 등록":"공식 근거에서 확인"}</p></div>{item.event_id&&<Link className="text-button" href={`/events/${item.event_id}`}>관련 근거 →</Link>}</div>):<p className="muted">확인된 일정이 없습니다. 임의의 실적 발표일은 표시하지 않습니다.</p>}</div></section></div><aside><section className="side-card"><div className="section-heading"><h2>내 포트폴리오</h2><Link className="text-button" href="/portfolio">전체 보기 →</Link></div><p className="small muted">등록한 보유 기업의 변화를 먼저 읽습니다.</p>{portfolio.data?.positions.length?portfolio.data.positions.slice(0,5).map(p=><div className="list-row" key={p.id}><div className="grow"><Link className="company-name" href={`/companies/${p.company.id}`}>{p.company.name}</Link><small className="muted" style={{display:"block"}}>{p.company.ticker}</small></div><strong className="small">{p.quantity}주</strong></div>):<p className="small muted">보유 기업을 추가해 보세요.</p>}<div className="notice">실시간 시세와 평가손익을 추정하지 않습니다.</div></section><section className="side-card"><h2>근거부터 확인하세요</h2><p className="muted">브리핑의 숫자와 표현은 원문 인용에 연결됩니다. 확인할 수 없는 내용은 별도로 표시합니다.</p><Link className="text-button" href="/questions">근거 질문으로 이동 →</Link></section></aside></div></>;
}
