'use client';
import {useState} from 'react';
import {useResearch} from './client';
import {rows,str,pct,measure} from './contracts';
import {Heading,Panel,Stat,State,Empty,Field,Table} from './ui';
export default function Analytics(){
 const [from,setFrom]=useState(()=>new Date(Date.now()-29*86400000).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10)),[device,setDevice]=useState(''),[screen,setScreen]=useState('');
 const data=useResearch('analytics',{from,to,device,screen}),d=data.data,days=rows(d?.days),pages=rows(d?.pages),retention=rows(d?.retention),max=Math.max(1,...days.map(x=>Number(x.users)));
 return <><Heading tag="PRODUCT ANALYTICS" title="사용자 행동 분석" description="동의한 로그인 사용자의 방문과 실제 활성 체류시간을 확인합니다."/><div className="research-filters"><Field label="시작일 (UTC)"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="종료일 (UTC)"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field><Field label="기기"><select value={device} onChange={e=>setDevice(e.target.value)}><option value="">전체</option><option value="desktop">데스크톱</option><option value="mobile">모바일</option></select></Field><Field label="화면"><select value={screen} onChange={e=>setScreen(e.target.value)}><option value="">전체 화면</option>{['today','explore','event','document','company','watchlist','onboarding','settings'].map(x=><option key={x}>{x}</option>)}</select></Field><button className="button secondary" onClick={data.reload}>새로고침</button></div><State resource={data}><div className="research-stats"><Stat label="DAU · 종료일" value={measure(d?.dau)}/><Stat label="WAU · 종료일 기준 7일" value={measure(d?.wau)}/><Stat label="화면 방문" value={measure(d?.views)}/><Stat label="이탈률" value={pct(d?.bounce_rate)} note="1회 방문 · 활성시간 10초 미만"/></div><div className="research-grid"><Panel title="날짜별 활성 사용자">{days.length?<><div className="research-chart" role="img" aria-label="날짜별 활성 사용자 막대 그래프">{days.map(x=><div key={str(x.day)} style={{height:`${Math.max(2,Number(x.users)/max*100)}%`}} title={`${x.day}: ${x.users}명`}/>)}</div><div className="research-chart-label"><span>{from}</span><span>{to}</span></div></>:<Empty/>}</Panel><Panel title="리텐션 · 관측 시작일 기준"><Table head={['코호트','재방문','관측 가능 표본','리텐션']}>{[1,7].map(day=>{const r=retention.find(x=>x.day===day);return <tr key={day}><td>D{day}</td><td>{r?str(r.numerator):'—'}</td><td>{r?str(r.denominator):'—'}</td><td>{r&&Number(r.denominator)>0?pct(Number(r.numerator)/Number(r.denominator)):'—'}</td></tr>;})}</Table><p className="research-micro">관측 기간이 충분한 사용자만 분모에 포함합니다. 가입일 기반 리텐션과 다릅니다.</p></Panel></div><Panel title="화면별 행동">{pages.length?<Table head={['화면','방문 수','사용자','활성시간 합계','클릭','온보딩 완료']}>{pages.map(x=><tr key={str(x.screen)}><td>{str(x.screen)}</td><td>{str(x.views)}</td><td>{str(x.users)}</td><td>{measure(Number(x.active_ms)/1000,'초')}</td><td>{str(x.clicks)}</td><td>{str(x.conversions)}</td></tr>)}</Table>:<Empty/>}</Panel><Panel title="화면 이동 경로">{rows(d?.paths).length?<Table head={['이전 화면','다음 화면','이동 수']}>{rows(d?.paths).map((x,i)=><tr key={i}><td>{str(x.screen)}</td><td>{str(x.next)}</td><td>{str(x.count)}</td></tr>)}</Table>:<Empty/>}</Panel><div className="research-note">수집 범위: 분석 동의한 로그인 사용자 · 최대 90일 보관 · UTC 기준. 탭이 보이고 최근 입력이 있을 때만 활성시간을 측정합니다. 클릭 내용·URL 식별자·질문·보유종목은 수집하지 않습니다. 비로그인 방문자 모수가 없어 회원가입 전환율은 미측정입니다.</div></State></>;
}
