'use client';
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import {useAuth} from '@/components/auth';
import {useAction,ActionNotice,Loading} from '@/components/ui';
import {research,useResearch} from './client';
import {row,str} from './contracts';
import {Panel,State,Field} from './ui';
import './research.css';
export default function Study({id}:{id:string}){
 const auth=useAuth(),resource=useResearch('study',{id},!!auth.token),action=useAction(),[consent,setConsent]=useState(false),[withdrawn,setWithdrawn]=useState(false);const d=resource.data,step=row(d?.step);
 if(auth.loading)return <Loading/>;
 return <main className="study-shell"><header><Link href="/">◈ SignalBrief</Link><span>금융정보 이해도 연구</span></header><ActionNotice action={action}/>{!auth.token?<Panel title="참여 전 로그인"><p>중복 참여 방지와 동의 철회를 위해 로그인이 필요합니다. 로그인 후 이 참여 링크를 다시 열어주세요.</p><Link href="/login" className="button primary">로그인</Link></Panel>:withdrawn?<Panel title="참여를 철회했습니다"><p>실험 응답과 행동 기록을 삭제했습니다. 철회된 결과는 관리자 통계와 새 보고서에서 제외됩니다.</p></Panel>:<State resource={resource}><h1>{str(d?.name)}</h1>{d?.joined?<><p className="research-micro">{d?.complete?'모든 과제를 제출했습니다.':`과제 ${Number(d?.phase)+1} / ${d?.total}`} · 답변의 정답은 실험 종료 전 공개하지 않습니다.</p><div className="study-progress"><span style={{width:`${Number(d?.phase)/Number(d?.total)*100}%`}}/></div>{d?.complete?<Panel title="참여해 주셔서 감사합니다"><p>제출한 결과가 저장되었습니다. 아래에서 동의를 철회할 수 있습니다.</p></Panel>:d?.status!=='running'?<Panel title="현재 실험이 중지되어 있습니다"><p>진행 재개 후 이 링크에서 이어서 참여할 수 있습니다.</p></Panel>:<StudyTask key={Number(d?.phase)} id={id} phase={Number(d?.phase)} step={step} onSubmit={resource.reload}/>}<button className="button secondary" disabled={action.busy} onClick={()=>action.run(async()=>{await research(auth.token,'withdraw',{id});setWithdrawn(true);})}>참여 철회 및 응답 삭제</button></>:<Panel title="연구 참여 동의"><div className="research-source">{str(d?.consent_text)}</div><p className="research-micro">동의문 버전: {str(d?.consent_version)} · 미동의 시 배정과 행동 수집이 시작되지 않습니다.</p><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> 내용을 읽었으며 자발적 참여에 동의합니다.</label><p><button className="button primary" disabled={!consent||action.busy||d?.status!=='running'} onClick={()=>action.run(async()=>{await research(auth.token,'join',{id,consent:true,consent_version:d?.consent_version});resource.reload();})}>{d?.status==='running'?'동의하고 참여하기':'실험이 아직 진행 중이 아닙니다'}</button></p></Panel>}</State>}</main>;
}
function StudyTask({id,phase,step,onSubmit}:{id:string;phase:number;step:Record<string,unknown>;onSubmit:()=>void}){
 const {token}=useAuth(),action=useAction(),[answer,setAnswer]=useState(''),[confidence,setConfidence]=useState(3),[ready,setReady]=useState(false),[failure,setFailure]=useState(''),[evidence,setEvidence]=useState(false),[active,setActive]=useState(0);
 const latest=useRef({active:0,evidence:false});useEffect(()=>{latest.current={active,evidence};},[active,evidence]);
 useEffect(()=>{if(!ready)return;const flush=()=>{const current=latest.current;void research(token,'study_event',{id,phase,active_ms:current.active,evidence_opened:current.evidence}).catch(()=>{});};const timer=setInterval(flush,15000);return()=>clearInterval(timer);},[ready,id,phase,token]);
 useEffect(()=>{let alive=true;research(token,'expose',{id,phase}).then(()=>{if(alive)setReady(true);}).catch(e=>{if(alive)setFailure(e.message);});return()=>{alive=false;};},[id,phase,token]);
 useEffect(()=>{if(!ready)return;let input=performance.now(),last=input;const interact=()=>{input=performance.now();};const timer=setInterval(()=>{const now=performance.now();if(document.visibilityState==='visible'&&document.hasFocus()&&now-input<30000)setActive(x=>Math.min(3600000,x+Math.floor(Math.min(2000,now-last))));last=now;},1000);window.addEventListener('pointerdown',interact);window.addEventListener('keydown',interact);window.addEventListener('scroll',interact);return()=>{clearInterval(timer);window.removeEventListener('pointerdown',interact);window.removeEventListener('keydown',interact);window.removeEventListener('scroll',interact);};},[ready]);
 return <><ActionNotice action={action}/>{failure&&<p role="alert" className="research-error">{failure}</p>}<Panel title="금융정보 읽기"><div className="research-source">{str(step.content)}</div><p><a className="research-source-link" href={str(step.source_url)} target="_blank" rel="noopener noreferrer" onClick={()=>{setEvidence(true);void research(token,'study_event',{id,phase,active_ms:active,evidence_opened:true}).catch(()=>{});}}>SEC 원문 확인 ↗</a></p></Panel><Panel title="질문에 답해 주세요"><form className="research-form" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await research(token,'study_event',{id,phase,active_ms:active,evidence_opened:evidence});await research(token,'submit',{id,phase,answer,confidence});onSubmit();});}}><Field label={str(step.question)}><input required maxLength={500} value={answer} onChange={e=>setAnswer(e.target.value)}/></Field><Field label="답변 확신도"><select value={confidence} onChange={e=>setConfidence(Number(e.target.value))}>{['매우 낮음','낮음','보통','높음','매우 높음'].map((x,i)=><option value={i+1} key={x}>{i+1} · {x}</option>)}</select></Field><button className="button primary" disabled={!ready||action.busy||!answer.trim()}>답변 제출</button></form></Panel></>;
}
