'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useCallback,useEffect,useState} from 'react';
import {z} from 'zod';
import type {User} from '@supabase/supabase-js';
import {useAuth} from '@/components/auth';
import {initializeSupabase} from '@/lib/supabase';
import {request,body} from '@/lib/api';
import {meSchema} from '@/lib/contracts';
import {usePrefs} from './preferences';
import {workspace,downloadJSON} from './client';
import {accountSchema} from './contracts';
import {useData,useMutation,Notice,Panel,Heading,Icon,Modal,DataState,SettingsTabs,Switch} from './ui';
export function useIdentity(){const {token}=useAuth(),[user,setUser]=useState<User|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);useEffect(()=>{let active=true;if(!token){setUser(null);return;}initializeSupabase().then(db=>db.auth.getUser()).then(r=>{if(r.error)throw r.error;if(active){setUser(r.data.user);setError('');}}).catch(()=>{if(active)setError('계정 인증 정보를 확인하지 못했습니다. 다시 시도해 주세요.');});return()=>{active=false;};},[token,revision]);const reload=useCallback(()=>setRevision(x=>x+1),[]);return {user,error,reload};}
export default function Account(){
 const auth=useAuth(),router=useRouter(),prefs=usePrefs(),{value,text:t,date}=prefs,identity=useIdentity(),res=useData({action:'account',p:{}},accountSchema),action=useMutation();
 const [edit,setEdit]=useState(false),[confirm,setConfirm]=useState(false),[name,setName]=useState(''),[bio,setBio]=useState('');

 const change=(patch:Parameters<typeof prefs.save>[0])=>void action.run(()=>prefs.save(patch),t('설정을 저장했습니다.','Settings saved.'));
 return <><Heading title={t('계정 정보','Account information')} section={t('설정','Settings')} description={t('내 계정과 개인 정보를 관리합니다.','Manage your account and personal information.')}/><SettingsTabs/><Notice action={action}/><DataState loading={!prefs.loaded&&!prefs.error} error={prefs.error||identity.error} retry={()=>{prefs.reload();identity.reload();}}/>
 <Panel className="ws-profile-hero"><span className="ws-avatar">{auth.me?.display_name.slice(0,1)}</span><div className="ws-profile-info"><h2>{auth.me?.display_name}<span className="ws-badge">{t('공개 베타','Public beta')}</span></h2><p>{identity.user?.email??t('이메일 확인 중','Checking email')}</p><p>{value.bio||t('한 줄 소개를 추가해 보세요.','Add a short introduction.')}</p><small>{t('회원 가입일','Joined')} {date(res.data?.created_at??null,'date')}</small></div><div className="ws-profile-side"><button className="ws-button" disabled={!prefs.loaded} onClick={()=>{setName(auth.me?.display_name??'');setBio(value.bio);setEdit(true);}}><Icon name="file" size={18}/>{t('프로필 수정','Edit profile')}</button><p>{t('이름과 한 줄 소개를 수정합니다. 계정 이니셜을 표시합니다.','Edit your name and bio. Your account initials are displayed.')}</p></div></Panel>
 <div className="ws-stack"><Panel className="ws-setting"><Icon name="clock"/><div><h2>{t('시간대 (타임존)','Time zone')}</h2><p>{t('새 작업 공간의 날짜·시간과 일반 알림 제한에 사용합니다.','Used for dates in the new workspace and ordinary alert limits.')}</p><label className="ws-field"><span>{t('시간대','Time zone')}</span><select disabled={prefs.busy||!prefs.loaded} value={value.timezone} onChange={e=>change({timezone:e.target.value})}>{['Asia/Seoul','America/New_York','America/Los_Angeles','Europe/London','Europe/Berlin','Asia/Tokyo','Australia/Sydney','UTC'].map(tz=><option key={tz}>{tz}</option>)}</select></label></div><aside className="ws-setting-help">{t('공시의 날짜만 알려진 경우 시간대 변환 없이 원래 날짜를 유지합니다. 기존 캘린더는 공시 원문 날짜를 따릅니다.','Date-only filings retain their original date. The existing calendar follows source dates.')}</aside></Panel>
 <Panel className="ws-setting"><Icon name="settings"/><div><h2>{t('언어 및 표시 설정','Language and appearance')}</h2><p>{t('메뉴 언어와 날짜·숫자 표시를 선택합니다.','Choose your menu language and date/number formatting.')}</p><div className="ws-fields"><label className="ws-field"><span>{t('언어','Language')}</span><select disabled={prefs.busy||!prefs.loaded} value={value.locale} onChange={e=>change({locale:e.target.value as 'ko'|'en'})}><option value="ko">한국어 (Korean)</option><option value="en">English</option></select></label><Link className="ws-button ws-secondary" href="/settings/appearance">{t('화면 설정','Appearance')} <Icon name="arrow" size={17}/></Link></div></div><aside className="ws-setting-help">{t('언어는 새로 추가된 작업 공간에 적용됩니다. 기존 분석 화면과 원문은 원래 언어를 유지합니다. 통화를 임의로 환산하지 않습니다.','Language applies to the new workspace. Existing analysis screens and sources retain their original language. Currency is not silently converted.')}</aside></Panel>
 <Panel className="ws-setting"><Icon name="shield"/><div><h2>{t('연결된 로그인 수단','Connected sign-in methods')}</h2><p>{t('실제 계정에 연결된 로그인 제공자입니다.','Providers connected to your actual account.')}</p>{identity.user?.identities?.map(i=><div className="ws-provider-row" key={i.identity_id}><span className="ws-provider-symbol">{i.provider==='google'?'G':'@'}</span><div><strong>{i.provider}</strong><small>{identity.user?.email}</small></div><span className="ws-badge green">{t('연결됨','Connected')}</span></div>)}<Link className="ws-link" href="/settings/security" style={{display:'inline-block',marginTop:12}}>{t('로그인·보안 관리','Manage sign-in & security')} →</Link></div><aside className="ws-setting-help">{t('유일한 로그인 수단은 해제할 수 없습니다. 연결 해제에는 추가 인증이 필요할 수 있습니다.','The only remaining sign-in method cannot be removed. Unlinking may require additional authentication.')}</aside></Panel>
 <Panel className="ws-setting"><Icon name="clock"/><div><h2>{t('방문·검색 기록','Browsing and search history')}</h2><div className="ws-toggle-row"><p>{t('최근 방문 100개와 검색어 10개를 저장합니다. 끄면 기존 방문·검색 기록도 삭제합니다.','Save up to 100 visits and 10 searches. Turning this off also clears existing browsing/search history.')}</p><Switch label={t('방문·검색 기록 저장','Save browsing/search history')} checked={value.history_enabled} disabled={prefs.busy||!prefs.loaded} onChange={v=>change({history_enabled:v})}/></div></div><aside className="ws-setting-help">{t('기본값은 꺼짐입니다. 북마크는 기록 설정과 별개로 유지됩니다.','Off by default. Bookmarks are stored separately from browsing history.')}</aside></Panel>
 <Panel className="ws-setting"><Icon name="shield"/><div><h2>{t('개인정보 및 통계','Privacy and analytics')}</h2><div className="ws-toggle-row"><p>{t('선택적 이용 통계에 동의합니다. 질문·보유 수량은 통계로 보내지 않습니다.','Opt in to usage analytics. Questions and holding quantities are not sent as analytics.')}</p><Switch label={t('선택적 이용 통계','Optional analytics')} checked={!!auth.me?.analytics_consent} disabled={action.busy} onChange={v=>void action.run(async()=>{await request('/v1/me',auth.token,meSchema,body('PATCH',{analytics_consent:v}));await auth.refresh();},t('통계 동의를 저장했습니다.','Analytics preference saved.'))}/></div><Link className="ws-link" href="/help?category=privacy">{t('개인정보 삭제 / 계정 탈퇴 요청','Request data or account deletion')} →</Link></div><aside className="ws-setting-help">{t('삭제 요청은 고객지원에 저장됩니다. 요청 즉시 계정이 삭제되었다고 표시하지 않습니다.','Deletion requests are recorded with support. Submitting a request does not claim immediate account deletion.')}</aside></Panel>
 <Panel className="ws-setting"><Icon name="download"/><div><h2>{t('내 데이터 내보내기','Export my data')}</h2><p>{t('내 계정에 저장된 정보를 JSON 파일로 내려받습니다.','Download your stored account information as JSON.')}</p><button className="ws-button ws-secondary" disabled={action.busy} onClick={()=>void action.run(async()=>{const data=await workspace(auth.token,{action:'export',p:{}},z.record(z.unknown()));downloadJSON(data,`SignalBrief-my-data-${new Date().toISOString().slice(0,10)}.json`);},t('내 데이터 파일을 만들었습니다.','Your data file is ready.'))}><Icon name="download" size={18}/>{t('데이터 내보내기','Export data')}</button></div><aside className="ws-setting-help">{t('프로필, 설정, 관심종목, 포트폴리오, 북마크, 질문·지원 요청이 포함됩니다. 다른 사용자의 데이터는 포함되지 않습니다.','Includes your profile, preferences, watchlist, portfolio, bookmarks, questions and support requests. No other user’s data is included.')}</aside></Panel>
 <Panel className="ws-setting"><Icon name="logout"/><div><h2>{t('로그아웃','Sign out')}</h2><p>{t('현재 기기의 로그인 세션을 종료합니다.','End the session on this device.')}</p><button className="ws-button ws-danger-button" onClick={()=>setConfirm(true)}>{t('로그아웃','Sign out')}</button></div><aside className="ws-setting-help">{t('다른 기기 세션은 보안 및 로그인에서 종료할 수 있습니다.','Other sessions can be ended from Security & sign-in.')}</aside></Panel></div>
 {edit&&<Modal title={t('프로필 수정','Edit profile')} onClose={()=>setEdit(false)}><Notice action={action}/><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{if(!name.trim())throw new Error(t('이름을 입력해 주세요.','Enter your name.'));await prefs.save({bio});await request('/v1/me',auth.token,meSchema,body('PATCH',{display_name:name.trim()}));await auth.refresh();setEdit(false);},t('프로필을 저장했습니다.','Profile saved.'));}}><label>{t('이름','Display name')}<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t('한 줄 소개','Short bio')}<textarea maxLength={160} value={bio} onChange={e=>setBio(e.target.value)}/></label><small className="ws-muted">{bio.length} / 160</small><footer><button type="button" className="ws-button ws-secondary" onClick={()=>setEdit(false)}>{t('취소','Cancel')}</button><button className="ws-button" disabled={action.busy}>{t('저장','Save')}</button></footer></form></Modal>}
 {confirm&&<Modal title={t('로그아웃할까요?','Sign out?')} onClose={()=>setConfirm(false)}><Notice action={action}/><button className="ws-button ws-danger-button" disabled={action.busy} onClick={()=>void action.run(async()=>{await auth.logout();router.replace('/login');})}>{t('현재 기기에서 로그아웃','Sign out on this device')}</button></Modal>}</>;
}
