'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {usePrefs} from './preferences';
import {catalogSchema} from './contracts';
import {useData,useMutation,Notice,Panel,Heading,Icon,SettingsTabs,Switch,Logo,DataState} from './ui';
export default function Appearance(){const prefs=usePrefs(),{value,text:t}=prefs,action=useMutation(),[font,setFont]=useState(value.font_scale),res=useData({action:'catalog',p:{kind:'company',limit:1}},catalogSchema);useEffect(()=>setFont(value.font_scale),[value.font_scale]);const save=(p:Parameters<typeof prefs.save>[0])=>void action.run(()=>prefs.save(p),t('표시 설정을 저장했습니다.','Display settings saved.'));
 const header=(icon:'settings'|'file'|'pie'|'timeline',title:string,body:string)=><header><Icon name={icon} size={24}/><div><h2>{title}</h2><p>{body}</p></div></header>;
 return <><Heading title={t('화면 및 언어 설정','Appearance & language')} section={t('설정','Settings')} description={t('나에게 맞는 화면 환경과 언어를 설정하세요.','Choose a comfortable appearance and language.')}/><SettingsTabs/><Notice action={action}/><DataState loading={!prefs.loaded&&!prefs.error} error={prefs.error} retry={prefs.reload}/><div className="ws-grid equal"><div className="ws-stack">
 <Panel className="ws-setting-card">{header('settings',t('테마 모드','Theme mode'),t('새 작업 공간의 색상 테마를 선택합니다.','Choose the theme for the new workspace.'))}<div className="ws-choice-row" role="radiogroup" aria-label={t('테마 모드','Theme mode')}>{[['light','☼','라이트 모드','Light','밝고 깔끔한 화면','A clear, light interface'],['dark','☾','다크 모드','Dark','어두운 화면','A dark interface'],['system','▱','시스템 설정','System','기기 설정 자동 적용','Follow device settings']].map(([key,symbol,ko,en,helpKo,helpEn])=><button key={key} className={`ws-choice ${value.theme===key?'selected':''}`} role="radio" aria-checked={value.theme===key} disabled={!prefs.loaded||prefs.busy} onClick={()=>save({theme:key as typeof value.theme})}><i className="ws-check-circle"/><span className="ws-theme-symbol">{symbol}</span><strong>{t(ko,en)}</strong><small>{t(helpKo,helpEn)}</small></button>)}</div></Panel>
 <Panel className="ws-setting-card">{header('file',t('화면 밀도','Layout density'),t('표시되는 카드의 간격을 조절합니다.','Adjust spacing between displayed cards.'))}<div className="ws-choice-row two" role="radiogroup" aria-label={t('화면 밀도','Layout density')}>{[['compact','컴팩트','Compact','좁은 간격으로','Closer spacing'],['comfortable','편안함','Comfortable','여유 있는 간격으로','More breathing room']].map(([key,ko,en,hko,hen])=><button className={`ws-choice ${value.ui_density===key?'selected':''}`} key={key} role="radio" aria-checked={value.ui_density===key} disabled={!prefs.loaded||prefs.busy} onClick={()=>save({ui_density:key as typeof value.ui_density})}><i className="ws-check-circle"/><Icon name="file" size={26}/><strong>{t(ko,en)}</strong><small>{t(hko,hen)}</small></button>)}</div></Panel>
 <Panel className="ws-setting-card">{header('file',t('글자 크기','Text size'),t('내용과 컨트롤의 글자 크기를 조절합니다.','Adjust text size in content and controls.'))}<label><input type="range" aria-label={t('글자 크기','Text size')} min="0" max="3" step="1" value={font} disabled={!prefs.loaded||prefs.busy} onChange={e=>setFont(Number(e.target.value))}/></label><div className="ws-slider-labels">{[[0,'작게','Small'],[1,'보통','Default'],[2,'크게','Large'],[3,'아주 크게','Largest']].map(([n,ko,en])=><span style={{fontWeight:font===n?700:400}} key={n}>{t(String(ko),String(en))}</span>)}</div><button className="ws-link" style={{marginTop:12}} disabled={font===value.font_scale||prefs.busy} onClick={()=>save({font_scale:font})}>{t('글자 크기 적용','Apply text size')}</button></Panel>
 <Panel><div className="ws-toggle-row"><div><h2>{t('차트 애니메이션','Chart animation')}</h2><p>{t('실제 시계열이 있을 때 선 그래프를 부드럽게 표시합니다.','Animate line charts when real series data is available.')}</p></div><Switch label={t('차트 애니메이션','Chart animation')} checked={value.chart_animation} disabled={!prefs.loaded||prefs.busy||value.reduced_motion} onChange={v=>save({chart_animation:v})}/></div></Panel>
 <Panel><div className="ws-toggle-row"><div><h2>{t('움직임 최소화','Reduce motion')}</h2><p>{t('시스템의 움직임 최소화 설정도 항상 존중합니다.','The system reduced-motion preference is always respected.')}</p></div><Switch label={t('움직임 최소화','Reduce motion')} checked={value.reduced_motion} disabled={!prefs.loaded||prefs.busy} onChange={v=>save({reduced_motion:v})}/></div></Panel>
 <Panel className="ws-setting-card">{header('settings',t('앱 언어','Workspace language'),t('새 작업 공간의 메뉴 언어를 선택합니다.','Choose the language of new workspace screens.'))}<div className="ws-choice-row two" role="radiogroup" aria-label={t('앱 언어','Workspace language')}>{[['ko','한국어','Korean'],['en','English','영어']].map(([key,label,sub])=><button className={`ws-choice ${value.locale===key?'selected':''}`} key={key} role="radio" aria-checked={value.locale===key} disabled={!prefs.loaded||prefs.busy} onClick={()=>save({locale:key as 'ko'|'en'})}><i className="ws-check-circle"/><strong>{label}</strong><small>{sub}</small></button>)}</div></Panel></div>
 <aside className="ws-stack"><Panel title={t('미리보기','Preview')} icon="search"><div className="ws-preview"><div className="ws-preview-bar"><Icon name="pie"/><strong>SignalBrief</strong></div><div className="ws-preview-body"><h3>{t('기업 개요','Company overview')}</h3><Panel><div className="ws-row" style={{justifyContent:'flex-start'}}><Logo ticker={res.data?.items[0]?.ticker??'SB'}/><div><strong>{res.data?.items[0]?.title??t('선택한 기업','Selected company')}</strong><p className="ws-muted ws-small">{res.data?.items[0]?.ticker??'—'} · {res.data?.items[0]?.market??'—'}</p></div></div><hr/><p>{t('이 미리보기는 선택한 색상·간격·글자 크기를 반영합니다. 시세나 실적을 임의로 생성하지 않습니다.','This preview reflects your theme, density and text size. No prices or financial results are fabricated.')}</p></Panel><Panel><strong>{t('최근 주요 변화','Recent changes')}</strong><p className="ws-small ws-muted" style={{marginTop:9}}>{t('검토된 데이터가 연결되면 표시됩니다.','Reviewed data appears when available.')}</p><span className="ws-badge" style={{marginTop:14}}>{t('화면 미리보기','Interface preview')}</span></Panel></div></div></Panel><Panel><div className="ws-row" style={{alignItems:'start'}}><Icon name="shield"/><div><h3>{t('설정은 저장 후 즉시 적용됩니다','Settings apply immediately after saving')}</h3><p className="ws-muted ws-small" style={{marginTop:10}}>{t('같은 계정으로 다시 접속해도 유지됩니다. 기존 투자 분석 화면의 원문 언어와 정보 밀도 설정은 별개입니다.','Your preferences persist across visits. Source language and the existing analysis-detail density are separate.')}</p><Link href="/settings/account" className="ws-link">{t('계정 설정','Account settings')} →</Link></div></div></Panel></aside></div></>;
}
