'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {request,body,emptySchema} from '@/lib/api';
import {portfolioSchema} from '@/lib/contracts';
import {decimalInput} from '@/lib/decimal-input';
import {usePrefs} from './preferences';
import {workspace} from './client';
import {companyDetailSchema,resourceSchema,resourceHref} from './contracts';
import {useData,useMutation,Notice,Panel,Heading,Empty,Logo,Chart,Icon,Modal,DataState,ResourceCard,External} from './ui';
import {useQuotes} from './market';
export default function CompanyOverview({id}:{id:string}){
 const {token}=useAuth(),{text:t,date,value}=usePrefs(),result=useData({action:'company',p:{id}},companyDetailSchema),action=useMutation(),[showPosition,setShowPosition]=useState(false),[period,setPeriod]=useState('6m');
 const data=result.data,company=data?.company,quotes=useQuotes(company?[company.ticker]:[],period),quote=quotes.quotes[0];
 useEffect(()=>{if(value.history_enabled&&company)void workspace(token,{action:'visit',p:{kind:'company',id:company.id}},z.unknown()).catch(()=>{});},[company,token,value.history_enabled]);
 const more=<Link href={`/search?q=${encodeURIComponent(company?.ticker??'')}`}>{t('더보기','View all')} ›</Link>;
 return <><Heading title={t('기업 개요','Company overview')} action={<button className="ws-icon-button" aria-label={t('기업 새로고침','Refresh company')} onClick={result.reload}><Icon name="clock"/></button>}/><DataState {...result} retry={result.reload}/><Notice action={action}/>{data&&company&&<>
 <Panel className="ws-hero-company"><Logo ticker={company.ticker} large/><div className="ws-company-summary"><h2>{company.title}</h2><div className="ws-company-sub">{company.ticker} · {company.market}</div><div className="ws-tags"><span>SEC EDGAR</span><span>{t('공식 공시','Official filings')}</span></div><p>{t('연결된 SEC 공시와 공개 검토를 통과한 분석을 확인하세요. 게시되지 않은 분석은 표시하지 않습니다.','Explore connected SEC filings and reviewed analyses. Unpublished analyses are never displayed.')}</p><Link className="ws-link" href={`/companies/${id}/timeline`}>{t('기업 타임라인 보기','Open company timeline')} ›</Link></div><div className="ws-company-price"><div className="ws-row"><div><div className="ws-price">{quote?.price!=null?new Intl.NumberFormat(value.locale,{style:'currency',currency:quote.currency}).format(quote.price):'—'}</div>{quote?.change_pct!=null&&<strong className={quote.change_pct<0?'ws-bad':'ws-good'}>{quote.change_pct>=0?'+':''}{quote.change_pct.toFixed(2)}%</strong>}</div><Chart values={quote?.history.map(x=>x.close)??[]}/></div><p className="ws-price-meta">{quote?`${quote.source} · ${date(quote.as_of)}`:t('시세 제공 권한 또는 공급자 연결 확인 필요','Price-feed permission or provider connection required')}</p><div className="ws-hero-actions"><button className="ws-button ws-secondary" disabled={action.busy} aria-pressed={data.watching} onClick={()=>void action.run(async()=>{await request(`/v1/watchlist/${id}`,token,emptySchema,body(data.watching?'DELETE':'PUT'));result.reload();},t('관심종목을 업데이트했습니다.','Watchlist updated.'))}><Icon name={data.watching?'check':'star'} size={18}/>{data.watching?t('관심종목 등록됨','Watching'):t('관심종목','Watchlist')}</button><button className="ws-button" onClick={()=>setShowPosition(true)}><Icon name="plus" size={18}/>{data.holding?t('보유 정보 수정','Edit holding'):t('포트폴리오에 추가','Add holding')}</button></div></div></Panel>
 <div className="ws-grid"><div className="ws-stack"><Panel title={t('핵심 지표 / 원문 사실','Key metrics / sourced facts')} icon="pie" action={more}><div className="ws-metrics">{data.facts.length?data.facts.slice(0,6).map(f=><Link className="ws-metric" href={`/events/${f.event_id}?panel=evidence`} key={f.id}><label>{f.field}</label><strong>{f.value_raw??t('원문 확인','View source')}</strong><small>{f.unit} {f.period}</small><small>{f.basis}</small></Link>):[['시가총액','Market cap'],['PER (TTM)','P/E (TTM)'],['EPS (TTM)','EPS (TTM)'],['매출액','Revenue'],['영업이익률','Operating margin'],['검증된 사실','Verified facts']].map(([ko,en])=><div key={ko} className="ws-metric"><label>{t(ko,en)}</label><strong>—</strong><small>{t('검증된 데이터 없음','No verified data')}</small></div>)}</div><p className="ws-small ws-muted" style={{marginTop:15}}>{t('분기·회계기준이 다른 값을 TTM 지표로 바꾸지 않습니다. 숫자를 선택하면 원문 근거로 이동합니다.','Different reporting periods are not relabeled as TTM metrics. Select a fact to inspect its evidence.')}</p></Panel>
 <Panel title={t('최근 중요 변화','Recent important changes')} icon="spark" action={more}>{data.events.length?<div className="ws-event-grid">{data.events.slice(0,3).map(e=><article className="ws-event-mini" key={e.id}><div className="ws-meta"><span className="ws-badge">{e.category}</span><time>{date(e.published_at,'date')}</time></div><Link href={resourceHref(e)}><h3>{e.title}</h3><p>{e.summary}</p></Link></article>)}</div>:<Empty title={t('아직 게시된 분석이 없습니다','No published analyses yet')} description={t('공시는 아래 근거 자료에서 확인할 수 있습니다. 분석 공개 전까지 가상의 이벤트를 만들지 않습니다.','Available filings are listed below. No illustrative events are inserted while review is pending.')}/>}</Panel>
 <Panel title={t('타임라인 미리보기','Timeline preview')} icon="clock" action={<Link href={`/companies/${id}/timeline`}>{t('전체 타임라인 보기','Full timeline')} ›</Link>}>{data.events.length?data.events.slice(0,5).map(e=><Link className="ws-timeline-row" href={resourceHref(e)} key={e.id}><i/><time>{date(e.published_at,'date')}</time><strong>{e.title}</strong></Link>):<Empty title={t('검토된 변화가 쌓이면 표시됩니다','Reviewed changes will appear here')}/>}</Panel></div><aside className="ws-stack"><Panel title={t('모니터링 포인트','Monitoring points')} icon="shield" action={more}>{data.facts.length?data.facts.slice(0,5).map(f=><Link className="ws-doc-row" href={`/events/${f.event_id}`} key={f.id}><Icon name="check" size={18}/><span>{f.field} · {f.period}</span><span className="ws-badge green">{t('근거','Sourced')}</span></Link>):<Empty title={t('확인된 모니터링 근거 없음','No verified monitoring points')} description={t('기업별 분석이 공개되면 원문에 연결된 확인 항목이 표시됩니다.','Source-linked items will appear when company analyses are published.')}/>}</Panel><Panel title={t('관련 문서 / 근거 자료','Documents / source evidence')} icon="file" action={<Link href={`/search?q=${company.ticker}&kind=document`}>{t('더보기','View all')} ›</Link>}>{data.documents.length?data.documents.slice(0,5).map(d=><div className="ws-doc-row" key={d.kind+d.id}><Icon name="file" size={20}/><Link href={resourceHref(d)}>{d.title}</Link><small>{date(d.published_at,'date')}</small></div>):<Empty title={t('수집된 자료가 없습니다','No collected documents')}/>}</Panel><Panel title={t('주가 차트','Price history')} icon="timeline"><label className="ws-field"><span>{t('조회 기간','Period')}</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="1m">{t('1개월','1 month')}</option><option value="3m">{t('3개월','3 months')}</option><option value="6m">{t('6개월','6 months')}</option><option value="1y">{t('1년','1 year')}</option></select></label><Chart values={quote?.history.map(x=>x.close)??[]}/><Link className="ws-link" href="/us">{t('실제 공급자 연결 상태 보기','View provider connections')} →</Link></Panel></aside></div></>}
 {showPosition&&<PositionModal id={id} onClose={()=>setShowPosition(false)} onSaved={()=>{setShowPosition(false);result.reload();}}/>}</>;
}
function PositionModal({id,onClose,onSaved}:{id:string;onClose:()=>void;onSaved:()=>void}){
 const {token}=useAuth(),{text:t}=usePrefs(),action=useMutation();
 const [quantity,setQuantity]=useState(''),[cost,setCost]=useState(''),[currency,setCurrency]=useState('USD'),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let alive=true;const ctrl=new AbortController();setLoading(true);setLoadError('');
  request('/v1/portfolio',token,portfolioSchema,{signal:ctrl.signal}).then(portfolio=>{if(!alive)return;const position=portfolio.positions.find(p=>p.company.id===id);setQuantity(decimalInput(position?.quantity));setCost(decimalInput(position?.average_cost));setCurrency(position?.currency??'USD');}).catch(()=>{if(alive)setLoadError(t('기존 보유 정보를 불러오지 못했습니다. 다시 시도해 주세요.','Could not load the current holding. Please retry.'));}).finally(()=>{if(alive)setLoading(false);});
  return()=>{alive=false;ctrl.abort();};
 },[id,token,revision,t]);
 const disabled=loading||!!loadError||action.busy;
 return <Modal title={t('보유 정보 입력','Holding details')} onClose={onClose}><Notice action={action}/><DataState loading={loading} error={loadError} retry={()=>setRevision(x=>x+1)}/><p className="ws-muted">{t('실제 보유 수량을 직접 입력하세요. 저장은 주문이나 거래가 아닙니다.','Enter your actual holding. Saving does not place a trade.')}</p><form onSubmit={e=>{e.preventDefault();if(disabled)return;void action.run(async()=>{if(!/^\d{1,20}(\.\d{1,8})?$/.test(quantity)||!/[1-9]/.test(quantity))throw new Error(t('0보다 큰 수량을 입력해 주세요.','Enter a positive quantity.'));if(cost&&!/^\d{1,20}(\.\d{1,8})?$/.test(cost))throw new Error(t('평균 단가를 확인해 주세요.','Check the average cost.'));await request(`/v1/portfolio/positions/${id}`,token,emptySchema,body('PUT',{quantity,average_cost:cost||null,currency}));onSaved();});}}><label>{t('보유 수량','Quantity')}<input required inputMode="decimal" value={quantity} disabled={disabled} onChange={e=>setQuantity(e.target.value)}/></label><label>{t('평균 단가 (선택)','Average cost (optional)')}<input inputMode="decimal" value={cost} disabled={disabled} onChange={e=>setCost(e.target.value)}/></label><label>{t('통화','Currency')}<select value={currency} disabled={disabled} onChange={e=>setCurrency(e.target.value)}>{['KRW','USD','EUR','JPY','GBP','AUD','CAD','HKD','CNY','CHF'].map(c=><option key={c} value={c}>{c}</option>)}</select></label><footer><button type="button" className="ws-button ws-secondary" onClick={onClose}>{t('취소','Cancel')}</button><button disabled={disabled} className="ws-button">{t('저장','Save')}</button></footer></form></Modal>;
}
export function DocumentView({id,kind}:{id:string;kind:'filing'|'document'}){const {token}=useAuth(),{text:t,value}=usePrefs(),res=useData({action:'resource',p:{kind,id}},resourceSchema),item=res.data;useEffect(()=>{if(item&&value.history_enabled)void workspace(token,{action:'visit',p:{kind:item.kind,id:item.id}},z.unknown()).catch(()=>{});},[item,token,value.history_enabled]);return <><Heading title={t('원문 자료','Source document')}/><DataState {...res} retry={res.reload}/>{item?<div className="ws-stack"><ResourceCard item={item}/><Panel title={t('공식 원문','Official source')}><p>{t('이 페이지는 수집된 원문을 연결합니다. 원문은 외부 제공자의 사이트에서 열립니다.','This page links to the collected original document on the provider’s website.')}</p><External url={item.source_url}>{t('원문 열기','Open source')}</External><p className="ws-small ws-muted" style={{marginTop:16}}>{item.source_url}</p><Link className="ws-link" href={`/companies/${item.company_id}`}>{t('기업 개요로 이동','Company overview')} →</Link></Panel></div>:!res.loading&&!res.error&&<Empty title={t('자료를 확인할 수 없습니다','Document not available')} description={t('원문이 비공개되었거나 수집 범위 밖입니다. 검색에서 다시 확인하세요.','The source may be withdrawn or outside current coverage. Try searching again.')} href="/search" label={t('검색으로 이동','Open search')}/>}</>;}
