// Authored product help, not financial/provider data. Counts derive from this collection.
export const helpCategories=[
 {id:'start',ko:'시작하기',en:'Getting started',description:'회원가입, 기본 사용법',english:'Accounts and first steps',icon:'timeline'},
 {id:'data',ko:'데이터 및 분석',en:'Data & analysis',description:'출처, 검토, 지원 범위',english:'Sources, review and coverage',icon:'pie'},
 {id:'portfolio',ko:'포트폴리오',en:'Portfolio',description:'보유종목과 관심종목',english:'Holdings and watchlists',icon:'file'},
 {id:'alerts',ko:'알림 및 캘린더',en:'Alerts & calendar',description:'알림 규칙과 주요 일정',english:'Alert rules and key dates',icon:'bell'},
 {id:'account',ko:'계정 및 보안',en:'Account & security',description:'프로필, 인증, 개인정보',english:'Profile, authentication, privacy',icon:'settings'},
 {id:'issues',ko:'문제 해결',en:'Troubleshooting',description:'오류 신고와 문의',english:'Errors and support',icon:'shield'}
] as const;
export const helpArticles=[
 {id:'calendar',category:'alerts',q:'실적 발표 일정은 어떻게 확인하나요?',en:'Where do I find company event dates?',a:'캘린더에서 연결된 공식 원문에 근거한 날짜를 확인하세요. 수집되지 않은 미래 일정을 작년 날짜로 추정하지 않습니다. 개인 일정도 직접 추가할 수 있습니다.',english:'The calendar shows dates supported by connected official sources. Uncollected future dates are not guessed from last year. You can also add your own reminders.',href:'/calendar'},
 {id:'watchlist',category:'portfolio',q:'관심종목은 몇 개까지 추가할 수 있나요?',en:'How many companies can I watch?',a:'현재 계정당 관심종목은 최대 50개입니다. 실제 지원 목록에 있는 기업을 추가할 수 있습니다. 보유종목과 관심종목은 별개입니다.',english:'The current limit is 50 watched companies per account. Choose from supported companies. Watchlists and holdings are separate.',href:'/watchlist'},
 {id:'returns',category:'portfolio',q:'포트폴리오 수익률은 어떻게 계산되나요?',en:'How are portfolio returns calculated?',a:'현재 정확한 포트폴리오 수익률은 제공하지 않습니다. 시세·환율·현금흐름이 불완전한 상태에서 수익률을 계산하지 않습니다. 입력한 보유 수량과 평균 단가는 관리할 수 있습니다.',english:'Complete portfolio returns are not currently provided. Returns are not calculated from incomplete prices, FX or cash-flow data. You can manage quantities and average costs.',href:'/portfolio'},
 {id:'alerts',category:'alerts',q:'알림이 오지 않아요. 어떻게 해야 하나요?',en:'Why am I not getting alerts?',a:'알림 센터의 개별 규칙, 앱 내 알림 허용, 중요도 기준, 제외 기업, 방해 금지 시간과 일일 최대 수를 확인하세요. 새 검토 완료 이벤트가 없으면 알림이 없을 수 있습니다. 이메일·일간 요약은 현재 미제공입니다.',english:'Check your alert rules, in-app toggle, threshold, muted companies, quiet hours and daily cap. No new reviewed event can mean no alert. Email and daily digest delivery are not currently available.',href:'/settings/notifications'},
 {id:'sources',category:'data',q:'데이터의 출처는 어디인가요?',en:'Where does the data come from?',a:'미국 기업은 SEC 원문을 연결합니다. 공개된 분석에는 검증된 근거만 표시합니다. 한국 공시·시세는 현재 보류되어 있습니다. 시세는 공급자 연결과 웹 표시 권한이 확인된 경우에만 표시됩니다.',english:'U.S. company sources come from SEC filings. Published analyses show verified evidence. Korean disclosures and prices are deferred. Quotes appear only when the provider and display permission are configured.',href:'/sources'},
 {id:'pricing',category:'account',q:'요금제는 어떻게 변경하나요?',en:'How do I change my plan?',a:'현재 공개 베타는 결제 기능이 활성화되어 있지 않습니다. 카드 결제 또는 유료 정기 구독을 생성하지 않습니다.',english:'Payments are not enabled in the current public beta. No card charge or paid recurring subscription is created.',href:'/pricing'},
 {id:'privacy',category:'account',q:'계정을 탈퇴하거나 데이터를 삭제하고 싶어요.',en:'How do I request account or data deletion?',a:'아래 문의 유형에서 개인정보를 선택하고 삭제를 원하는 범위를 적어 주세요. 요청이 저장되며 운영자가 처리합니다. 즉시 탈퇴 완료로 표시하지 않습니다. 내 데이터 내보내기는 계정 설정에서 직접 실행할 수 있습니다.',english:'Choose Privacy in the support form below and specify the data to delete. The request is recorded for operator handling, not marked as immediately completed. Export your data directly from account settings.',href:'/settings/account'},
 {id:'mobile',category:'start',q:'모바일에서도 사용할 수 있나요?',en:'Can I use SignalBrief on a phone?',a:'브라우저에서 모바일 화면에 맞게 사용할 수 있습니다. 새 작업 공간은 하단 메뉴로 이동하며, 세부 필터와 설정은 한 열로 표시됩니다.',english:'Yes. The browser layout adapts to your phone. The new workspace uses bottom navigation and single-column filters and settings.',href:'/explore'},
 {id:'refresh',category:'data',q:'정보는 얼마나 자주 업데이트되나요?',en:'How often is information updated?',a:'기업별 마지막 수집 시각과 원문 날짜를 확인하세요. 자동 수집이 연결되지 않은 상태에서 실시간 업데이트를 보장하지 않습니다. 분석 검토가 완료되어야 이벤트가 공개됩니다.',english:'Check each company’s last collection time and source date. Real-time updates are not guaranteed when scheduled collection is not configured. Events are published only after review.',href:'/us'},
 {id:'errors',category:'issues',q:'오류가 발생하거나 페이지가 열리지 않으면?',en:'What should I do when a page fails?',a:'다시 시도 후에도 문제가 지속되면 아래 문의에 재현 방법, 발생 시각과 화면을 첨부해 주세요. 비밀번호, 인증 코드, API 키는 절대 첨부하지 마세요.',english:'Retry first. If the issue persists, include reproduction steps, time and a screenshot in a support request. Never include passwords, authentication codes or API keys.',href:'/status'},
 {id:'start',category:'start',q:'첫 관심종목은 어떻게 등록하나요?',en:'How do I add my first watchlist company?',a:'검색 / 탐색에서 지원 기업을 선택하고 기업 개요의 관심종목 버튼을 누르세요. 포트폴리오에는 실제 보유 수량을 별도로 입력합니다.',english:'Choose a supported company in Discover, then use the Watchlist button on its overview. Add actual holding quantities separately to your portfolio.',href:'/explore'},
 {id:'mfa',category:'account',q:'2단계 인증은 어떻게 설정하나요?',en:'How do I set up two-step verification?',a:'보안 및 로그인에서 인증 앱을 연결하세요. QR 코드를 스캔하고 6자리 코드를 검증해야 활성화됩니다. 인증 코드는 저장하거나 문의에 보내지 마세요.',english:'Connect an authenticator from Security & sign-in. Scan its QR code and verify a six-digit code to activate it. Never send authentication codes to support.',href:'/settings/security'}
];
export function searchHelp(query:string,category:string){const q=query.trim().toLowerCase();return helpArticles.filter(x=>(!category||x.category===category||x.id===category)&&(!q||`${x.q} ${x.en} ${x.a} ${x.english}`.toLowerCase().includes(q)));}
