'use client';
import Link from 'next/link';
import {useRef,useState} from 'react';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {initializeSupabase} from '@/lib/supabase';
import {usePrefs} from './preferences';
import {workspace,validateAttachment} from './client';
import {ticketSchema} from './contracts';
import {helpCategories,helpArticles,searchHelp} from './help-content';
import {useData,useMutation,Notice,Panel,Heading,Icon,DataState,Empty} from './ui';
const ticketsSchema=z.array(ticketSchema);
export default function Help({initialCategory=''}:{initialCategory?:string}){
 const {text:t,date}=usePrefs(),auth=useAuth(),[category,setCategory]=useState(initialCategory),[query,setQuery]=useState(''),[draft,setDraft]=useState(''),[formType,setFormType]=useState<'general'|'data'|'bug'|'feedback'|'privacy'>(initialCategory==='privacy'?'privacy':'general'),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[file,setFile]=useState<File|null>(null),[admin,setAdmin]=useState(false),[pending,setPending]=useState<string|null>(null),[savedTicket,setSavedTicket]=useState<string|null>(null);
 const action=useMutation(),reqKey=useRef<string|null>(null),fileInput=useRef<HTMLInputElement>(null),uploadedPath=useRef<string|null>(null),tickets=useData({action:'tickets',p:{admin:admin&&!!auth.me?.is_admin}},ticketsSchema),articles=searchHelp(query,category);
 function reset(){setPending(null);setTitle('');setMessage('');setFile(null);reqKey.current=null;uploadedPath.current=null;if(fileInput.current)fileInput.current.value='';}
 async function submit(){await action.run(async()=>{let checked:Awaited<ReturnType<typeof validateAttachment>>|null=null;if(file)checked=await validateAttachment(file);reqKey.current??=crypto.randomUUID();
  const ticket=await workspace(auth.token,{action:'ticket_create',p:{request_key:reqKey.current,category:formType,title,message}},ticketSchema);setPending(ticket.id);setSavedTicket(ticket.id);tickets.reload();
  if(file&&checked){const db=await initializeSupabase();const path=uploadedPath.current??`${auth.me!.id}/${ticket.id}/${crypto.randomUUID()}.${checked.extension}`;
   if(!uploadedPath.current){const uploaded=await db.storage.from('signalbrief-support').upload(path,file,{contentType:checked.mime,upsert:false});if(uploaded.error)throw new Error(t('문의는 저장되었지만 첨부 업로드가 실패했습니다. 첨부 다시 전송을 눌러 주세요.','Your request was saved, but the attachment upload failed. Retry the attachment.'));uploadedPath.current=path;}
   await workspace(auth.token,{action:'ticket_attach',p:{ticket_id:ticket.id,object_path:path,filename:file.name.slice(0,150),mime_type:checked.mime,size_bytes:file.size}},z.object({attached:z.boolean()}));
  }
  reset();tickets.reload();},t('문의가 저장되었습니다. 아래 내 문의에서 처리 상태를 확인하세요.','Your request was saved. Check its state under My requests below.'));}
 const jump=(type:typeof formType)=>{setFormType(type);document.getElementById('ws-support-form')?.scrollIntoView({behavior:'smooth',block:'center'});document.getElementById('support-title')?.focus();};
 return <><Heading title={t('도움말 및 지원','Help & support')} description={t('SignalBrief를 더 잘 활용할 수 있도록 필요한 정보를 빠르게 찾아보세요.','Find answers and get help using SignalBrief.')}/><section className="ws-help-hero"><h2><Icon name="search" size={36}/>{t('무엇을 도와드릴까요?','How can we help?')}</h2><p>{t('기능 안내와 문제 해결 방법을 검색하세요.','Search feature guides and troubleshooting steps.')}</p><form className="ws-search-form" onSubmit={e=>{e.preventDefault();setQuery(draft);setCategory('');}}><Icon name="search"/><input maxLength={100} value={draft} onChange={e=>setDraft(e.target.value)} aria-label={t('도움말 검색','Search help')} placeholder={t('예) 실적 발표, 포트폴리오, 알림 설정','Try portfolio, sources, alerts or account')}/><button className="ws-button">{t('검색','Search')}</button></form><div className="ws-chips small">{[['실적','filing'],['포트폴리오','portfolio'],['알림','alerts'],['데이터','data'],['계정','account']].map(([ko,en])=><button key={ko} className="ws-chip" onClick={()=>{setDraft(t(ko,en));setQuery(t(ko,en));setCategory('');}}>#{t(ko,en)}</button>)}</div><div className="ws-help-art" aria-hidden="true"><span>?</span></div></section>
 <div className="ws-section-title"><h2>{t('도움말 카테고리','Help categories')}</h2><button className="ws-link" onClick={()=>{setCategory('');setQuery('');setDraft('');}}>{t('전체 도움말 보기','All help articles')} ›</button></div><div className="ws-help-categories">{helpCategories.map(c=><button className={`ws-help-category ${category===c.id?'selected':''}`} key={c.id} onClick={()=>{setCategory(category===c.id?'':c.id);setQuery('');setDraft('');}} aria-pressed={category===c.id}><span className="ws-category-icon"><Icon name={c.icon} size={25}/></span><div><strong>{t(c.ko,c.en)}</strong><p>{t(c.description,c.english)}</p><small>{helpArticles.filter(x=>x.category===c.id).length} {t('개 문서','articles')} ›</small></div></button>)}</div>
 <div className="ws-grid equal"><div className="ws-stack"><Panel title={t('자주 묻는 질문','Frequently asked questions')} icon="search"><div>{articles.map((a,i)=><details className="ws-faq" key={a.id}><summary><span>{i+1}</span>{t(a.q,a.en)}</summary><div><p>{t(a.a,a.english)}</p><Link href={a.href}>{t('관련 화면 열기','Open related page')} →</Link>{a.id==='privacy'&&<button className="ws-link" onClick={()=>jump('privacy')}>{t('삭제 요청 작성','Write deletion request')}</button>}</div></details>)}{!articles.length&&<Empty title={t('일치하는 도움말이 없습니다','No matching help articles')} description={t('다른 검색어를 사용하거나 문의를 남겨 주세요.','Try another query or send a support request.')}/>}</div></Panel><Panel title={t('서비스 운영 현황','Service status')} icon="shield" action={<Link href="/status">{t('상태 확인','Check status')} ›</Link>}><p className="ws-small ws-muted">{t('모든 서비스가 정상이라고 가정하지 않습니다. 상태 화면에서 실제 API 진단과 공급자 점검 시각을 확인하세요.','Status is not assumed to be healthy. Check actual API diagnostics and provider-check times on the status page.')}</p></Panel></div>
 <div className="ws-stack"><Panel title={t('문의하기','Contact support')} icon="file"><p className="ws-small ws-muted" style={{marginBottom:14}}>{t('문의는 계정에 연결되어 비공개로 저장됩니다. 비밀번호·인증 코드·API 키는 보내지 마세요.','Requests are stored privately under your account. Never send passwords, authentication codes or API keys.')}</p><Notice action={action}/>{pending&&<div role="status" className="ws-notice">{t('문의가 저장되었습니다. 첨부 전송을 완료하거나 새 문의를 시작하세요.','Request saved. Finish the attachment or start a new request.')}<code>{pending.slice(0,8)}</code></div>}<form id="ws-support-form" className="ws-support-form" onSubmit={e=>{e.preventDefault();void submit();}}><div className="ws-fields"><label><span>{t('문의 유형','Type')}</span><select value={formType} disabled={action.busy||!!pending} onChange={e=>setFormType(e.target.value as typeof formType)}>{[['general','일반 문의','General'],['data','데이터 문의','Data'],['bug','오류 신고','Bug report'],['feedback','개선 제안','Feedback'],['privacy','개인정보 / 삭제 요청','Privacy / deletion']].map(([v,ko,en])=><option key={v} value={v}>{t(ko,en)}</option>)}</select></label><label><span>{t('제목','Subject')}</span><input id="support-title" required maxLength={120} value={title} disabled={action.busy||!!pending} onChange={e=>{setTitle(e.target.value);reqKey.current=null;}} placeholder={t('제목을 입력하세요','Enter a subject')}/></label></div><label><span id="ws-support-message-label">{t('문의 내용','Message')}</span><textarea aria-labelledby="ws-support-message-label" required maxLength={2000} value={message} disabled={action.busy||!!pending} onChange={e=>{setMessage(e.target.value);reqKey.current=null;}} placeholder={t('상황과 재현 방법을 자세히 알려 주세요.','Describe what happened and how to reproduce it.')}/><small style={{textAlign:'right'}}>{message.length} / 2,000</small></label><label><span><Icon name="upload" size={15}/> {t('파일 첨부 (선택)','Attachment (optional)')}</span><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp,application/pdf" disabled={action.busy||!!pending} onChange={e=>setFile(e.target.files?.[0]??null)}/><small>{t('PNG·JPEG·WebP·PDF / 5MB 이하. 실제 파일 형식을 검증합니다.','PNG, JPEG, WebP or PDF / up to 5 MB. The actual file format is checked.')}</small></label><button className="ws-button full" disabled={action.busy}>{action.busy?t('저장 중…','Saving…'):pending?t('첨부 다시 전송','Retry attachment'):t('문의 내용 제출하기','Submit request')}</button>{pending&&<button type="button" className="ws-link" onClick={reset}>{t('저장된 문의는 유지하고 새 문의 작성','Keep saved request and start a new one')}</button>}</form>{savedTicket&&!pending&&<small className="ws-muted">{t('최근 접수 번호','Latest request ID')}: {savedTicket}</small>}</Panel>
 <Panel><div className="ws-row"><div><h2>{t('문제 신고 및 의견 보내기','Report a problem or share feedback')}</h2><p className="ws-small ws-muted" style={{marginTop:7}}>{t('불편한 점이나 개선 아이디어를 남겨 주세요.','Tell us what could work better.')}</p></div><button className="ws-button ws-secondary" disabled={!!pending} onClick={()=>jump('feedback')}>{t('의견 보내기','Send feedback')} →</button></div></Panel><Panel title={t('추가 정보','More information')} icon="shield"><div className="ws-footer-links"><Link href="/privacy">{t('개인정보처리방침','Privacy')}</Link><Link href="/terms">{t('이용약관','Terms')}</Link><Link href="/disclaimer">{t('투자 유의사항','Investment notice')}</Link><Link href="/settings/account">{t('내 데이터 관리','Manage my data')}</Link></div></Panel></div></div>
 <div style={{marginTop:18}}><Panel title={admin?t('지원 요청 관리','Manage support requests'):t('내 문의','My requests')} icon="file" action={auth.me?.is_admin?<button onClick={()=>setAdmin(!admin)}>{admin?t('내 문의만','My requests only'):t('운영자 관리','Operator view')}</button>:<button onClick={tickets.reload}>{t('새로고침','Refresh')}</button>}><DataState {...tickets} retry={tickets.reload}/>{tickets.data?.map(ticket=><article className="ws-ticket" key={ticket.id}><span className="ws-badge">{ticket.state==='open'?t('접수됨','Received'):ticket.state==='in_progress'?t('처리 중','In progress'):t('처리 완료','Resolved')}</span><strong>{ticket.title}</strong><small className="ws-muted"> · {date(ticket.created_at)} · {ticket.id.slice(0,8)}</small><p>{ticket.message}</p>{ticket.attachments?.map(file=><button key={file.object_path} className="ws-link" disabled={action.busy} onClick={()=>void action.run(async()=>{const db=await initializeSupabase(),r=await db.storage.from('signalbrief-support').createSignedUrl(file.object_path,60);if(r.error)throw new Error(t('첨부파일을 열지 못했습니다.','Could not open attachment.'));const a=document.createElement('a');a.href=r.data.signedUrl;a.target='_blank';a.rel='noopener noreferrer';a.click();})}>{file.filename} ↗</button>)}{admin&&auth.me?.is_admin&&<label className="ws-field" style={{maxWidth:180}}><span>{t('처리 상태','Status')}</span><select value={ticket.state} disabled={action.busy} onChange={e=>void action.run(async()=>{await workspace(auth.token,{action:'ticket_update',p:{id:ticket.id,state:e.target.value as 'open'|'in_progress'|'resolved'}},z.unknown());tickets.reload();})}><option value="open">{t('접수됨','Received')}</option><option value="in_progress">{t('처리 중','In progress')}</option><option value="resolved">{t('처리 완료','Resolved')}</option></select></label>}</article>)}{tickets.data&&!tickets.data.length&&<Empty title={t('아직 접수한 문의가 없습니다','No requests submitted yet')}/>}</Panel></div></>;
}
