'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useAuth} from '@/components/auth';
import {usePrefs} from './preferences';
import {workspace} from './client';
import {catalogSchema,notificationsSettingsSchema} from './contracts';
import {useData,useMutation,Notice,Panel,Heading,Icon,DataState,SettingsTabs,Switch,Modal} from './ui';
export default function NotificationSettings(){const {token}=useAuth(),prefs=usePrefs(),{text:t,value}=prefs,res=useData({action:'notifications',p:{}},notificationsSettingsSchema),companies=useData({action:'catalog',p:{kind:'company',limit:50}},catalogSchema),action=useMutation();const [mute,setMute]=useState(false),[start,setStart]=useState(value.quiet_start),[end,setEnd]=useState(value.quiet_end),[threshold,setThreshold]=useState(.75),[cap,setCap]=useState(value.daily_cap);
 useEffect(()=>{setStart(value.quiet_start);setEnd(value.quiet_end);setCap(value.daily_cap);},[value.quiet_start,value.quiet_end,value.daily_cap]);useEffect(()=>{if(res.data)setThreshold(res.data.notify_min_score);},[res.data]);
 const change=(patch:Parameters<typeof prefs.save>[0])=>void action.run(()=>prefs.save(patch),t('알림 설정을 저장했습니다.','Notification preferences saved.'));
 const baseChange=(p:{realtime_enabled?:boolean;notify_min_score?:number})=>void action.run(async()=>{await workspace(token,{action:'notification_save',p},notificationsSettingsSchema);res.reload();},t('알림 설정을 저장했습니다.','Notification preferences saved.'));
 const row=(icon:'bell'|'file'|'shield'|'clock'|'pie',title:string,description:string,control:React.ReactNode)=><div className="ws-notification-row"><span className="ws-tile-icon"><Icon name={icon} size={27}/></span><div><h2>{title}</h2><p>{description}</p></div><div className="ws-notification-control">{control}</div></div>;
 return <><Heading title={t('알림 설정','Notification settings')} section={t('설정','Settings')} description={t('중요한 소식을 놓치지 않도록 나에게 맞는 알림을 설정하세요.','Control which important changes interrupt you.')}/><SettingsTabs/><Notice action={action}/><DataState {...res} retry={res.reload}/><DataState loading={false} error={prefs.error} retry={prefs.reload}/><div className="ws-grid"><Panel className="ws-notification-list">
 {row('bell',t('앱 내 알림','In-app alerts'),t('검토된 이벤트가 게시될 때 일반 알림을 생성합니다.','Generate ordinary alerts when reviewed events are published.'),<div className="ws-row"><Switch label={t('앱 내 알림','In-app alerts')} checked={res.data?.realtime_enabled??false} disabled={!res.data||action.busy} onChange={v=>baseChange({realtime_enabled:v})}/><span className="ws-link">{res.data?.realtime_enabled?t('켜짐','On'):t('꺼짐','Off')}</span></div>)}
 {row('file',t('이메일 알림','Email alerts'),t('메일 발송 서비스와 발송 작업이 연결된 후 제공됩니다.','Requires a configured mail provider and delivery worker.'),<><Switch label={t('이메일 알림 — 미제공','Email alerts — unavailable')} checked={false} disabled onChange={()=>{}}/><span className="ws-badge gray">{t('현재 미제공','Not available')}</span></>)}
 {row('file',t('일간 요약 리포트','Daily digest'),t('예약 발송 기능은 아직 활성화되지 않았습니다.','Scheduled digest delivery is not enabled.'),<><select aria-label={t('일간 요약 발송','Daily digest delivery')} disabled value="off"><option value="off">{t('받지 않음 — 미제공','Off — unavailable')}</option></select><Link className="ws-link" href="/us">{t('연결 상태','Connection status')} →</Link></>)}
 {row('shield',t('정정 / 철회 안내','Corrections / withdrawals'),t('알림을 꺼도 분석 화면의 정정·철회 표시는 유지됩니다.','Disabling alerts does not remove correction or withdrawal notices on analyses.'),<span className="ws-badge green">{t('분석 화면에서 확인','Shown on analysis')}</span>)}
 {row('bell',t('알림 제외 기업','Muted companies'),t('선택 기업의 새 일반 알림 생성을 중단합니다.','Stop generating new ordinary alerts for selected companies.'),<div className="ws-chips">{value.muted_companies.map(id=><button disabled={prefs.busy} className="ws-chip" key={id} onClick={()=>change({muted_companies:value.muted_companies.filter(x=>x!==id)})}>{companies.data?.items.find(x=>x.id===id)?.ticker??t('기업','Company')} ×</button>)}<button className="ws-chip" disabled={!prefs.loaded} onClick={()=>setMute(true)}>+ {t('추가','Add')}</button></div>)}
 {row('pie',t('중요도 임계값','Importance threshold'),t('서버가 계산한 관련도 점수가 기준 이상인 알림만 생성합니다.','Only generate alerts meeting the server-calculated relevance threshold.'),<div style={{width:'100%'}}><label className="ws-field"><span>{Math.round(threshold*100)} / 100</span><input aria-label={t('중요도 임계값','Importance threshold')} type="range" min="0" max="1" step="0.05" disabled={!res.data||action.busy} value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><div className="ws-slider-labels"><span>{t('낮음','Low')}</span><span>{t('높음','High')}</span></div><button className="ws-link" disabled={action.busy||threshold===res.data?.notify_min_score} onClick={()=>baseChange({notify_min_score:threshold})}>{t('기준 적용','Apply threshold')}</button></div>)}
 {row('clock',t('방해 금지 시간','Quiet hours'),t('설정한 시간대에는 새 일반 알림이 생성되지 않습니다. 나중에 몰아서 보내지 않습니다.','Ordinary alerts are not generated during this period. They are not delivered later in a batch.'),<div style={{width:'100%'}}><div className="ws-row"><span>{value.timezone}</span><Switch label={t('방해 금지 시간','Quiet hours')} checked={value.quiet_enabled} disabled={!prefs.loaded||prefs.busy} onChange={v=>change({quiet_enabled:v})}/></div><div className="ws-fields" style={{marginTop:12}}><label className="ws-field"><span>{t('시작 시간','Start')}</span><input type="time" value={start} disabled={!prefs.loaded||prefs.busy} onChange={e=>setStart(e.target.value)}/></label><label className="ws-field"><span>{t('종료 시간','End')}</span><input type="time" value={end} disabled={!prefs.loaded||prefs.busy} onChange={e=>setEnd(e.target.value)}/></label></div><button className="ws-link" disabled={prefs.busy||!start||!end||start===value.quiet_start&&end===value.quiet_end} onClick={()=>change({quiet_start:start,quiet_end:end})}>{t('시간 적용','Apply hours')}</button><small className="ws-muted">{start===end?t('시작·종료가 같으면 하루 종일 중단됩니다.','Matching times mute the entire day.'):''}</small></div>)}
 {row('bell',t('일일 최대 알림 수','Daily alert cap'),t('선택한 시간대의 하루를 기준으로 새 일반 알림 수를 제한합니다.','Limit newly generated ordinary alerts per day in your selected time zone.'),<div style={{width:'100%'}}><label className="ws-field"><span>{cap} {t('개 / 일','per day')}</span><input type="range" min="1" max="100" step="1" aria-label={t('일일 최대 알림 수','Daily alert cap')} value={cap} disabled={!prefs.loaded||prefs.busy} onChange={e=>setCap(Number(e.target.value))}/></label><div className="ws-slider-labels"><span>1</span><span>50</span><span>100</span></div><button className="ws-link" disabled={prefs.busy||cap===value.daily_cap} onClick={()=>change({daily_cap:cap})}>{t('최대 수 적용','Apply cap')}</button></div>)}
 </Panel><aside className="ws-stack"><Panel title={t('현재 알림 정책 요약','Current alert policy')} icon="bell"><div className="ws-policy-list">{[[t('앱 내 알림','In-app alerts'),res.data?.realtime_enabled?t('켜짐','On'):t('꺼짐','Off'),'bell'],[t('이메일 / 일간 요약','Email / digest'),t('현재 미제공','Not available'),'file'],[t('알림 제외 기업','Muted companies'),String(value.muted_companies.length),'shield'],[t('중요도 기준','Importance threshold'),`${Math.round((res.data?.notify_min_score??0)*100)} / 100`,'pie'],[t('방해 금지 시간','Quiet hours'),value.quiet_enabled?`${value.quiet_start} – ${value.quiet_end}`:t('꺼짐','Off'),'clock'],[t('일일 최대 알림 수','Daily cap'),String(value.daily_cap),'bell']].map(([title,content,icon])=><div key={title}><Icon name={icon as 'bell'|'file'|'shield'|'pie'|'clock'}/><div><strong>{title}</strong><small>{content}</small></div></div>)}</div><Link className="ws-button ws-secondary full" style={{marginTop:16}} href="/alerts">{t('알림 센터 열기','Open alert center')}</Link></Panel><Panel title={t('알림 관련 안내','About notifications')} icon="shield"><p className="ws-muted ws-small">{t('기업별 알림 규칙은 알림 센터에서 관리하세요. 이 설정은 실제 새 알림 생성에 적용되며 기존 알림이나 원문 분석을 삭제하지 않습니다. 브라우저 푸시·이메일 예약 발송은 포함되지 않습니다.','Manage individual alert rules in the alert center. These settings affect actual new alert generation, without deleting existing notifications or analyses. Background push and scheduled email delivery are not included.')}</p><Link className="ws-link" href="/help?category=alerts">{t('도움말 보기','Read help')} →</Link></Panel></aside></div>
 {mute&&<Modal title={t('알림 제외 기업 추가','Mute a company')} onClose={()=>setMute(false)}><Notice action={action}/><DataState {...companies} retry={companies.reload}/><div className="ws-stack">{companies.data?.items.map(c=><button className="ws-button ws-secondary" key={c.id} disabled={value.muted_companies.includes(c.id)||prefs.busy} onClick={()=>void action.run(async()=>{await prefs.save({muted_companies:[...new Set([...value.muted_companies,c.id])]});setMute(false);})}>{c.title} · {c.ticker}{value.muted_companies.includes(c.id)?' ✓':' +'}</button>)}</div></Modal>}</>;
}
