'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useEffect,useState} from 'react';
import {z} from 'zod';
import {useAuth} from '@/components/auth';
import {usePrefs} from './preferences';
import {workspace} from './client';
import {catalogSchema,searchesSchema,resourceKind,type Resource} from './contracts';
import {useData,useMutation,Panel,Heading,Empty,Logo,Icon,DataState,ResourceCard,Notice} from './ui';
import {useQuotes} from './market';
export function SearchForm({initial='',submit}:{initial?:string;submit:(q:string)=>void}){const {text:t}=usePrefs(),[query,setQuery]=useState(initial);useEffect(()=>setQuery(initial),[initial]);return <form className="ws-search-form" onSubmit={e=>{e.preventDefault();submit(query.trim());}}><Icon name="search"/><input aria-label={t('검색어','Search query')} value={query} maxLength={100} placeholder={t('종목명, 공시 유형 또는 키워드','Company, filing type or keyword')} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" className="ws-icon-button" aria-label={t('검색어 지우기','Clear search')} onClick={()=>setQuery('')}><Icon name="close" size={17}/></button>}<button className="ws-button">{t('검색','Search')}</button></form>;}
export default function Explore(){
 const {token}=useAuth(),{text:t,date,value}=usePrefs(),router=useRouter(),[market,setMarket]=useState('');
 const companies=useData({action:'catalog',p:{kind:'company',limit:50,market}},catalogSchema),content=useData({action:'catalog',p:{limit:20}},catalogSchema),recent=useData({action:'searches',p:{}},searchesSchema),action=useMutation();
 const marketData=useQuotes(companies.data?.items.map(x=>x.ticker).slice(0,8)??[]);
 const search=(q:string)=>{router.push(`/search?q=${encodeURIComponent(q)}`);};
 return <><div className="ws-discover-top"><div><Heading title={t('검색 / 탐색','Search / discover')} description={t('지원 기업과 실제 수집된 공시·분석을 한 번에 검색하세요.','Search supported companies, collected filings and reviewed analyses.')}/><SearchForm submit={search}/><div className="ws-chips small">{companies.data?.items.slice(0,5).map(c=><button key={c.id} className="ws-chip" onClick={()=>search(c.ticker)}>{c.ticker}</button>)}</div></div><div className="ws-discover-callout"><Icon name="spark" size={28}/><strong>{t('근거를 찾는 가장 빠른 시작','Start with the evidence')}</strong><p>{t('공시, 이벤트, 기업 정보를 연결합니다. 인기 순위나 투자 추천이 아닙니다.','Connect filings, events and companies. Not a popularity ranking or investment recommendation.')}</p></div></div>
 <DataState {...companies} retry={companies.reload}/><Notice action={action}/><div className="ws-discover-three"><Panel title={t('최근 검색어','Recent searches')} icon="clock" action={<button disabled={action.busy} onClick={()=>void action.run(async()=>{await workspace(token,{action:'searches_clear',p:{}},z.unknown());recent.reload();})}>{t('기록 지우기','Clear history')}</button>}><DataState {...recent} retry={recent.reload}/>{recent.data?.length?recent.data.map(r=><button className="ws-list-link" key={r.query} onClick={()=>search(r.query)}><Icon name="search" size={16}/><span>{r.query}</span><small>{date(r.searched_at,'date')}</small></button>):<Empty title={t('최근 검색 기록이 없습니다','No recent searches')} description={value.history_enabled?t('검색을 실행하면 여기에 표시됩니다.','Your searches will appear here.'):t('설정에서 방문·검색 기록 저장을 켤 수 있습니다.','Enable browsing/search history in settings.')} href="/settings/account" label={t('기록 설정','History settings')}/>}</Panel>
 <Panel title={t('기업 바로 검색','Quick company search')} icon="search">{companies.data?.items.map(c=><button key={c.id} className="ws-list-link" onClick={()=>search(c.ticker)}><Icon name="search" size={16}/><span>{c.company_name}</span><Icon name="arrow" size={15}/></button>)}{companies.data&&!companies.data.items.length&&<Empty title={t('지원 기업이 없습니다','No supported companies')}/>}</Panel>
 <Panel title={t('지원 티커','Supported tickers')} icon="timeline" action={<Link href="/search?kind=company">{t('더보기','View all')} ›</Link>}>{companies.data?.items.slice(0,6).map(c=>{const q=marketData.quotes.find(x=>x.symbol===c.ticker);return <Link key={c.id} href={`/companies/${c.id}`} className="ws-list-link"><span>{c.ticker}</span><small>{q?.price==null?'—':new Intl.NumberFormat(value.locale,{style:'currency',currency:q.currency}).format(q.price)}</small><small className={q?.change_pct!=null&&q.change_pct<0?'ws-bad':'ws-good'}>{q?.change_pct==null?t('시세 미연결','No quote'):`${q.change_pct>0?'+':''}${q.change_pct.toFixed(2)}%`}</small></Link>;})}<p className="ws-small ws-muted" style={{marginTop:12}}>{t('실제 지원 기업만 표시 · 인기 순위 아님','Supported companies only · not a popularity ranking')}</p></Panel></div>
 <div className="ws-section-title"><h2><Icon name="file"/>{t('공시 유형으로 탐색하기','Browse filing types')}</h2></div><div className="ws-chips">{[...new Set(content.data?.items.filter(x=>x.kind!=='company').map(x=>x.category)??[])].slice(0,12).map(kind=><button className="ws-chip" key={kind} onClick={()=>search(kind)}><Icon name="file" size={17}/>{kind}</button>)}{!content.loading&&!content.data?.items.some(x=>x.kind!=='company')&&<p className="ws-muted">{t('공시가 수집되면 실제 유형이 표시됩니다.','Filing types appear after source collection.')}</p>}</div>
 <div className="ws-section-title"><h2><Icon name="pie"/>{t('시장으로 필터링','Filter by market')}</h2></div><div className="ws-chips">{['',...(companies.data?.markets??[])].map(m=><button key={m} className={`ws-chip ${market===m?'active':''}`} aria-pressed={market===m} onClick={()=>setMarket(m)}>{m||t('전체','All')}</button>)}<Link className="ws-chip" href="/sources">{t('지원 범위 확인','Coverage')}</Link></div>
 <div className="ws-section-title"><h2><Icon name="star"/>{t('지원 기업','Supported companies')}</h2><Link className="ws-link" href="/search?kind=company">{t('전체 보기','View all')} ›</Link></div><div className="ws-company-grid">{companies.data?.items.map(c=><CompanyTile key={c.id} item={c}/>)}</div><div className="ws-section-title"><h2><Icon name="file"/>{t('최근 수집된 자료','Recently collected sources')}</h2><Link className="ws-link" href="/search?kind=document">{t('더보기','View all')} ›</Link></div><DataState {...content} retry={content.reload}/><div className="ws-grid equal">{content.data?.items.filter(x=>x.kind!=='company').slice(0,4).map(c=><ResourceCard key={c.kind+c.id} item={c}/>)}</div><p className="ws-small ws-muted" style={{marginTop:18}}>{t('한국 시장·산업별 분류는 현재 제공 범위에 포함되지 않습니다. 지원되지 않는 필터를 활성화하지 않습니다.','Korean markets and sector classification are not available in this release. Unsupported filters are not enabled.')}</p></>;
}
function CompanyTile({item}:{item:Resource}){const {text:t}=usePrefs();return <article className="ws-company-tile"><Link href={`/companies/${item.id}`}><Logo ticker={item.ticker}/><strong>{item.title}</strong><small>{item.ticker} · {item.market}</small><div className="ws-badge" style={{marginTop:12}}>SEC EDGAR</div><p className="ws-small ws-muted" style={{marginTop:9}}>{t('공시·근거·타임라인 확인','Filings, evidence and timeline')}</p></Link><Link className="ws-icon-button" href={`/companies/${item.id}`} aria-label={`${item.title} ${t('열기','Open')}`}><Icon name="arrow" size={17}/></Link></article>;}
export function SearchResults({initial,initialKind,initialMarket='',initialDays=0,initialOffset=0,initialSort='relevance'}:{initial:string;initialKind:string;initialMarket?:string;initialDays?:number;initialOffset?:number;initialSort?:'relevance'|'newest'}){
 const router=useRouter(),{token}=useAuth(),{text:t,value}=usePrefs();
 const kind:z.infer<typeof resourceKind>|''=resourceKind.safeParse(initialKind).success?initialKind as z.infer<typeof resourceKind>:'';
 const [filterOpen,setFilterOpen]=useState(false);
 const p={q:initial,kind,market:initialMarket,days:initialDays,offset:initialOffset,limit:12,sort:initialSort};const res=useData({action:'catalog',p},catalogSchema),data=res.data;
 const set=(patch:Partial<typeof p>)=>{const v={...p,...patch,offset:patch.offset??0};const params=new URLSearchParams();Object.entries(v).forEach(([key,val])=>{if(val!==''&&val!==0)params.set(key,String(val));});router.push(`/search?${params}`);};
 useEffect(()=>{if(initial.trim()&&value.history_enabled)void workspace(token,{action:'search_record',p:{query:initial}},z.unknown()).catch(()=>{});},[initial,token,value.history_enabled]);
 const filters=<Panel title={t('검색 필터','Search filters')} icon="search"><div className="ws-filter-group"><h3>{t('시장','Market')}</h3>{['',...(data?.markets??[])].map(m=><label className="ws-radio" key={m}><input type="radio" name="market" checked={initialMarket===m} onChange={()=>set({market:m})}/><span>{m||t('전체 시장','All markets')}</span></label>)}</div><div className="ws-filter-group"><h3>{t('기간','Date range')}</h3>{[[0,t('전체 기간','All time')],[7,t('최근 1주일','Last week')],[30,t('최근 1개월','Last month')],[90,t('최근 3개월','Last 3 months')],[365,t('최근 1년','Last year')]].map(([days,label])=><label className="ws-radio" key={days}><input type="radio" name="period" checked={initialDays===days} onChange={()=>set({days:Number(days)})}/><span>{label}</span></label>)}</div><button className="ws-link" onClick={()=>set({market:'',days:0,kind:''})} style={{marginTop:17}}>{t('필터 초기화','Reset filters')}</button></Panel>;
 return <><Heading title={t('검색 결과','Search results')}/><div className="ws-grid"><div><SearchForm initial={initial} submit={q=>set({q})}/><nav className="ws-tabs" aria-label={t('검색 결과 유형','Result type')}>{[['',t('전체','All')],['company',t('기업','Companies')],['event',t('이벤트','Events')],['document',t('문서','Documents')]].map(([k,label])=><button key={k} className={kind===k?'active':''} aria-pressed={kind===k} onClick={()=>set({kind:k as typeof kind})}>{label} {data&&`(${k===''?Object.values(data.counts).reduce((a,b)=>a+b,0):k==='document'?(data.counts.document??0)+(data.counts.filing??0):data.counts[k]??0})`}</button>)}</nav><div className="ws-toolbar"><button className="ws-chip" onClick={()=>setFilterOpen(!filterOpen)} aria-expanded={filterOpen}><Icon name="search" size={17}/>{t('필터','Filters')}</button><select aria-label={t('정렬','Sort')} value={initialSort} onChange={e=>set({sort:e.target.value as 'relevance'|'newest'})}><option value="relevance">{t('관련도순','Relevance')}</option><option value="newest">{t('최신순','Newest')}</option></select><small>{data?`${data.total} ${t('건의 검색 결과','results')}`:''}</small></div>{filterOpen&&filters}<DataState {...res} retry={res.reload}/><div className="ws-stack">{data?.items.map(item=><ResourceCard item={item} key={item.kind+item.id}/>)}{data&&!data.items.length&&<Empty title={t('검색 결과가 없습니다','No results found')} description={t('종목코드, 기업명 또는 실제 공시 유형으로 다시 검색해 보세요.','Try a ticker, company name or collected filing type.')} href="/explore" label={t('지원 기업 탐색','Browse supported companies')}/>}</div>{data&&<div className="ws-pagination"><button className="ws-button ws-secondary" disabled={initialOffset===0} onClick={()=>set({offset:Math.max(0,initialOffset-12)})}>{t('이전','Previous')}</button><span>{Math.floor(initialOffset/12)+1}</span><button className="ws-button ws-secondary" disabled={data.next_offset===null} onClick={()=>set({offset:data.next_offset??0})}>{t('다음','Next')}</button></div>}</div><aside className="ws-stack">{filters}<Panel title={t('관련 기업','Related companies')} icon="pie">{[...new Map(data?.items.map(x=>[x.company_id,x])??[]).values()].slice(0,6).map(c=><Link className="ws-list-link" href={`/companies/${c.company_id}`} key={c.company_id}><Logo ticker={c.ticker}/><span>{c.company_name}<small className="ws-muted"> · {c.ticker}</small></span><Icon name="arrow" size={16}/></Link>)}</Panel><Panel title={t('검색 범위 안내','Search coverage')} icon="shield"><p className="ws-small ws-muted">{t('지원 기업과 실제 수집된 SEC 원문, 검토가 완료된 이벤트만 검색합니다. 검색 결과 수는 실시간 응답으로 계산됩니다.','Search covers supported companies, collected SEC sources and reviewed events. Counts come from the actual response.')}</p><Link className="ws-link" href="/sources">{t('데이터 출처','Data sources')} →</Link></Panel></aside></div></>;
}
