'use client';
import Link from 'next/link';
import Image from 'next/image';
import {useEffect,useState,type FormEvent} from 'react';
import {initializeSupabase} from '@/lib/supabase';
import {usePrefs} from './preferences';
import {useIdentity} from './account';
import {securitySchema} from './contracts';
import {useData,useMutation,Notice,Panel,Heading,Icon,Modal,DataState,SettingsTabs,Empty} from './ui';
type Factor={id:string;friendly_name?:string;status:string};
export default function Security(){
 const {text:t,date}=usePrefs(),identity=useIdentity(),result=useData({action:'security',p:{}},securitySchema),action=useMutation();
 const [factors,setFactors]=useState<Factor[]>([]),[mfaLoading,setMfaLoading]=useState(true),[mfaError,setMfaError]=useState(''),[revision,setRevision]=useState(0),[setup,setSetup]=useState<{id:string;qr:string;secret:string}|null>(null),[code,setCode]=useState(''),[remove,setRemove]=useState<Factor|null>(null),[sessionConfirm,setSessionConfirm]=useState(false),[unlink,setUnlink]=useState<string|null>(null),[current,setCurrent]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[show,setShow]=useState(false),[passwordCode,setPasswordCode]=useState('');
 useEffect(()=>{let live=true;setMfaLoading(true);initializeSupabase().then(db=>db.auth.mfa.listFactors()).then(r=>{if(r.error)throw r.error;if(live){setFactors(r.data.totp);setMfaError('');}}).catch(()=>{if(live)setMfaError('2단계 인증 상태를 확인하지 못했습니다.');}).finally(()=>{if(live)setMfaLoading(false);});return()=>{live=false;};},[revision]);
 const verified=factors.filter(x=>x.status==='verified'),hasPassword=identity.user?.identities?.some(i=>i.provider==='email');
 async function begin(){await action.run(async()=>{const db=await initializeSupabase();for(const f of factors.filter(x=>x.status!=='verified')){const r=await db.auth.mfa.unenroll({factorId:f.id});if(r.error)throw new Error(t('미완료 설정을 정리하지 못했습니다.','Could not clear incomplete enrollment.'));}const r=await db.auth.mfa.enroll({factorType:'totp',friendlyName:'SignalBrief Authenticator'});if(r.error)throw new Error(t('2단계 인증 설정을 시작하지 못했습니다.','Could not start MFA enrollment.'));setSetup({id:r.data.id,qr:r.data.totp.qr_code,secret:r.data.totp.secret});setCode('');});}
 async function changePassword(e:FormEvent){e.preventDefault();await action.run(async()=>{if(password.length<12||password.length>128||password!==repeat)throw new Error(t('12~128자와 비밀번호 확인을 점검해 주세요.','Use 12–128 characters and matching confirmation.'));const db=await initializeSupabase();if(!identity.user?.email)throw new Error(t('이메일 확인이 필요합니다.','A verified email is required.'));
  if(hasPassword){const verify=await db.auth.signInWithPassword({email:identity.user.email,password:current});if(verify.error)throw new Error(t('현재 비밀번호를 확인해 주세요.','Check your current password.'));}
  if(verified.length){const check=await db.auth.mfa.challengeAndVerify({factorId:verified[0].id,code:passwordCode});if(check.error)throw new Error(t('현재 인증 앱의 코드를 확인해 주세요.','Check the current authenticator code.'));}
  const changed=await db.auth.updateUser({password});if(changed.error)throw new Error(t('추가 인증 또는 비밀번호 재설정 메일이 필요합니다.','Additional authentication or a password reset email is required.'));setCurrent('');setPassword('');setRepeat('');setPasswordCode('');identity.reload();result.reload();},t('비밀번호가 변경되었습니다. 다른 기기 세션도 필요하면 종료하세요.','Password changed. Review and end other sessions as needed.'));}
 return <><Heading title={t('보안 및 로그인','Security & sign-in')} section={t('설정','Settings')} description={t('인증 수단과 로그인 세션을 직접 관리하세요.','Manage authentication methods and sessions.')}/><SettingsTabs/><Notice action={action}/>
 <Panel className="ws-security-summary"><span className="ws-security-shield"><Icon name="shield" size={51}/></span><div><h2>{mfaLoading?t('보안 설정 확인 중','Checking security settings'):verified.length?t('2단계 인증이 설정되어 있습니다','Two-step verification is enabled'):t('2단계 인증으로 계정을 보호하세요','Protect your account with two-step verification')}</h2><p>{t('마지막 로그인','Last sign-in')}: {date(identity.user?.last_sign_in_at??null)}</p><p className="ws-small">{t('이 화면은 인증 상태를 표시하며, 의심스러운 활동이 없다고 보장하지 않습니다.','This reflects authentication state, not a guarantee that no suspicious activity occurred.')}</p></div><div className="ws-stack"><span><Icon name="shield" size={17}/>{identity.user?.email_confirmed_at?t('이메일 인증 완료','Email verified'):t('이메일 인증 상태 확인 필요','Check email verification')}</span><span><Icon name="clock" size={17}/>{t('현재 로그인 기록 확인 가능','Review current session records')}</span></div></Panel>
 <div className="ws-grid equal"><div className="ws-stack"><Panel title={hasPassword?t('비밀번호 변경','Change password'):t('비밀번호 설정','Set a password')} icon="shield"><form className="ws-stack" onSubmit={changePassword}>{hasPassword&&<label className="ws-field"><span>{t('현재 비밀번호','Current password')}</span><input required value={current} type={show?'text':'password'} autoComplete="current-password" maxLength={128} onChange={e=>setCurrent(e.target.value)}/></label>}<label className="ws-field"><span>{t('새 비밀번호','New password')}</span><input required type={show?'text':'password'} value={password} autoComplete="new-password" minLength={12} maxLength={128} onChange={e=>setPassword(e.target.value)}/></label><label className="ws-field"><span>{t('새 비밀번호 확인','Confirm new password')}</span><input required type={show?'text':'password'} value={repeat} autoComplete="new-password" maxLength={128} onChange={e=>setRepeat(e.target.value)}/></label>{verified.length>0&&<label className="ws-field"><span>{t('인증 앱 코드','Authenticator code')}</span><input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={passwordCode} onChange={e=>setPasswordCode(e.target.value.replace(/\D/g,''))}/></label>}<label className="ws-radio"><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/><span>{t('비밀번호 보기','Show passwords')}</span></label><div className="ws-requirements">{t('12자 이상 128자 이하 · 다른 서비스와 다른 긴 비밀번호를 사용하세요. 정기적인 강제 변경은 요구하지 않습니다.','Use a unique password of 12–128 characters. Routine forced password rotation is not required.')}</div><button className="ws-button full" disabled={action.busy||!identity.user}>{t('비밀번호 저장','Save password')}</button><Link className="ws-link" href="/forgot-password">{t('비밀번호 재설정 메일 받기','Request password reset email')} →</Link></form></Panel>
 <Panel title={t('최근 계정 활동','Recent account activity')} icon="clock" action={<button onClick={result.reload}>{t('새로고침','Refresh')}</button>}><DataState {...result} retry={result.reload}/>{result.data?.history.length?result.data.history.map((x,i)=><div className="ws-history-row" key={i}><time>{date(x.created_at)}</time><strong>{x.action}</strong></div>):result.data&&<Empty title={t('기록된 계정 활동이 없습니다','No recorded account activity')}/>}</Panel></div><div className="ws-stack"><Panel title={t('연결된 계정','Connected accounts')} icon="settings">{identity.error&&<div role="alert">{identity.error}</div>}{identity.user?.identities?.map(i=><div className="ws-provider-row" key={i.identity_id}><span className="ws-provider-symbol">{i.provider==='google'?'G':'@'}</span><div><strong>{i.provider}</strong><small>{identity.user?.email}</small></div><span className="ws-badge green">{t('연결됨','Connected')}</span>{i.provider!=='email'&&<button className="ws-button ws-secondary" disabled={(identity.user?.identities?.length??0)<2||action.busy} onClick={()=>setUnlink(i.identity_id)}>{t('연결 해제','Unlink')}</button>}</div>)}<p className="ws-small ws-muted" style={{marginTop:12}}>{t('마지막 로그인 수단의 해제는 차단됩니다. 제공자 또는 MFA 정책에 따라 추가 인증이 필요할 수 있습니다.','Removing the last sign-in method is blocked. Provider or MFA policies may require further authentication.')}</p></Panel>
 <Panel title={t('2단계 인증','Two-step verification')} icon="shield"><DataState loading={mfaLoading} error={mfaError} retry={()=>setRevision(x=>x+1)}/><p className="ws-muted ws-small">{t('인증 앱으로 생성한 코드를 확인한 후에만 활성화됩니다.','Activation requires verification of a code from your authenticator app.')}</p>{verified.map(f=><div className="ws-toggle-row" key={f.id}><div><strong>{f.friendly_name||t('인증 앱','Authenticator')}</strong><p>{t('설정됨','Enabled')}</p></div><button className="ws-button ws-secondary" disabled={action.busy} onClick={()=>{setCode('');setRemove(f);}}>{t('관리','Manage')}</button></div>)}{!verified.length&&!mfaLoading&&<button className="ws-button" style={{marginTop:16}} disabled={action.busy||!!mfaError} onClick={()=>void begin()}>{t('2단계 인증 설정','Set up two-step verification')}</button>}</Panel>
 <Panel title={t('활성 세션 및 기기','Active sessions & devices')} icon="settings" action={<button onClick={result.reload}>{t('새로고침','Refresh')}</button>}><DataState {...result} retry={result.reload}/>{result.data?.sessions.map(s=><div className="ws-session" key={s.id}><Icon name="settings"/><div><strong>{s.current?t('현재 세션','Current session'):t('다른 로그인 세션','Other sign-in session')}</strong><p>{s.user_agent||t('기기 정보 없음','Device information unavailable')}</p><p>{date(s.last_seen)} · {s.aal??'—'}</p></div>{s.current&&<span className="ws-badge green">{t('현재','Current')}</span>}</div>)}{result.data&&!result.data.sessions.length&&<Empty title={t('활성 세션 기록 없음','No active session records')}/>}<button className="ws-button ws-secondary full" style={{marginTop:15}} onClick={()=>setSessionConfirm(true)} disabled={action.busy}>{t('다른 모든 기기 로그아웃','Sign out all other sessions')}</button><p className="ws-small ws-muted" style={{marginTop:12}}>{t('다른 세션의 갱신 권한이 해제됩니다. 이미 발급된 접근 토큰은 만료 시까지 유효할 수 있습니다. 위치를 임의로 추정하지 않습니다.','Refresh access is revoked for other sessions. Existing access tokens may remain valid until expiry. Device locations are not guessed.')}</p></Panel>
 <Panel title={t('보안 알림 안내','Security notification information')} icon="bell"><p className="ws-muted ws-small">{t('새 기기 로그인 이메일 알림은 아직 제공하지 않습니다. 인증 제공자가 보내는 복구·확인 이메일과 앱의 투자 알림은 별개입니다.','New-device login emails are not yet provided. Authentication recovery/confirmation emails are separate from investment alerts.')}</p></Panel></div></div>
 {(setup||remove)&&<Modal title={setup?t('인증 앱 연결','Connect authenticator'):t('2단계 인증 해제','Disable two-step verification')} onClose={()=>{setSetup(null);setRemove(null);setCode('');setRevision(x=>x+1);}}><Notice action={action}/>{setup?<><p>{t('인증 앱에서 QR 코드를 스캔하고 6자리 코드를 입력하세요.','Scan the QR code in your authenticator, then enter its six-digit code.')}</p><Image unoptimized width={180} height={180} className="ws-mfa-qr" alt={t('인증 앱 등록 QR 코드','Authenticator enrollment QR code')} src={setup.qr.startsWith('data:image/')?setup.qr:''}/><details><summary>{t('수동 설정 키 보기','Show manual setup key')}</summary><code className="ws-secret">{setup.secret}</code></details></>:<p>{t('현재 인증 코드를 확인해야 해제됩니다. 인증 앱에 저장된 코드가 없으면 이 작업을 진행하지 마세요.','Verify your current authenticator code to disable MFA. Do not proceed without access to the authenticator.')}</p>}<form onSubmit={e=>{e.preventDefault();void action.run(async()=>{if(!/^\d{6}$/.test(code))throw new Error(t('6자리 코드를 입력해 주세요.','Enter a six-digit code.'));const db=await initializeSupabase(),id=setup?.id??remove!.id,r=await db.auth.mfa.challengeAndVerify({factorId:id,code});if(r.error)throw new Error(t('인증 코드가 잘못되었거나 만료되었습니다.','The verification code is invalid or expired.'));if(remove){const removed=await db.auth.mfa.unenroll({factorId:id});if(removed.error)throw new Error(t('인증 해제를 완료하지 못했습니다.','Could not disable MFA.'));}setSetup(null);setRemove(null);setCode('');setRevision(x=>x+1);result.reload();},t('2단계 인증 설정을 업데이트했습니다.','Two-step verification updated.'));}}><label>{t('인증 코드','Verification code')}<input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button className="ws-button" disabled={action.busy}>{setup?t('인증 후 활성화','Verify and enable'):t('인증 후 해제','Verify and disable')}</button></form></Modal>}
 {sessionConfirm&&<Modal title={t('다른 세션을 종료할까요?','End other sessions?')} onClose={()=>setSessionConfirm(false)}><Notice action={action}/><p>{t('현재 기기는 로그인 상태를 유지합니다. 다른 기기의 접근 토큰은 만료 후 더 이상 갱신되지 않습니다.','This device stays signed in. Other devices cannot refresh their access after token expiry.')}</p><button className="ws-button ws-danger-button" disabled={action.busy} onClick={()=>void action.run(async()=>{const db=await initializeSupabase(),r=await db.auth.signOut({scope:'others'});if(r.error)throw new Error(t('다른 세션을 종료하지 못했습니다.','Could not end other sessions.'));setSessionConfirm(false);result.reload();},t('다른 세션의 갱신 권한을 해제했습니다.','Other session refresh access was revoked.'))}>{t('다른 세션 종료','End other sessions')}</button></Modal>}
 {unlink&&<Modal title={t('계정 연결 해제','Unlink account')} onClose={()=>setUnlink(null)}><Notice action={action}/><p>{t('이 제공자로는 더 이상 로그인할 수 없습니다. 다른 로그인 수단을 먼저 확인하세요.','You will no longer be able to sign in with this provider. Confirm another sign-in method first.')}</p><button className="ws-button ws-danger-button" disabled={action.busy} onClick={()=>void action.run(async()=>{const i=identity.user?.identities?.find(x=>x.identity_id===unlink);if(!i||(identity.user?.identities?.length??0)<2)throw new Error(t('다른 로그인 수단이 필요합니다.','Another sign-in method is required.'));const db=await initializeSupabase(),r=await db.auth.unlinkIdentity(i);if(r.error)throw new Error(t('추가 인증이 필요하거나 제공자 연결 해제가 허용되지 않습니다.','Additional authentication is required or provider unlinking is not allowed.'));setUnlink(null);identity.reload();},t('연결을 해제했습니다.','Account unlinked.'))}>{t('연결 해제','Unlink')}</button></Modal>}</>;
}
