'use client';
import {useCallback,useEffect,useState} from 'react';
import {useAuth} from '@/components/auth';
import {PageHeading} from '@/components/ui';
type Row=Record<string,unknown>;
export default function US(){
 const {token,me}=useAuth(),[items,setItems]=useState<Row[]>([]),[status,setStatus]=useState<Row|null>(null),[fx,setFX]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[symbol,setSymbol]=useState('AAPL'),[analysis,setAnalysis]=useState<Row|null>(null);
 const api=useCallback(async(path:string,payload?:Row)=>{const r=await fetch('/api/us/'+path,{method:payload?'POST':'GET',headers:{...(token?{Authorization:`Bearer ${token}`} :{}),...(payload?{'Content-Type':'application/json'}:{})},body:payload?JSON.stringify(payload):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error?.code??'request_failed');return d;},[token]);
 const load=useCallback(async()=>{if(!token)return;try{const [f,s,x]=await Promise.all([api('filings'),api('status'),api('fx').catch(()=>null)]);setItems(f.items??[]);setStatus(s);setFX(x);setError('');}catch(e){setError(e instanceof Error?e.message:'load_failed');}},[api,token]);
 useEffect(()=>{void load();},[load]);
 async function action(name:string,payload?:Row){setBusy(true);try{const d=await api(name,payload);setAnalysis(d);await load();}catch(e){setError(e instanceof Error?e.message:'request_failed');}finally{setBusy(false);}}
 return <><PageHeading title="미국 기업 공시" description="SEC의 실제 제출 내역을 확인합니다. AI 분석은 별도 검토 후 공개됩니다."/><div className="notice"><strong>US 초기 버전</strong>OpenDART·KRX 연결은 보류했습니다. 한국 공시·시세를 임의로 생성하지 않습니다. FMP 시세는 웹사이트 표시 권한이 확인된 경우에만 제공됩니다.</div>{error&&<p role="alert" className="notice danger">요청 오류: {error}</p>}<div className="two-column"><section className="panel"><h2>최근 SEC 제출 내역</h2>{items.length?items.map(f=><article className="list-row" key={String(f.id)}><div className="grow"><strong>{String((f.companies as Row)?.name??'')} · {String(f.form)}</strong><p className="small muted">{String(f.filing_date)} · {String(f.accession)}</p><a className="source-link" href={String(f.document_url)} rel="noopener noreferrer" target="_blank">SEC 원문 열기 ↗</a></div><div className="button-row"><button className="button secondary" disabled={busy} onClick={()=>action('analysis?filing_id='+encodeURIComponent(String(f.id)))}>분석 상태</button>{me?.is_admin&&<button className="button primary" disabled={busy} onClick={()=>action('analyze',{filing_id:f.id})}>AI 검토안 생성</button>}</div></article>):<p className="muted">아직 수집된 공시가 없습니다. SEC 연락 이메일과 수집 실행이 필요합니다.</p>}</section><aside><section className="panel"><h2>환율 · 일일 참고값</h2>{fx?<><strong>1 USD = {String(fx.rate)} KRW</strong><p className="small muted">기준일 {String(fx.date)} · Frankfurter · 실시간 거래 환율 아님</p></>:<p>환율을 확인하지 못했습니다.</p>}</section><section className="panel"><h2>연결 상태</h2><p>FMP 웹 표시: {status?.fmp_display?'허용 확인됨':'권한 확인 대기'}</p><p>GNews 배포 사용: {status?.gnews_deployed?'허용 확인됨':'요금제 확인 대기'}</p><p>AI 운영 예산: {status?.ai_budget_enabled?'설정됨':'승인 필요'}</p><p>자동 수집: {status?.scheduled_ingestion?'설정됨':'아직 시작하지 않음'}</p><a className="text-button" href="/status">로그인·API 진단 보기 →</a></section></aside></div>{me?.is_admin&&<section className="panel"><h2>US 운영 작업</h2><label className="field"><span>수집 기업 · SEC 지원 기업만</span><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{['AAPL','MSFT','NVDA','TSLA'].map(s=><option key={s}>{s}</option>)}</select></label><div className="button-row"><button className="button primary" disabled={busy} onClick={()=>action('ingest',{symbol})}>SEC 공시 수집</button><button className="button secondary" disabled={busy} onClick={()=>action('verify',{})}>공급자 호출 검사</button></div><p className="small muted">OpenAI 호출은 서버 예산이 설정된 경우에만 실행됩니다. 메일은 이 검사에서 발송하지 않습니다.</p></section>}{analysis&&<section className="panel"><h2>조회 결과</h2><pre>{JSON.stringify(analysis,null,2)}</pre></section>}</>;
}
